### ISSUE TITLE
SoqlSyncDownTarget nextRecordsUrl not getting updated in continueFetch

### ISSUE THREAD

**Issue by mzaklama** [forcedotcom/SalesforceMobileSDK-Android#1000]
There is an issue in the Class: SoqlSyncDownTarget Method: continueFetch.
If you have a query that returns records more than the limit, the nextReocrdsUrl is not updated there. It should be updated like in the startFetch method.
This causes and endless loop of requests as it always keep using the first nextRecordsUrl from the first call in startFetch methos.

**Comment by wmathurin** [comment]
This has been fixed in unstable (for our next release).
Here is the commit with the fix:
https://github.com/forcedotcom/SalesforceMobileSDK-Android/commit/6f8432fedd8e7d27a26926f11f095bc2cef59bac
