### ISSUE TITLE
File Upload Android

### ISSUE THREAD

**Issue by shanuka** [forcedotcom/SalesforceMobileSDK-Android#1003]
Hi ,
im using API v 3.3. 
~~~
RestRequest uploadImage= FileRequests.uploadFile(getOutputMediaFile(1), "PigePhotos", "Téléchargé via Android APP","image/jpeg");
~~~
uploadFile method missing. please help me to

**Comment by bhariharan** [comment]
The file upload method has moved to ```RestClient.java```.

```public RestResponse uploadFile(File theFile, String name, RestClient client, String title, String description)```
