### ISSUE TITLE
Failed to install 'com.salesforce':CordovaError: Plugin doesn't support this project's cordova-android version.

### ISSUE THREAD

**Issue by stvnhg** [forcedotcom/SalesforceMobileSDK-Android#1016]
Hello

I'm trying to create a new project but I keep getting an error. 
```
Copying template files...
Project successfully created.
Fetching plugin "https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugi
n" via git clone
Installing "com.salesforce" for android
Failed to install 'com.salesforce':CordovaError: Plugin doesn't support this pro
ject's cordova-android version. cordova-android: 3.6.4, failed version requireme
nt: 5.0.0
    at checkEngines (C:\Users\stvnhg\AppData\Roaming\npm\node_modules\cordova\no
de_modules\cordova-lib\src\plugman\install.js:116:29)
    at _fulfilled (C:\Users\stvnhg\AppData\Roaming\npm\node_modules\cordova\node
_modules\q\q.js:798:54)
    at self.promiseDispatch.done (C:\Users\stvnhg\AppData\Roaming\npm\node_modul
es\cordova\node_modules\q\q.js:827:30)
    at Promise.promise.promiseDispatch (C:\Users\stvnhg\AppData\Roaming\npm\node
_modules\cordova\node_modules\q\q.js:760:13)
    at C:\Users\stvnhg\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q
.js:574:44
    at flush (C:\Users\stvnhg\AppData\Roaming\npm\node_modules\cordova\node_modu
les\q\q.js:108:17)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
Plugin doesn't support this project's cordova-android version. cordova-android:
3.6.4, failed version requirement: 5.0.0
```

I installed forcedroid@3.3.1 and cordova@4.0.0 globally. I also tried with cordova@5.0.0 but no luck.  Any ideas?

Thank you

**Comment by bhariharan** [comment]
@stvnhg ```forcedroid@3.3.1``` doesn't support ```Cordova 5.0```. Please install the latest ```forcedroid - 4.0.0``` and try again. This supports ```Cordova 5.0```. Feel free to reopen if you still see issues.

**Comment by stvnhg** [comment]
@bhariharan Like I said, my first try was with cordova 4.0.0 and it didn't work. After that tried with cordova 5.0.0 and I got the same error. Any ideas?

Thank you

**Comment by bhariharan** [comment]
@stvnhg If you're using ```forcedroid@3.3.x```, then you'll need to use ```Cordova platform 3.6.x```, and ```Cordova CLI < 4.0```. ```forcedroid@3.3.x``` will NOT work with ```Cordova 5.x```.

**Comment by stvnhg** [comment]
@bhariharan I can't get it to work. These are the steps I've taken.

First try
```npm install forcedroid -g```
```npm install cordova@3.6.3-0.2.13 -g```
```forcedroid create```
Error message: Installed cordova command line tool version (3.6.3-0.2.13) is less than the mini
mum required version (4.0).  Please update your version of Cordova.

Second try (Uninstalled everything first)
```npm install forcedroid -g```
```npm install cordova@4.0.0 -g```
```forcedroid create```

Got the following error. 
![image](https://cloud.githubusercontent.com/assets/2606317/12016851/45f48de4-ad50-11e5-93d3-20e9563187d6.png)

Any ideas? Thank you!

**Comment by bhariharan** [comment]
@stvnhg Unfortunately, the ```master``` branch of the plugin repo is being pulled by the script, instead of the specific tag. We fixed this bug recently, but since you have an older version of ```forcedroid```, you'll need to upgrade to the latest.

**Comment by jayadaadrit** [comment]
Android project created with cordova-android@5.1.1
Installing "com.salesforce" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 5.1.1, failed version requirement: 5.0.0
Skipping 'com.salesforce' for android

Can you please help me on this?

**Comment by wmathurin** [comment]
The solution is in the error message. We don't support 5.1.1, you need to install cordova-android@5.0.0 instead,

**Comment by jayadaadrit** [comment]
Hello,
What's the error about when I'm trying to add any plugin.
Fetching plugin "cordova-plugin-x-toast" via npm
Installing "cordova-plugin-x-toast" for android
**Error: Cannot read property 'attrib' of null**

**Comment by wmathurin** [comment]
I recommend you post that question on the cordova-plugin-x-toast repo: https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin

**Comment by jayadaadrit** [comment]
But I'm getting this error for nearly all the plugins.
