### ISSUE TITLE
Error while creating hybrid application using forcedroid

### ISSUE THREAD

**Issue by asinha08** [forcedotcom/SalesforceMobileSDK-Android#1048]
I am working on mac machine. I am getting following error when I am creating hybrid application using forcedroid. Please note: I have shelljs installed as -g and i think forcedroid also have shelljs. So that should not be a problem. For security reason i have add XXXXX in the message below. my cordova version is 6.0.0 I am stuck and block. Please help

    $ forcedroid create
    Enter your application type (native, react_native, hybrid_remote, or hybrid_local): hybrid_local
    Enter your application name: XXXX
    Enter the target directory of your app (must be an existing empty folder): /Users/XXXX/git/force
    Enter the package name for your app (com.mycompany.my_app): XXXXXXXX
    Creating a new cordova project.
    /Users/XXXXX/git/force/XXXXX /Users/XXXXX/git/XXXXXX
    Adding android project...
    Creating Cordova project for the Android platform:
    Path: platforms/android
    Package: XXXXXXXX
    Name: XXXX
    Activity: MainActivity
    Android target: android-23
    Android project created with cordova-android@5.0.0
    Discovered plugin "cordova-plugin-whitelist" in config.xml.Installing to the project
    Fetching plugin "cordova-plugin-whitelist@1" via npm
    Installing "cordova-plugin-whitelist" for android
    This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.       
    Fetching plugin "https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin" via git clone
    Repository "https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin" checked out to git ref "v4.0.2".
    Installing "com.salesforce" for android
    Dependent plugin "cordova-plugin-whitelist" already installed on android.
    Fetching plugin "cordova-plugin-device" via npm
    Installing "cordova-plugin-device" for android
    Fetching plugin "phonegap-plugin-push" via npm
    Installing "phonegap-plugin-push" for android
    Running SalesforceMobileSDK plugin android post-install script
    The node package shelljs is required to use this script. Run 'npm install shelljs' before running this script. shell.js: internal error
    Error: ENOENT: no such file or directory, stat '/usr/local/lib/node_modules/forcedroid/external/shared/samples/userlist/*'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at /usr/local/lib/node_modules/forcedroid/node_modules/shelljs/src/cp.js:148:21
    at Array.forEach (native)
    at Object._cp (/usr/local/lib/node_modules/forcedroid/node_modules/shelljs/src/cp.js:144:13)
    at Object.cp (/usr/local/lib/node_modules/forcedroid/node_modules/shelljs/src/common.js:240:23)
    at createHybridApp (/usr/local/lib/node_modules/forcedroid/node/forcedroid.js:179:17)
    at createApp (/usr/local/lib/node_modules/forcedroid/node/forcedroid.js:128:9)
    at processArgsInteractiveHelper (/usr/local/lib/node_modules/forcedroid/external/shared/node/commandLineUtils.js:81:16)
    at processArgsInteractiveHelper (/usr/local/lib/node_modules/forcedroid/external/shared/node/commandLineUtils.js:107:13)

**Comment by wmathurin** [comment]
Forcedroid depends on shelljs and shelljs published a new version (0.6.0) a few days back that broke forcedroid. We will have a patch out very soon with the fix.

**Comment by asinha08** [comment]
As I am stuck. What we need to do, to fix this manually.

**Comment by bhariharan** [comment]
@asinha08 Stay tuned. We'll have a fix for this the upcoming week, at which time you can upgrade to the latest ```forcedroid```.

**Comment by asinha08** [comment]
@wmathurin & @bhariharan, can you please let me know the date by which patch will be released.

**Comment by asinha08** [comment]
Also please let me know shelljs version which is compatible with current forcedroid.

**Comment by kchitalia** [comment]
Current forcedroid should work with shelljs 0.5.3

Sent from my iPhone

On Feb 15, 2016, at 10:27 PM, Ashish Sinha <notifications@github.com> wrote:

Also please let me know shelljs version which is compatible with current
forcedroid.

—
Reply to this email directly or view it on GitHub
<https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1048#issuecomment-184541775>
.

**Comment by bhariharan** [comment]
@asinha08 Sometime this week.

**Comment by gsupratim0505** [comment]
@asinha08 when you install forcedroid or forceios the latest version of shelljs gets installed as a node module under forcedroid folder. you can uninstall shell js and install shelljs version 0.5.3 under forcedroid folder. it worked for me

**Comment by asinha08** [comment]
yup workaround solves the issue
