### ISSUE TITLE
New SmartStore entries in native Android app

### ISSUE THREAD

**Issue by fungi-fungi** [forcedotcom/SalesforceMobileSDK-Android#1065]
Hi,

I am trying to get syncUp to work and was wondering fs there is a reason why fields 
"__local__", "__locally_created__" etc are not set automatically on 

`smartStore.create(SOUP_NAME, object)`

please let me know if I am missing something. 

Best, Iurii

**Comment by wmathurin** [comment]
SmartStore can be used independently of SmartSync (it is just the store SmartSync happens to use).
The local and locally_created flags are for SmartSync only and therefore it doesn't make sense to have SmartStore's methods manage them.

**Comment by fungi-fungi** [comment]
Thank you for clarification
