### ISSUE TITLE
 Unable to instantiate application com.salesforce.androidsdk.phonegap.app.HybridApp: java.lang.ClassNotFoundException: Didn't find class "com.salesforce.androidsdk.phonegap.app.HybridApp va.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by saikumar100** [forcedotcom/SalesforceMobileSDK-Android#1079]
Hi, I m trying to develop salesforce hybrid_local app.
My cordova version@5.4.1
eclipse ADT 23.0.2
When ever i run my app in android device getting crashed.
Exception:03-14 17:39:19.268: E/AndroidRuntime(1236): java.lang.RuntimeException: Unable to instantiate application com.salesforce.androidsdk.phonegap.app.HybridApp: java.lang.ClassNotFoundException: Didn't find class "com.salesforce.androidsdk.phonegap.app.HybridApp
va.lang.ClassNotFoundException: Didn't find class "com.salesforce.androidsdk.phonegap.app.HybridApp" on path: DexPathList[[zip file "/data/app/com.test-8.apk"],nativeLibraryDirectories=[/data/app-lib/com.test-8, /vendor/lib, /system/lib]]

**Comment by wmathurin** [comment]
Was there any error when you generated your application with forcedroid?
It looks like the Mobile SDK library projects might be missing.

**Comment by saikumar100** [comment]
I have created project with cordova platform add android@5.0.0

**Comment by saikumar100** [comment]
Whenever i create an Android hybrid app with help of forcedroid, in terminal it is throwing error Variable(s) SENDER_ID missing. So because of that reason i am using cordova.
Full detailed steps in creating project is:
Step-1:
cordova create TestApp com.test.app TestApp.
Step-2:
Edited index.html,force.js,bootconfig.json files
Step-3:
Added cordova sdk plugin,
cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin
Step-3:
Added cordova plugin inAppBrowser
Step-4:
Installed shelljs@0.5.3
Step-4
cordova platform add android@5.0.0
---------
After this when ever i build using cordova i.e., cordova build got,
BUILD FAILED---
AndroidManifest.xml having duplicate PushHandlerActivity.

So instead of building from cordova i have build using Eclipse ADT where i got dependency error so after fixing every dependency build & run the project then apk is getting crashed.

**Comment by wmathurin** [comment]
Trying installing shelljs@0.5.3 first, then install the SalesforceMobileSDK-CordovaPlugin.

**Comment by jclark-dot-org** [comment]
I am having the same issue.  I originally worked around the sender ID issue by using a custom fork of SalesforceMobileSDK-CordovaPlugin that sets the SenderID, but based on [feedback from salesforce][1] on an upcoming patch to address this, I switched to the unstable branch of the official repo. Either way, I continue to have issues with the manifest file getting duplicate entries, as noted above and for which I have a workaround, and with this ClassNotFound error, for which I do not have a workaround.

I've posted a [full rundown on SF StackExchange][2], but at this point it doesn't add any much to the above discussion; this remains an open issue.

[1]: https://plus.google.com/106416138732002084790/posts/RHKzqZXFgdt
[2]: http://salesforce.stackexchange.com/questions/115033/cannot-create-working-remote-hybrid-android-app-with-mobile-sdk-4-1

**Comment by toddhalfpenny** [comment]
@jclark-dot-org I have seen that the order in which plugins are added is important when it comes to duplicate entries in the manifest. If you have more than one then at the moment I find I need to add the SF one last, and then add the platform; doing it this way I no longer see the errors in the manifest.

I have also mentioned this in https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1074#issuecomment-197744303

**Comment by jclark-dot-org** [comment]
@toddhalfpenny That's not working for me on a new forcedroid project with no other plugins, see my [comment  on issue #1074][1].  When you do this and it eliminates the duplicate entry issue, do you then get the ClassNotFoundException issue from the OP?

[1]: https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1074#issuecomment-201320241

**Comment by ravitheja-bandari** [comment]
Hi all, I am facing the same issue which @jclark-dot-org is facing while creating salesforce hybrid_local app. I tried all the fixes provided by @jclark-dot-org [here](http://salesforce.stackexchange.com/questions/115033/cannot-create-working-remote-hybrid-android-app-with-mobile-sdk-4-1?newreg=99bbdd7deef04288bf990d042248c2af) but ended up getting  java.lang.ClassNotFoundException: Didn't find class "com.salesforce.androidsdk.phonegap.app.HybridApp" with a crash and My app doesn't even open. 

Did anyone get a fix for the above error?

**Comment by saikumar100** [comment]
Hi, I have found the solution and you can check out here "https://sainickblog.wordpress.com/2016/04/20/creating-your-first-cordova-hybrid-android-app-using-salesforce-mobilesdkfor-linux-users/"

**Comment by ravitheja-bandari** [comment]
@saikumar100  I just created an application following the steps as mentioned in the link given by you. Still facing the same problem. Once I build and run the application either from android studio or from CLI, I am getting the following error. 

java.lang.ClassNotFoundException: Didn't find class "com.salesforce.androidsdk.phonegap.app.HybridApp"

**Comment by saikumar100** [comment]
1) Don't build Using this command "cordova build"
2)Open your salesforce project in latest version of Android studio.
3)Add gradle dependencies to ur project(if you are using Android studio then it will automatically include dependencies for you).
4)After importing project into android studio build your project in Android Studio.
5)Run android app inside android studio.

**Comment by bhariharan** [comment]
Closing this issue, since it is fixed.

**Comment by kanavkhurana** [comment]
Hi @saikumar100 The blog that you've mentioned doesn't exist anymore it seems. Could you please help me with how you got around the ClassNotFoundException?
@jclark-dot-org were you able to get around this? :)

**Comment by kanavkhurana** [comment]
Hi @saikumar100 and @bhariharan 
1. I imported the folder 'app name -> Platforms -> android into Android Studio without running "cordova build". 
2. When I'm trying to 'make' the android folder, I'm getting the following error:
Error:(15, -1) android-apt-compiler: [android] 
/platforms/android/AndroidManifest.xml:15: Tag <category> attribute name has invalid character '$'.
Error:(35, -1) android-apt-compiler: [android] 
/platforms/android/AndroidManifest.xml:35: Tag <permission> attribute name has invalid character '$'.
Error:(36, -1) android-apt-compiler: [android] 
/platforms/android/AndroidManifest.xml:36: Tag <uses-permission> attribute name has invalid character '$'.

Any idea how to get past this?

**Comment by kanavkhurana** [comment]
@bhariharan would appreciate some assistance here. :) We are Salesforce Developers without much knowledge about Android Development. I've been trying to get rid of this error for a week now. Any assistance would be highly appreciated! Thanks.

**Comment by wmathurin** [comment]
Please only use github issues for actual bugs.
To get help on how to use the Mobile SDK from our developer community, please please post your questions on our [Google+ community](https://plus.google.com/u/1/communities/114225252149514546445)

**Comment by kanavkhurana** [comment]
Thanks for responding @wmathurin. I will do that. Have a request - if this is a common issue, please share your thoughts here as well. Thanks in advance.

**Comment by kanavkhurana** [comment]
Thanks for the update! I have done that.

**Comment by saikumar100** [comment]
Hi @kanavkhurana , I have added a whole detailed steps of creating an hybrid app in below blog.
https://nickblogss.wordpress.com/2016/04/20/creating-your-first-cordova-hybrid-android-app-using-salesforce-mobilesdkfor-linux-users
