### ISSUE TITLE
React native error: Can't find variable: __fbBatchedBridge

### ISSUE THREAD

**Issue by lucyyu24** [forcedotcom/SalesforceMobileSDK-Android#1081]
Got JS Exception: ReferenceError: Can't find variable: __fbBatchedBridge

Getting this error when instantiating the app using forcedroid for react-native even though the server is running.

**Comment by wmathurin** [comment]
Please follow the recommendation here https://github.com/facebook/react-native/issues/4881#issuecomment-166148096
Re-open if you are still having issues.
