### ISSUE TITLE
Unable to run react native app

### ISSUE THREAD

**Issue by TRPLucy** [forcedotcom/SalesforceMobileSDK-Android#1084]
Running the react native template app in Android Studio, I get this exception:
`java.lang.AssertionError: Attached DialogModule to host with pending alert but no FragmentManager (not attached to an Activity).`
I made sure the server's running and I was able to log in to Salesforce, but the app crashes after login.

On the first run, I also got a:
`android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@8db00db -- permission denied for this window type`
I was able to bypass it by adding this:
```
if (!Settings.canDrawOverlays(this)) {
            Intent intent = new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,
                    Uri.parse("package:" + getPackageName()));
            startActivityForResult(intent, 1234);
        }
```

**Comment by wmathurin** [comment]
A fix is making its way into the unstable branch: see https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1085/commits/17153f666f4f8de43a7f6acd0e31926df1363aba

**Comment by TRPCindy** [comment]
Thanks. It works fine after I pull the unstable branch.
