### ISSUE TITLE
Getting AuthFailureError on SOQL Requests

### ISSUE THREAD

**Issue by rjain90** [forcedotcom/SalesforceMobileSDK-Android#1092]
Hi, I'm trying to execute queries in my android app but keep getting AuthFailureError everytime.  My code is:

```
sendRequest("SELECT Email__c, Phone__c, Address__c FROM Resume__c");

private void sendRequest(String soql) throws UnsupportedEncodingException {
     
     RestRequest restRequest = RestRequest.getRequestForQuery(getString(R.string.api_version), soul);
     if(restClient!=null) {
        restClient.sendAsync(restRequest, new RestClient.AsyncRequestCallback() {
            
            @Override
            public void onSuccess(RestRequest request, RestResponse result) {
            }

            @Override public void onError(Exception exception) { exception.printStackTrace(); }
```

**Comment by wmathurin** [comment]
What version of the SDK are you using?
How did you get your restClient object in the code above?

**Comment by rjain90** [comment]
I'm using SDK Version Code - 47, Version Name - 4.0.2.
I got the restClient in the onResume of the SalesforceActivity. We have used the same restClient object for other type of requests successfully. For Eg: the following request runs perfectly
`restClient.sendAsync(restRequest, new RestClient.AsyncRequestCallback(){...})`
where restRequest is a request to fetch feed-elements from a group.

**Comment by ritunagpal** [comment]
that's the same issue i am facing, i try to run(execute) the template app(which describes how to use the SOQL queries)included in the salesforce but no use,after executing the simple "SELECT Name from contacts" got the Auth Faliure error.

**Comment by wmathurin** [comment]
Make sure the oauth client id you are using in your application has the right scopes. For more information check out our developer guide: https://bitly.com/1vwq1rL
