### ISSUE TITLE
I'm trying to execute SOQL queries in my android app but keep getting AuthFailureError everytime

### ISSUE THREAD

**Issue by ritunagpal** [forcedotcom/SalesforceMobileSDK-Android#1094]
I also try to simply run the template app included in salesforce sdk but still i am getting auth faliure error.
api_version used is v35.0.
Following is my code :

 sendRequest("SELECT Name From CONTACTS");

private void sendRequest(String soql) throws UnsupportedEncodingException {
RestRequest restRequest = RestRequest.getRequestForQuery( getString(R.string.api_version), soql);
if(restClient!=null) {
restClient.sendAsync(restRequest, new RestClient.AsyncRequestCallback() {

    @Override
    public void onSuccess(RestRequest request, RestResponse result) {
    }

    @Override public void onError(Exception exception) { exception.printStackTrace(); }

**Comment by wmathurin** [comment]
Are you running the template application from the Mobile SDK repo or did you generate an application using forcedroid?

**Comment by ritunagpal** [comment]
I am running the app from mobile sdk repo(I simply take clone and import that in android studio and execute it).

I simply create an free trial account on salesforce and then 
I run the application named **Rest Explorer** and login from my username and password
and execute the simple query,

Please find the screenshot for your reference.
![screenshot_2016-03-30-16-48-09](https://cloud.githubusercontent.com/assets/16553830/14199086/c3d825f6-f7fe-11e5-967d-35718ac5a88b.png)

**Comment by wmathurin** [comment]
In a browser, could connect to your org using the workbench https://workbench.developerforce.com/login.php, then try to do the same query from the workbench's rest explorer?
I just want to make sure the user/org you are using is allowed to do those API calls.

**Comment by ritunagpal** [comment]
Thanks for your response,
Yes i think my account was expired now i have created an new account and that template app works.

But still i am not able to **execute the query for an organization** ,and yes i have made the chatter api requests with that object and succesully implemented it.
Here is the brief description what i have done

I included an server.xml file which takes the user to my organization url and after successfully login to my organization  , 
I got an object of restclient contains all the required info of the community(community id and community url) as well as user.

Now i am making an soql request followed by an example as explained in template sample app ,
But still i am getting the Auth Falue errror.

**Comment by wmathurin** [comment]
I don't think it's an SDK issue. It could be a permission issue. Have you tried your query in workbench:
https://workbench.developerforce.com/login.php

**Comment by ritunagpal** [comment]
Yes,actually those query works fine in the ios app,but not in android app.
Do you still think it can be the permission issue.

**Comment by ritunagpal** [comment]
Solved!

**Comment by bhariharan** [comment]
@ritunagpal What was the issue?

**Comment by ritunagpal** [comment]
Actually in boofconfig file we need to give the permission for token,which was missing.
