### ISSUE TITLE
README.md for forcedroid doesn't contain instructions about how to use forcedroid 

### ISSUE THREAD

**Issue by BrettMN** [forcedotcom/SalesforceMobileSDK-Android#1104]
The README.md at https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/hybrid/README.md states that: 

># Creating a new hybrid application using SalesforceSDK

>To create a new hybrid application, follow the instructions here:

>* [Using forcedroid to create Mobile SDK apps](https://www.npmjs.org/package/forcedroid)

And the link is for forcedroid on npmjs.org.  The README.md that is used for the npm packange contains no data for using forcedroid.  

Would it be possible to add details about the use of forcedroid and any important details to the README.md that is displayed for the npm package?

If not could references that say instructions are found at https://www.npmjs.org/package/forcedroid be removed?

**Comment by rwhitley** [comment]
We'll work on improving that, but in the meantime you can get the instructions from the Mobile SDK Dev Guide here: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/hybrid_ios.htm

**Comment by bhariharan** [comment]
Thanks for bringing this to our attention @BrettMN. The instructions for ```npm``` are [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/npm.md). Looks like there's a bug in the script that swaps the readme files while publishing. I'll look into getting that fixed.

**Comment by huminzhi** [comment]
The issue is fixed or solved in latest build.
