### ISSUE TITLE
Access the file from salesforce

### ISSUE THREAD

**Issue by ritunagpal** [forcedotcom/SalesforceMobileSDK-Android#1125]
Hi,I am using salesforce for my android app in backend.

and somewhere while using SOQL, I am getting response something like this : 

Article_FileNames":"Template.doc"
Article_FileContentTypes":"application/msword
Article_FileBodys":"/services/data/v35.0/sobjects/Hub_Knowledge_Articlekav/xxxxxxxxxxx/Article_FileBodys
ArticleNumber":"000001010
LastPublishedDate":"2015-12-09T20:34:48.000+0000

Now i am not getting, how I can let the user open the file named "Template.doc" on click.
How to open this file ?
is there any file path or id which will linkify this filename ?

Any help will be appreciated!

**Comment by wmathurin** [comment]
Please submit your question to our [Google Plus Community](http://sfdc.co/mobilesdkcommunity). We reserve the Issues site(s) for bug reporting. Thank you!
