### ISSUE TITLE
Creating a Salesforce Hybrid problems

### ISSUE THREAD

**Issue by claudiobarjasmartinez** [forcedotcom/SalesforceMobileSDK-Android#1156]
I tried to create a salesforce Hybride app, but when i want to run this on my android emulator it's not working. 

It's skipping the authentication screen(which was correctly implemented) and i'm seeing an empty user list. Just a blank user list, so somethings wrong with the android build of this project.

I've tried several ways, but i can't solve this. Does anyone else knows a way to correct this defect? Thx

**Comment by bhariharan** [comment]
This forum is for know bugs or issues in ```Mobile SDK``` code. For other questions or issues, please post on our Google+ community [here](https://plus.google.com/communities/114225252149514546445).
