### ISSUE TITLE
Post Apex Request

### ISSUE THREAD

**Issue by ritunagpal** [forcedotcom/SalesforceMobileSDK-Android#1235]
Please fill out the following details:

1. Version of Mobile SDK Used: 4.0.2
2. Issue found in Native App or Hybrid App:Native App
3. OS Version:ALL
4. Device:Android
5. Steps to reproduce: Apex call
6. Actual behavior:Volley Server Error
7. Expected Behavior: Succesfully make request
8. Error `Log:

I want to make an post apex request. The info i have is post endpoint and post body, I have successfully make the chatter api hits for our community but i don't know how to make an apex request.

In this request also like all other, we have to connect with the community? Also i go through some [links ](http://salesforce.stackexchange.com/questions/13294/patch-request-using-apex-httprequest)

which shows the post apex request but here also, how can i get(import) HTTPRequest class in my android project ? I tried to call but it in suggestion i cant see any HTTPRequest of salesforce/apex i can see only of apache.
req.setEndpoint(URL.getSalesforceBaseUrl().toExternalForm() + '/services/data/v28.0/sobjects/CurrencyType/');
is not avaible in apache http of android.

Please let me know where i am doing wrong ?`
Any help would be appreciated.

**Comment by huminzhi** [comment]
@ritunagpal Version of Mobile SDK Used: 4.0.2 is quite old, we are now at v4.3.
For rest request, you don't need to use HTTPRequest, you can use RestClient(RestRequest/RestResponse) in the SDK. You should be able to find some example [here](https://trailhead.salesforce.com/mobile_sdk_native_android/mobilesdk_android_rest_apis), hope it helps

**Comment by ritunagpal** [comment]
Ok @huminzhi, yes i have used restclient for chatter apis and integrate succesfully in android but i need help in using apex request in my project, i have endpoint url and post body to make this request.
It will be helpful if you can give any example to make this request.

**Comment by huminzhi** [comment]
@ritunagpal so if the url is absolute URL like "https://....", SDK won't change it during resolveURL..
so you just need to new RestRequest(RestMethod method, String path, RequestBody requestBody) with absolute path of you apex endpoint, then sendAsync it using RestClient..
