### ISSUE TITLE
forcedroid/Cordova issue when adding plugins

### ISSUE THREAD

**Issue by craigisakson** [forcedotcom/SalesforceMobileSDK-Android#1244]
Please fill out the following details:
1. Version of Mobile SDK Used: forcedroid v4.3.1
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: android-23
4. Device: n/a
5. Steps to reproduce: Unable to add Cordova plugins to the app created by forcedroid
6. Actual behavior: I create an app using forcedroid.  After the app is created, I add the plugins for Cordova that I need.  Due to other issues that I have solved in the past before I remove the Cordova Salesforce plugin and then re-add the plugin.  Everything run without error but when importing the project into Android Studio, there are build variant issues that pop up due to dependencies.  

We have been able to get around this somewhat by removing the shelljs npm package before the initial run of forcedroid create.  Then before re-adding the Salesforce plugin after adding the other plugins, we add shelljs back and it seems that the scripts that clean everything up works.  The problem with doing this is we are not able to add plugins to apps that are already developed so we would need to do a lot of rework once the plugin's are added.

To me, it seems like the issue would be related to shelljs and how it gets ran.  Any help with this issue would be greatly appreciated!
1. Expected Behavior:  The newly created app would compile.
2. Error Log:

Here is the run through the terminal.

Craig-Isaksons-MacBook-Air:TestApp craigisakson$ forcedroid version
forcedroid version 4.3.1

Craig-Isaksons-MacBook-Air:TestApp craigisakson$ forcedroid create
Enter your application type (native, react_native, hybrid_remote, or hybrid_local): hybrid_remote
Enter your application name: TEST
Enter the target directory of your app (defaults to current directory): 
Enter the package name for your app (com.mycompany.my_app): com.sundoginteractive.test
Enter the start page for your app (only applicable for hybrid_remote apps): start
Creating a new cordova project.
/Users/craigisakson/Desktop/TestApp/TEST /Users/craigisakson/Desktop/TestApp
Adding android project...
Creating Cordova project for the Android platform:
    Path: platforms/android
    Package: com.sundoginteractive.test
    Name: TEST
    Activity: MainActivity
    Android target: android-23
Android project created with cordova-android@5.0.0
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Fetching plugin "cordova-plugin-whitelist@1" via npm
Installing "cordova-plugin-whitelist" for android

```
           This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
```

Fetching plugin "https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin" via git clone
Repository "https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin" checked out to git ref "v4.3.1".
Installing "com.salesforce" for android
Dependent plugin "cordova-plugin-whitelist" already installed on android.
Fetching plugin "https://github.com/apache/cordova-plugin-device" via git clone
Repository "https://github.com/apache/cordova-plugin-device" checked out to git ref "r1.0.1".
Installing "cordova-plugin-device" for android
Fetching plugin "https://github.com/phonegap/phonegap-plugin-push" via git clone
Repository "https://github.com/phonegap/phonegap-plugin-push" checked out to git ref "1.5.0".
Installing "phonegap-plugin-push" for android
Running SalesforceMobileSDK plugin android post-install script
Moving Salesforce libraries to the correct location
Fixing Gradle dependency paths in Salesforce libraries
Fixing root level Gradle file for the generated app
include ":SalesforceSDK"

include ":SmartStore"

include ":SmartSync"

include ":SalesforceHybrid"

Moving Gradle wrapper files to application directory
Fixing application build.gradle
allprojects {
    repositories {
        mavenCentral()
    }
}
Done running SalesforceMobileSDK plugin android post-install script
Fixing AndroidManifest.xml file for Salesforce SDK Plugin.
Fixed AndroidManifest.xml
Removing duplicate entry from AndroidManifest.xml.
Removed duplicate entry in AndroidManifest.xml.
/Users/craigisakson/Desktop/TestApp

Your application project is ready in TEST.

To use your new application in Android Studio, do the following:
- Launch Android Studio and select `Import project (Eclipse ADT, Gradle, etc.)` from the Welcome screen
- Navigate to the TEST/TEST/platforms/android folder, select it and click `Ok`
- From the dropdown that displays the available targets, choose the sample app you want to run and click the play button

Before you ship, make sure to plug your OAuth Client ID,
Callback URI, and OAuth Scopes into www/bootconfig.json

Craig-Isaksons-MacBook-Air:TestApp craigisakson$ cd TEST

Craig-Isaksons-MacBook-Air:TEST craigisakson$ cordova plugin add cordova-plugin-inappbrowser
Fetching plugin "cordova-plugin-inappbrowser" via npm
Installing "cordova-plugin-inappbrowser" for android
Fixing AndroidManifest.xml file for Salesforce SDK Plugin.
Already fixed. Skipping.

Craig-Isaksons-MacBook-Air:TEST craigisakson$ cordova plugin add phonegap-plugin-barcodescanner
Fetching plugin "phonegap-plugin-barcodescanner" via npm
Installing "phonegap-plugin-barcodescanner" for android
Fetching plugin "cordova-plugin-compat" via npm
Installing "cordova-plugin-compat" for android
Fixing AndroidManifest.xml file for Salesforce SDK Plugin.
Already fixed. Skipping.

Craig-Isaksons-MacBook-Air:TEST craigisakson$ cordova plugin remove com.salesforce
Uninstalling 2 dependent plugins.
Uninstalling cordova-plugin-device from android
Uninstalling phonegap-plugin-push from android
Uninstalling com.salesforce from android
Removing "com.salesforce"

Craig-Isaksons-MacBook-Air:TEST craigisakson$ cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin
Fetching plugin "https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin" via git clone
Repository "https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin" checked out to git ref "master".
Installing "com.salesforce" for android
Dependent plugin "cordova-plugin-whitelist" already installed on android.
Fetching plugin "https://github.com/apache/cordova-plugin-device" via git clone
Repository "https://github.com/apache/cordova-plugin-device" checked out to git ref "r1.0.1".
Installing "cordova-plugin-device" for android
Fetching plugin "https://github.com/phonegap/phonegap-plugin-push" via git clone
Repository "https://github.com/phonegap/phonegap-plugin-push" checked out to git ref "1.5.0".
Installing "phonegap-plugin-push" for android
Running SalesforceMobileSDK plugin android post-install script
Moving Salesforce libraries to the correct location
Fixing Gradle dependency paths in Salesforce libraries
Fixing root level Gradle file for the generated app
include ":SalesforceSDK"

include ":SmartStore"

include ":SmartSync"

include ":SalesforceHybrid"

Moving Gradle wrapper files to application directory
Fixing application build.gradle
Done running SalesforceMobileSDK plugin android post-install script
Fixing AndroidManifest.xml file for Salesforce SDK Plugin.
Already fixed. Skipping.
Craig-Isaksons-MacBook-Air:TEST craigisakson$

**Comment by bhariharan** [comment]
This has been fixed [here](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/pull/258) and will be a part of our upcoming `Mobile SDK 5.0` release.
