### ISSUE TITLE
Salesforce Apex request

### ISSUE THREAD

**Issue by ritunagpal** [forcedotcom/SalesforceMobileSDK-Android#1255]
Please fill out the following details:

1. Version of Mobile SDK Used: 4.0.2
  2   Issue found in Native App or Hybrid App:Native App
 3    OS Version:ALL
  4   Device:Android
 5   Steps to reproduce: Apex call
 6  Actual behavior:Pdf in invalid format.

I am not able to open the email received on executing the apex request from the android app.
I am trying to execute the apex request using http method "GET" and passing some parameters and getting response as "OK" in result.
On successful, i get the mail of an document in pdf format.
But the problem is that the pf is not opening from my mail.
I always get the message "PDF IS N INVALID FORMAT".

But the ios app works.

**Comment by bhariharan** [comment]
@ritunagpal It sounds like the response was successful and you're getting the file back? We don't control what happens after the download is complete. Also, this forum is reserved for known issues/bugs with `Mobile SDK`. For other questions, please use our [Google+ Community](https://plus.google.com/u/1/communities/114225252149514546445).
