### ISSUE TITLE
Salesforce Community Hybrid Remote app Never Login after a session Timeout

### ISSUE THREAD

**Issue by GaneshSawant** [forcedotcom/SalesforceMobileSDK-Android#1271]
Please fill out the following details:
1. Version of Mobile SDK Used:  SalesforceSDK 4.3 /  cordova 5.4.0
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: Android Marshmallow
4. Device: One Plus Three/Samsung Galaxy S6
5. Steps to reproduce: Login to Salesforce Mobile hybrid App, keep it idle for some time(until session timeout value), after session timeout, we are not able to login back 
6. Actual behavior: User not able to login at all after Session timeout
7. Expected Behavior: User should be able to login everytime even if its a session timeout
8. Error Log:

**Comment by huminzhi** [comment]
@GaneshSawant  do you mean you cannot login even after enter username/password in the login page?  And what's the error message you are seeing?

**Comment by GaneshSawant** [comment]
@huminzhi .. thanks for follow up. Yes I cant go past login page after session timeout.
There is no error, the login history of community user shows successful login as well.
My initial investigation points that, app url after session timeout still contains the session id which is expired. Not sure how to reset the URL after session timeout.

**Comment by huminzhi** [comment]
That's indeed weird @GaneshSawant , actually in step5, you should not get logout, the mobile app should be able to refresh token and re-establish a session for you. It sounds like a bug in this area, let me double check and get back to you..

**Comment by GaneshSawant** [comment]
Thanks @huminzhi  for looking into this Issue.
I faced similar issue when trying to logout from the community hybrid app but that got fixed when I explicitly called the cordova Logout Method. 

In order to fix this issue, I again tried similar fix, calling logout Method on the Login Screen when there is a session timeout(I am checking if the URL contains Sid and if the the User is Guest user). 
This fix did work but then the cordova.js file I included on the Login page giving some popup messages. 

I am still not sure why as the same static resource is used on the landing page where we fixed the Logout button Issue previously.

**Comment by bhariharan** [comment]
@GaneshSawant In a hybrid app, you always need to call the explicit `Cordova` methods on our plugin for login and logout, i.e., `authenticate` and `logout`. Otherwise, the login or logout will only occur within the `WebView` and the native app would have no knowledge of this request.

**Comment by GaneshSawant** [comment]
@bhariharan  Thanks for your suggestions.
We have built hybrid remote app for our community. we did used the logout cordova method to resolve the logout issue.
May I get more details about the authenticate method, any reference documentation on how to use the authenticate method will be of great help.

As I pointed out earlier, on Session timeout the app URL contains the old Sid param and somehow not able to redirect even after successful login.
Will Authenticate method will work in this scenario ?

Many Thanks,
Ganesh

**Comment by huminzhi** [comment]
@GaneshSawant You can find more info in our trailhead: https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/dev_hybrid_apps_run.htm

**Comment by bhariharan** [comment]
@GaneshSawant You need to use our `Cordova OAuth` plugin. It sets the required session and domain cookies.

**Comment by GaneshSawant** [comment]
@bhariharan Thanks Again.
May I know what do you mean by use Cordova OAuth plugin ?
Do I need to call any specific method or just install the plugin as mentioned by @huminzhi  ?

Many Thanks :)

**Comment by GaneshSawant** [comment]
@huminzhi @bhariharan I guess I already installed the Cordova OAuth plugin... after running the command again... its showing existing files skipped messages.
please correct me if I am missing anything here.

In order to create a project on first place.. I used Forcedroid create method.

**Comment by GaneshSawant** [comment]
@bhariharan @huminzhi  Thanks guys for your suggestion.
Today when I tried  to used the Cordova Authenticate method... results were better as compared to logout method.

On the App login page I am trying to check if its a session timeout and if yes calling the cordova authenticate method.

If you launch the app after session timeout, on first launch it stuck to login page itself but somehow authenticate method did its part.
If you close the app and relaunch 2nd time, it will directly taking me to the landing page.

Session management screen showing new Session created automatically thanks to authenticate method.

Is there any way I can directly go to Landing page on first launch itself on Session timeout.
Onload Javascript 
					var sid = '{!SidPresent}';
					var mapp = '{!isMobileApp}';
					if(sid=='true' && mapp=='true') {
						window.alert('Session Expired... Please login Again');
						var sfOAuthPlugin = cordova.require("com.salesforce.plugin.oauth");
						sfOAuthPlugin.logout();
						sfOAuthPlugin.authenticate();		
		
					}	

I tried to use the getAppHomeUrl method along with authenticate as well but it didnt worked :(

Many thanks

**Comment by huminzhi** [comment]
@GaneshSawant You don't need to handle "Session Expired" because mobileSDK does all that for you... as long as you are using .authenticate() method, it should automatically refresh the session for you... BTW, will you please add this topic to our community: https://plus.google.com/u/1/communities/114225252149514546445. Thanks!

**Comment by bhariharan** [comment]
@GaneshSawant This forum is for known bugs/issues with our code. For everything else, please use our Google+ community mentioned above.
