### ISSUE TITLE
Clean Resync Ghosts get Object Name After From

### ISSUE THREAD

**Issue by mzaklama** [forcedotcom/SalesforceMobileSDK-Android#1273]
Please fill out the following details:

1. Version of Mobile SDK Used: 4.3.1
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Android 5.0
4. Device: Samsung
5. Steps to reproduce:
SoqlSyncDownTarget.java Line 154
If you have a field containing FROM, the split does not get the correct Soup/Object.
eg: I have a field called From_Customer__c and an Object called Stock_Transfers__c; the soql StringBuilder after line 154 is equal to "SELECT Id FROM_Customer__c," instead of "SELECT Id FROM Stock_Transfers".
I had to change this line to be soql.append(fromClause[fromClause.length - 1]);

**Comment by mzaklama** [comment]
My fix will not work if the Object itself contains "FROM"

**Comment by mzaklama** [comment]
A better fix is to change lines 152 and 153 to
soql.append(" FROM ");
final String[] fromClause = query.split("([ ][fF][rR][oO][mM])[ ]");

This way it will insure that we get the FROM that is not included in a Field name or an Object Name

**Comment by bhariharan** [comment]
@mzaklama Thanks for reporting this. Mind sending us a pull request against `unstable`?

**Comment by bhariharan** [comment]
Fixed [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1296).
