### ISSUE TITLE
Can't link external component to freshly created app

### ISSUE THREAD

**Issue by pedramsaleh** [forcedotcom/SalesforceMobileSDK-Android#1307]
Please fill out the following details:

1. Version of Mobile SDK Used: 4.3.1
2. Issue found in Native App or Hybrid App: Error "configuration with name default not found" when building React Native app in Android Studio
3. OS Version: macOS 10.12.1
4. Device: MacBook Pro
5. Steps to reproduce: create react_native app with forcedroid, install react-native-fs and try to incorporate into project by following these steps: https://github.com/johanneslumpe/react-native-fs#usage-android
6. Actual behavior: "Configuration with name default not found" error when building
7. Expected Behavior: Expected it to build
8. Error Log: Error:Configuration with name 'default' not found.

There is no "android" directory like when creating a project using react-native init, so the instructions for linking external components do not apply. The locations of build.gradle, settings.gradle and MainApplication.java are different. It's not clear if that file is used as expected since it's buried deep in the node_modules directory. Is there a mapping for the locations of configuration files created by forcedroid as opposed to creating a project with react-native init? That would help a lot when trying to link external libraries/components.

**Comment by wmathurin** [comment]
In our soon to be released 5.0 release, the generated application with forcedroid (or forceios) will be very similar to the one you get when using react-native init and so the issue you have above should be resolved.
(We are planning to release 5.0 in the next couple of weeks or so #safeharbor)
