### ISSUE TITLE
Issue with cleanResyncGhosts(long syncId)

### ISSUE THREAD

**Issue by jensonpp** [forcedotcom/SalesforceMobileSDK-Android#1339]
@bhariharan @wmathurin @khawkins 

1. Version of Mobile SDK Used: v4.3.1, v5.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 6.0.1
4. Device: Multiple devices like Samsung Galaxy S4, S6 Edge, Nexus5 etc

5. Steps to reproduce: Fetch data from a table in the remote server using a particular condition using syncDown in SmartSync library. Then again fetch data from the same table in the remote server with another condition. Data fetched in both the conditions will be different.

6. Actual behavior: Data fetched using the first condition is being removed from local DB by the cleanResyncGhosts(long syncId) method and the data fetched using the second condition remains in the local DB.

7. Expected Behavior: Data fetched by both conditions should remain in local DB even after cleanResyncGhosts(long syncId) method is invoked.

**Comment by wmathurin** [comment]
Unfortunately, as you discovered, cleanResyncGhosts will clean more that the ghosts if the table is populated through multiple sync down operations (since we don't record the sync down through which the record was downloaded). I'm tagging this issue as an enhancement and we will look at improving cleanResyncGhosts in the future.

**Comment by ramanRajSaxenaTry** [comment]
can you please tell something more on this that you you are using that long sync id for cleanResyncGhosts

**Comment by bhariharan** [comment]
This issue has been resolved [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1597) and will be a part of our next release.
