### ISSUE TITLE
forcedroid hybrid remote app not launching on Clicking Push Notification

### ISSUE THREAD

**Issue by GaneshSawant** [forcedotcom/SalesforceMobileSDK-Android#1341]
I recently upgraded the forcedroid version to 5.0,0 and we are working on the Hybrid remote app for our Salesforce community.

After enabling Push notifications, clicking on the Notification is not opening the app which was working previously with forcedroid version 4.3.0

Please do let me know if I am missing something or do we need to handle this explicitly ? 

Thank you,
Ganesh

**Comment by GaneshSawant** [comment]
Hello Team, 

May I please know if we have any update on the above issue ?

**Comment by bhariharan** [comment]
This should be fixed on the `dev` branch and will be a part of our upcoming `5.1` release. Feel free to reopen this issue if it exists in `5.1` as well.
