### ISSUE TITLE
Connected app name is "SalesforceMobileSDK Sample App"

### ISSUE THREAD

**Issue by mkoo21** [forcedotcom/SalesforceMobileSDK-Android#1347]
All of the apps we create using SalesforceMobileSDK create connected apps with the name "SalesforceMobileSDK Sample App". This name is also shown on the oauth authentication screen.
![screen_shot_2017-01-26_at_4 52 20_pm](https://cloud.githubusercontent.com/assets/12832801/22389649/bc7da922-e4b4-11e6-87b7-229565982205.png)

How can we change this to a different name?

**Comment by wmathurin** [comment]
That name is the name of the connected app you are using. 

You need to create your own connected app (see https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/connected_apps_howto.htm) and use it in your application.

When your run forcedroid/ios, the last thing printed in the terminal is something like

_Before you ship, make sure to plug your OAuth Client ID and Callback URI, and OAuth Scopes into (with the name of the file for the application generated)_

**Comment by majidalik** [comment]
I created a new one connected app and picked their consumer key and secret paste it in android app But still app showing **Connected app name is "SalesforceMobileSDK Sample App"**
