### ISSUE TITLE
POST sendRequest from Android not including complete body

### ISSUE THREAD

**Issue by rgoldiez** [forcedotcom/SalesforceMobileSDK-Android#1367]
(Moving https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/21 here)...

Please fill out the following details:

1. Version of Mobile SDK Used: 
SDK 5.0.1

2. Issue found in Native App or Hybrid App: 
React Native

3. OS Version: 
Android Marshmellow (although does not matter)

4. Device: 
Emulator (although does not matter)

5. Steps to reproduce: 
Perform a sendRequest with a JSON body that is more complex that a simple `{string: string}`, such as posting a chatter feed element.  Example React Native code below:

```
var endPoint = '/services/data';
var path = '/v35.0/connect/communities/'+communityID+'/chatter/feed-elements';
var body = { 
  body: { messageSegments: [ { type: 'Text', text: 'Hello from Android!' } ] }, // <-- note the complex portion of the body
  feedElementType: 'FeedItem',
  subjectId: subjectId,
  visibility: 'AllUsers' 
}
forceClient.sendRequest(
  endPoint,
  path,
  (resp) => {
    // success code here
    console.log(resp);
  },
  (err) => {
    // error code here
    console.log(err);
  },
  'POST',
  body
);
```

6. Actual behavior:
Portions of the body are dropped that do not conform to the Android/Java `Map<String, String>`.  Logs below from Android Studio.

SalesforceNetReactBridge.sendRequest called: 
```
{"endPoint":"/services/data","path":"/v35.0/connect/communities/0DB6100000000KLGAY/chatter/feed-elements","method":"POST","queryParams":{"body":{"messageSegments":[{"type":"Text","text":"Hello from Android!"}]},"feedElementType":"FeedItem","subjectId":"a0261000001lyo8AAA","visibility":"AllUsers"},"headerParams":{},"fileParams":{}}
```
The following response comes back:
```
[{"errorCode":"MISSING_ARGUMENT","message":"No attachment found and body is empty. Provide a non-empty 'text' parameter, or a rich input including non-empty message segments. If providing rich JSON/XML input in REST, make sure to include Content-Type header. In multipart REST, include the Content-Type in the part."}]
```
7. Expected Behavior:
Complete body is sent.

8. Error Log:
See above.

It seems that the issue is [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SalesforceNetReactBridge.java#L137) and [here]( https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SalesforceNetReactBridge.java#L170).  It appears that the sendRequest method on the native side is only prepared to accept a simple JSON object `{string: string}` and not something more complex, as you need to post a chatter message and other standard APIs.

**Comment by rgoldiez** [comment]
@wmathurin - Any ideas for a workaround, other than calling out to Salesforce with the standard React Native `fetch`, sticking in the token to the header, etc.

**Comment by wmathurin** [comment]
We'll try and fix it for the next release. Until then, you could fork the SDK and fix https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceReact/src/com/salesforce/androidsdk/reactnative/bridge/SalesforceNetReactBridge.java#L137 to expect a string->object map.

**Comment by rgoldiez** [comment]
Thanks @wmathurin.  I fixed per your suggested and created a PR -> https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1370

**Comment by bhariharan** [comment]
The PR has been merged.
