### ISSUE TITLE
Build.gradle file not correctly synced from SalesforceMobileSDK-Android when using forcedroid

### ISSUE THREAD

**Issue by cloaked-ninja** [forcedotcom/SalesforceMobileSDK-Android#1368]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.0.1
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Windows 10
4. Device: Android Studio 
5. Steps to reproduce:

Follow steps on Salesforce Mobile SDK Trailhead walkthrough (creating a new native using forcedroid npm package):

[Walkthrough](https://trailhead.salesforce.com/modules/mobile_sdk_native_android/units/mobilesdk_android_getting_started)

> At the command prompt, change to the directory where you want to store your project, then type:
> forcedroid create
> As forcedroid prompts you, enter the following values:
> Application type: native
> Application name: MyTrailNative
> Package name: com.mytrail.android
> Organization name: MyApps, Inc.
> Output directory: TrailAndroidApps

...

> From the welcome screen, select Import project (Eclipse ADT, Gradle, etc.). Or, if Android Studio is already running, select File | New | Import Project.
> Browse to your target directory—TrailAndroidApps—and click OK.
> Android Studio automatically builds your workspace. This process can take several minutes. When the status bar reports “Gradle build successful”, you’re ready to run the project.

6. Actual behavior:
Gradle sync fails.  

7. Expected Behavior:
Should be able to run the app on import per the Salesforce walkthrough.

Apparent cause is that build.gradle file not correctly updated from Github repository.

8. Error Log:

Error:(2, 0) Plugin with id 'com.github.dcendents.android-maven' not found.

To fix this error, need to go to Github repository for SalesforceMobileSDK-Android and manually copy and paste the code from [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/build.gradle) into the top 'build.gradle' file in the imported Android project.

Replaces this:
```
buildscript {
  repositories {
    jcenter()
  }

  dependencies {
    classpath 'com.android.tools.build:gradle:2.2.2'
  }
}

allprojects {
  repositories {
    jcenter()
  }
}
```

With this:
```
buildscript {
  repositories {
    jcenter()
  }

  dependencies {
    classpath 'com.android.tools.build:gradle:2.2.2'
    classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
  }
}

plugins {
  id "com.jfrog.bintray" version "1.7.3"
}

allprojects {
  group = 'com.salesforce.mobilesdk'
  version = '5.0.1'
  repositories {
    maven {
      // All of React Native (JS, Android binaries) is installed from npm
      url "$rootProject.projectDir/node_modules/react-native/android"
    }
    jcenter()
  }
}
```
Then the gradle file syncs.

**Comment by vinodr** [comment]
I am getting this error on the /libs/SalesforceReact/build.gradle file too.

**Comment by bhariharan** [comment]
@cloaked-ninja @vinodr Yup - I've fixed this in our `dev` branch. For now, please use `forcedroid@5.0.0` instead of `forcedroid@5.0.1` - there are no code changes in `5.0.1` over `5.0.0`. This is already fixed in the `dev` branch and will be in the next `forcedroid` release.

**Comment by carlosabella** [comment]
Hi, I know this issue is closed, but @bhariharan how do we use forcedroid@5.0.0 instead of forcedroid@5.0.1? I'm new in this world , I'm a little bit lost.

Thanks for your help

**Comment by bhariharan** [comment]
@carlosabella `npm install forcedroid@5.0.0`. Then `node_modules/.bin/forcedroid create`. Run through the steps to create an app.

**Comment by carlosabella** [comment]
Thanks!
