### ISSUE TITLE
com.salesforce issue for Cordova-android version@6.2.1

### ISSUE THREAD

**Issue by karthik2391** [forcedotcom/SalesforceMobileSDK-Android#1395]
Please fill out the following details:

1. Version of Mobile SDK Used: 25
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version:
4. Device: Android
5. Steps to reproduce:run command - cordova platform add android@6.2.1                                   
6. Actual behavior: Installing "com.salesforce" for android
 Plugin doesn't support this project's cordova-android version. cordova-android: 6.2.1, failed version requirement: 6.1.0
Skipping 'com.salesforce' for android
7. Expected Behavior: Create project
8. Error Log: 
9. Additional Info : If i use cordova-android@6.1.0 version  i am getting below error:
          Failed to install 'cordova-plugin-whitelist':Error: cmd: Command failed with exit code 1

Please help.  I am stuck on this for couple of days.

**Comment by bhariharan** [comment]
We don't support 6.2.1 yet. Please use 6.1.0.

**Comment by karthik2391** [comment]
I am facing below issue with 6.1.0
Failed to install 'cordova-plugin-whitelist':Error: cmd: Command failed with exit code 1 

is there any work around for this?

**Comment by bhariharan** [comment]
The issue you've reported clearly states that you're installing 6.2.1 instead of 6.1.0.

```
Steps to reproduce:run command - cordova platform add android@6.2.1
Actual behavior: Installing "com.salesforce" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 6.2.1, failed version requirement: 6.1.0
Skipping 'com.salesforce' for android
```

**Comment by karthik2391** [comment]
Yes i my question in additional info i have clearly mentioned in additional info that when i am using 6.1.0 i   am getting cordova-plugin-whitelist error. If i use 6.2.1 whitelist error is solved but  i am getting com.salesforce  issue

**Comment by rwhitley** [comment]
It looks like someone else solved it and posted on StackExchange. Does this help?

http://stackoverflow.com/questions/42784576/failed-to-install-cordova-plugin-whitelist-error-using-forcedroid-command-lin

**Comment by karthik2391** [comment]
Sorry i should  have posted  my  complete error log. My environment  variables  are set correctly no issue with that.  Please see error log for cordova-android@6.1.0

Installing "cordova-plugin-whitelist" for android
ANDROID_HOME=C:\Users\karthikeya_piduru\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_121
Subproject Path: CordovaLib
Exception in thread "main" java.lang.NullPointerException
        at org.gradle.wrapper.PathAssembler.getDistName(PathAssembler.java:77)
        at org.gradle.wrapper.PathAssembler.getDistribution(PathAssembler.java:43)
        at org.gradle.wrapper.Install.createDist(Install.java:43)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Failed to install 'cordova-plugin-whitelist':Error: cmd: Command failed with exit code 1
    at ChildProcess.whenDone (c:\BaxteTest\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Error: cmd: Command failed with exit code 1

**Comment by bhariharan** [comment]
Have you tried using `forcedroid` to set up your project and dependencies? The stack trace that you've posted doesn't have a lot of information on the failure.
