### ISSUE TITLE
Login Callback Method Called Twice

### ISSUE THREAD

**Issue by vinod1988** [forcedotcom/SalesforceMobileSDK-Android#1397]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.0
2. Issue found in Native App or Hybrid App: android native app
3. OS Version: 4.0.3 and above
4. Device: android 
5. Steps to reproduce: login and then call another activity (after login the activity called twice)
6. Actual behavior:  method called twice
7. Expected Behavior: It should be call once, When the login is success
8. Error Log:

	

      @Override
      public void onResume(RestClient client) {
             // Keeping reference to rest client
              this.client = client;
 		// Show everything
 	findViewById(R.id.root).setVisibility(View.VISIBLE);
 	isLoggedIn = true;
         if (client != null) {
          
         }

}

**Comment by bhariharan** [comment]
Yup - this is by design the first time login occurs.
Steps:
- Kick off your `MainActivity` -> `onResume` is called.
- `onResume` is where we attempt to fetch a valid `RestClient`.
- This kicks off the login flow -> `onPause` is called and `LoginActivity` is launched.
- Login process completes and `finish` is called on `LoginActivity`.
- `onResume` is called on `MainActivity` -> This time there's a valid `RestClient`.

**Comment by vinod1988** [comment]
Thanks for quick response.

Steps to replicate the issue in my app.

I have created the SplashActivity (this is my main activity) launch on first time install the application.

SplashActivity -----> if user is not logged in then its calling a LoginActivitity(Salesforce standard login). This time the onResume method called for my SplashActivity.

LoginActivity----> enter the valid username and password then onResume (SplashActvity called twice) and i am checking RestClient client is null or not if not null then passing the HomeActivity.

After few second the HomeActivity called twice. Let me know where is the loop whole or what mistake i am doing.
 

SplashActivity calling this method.

     @override
     public void onResume(RestClient client) {
             this.client = client;

               if (client != null  && this.client.getAuthToken() != null) {
                 // here i am calling my HomeActivity class
             }

      }

Let me know what mistake i am doing. Can you please guide me for this. Thanks for your response.

**Comment by bhariharan** [comment]
@vinod1988 Your `onResume` should look different. It should look more like [this](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/SalesforceActivity.java#L77). We have base activities in the `Mobile SDK` such as `SalesforceActivity` for this purpose, to do all the heavy-lifting around account management for you. You can simply extend `SalesforceActivity` and `onResume(RestClient client)` will be called when a valid client is available post-authentication. This avoids the issues you're seeing around double calling. I'd recommend that path.

**Comment by vinod1988** [comment]
@bhariharan Thanks for the reply.  I am giving you the my SplashActivity blue print code. Let me know where i am doing the wrong.

          
public class SplashActivity extends SalesforceActivity implements LoaderManager.LoaderCallbacks<JSONArray> {

    private RestClient client;
 
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);

		// Setup view
		setContentView(R.layout.activity_splash_main);

	}

	
	@Override
	public void onResume(RestClient client) {
	
        this.client = client;

 		if (client != null  && this.client.getAuthToken() != null) {
                      // here i am calling my HomeActivity class
                  }

	    }
     }

This is my code that i have written inside the SplashActivity let me know where i am doing the wrong or not calling the proper method.  @bhariharan  Can u please guide me for this snippet code where i am doing the wrong. Thanks for your response.

**Comment by bhariharan** [comment]
@vinod1988 This forum is reserved for known issues/bugs with our code. Please post other queries/discussions in our [Google+ community](https://plus.google.com/u/1/communities/114225252149514546445?cfem=1).
