### ISSUE TITLE
Native Android - SDK has no support for AppCompactActivity & AppCompactTheme

### ISSUE THREAD

**Issue by ravikanasagra1** [forcedotcom/SalesforceMobileSDK-Android#1398]
Please fill out the following details:

Version of Mobile SDK Used: 5 (latest)
Issue found in Native App or Hybrid App: Android Native
OS Version: 5 and above
Device: Any
Issue - I was going through sdk code and have observed that it is using Activity and has holo theme.

I want to have uniform material design. New applications are developed extending AppCompactActivity which is more suitable to have uniform material look and feel across various OS.

Kindly look into it.

**Comment by bhariharan** [comment]
The activities we provide out of the box are simply helpers. We don't have any UI components on the `Mobile SDK` other than `LoginActivity` and `PasscodeActivity`. You're welcome to use `AppCompatActivity` and `AppcompatTheme` in your application. The `Mobile SDK` should have no bearing on this.
