### ISSUE TITLE
Native Android - SDK has no support for AppCompactActivity & AppCompactTheme

### ISSUE THREAD

**Issue by ravikanasagra1** [forcedotcom/SalesforceMobileSDK-Android#1400]
Regd Closed Issue - https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1398 

Login flow worked using these SDK activities. Lets say I need my first activity to be app compact activity then I could not able to use it. My first activity should be SDK derived activity, what I understand here. Correct me if I am wrong.

**Comment by bhariharan** [comment]
@ravikanasagra1 The SDK derived activity simply provides helpers that automatically handle PIN policies, user switches, logout, etc. You can implement your own activity that's patterned on our top level activity. There's no restriction on what the first activity should be.

**Comment by ravikanasagra1** [comment]
Kindly wait before close an issue. I have to every time create  new issue for this ongoing issue. I would like SDK activity to be derived from AppCompactActivity.

**Comment by bhariharan** [comment]
@ravikanasagra1 I think you're missing the point. We don't have activities in the `Mobile SDK` that extend from `AppCompatActivity` deliberately because we don't want to have a dependency on the `Android Support Library`. You're welcome to create an implementation in your app.
