### ISSUE TITLE
Launcher screen after login

### ISSUE THREAD

**Issue by ravikanasagra1** [forcedotcom/SalesforceMobileSDK-Android#1401]
Please fill out the following details:

Version of Mobile SDK Used: 5 (latest)
Issue found in Native App or Hybrid App: Android Native
OS Version: 5 and above
Device: Any
Issue - I want to show splash screen to used once login operation is successful. I was trying to implement splash screen using splash activity on project created from forcedroid native template. I got stopped to make splash activity since one first activity derived from SDK activity requires first to call framework login activity and do authentication. Kindly help how do I implement splash screen? I would need it to do smart store & smart sync activity behind this splash screen between after login and before first activity load.

**Comment by bhariharan** [comment]
This forum is meant for bugs identified with the `Mobile SDK`. For queries/discussions, please use our [Google+ community](https://plus.google.com/communities/114225252149514546445).

**Comment by ravikanasagra1** [comment]
This https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1402 was bug too. :)
