### ISSUE TITLE
Plugin with id 'com.github.dcendents.android-maven-plugin' not found

### ISSUE THREAD

**Issue by jorgjanke** [forcedotcom/SalesforceMobileSDK-Android#1402]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.0.1
Android Studio: 2.3.1 

2. Issue found in Native App or Hybrid App:
Plugin with id 'com.github.dcendents.android-maven-plugin' not found
also replacing it with com.github.dcendents.android-maven-gradle-plugin did not help
nor did adding the dependency
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'

3. OS Version: MacOS 10.12
4. Device: -
5. Steps to reproduce: following steps in Trailhead with the current Android Studio version
https://trailhead.salesforce.com/trails/mobile_sdk_intro/modules/mobile_sdk_native_android/units/mobilesdk_android_getting_started 
6. Actual behavior: Plugin with id 'com.github.dcendents.android-maven-plugin' not found
7. Expected Behavior: no error
8. Error Log:

**Comment by jorgjanke** [comment]
... forgot to mention: in the example project, the top level build.gradle contains 
android { .. } - which the current Android Studio/SDK does not like.

**Comment by bhariharan** [comment]
I have fixed this [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1361/files#diff-dc87dd7b3fc7bb6d6127643a2c004527R1). This will be a part of our upcoming `5.1` release. Meanwhile, add the following lines to `build.gradle` to solve this:
```
buildscript {
     repositories {
         jcenter()
     }
 
     dependencies {
         classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
         classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3'
     }
 }
```

**Comment by jorgjanke** [comment]
Perfect - Thanks!

**Comment by Saitama0811** [comment]
Thanks sir worked like charm

**Comment by gitbharatarmy** [comment]
its working thanks

**Comment by RAVIKUMAR-GUJJULA** [comment]
Thanks you very much for your valueble solution

**Comment by fatihhidiroglu** [comment]
Thanks @bhariharan  problem solved.

**Comment by uvios** [comment]
Thanks It works

**Comment by sagarkhurana00786** [comment]
Thanks

**Comment by halilbulentorhon** [comment]
> I have fixed this [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1361/files#diff-dc87dd7b3fc7bb6d6127643a2c004527R1). This will be a part of our upcoming `5.1` release. Meanwhile, add the following lines to `build.gradle` to solve this:
> 
> ```
> buildscript {
>      repositories {
>          jcenter()
>      }
>  
>      dependencies {
>          classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
>          classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3'
>      }
>  }
> ```

Best solution ever!!!
