### ISSUE TITLE
Forcedroid create failed on Win 10, Win 8.1 and Mac 10.12

### ISSUE THREAD

**Issue by 8Bhatb** [forcedotcom/SalesforceMobileSDK-Android#1411]
Please fill out the following details:

Disclaimer : This is my first time posting an  issue, please be gentle :). I tried this on new VMs for Windows 10 and 8.1 and a clean macbook. All of them returned the same issue. Could someone use forcedroid on a fresh install and confirm it works without issues

1. Version of Mobile SDK Used: 5.1.0 (didnt specify a version, forcedroid seems to pull 5.1.0)
Node v7.10.0
NPM v4.2.0
GIT 2.12.2.2
2. Issue found in Native App or Hybrid App: hybrid remote
3. OS Version: Windows 10.1 Pro, Windows 8.1 Pro, Mac OSX 10.12 Sierra, 
4. Device: Android
5. Steps to reproduce: https://trailhead.salesforce.com/modules/mobile_sdk_hybrid/units/mobilesdk_hybrid_getting_started
6. Actual behavior:
forcedroid fails with an EISDIR error. This happens during 
cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v5.1.0 --force
On further research, the error is thrown in sha.get(p,function()) inside add-local-tarball.js. sha.get is expecting a file, instead, a directory in tmp folder is passed.
7. Expected Behavior:
forcedroid create succeeds and 
8. Error Log:
Errorlog attached

**Comment by 8Bhatb** [comment]
[2017-05-07T02_49_29_953Z-debug.log.txt](https://github.com/forcedotcom/SalesforceMobileSDK-Android/files/981512/2017-05-07T02_49_29_953Z-debug.log.txt)

**Comment by bhariharan** [comment]
Closing this issue, since there's an issue logged in the plugin repo for this.
