### ISSUE TITLE
Gradle dependency and minSDK lovering

### ISSUE THREAD

**Issue by Luten** [forcedotcom/SalesforceMobileSDK-Android#1417]
Please make SDK available by adding gradle dependency - it is Android industry standart way to add dependencies.

Also consider minAndroidSDK lovering - there are more than 20% audience on API<21 (accodring to https://developer.android.com/about/dashboards/index.html)

**Comment by Luten** [comment]
UPDATE:
Found gradle dependancy in blogpost:
https://rwhitleysfdc.wordpress.com/2017/02/14/consuming-mobile-sdk-for-android-through-gradle/

The good way is to add this as 1 step of integration:
Add to gradle dependency one of the following:
```
//For the SalesforceSDK library:
compile 'com.salesforce.mobilesdk:SalesforceSDK:5.0.0'

//For the SmartStore library (also imports the SalesforceSDK library):
compile 'com.salesforce.mobilesdk:SmartStore:5.0.0'

//For the SmartSync library (also imports the SalesforceSDK and SmartStore libraries):
compile 'com.salesforce.mobilesdk:SmartSync:5.0.0'
```

**Comment by bhariharan** [comment]
@Luten The steps to add our libraries from `jCenter` are documented in our [dev guide](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/android_update_maven.htm?search_text=gradle). As for our `minSDK`, it's currently `API 19`. We won't be lowering it below `19`.
