### ISSUE TITLE
SyncUpTarget Not syncup local soup data to salesforce, Android Native salesforce SDK

### ISSUE THREAD

**Issue by vinod1988** [forcedotcom/SalesforceMobileSDK-Android#1430]
Please fill out the following details:

1. Version of Mobile SDK Used:  5.0.1
2. Issue found in Native App or Hybrid App: Android Native
3. OS Version: 4.4.4
4. Device: Samsung
5. Steps to reproduce: Create the standard or custom object soup and add the data in soup and try to syncup on salesforce but the data is not showing on salesforce and syncup is showing done result.
6. Actual behavior: actual soup data will push to salesforce.
7. Expected Behavior: all soup data should be sync up to salesforce either standard or custom object.
8. Error Log: Its showing syncup done successfully 

       public synchronized void syncUp() {

        final SyncUpTarget target = new SyncUpTarget();

        final SyncOptions options = SyncOptions.optionsForSyncUp(Arrays.asList(OfflineOrderObject.OFFLINE_ORDER_FIELDS_SYNC_UP), SyncState.MergeMode.OVERWRITE);
        try {
            mSyncManager.syncUp(target, options, SoupName.OFFLINE_ORDER_SOUP, new SyncManager.SyncUpdateCallback() {

                @Override
                public void onUpdate(SyncState sync) {
                    if (SyncState.Status.DONE.equals(sync.getStatus())) {
                        DebugLog.d("Case syncUp done");
                        syncDownOfflineOrder();

                    } else if (SyncState.Status.FAILED.equals(sync.getStatus())) {
                        DebugLog.d("Case syncUp FAILED");

                    } else if (SyncState.Status.RUNNING.equals(sync.getStatus())) {
                        DebugLog.d("Case syncUp RUNNING");

                    } else if (SyncState.Status.NEW.equals(sync.getStatus())) {
                        DebugLog.d("Case syncUp NEW");
                    }
                }
            });
        } catch (JSONException e) {
            DebugLog.d("JSONException occurred while parsing"+e);
        } catch (SyncManager.SmartSyncException e) {
            DebugLog.d("SmartSyncException occurred while attempting to sync up"+e);
        }
    }

Note: the syncdown is working on my app successfully but when i am trying to created the data in my local and try to push it on salesforce the sync state showing me done but the data not up on salesforce. Let me know the cause for the syncup. Is there any configuration required for syncup.

Can any one please help me out for this issues.

**Comment by wmathurin** [comment]
Sync up looks for records marked as dirty (i.e. with the field \_\_local\_\_ set to true and also one or several of the fields \_\_locally\_created\_\_, \_\_locally\_updated\_\_, \_\_locally\_deleted\_\_). Make sure to set those fields on your locally created/modified/deleted records before calling sync up.

Anyway please on use github issues for actual bugs.
To get help on how to use the Mobile SDK, please go to our [Google community](https://plus.google.com/u/1/communities/114225252149514546445)

**Comment by vinod1988** [comment]
@wmathurin 

This is a bug. If i am wrong, Could please double check the my code while i am inserting into soup.
here is my code. And also i am setting all the fields required in for local and server sync up. I have used the mobile SDK properly as per your doc. All the data from salesforce sever is sync down only the bug in SDK is syncup data is not going on salesforce and not showing any issue. This is a major bug in SDK if the data is not sync up on the salesforce seer it should be show a error message for the incorrect soup entry or issue so that user can resolve it. Please sir i request you to check this and let me know why this bug comes in SDK.




          JSONObject offlineJSONObj = new JSONObject();

                offlineJSONObj.put(Constants.ID, "local_" + System.currentTimeMillis() + Constants.EMPTY_STRING);
                offlineJSONObj.put("_soupLastModifiedDate" , System.currentTimeMillis()+Constants.EMPTY_STRING);

                final JSONObject offAttributes = new JSONObject();
                offAttributes.put(Constants.TYPE.toLowerCase(), SoupName.OFFLINE_ORDER_SOUP);
                offlineJSONObj.put(Constants.ATTRIBUTES, offAttributes);

                offlineJSONObj.put(OfflineOrderObject.ACCOUNT , "001N000000qg8BEIAY");
                offlineJSONObj.put(OfflineOrderObject.CANCELLATION , Constants.NULL_STRING);
                offlineJSONObj.put(OfflineOrderObject.DEPOT , "a0wN00000048mkcIAA");
                offlineJSONObj.put(OfflineOrderObject.DISTRIBUTION , Constants.NULL_STRING);
                offlineJSONObj.put(OfflineOrderObject.DIVISION , Constants.NULL_STRING);
                offlineJSONObj.put(OfflineOrderObject.OFFLINE_MOBILE_LINE_ITEM , Constants.NULL_STRING);
                offlineJSONObj.put(OfflineOrderObject.ORDER_TYPE , "a1ON00000013SuzMAE");
                offlineJSONObj.put(OfflineOrderObject.REASON_FOR_CANCELLATION , "NO");
                offlineJSONObj.put(OfflineOrderObject.SALES_ORG , "India");
                offlineJSONObj.put(OfflineOrderObject.SAP_NUMBER , Constants.NULL_STRING);
                offlineJSONObj.put(OfflineOrderObject.SFDC_NUMBER , Constants.NULL_STRING);
                offlineJSONObj.put(OfflineOrderObject.SHIPPING_LOCATION , "a16N0000003TVYBIA4");
                offlineJSONObj.put(OfflineOrderObject.STATUS , "Draft");

                offlineJSONObj.put(SyncManager.LOCAL, true);
                offlineJSONObj.put(SyncManager.LOCALLY_UPDATED, false);
                offlineJSONObj.put(SyncManager.LOCALLY_CREATED, true);
                offlineJSONObj.put(SyncManager.LOCALLY_DELETED, false);

                JSONObject responseOfflineJSONObj = mSmartStore.create(SoupName.OFFLINE_ORDER_SOUP, offlineJSONObj);

**Comment by wmathurin** [comment]
This code looks okay. But I would have to see the soup creation code and the sync up code as well.
Sync up is used by hundred of apps successfully so I don't think it's a bug. Please post your question on the google + community.

**Comment by vinod1988** [comment]
@wmathurin Thanks for your reply. I am just giving the my soup creation and sync up code below with steps.

    public class OfflineOrderLoaders extends AsyncTaskLoader<JSONArray> {

    private final SmartStore mSmartStore;
    private final SyncManager mSyncManager;
    private long accountSyncId = -1;


    public OfflineOrderLoaders(Context context, UserAccount account) {
        super(context);
        mSmartStore = SmartSyncSDKManager.getInstance().getSmartStore(account);
        mSyncManager = SyncManager.getInstance(account);
    }


    @Override
    public JSONArray loadInBackground() {
        if (!mSmartStore.hasSoup(SoupName.OFFLINE_ORDER_SOUP)) {
            return null;
        }

        final QuerySpec querySpec = QuerySpec.buildAllQuerySpec(SoupName.OFFLINE_ORDER_SOUP, null, QuerySpec.Order.ascending, OfflineOrderObject.LIMIT);
        JSONArray results = null;
        try {
            results = mSmartStore.query(querySpec, 0);
            DebugLog.d("results="+results);

        } catch (JSONException e) {
            DebugLog.d("JSONException occurred while parsing"+e);
        } catch (SmartSqlHelper.SmartSqlException e) {
            DebugLog.d("SmartSqlException occurred while fetching data"+e);
        }

        return results;
    }



    /**
     * Pushes local changes up to the server.
     */
    public synchronized void syncUp() {

        final SyncUpTarget target = new SyncUpTarget();

        final SyncOptions options = SyncOptions.optionsForSyncUp(Arrays.asList(OfflineOrderObject.OFFLINE_ORDER_FIELDS_SYNC_UP), SyncState.MergeMode.OVERWRITE);
        try {
            mSyncManager.syncUp(target, options, SoupName.OFFLINE_ORDER_SOUP, new SyncManager.SyncUpdateCallback() {

                @Override
                public void onUpdate(SyncState sync) {
                    if (SyncState.Status.DONE.equals(sync.getStatus())) {
                        DebugLog.d("Case syncUp done");
                        syncDownOfflineOrder();

                    } else if (SyncState.Status.FAILED.equals(sync.getStatus())) {
                        DebugLog.d("Case syncUp FAILED");

                    } else if (SyncState.Status.RUNNING.equals(sync.getStatus())) {
                        DebugLog.d("Case syncUp RUNNING");

                    } else if (SyncState.Status.NEW.equals(sync.getStatus())) {
                        DebugLog.d("Case syncUp NEW");
                    }
                }
            });
        } catch (JSONException e) {
            DebugLog.d("JSONException occurred while parsing"+e);
        } catch (SyncManager.SmartSyncException e) {
            DebugLog.d("SmartSyncException occurred while attempting to sync up"+e);
        }
    }



    /**
     * Pulls the latest records from the server.
     */
    public synchronized void syncDownOfflineOrder() {

        mSmartStore.registerSoup(SoupName.OFFLINE_ORDER_SOUP, OfflineOrderObject.OFFLINE_ORDER_INDEX_SPEC);

        final SyncManager.SyncUpdateCallback callback = new SyncManager.SyncUpdateCallback() {

            @Override
            public void onUpdate(SyncState sync) {
                if (SyncState.Status.DONE.equals(sync.getStatus())) {
                    // fireLoadCompleteIntent();
                    DebugLog.d("syncDownOfflineOrder done");
                }
            }
        };
        try {
            if (accountSyncId == -1) {

                final SyncOptions options = SyncOptions.optionsForSyncDown(SyncState.MergeMode.LEAVE_IF_CHANGED);

                final String soqlQuery = SOQLBuilder.getInstanceWithFields(OfflineOrderObject.OFFLINE_ORDER_FIELDS_SYNC_DOWN).from(SoupName.OFFLINE_ORDER_SOUP).limit(OfflineOrderObject.LIMIT).build();

                DebugLog.d("soqlQuery="+soqlQuery);

                final SyncDownTarget target = new SoqlSyncDownTarget(soqlQuery);
                final SyncState sync = mSyncManager.syncDown(target, options, SoupName.OFFLINE_ORDER_SOUP, callback);
                accountSyncId = sync.getId();
            } else {
                mSyncManager.reSync(accountSyncId, callback);
            }
        } catch (JSONException e) {
            DebugLog.e("JSONException occurred while parsing"+e);
        } catch (SyncManager.SmartSyncException e) {
            DebugLog.e("SmartSyncException occurred while attempting to sync down"+e);
        }
    }


}




Step-1 I am calling this on after user login with salesforce successfully.
Step-2 I am calling the above class methods for data sync down. using below code.

		OfflineOrderLoaders offlineOrderLoaders = new OfflineOrderLoaders(this, mUserAccount);
		offlineOrderLoaders.syncDownOfflineOrder();

Step-3 The above 2 line of code will sync down all the data from salesforce to my local soup and its showing it on soup entry successfully.

Step-4 Using below code to  create the soup entry in my local soup.

JSONObject offlineJSONObj = new JSONObject();

            offlineJSONObj.put(Constants.ID, "local_" + System.currentTimeMillis() + Constants.EMPTY_STRING);
            offlineJSONObj.put("_soupLastModifiedDate" , System.currentTimeMillis()+Constants.EMPTY_STRING);

            final JSONObject offAttributes = new JSONObject();
            offAttributes.put(Constants.TYPE.toLowerCase(), SoupName.OFFLINE_ORDER_SOUP);
            offlineJSONObj.put(Constants.ATTRIBUTES, offAttributes);

            offlineJSONObj.put(OfflineOrderObject.ACCOUNT , "001N000000qg8BEIAY");
            offlineJSONObj.put(OfflineOrderObject.CANCELLATION , Constants.NULL_STRING);
            offlineJSONObj.put(OfflineOrderObject.DEPOT , "a0wN00000048mkcIAA");
            offlineJSONObj.put(OfflineOrderObject.DISTRIBUTION , Constants.NULL_STRING);
            offlineJSONObj.put(OfflineOrderObject.DIVISION , Constants.NULL_STRING);
            offlineJSONObj.put(OfflineOrderObject.OFFLINE_MOBILE_LINE_ITEM , Constants.NULL_STRING);
            offlineJSONObj.put(OfflineOrderObject.ORDER_TYPE , "a1ON00000013SuzMAE");
            offlineJSONObj.put(OfflineOrderObject.REASON_FOR_CANCELLATION , "NO");
            offlineJSONObj.put(OfflineOrderObject.SALES_ORG , "India");
            offlineJSONObj.put(OfflineOrderObject.SAP_NUMBER , Constants.NULL_STRING);
            offlineJSONObj.put(OfflineOrderObject.SFDC_NUMBER , Constants.NULL_STRING);
            offlineJSONObj.put(OfflineOrderObject.SHIPPING_LOCATION , "a16N0000003TVYBIA4");
            offlineJSONObj.put(OfflineOrderObject.STATUS , "Draft");

            offlineJSONObj.put(SyncManager.LOCAL, true);
            offlineJSONObj.put(SyncManager.LOCALLY_UPDATED, false);
            offlineJSONObj.put(SyncManager.LOCALLY_CREATED, true);
            offlineJSONObj.put(SyncManager.LOCALLY_DELETED, false);

            JSONObject responseOfflineJSONObj = mSmartStore.create(SoupName.OFFLINE_ORDER_SOUP, offlineJSONObj);

This code create the soup entry in my local soup successfully. 

Step-5 I have one sync button in my applications, When i click on the sync button i am calling the below code. i am calling below method on my sync button on click method. 

 private void startLocalDataSync()  {

        Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {

                final SalesforceSDKManager sdkManager = SalesforceSDKManager.getInstance();

                Account useraccount = SmartSyncSDKManager.getInstance().getUserAccountManager().buildAccount(mUserAccount);
                final UserAccount user = sdkManager.getUserAccountManager().buildUserAccount(useraccount);

                OfflineOrderLoaders offlineOrderLoaders = new OfflineOrderLoaders(TmHomeActivity.this, user);
                offlineOrderLoaders.syncUp();

                DebugLog.d("Sync data on server");
            }
        });

        thread.start();

    }

Step-6 Now the issue is that the syncup is called and the sync state is showing me  a done. The syncup data is not coming in salesforce but the salesforce data is coming on sync down method. 

Let me know this sync up bug, Why this is showing me the done state if the data is not enter on salesforce, this is a major bug for  data syncup issues.

**Comment by wmathurin** [comment]
What's in OFFLINE_ORDER_INDEX_SPEC?

**Comment by vinod1988** [comment]
@wmathurin thanks for your reply. Its my indexspec. Below is my snippet code. Let me know why this happen. But i have tried it on my developer account using this url (login.salesforce.com) for my developer org the data is syncup on salesforce but when i am trying for license sandbox account its not working and even not showing any error. If something went wrong with permission it should be show a generic error message. I think this is am biggest bug in sync up call. Still i am doing the RND with salesforce. 

Let me know if i am figure out or you can help me out for that.

     public static IndexSpec[] OFFLINE_ORDER_INDEX_SPEC = {

            new IndexSpec("Id", SmartStore.Type.string),
            new IndexSpec(ACCOUNT, SmartStore.Type.string),
            new IndexSpec(CANCELLATION, SmartStore.Type.string),
            new IndexSpec(DEPOT, SmartStore.Type.string),
            new IndexSpec(DISTRIBUTION, SmartStore.Type.string),
            new IndexSpec(DIVISION, SmartStore.Type.string),
            new IndexSpec(OFFLINE_MOBILE_LINE_ITEM, SmartStore.Type.string),
            new IndexSpec(ORDER_TYPE, SmartStore.Type.string),
            new IndexSpec(REASON_FOR_CANCELLATION, SmartStore.Type.string),
            new IndexSpec(SALES_ORG, SmartStore.Type.string),
            new IndexSpec(SAP_NUMBER, SmartStore.Type.string),
            new IndexSpec(SFDC_NUMBER, SmartStore.Type.string),
            new IndexSpec(SHIPPING_LOCATION, SmartStore.Type.string),
            new IndexSpec(STATUS, SmartStore.Type.string),

            new IndexSpec(SyncManager.LOCALLY_CREATED, SmartStore.Type.string),
            new IndexSpec(SyncManager.LOCALLY_UPDATED, SmartStore.Type.string),
            new IndexSpec(SyncManager.LOCALLY_DELETED, SmartStore.Type.string),
            new IndexSpec(SyncManager.LOCAL, SmartStore.Type.string)

    };

**Comment by wmathurin** [comment]
If you use Mobile SDK 5.1, you will get more log messages during sync operations by doing:
```java
syncManager.getLogger().setLogLevel(Log.DEBUG);
```
You should be able to pinpoint what error is happening and when from the logs.

**Comment by vinod1988** [comment]
@wmathurin thanks for reply. But i am using the SDK version 5.0.1 how to upgrade it for 5.1?

**Comment by bhariharan** [comment]
Please follow the upgrade steps outlined in our dev guide [here](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/migration_android_50_51.htm).

**Comment by azharosws** [comment]
Even i am getting such problem. Any solution for syncup?

**Comment by dineshkarthi95** [comment]
Im facing the Similar problem Syncdown is working fine but SyncUp is not working and im getting status as Done

**Comment by sabyasachiRepo** [comment]
@dineshkarthi95 make sure while inserting soup data locally you have type and attribute field involved. check @vinod1988 code for reference
