### ISSUE TITLE
Skipping authentication in android native app

### ISSUE THREAD

**Issue by EssenKh** [forcedotcom/SalesforceMobileSDK-Android#1431]
Encountring problem while developing using SalesforceMobileSDK with native android app, 
Can't retrieve data without authentication to the salesforce platform.
display data without authentication
this issue is not discussed on SalesforceMobileSDK google+ group, many posts about it without answers.
Regards

**Comment by bhariharan** [comment]
@EssenKh This forum is for known bugs/issues in our code. Please use the Google+ community for everything else.

**Comment by EssenKh** [comment]
@bhariharan 
I am stuck for many days and I have posted my problem many times on Google+ community and no one can answer them.
Thank you for advance, If you can have a look on my issue.
Best Regards

**Comment by bhariharan** [comment]
What is the issue?

**Comment by EssenKh** [comment]
@bhariharan 
While I am working on a project, Salesforce Mobile application destinated to two types of users, user as visitor to my application, and a user as my client.
The visitor doesn't have an account to access to the app. But He  have access to see some news, and gelocation info that comes from salesforce.
My issue is how to access data without authentication, is there any way to display data for this user ?
if not ! is there anyway to make authentication in background with specific login and password just to display data.
Regards

**Comment by EssenKh** [comment]
@bhariharan 
I am using forcedroid native application

**Comment by bhariharan** [comment]
It depends on how you've set up the data on your org. If the APIs require authentication, then you have to use the `WebView` for authentication. There's no way to get around it without user input.

**Comment by EssenKh** [comment]
do you mean, setting connected app ?

**Comment by bhariharan** [comment]
@EssenKh This discussion is more suited for the community. Please read Salesforce documentation and help articles on how to configure your org. This is not related to the `Mobile SDK` product, which is simply a client side mobile framework.

**Comment by EssenKh** [comment]
@bhariharan 
I am student and this is my final project and soon my defense, I am really stuck from March till now with ionic technologies and cordova, and it's ended by geting rid of one of modules i have validated on trailhead.
I see there is no community and documentation whenever i post, no one answer.
Best Regards.

**Comment by EssenKh** [comment]
@bhariharan 
bu the way I read SalesforceMobileSDK doc, and on page 144 i found that there is a method on react called shouldAuthenticate, as I understand, setting false as return to this method will skip authentication
