### ISSUE TITLE
Cannot use NoActionBar theme for the LoginActivity

### ISSUE THREAD

**Issue by emsto** [forcedotcom/SalesforceMobileSDK-Android#1433]
We are developing a native Android app connected to a Salesforce Community and we want to remove the Action Bar on the Login Activity and disable the server add/switch capabilities. We are doing this by setting a _NoActionBar_ theme for the Login Activity, but unfortunately the activity crashes with a NullPointerException: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setTitle(java.lang.CharSequence)' on a null object reference at com.salesforce.androidsdk.ui.LoginActivity.loadingLoginPage(LoginActivity.java:237) at com.salesforce.androidsdk.ui.OAuthWebviewHelper.doLoadPage(OAuthWebviewHelper.java:301)

After a quick check it turned out that the action bar is referenced only the _com.salesforce.androidsdk.ui.LoginActivity.loadingLoginPage_ method and a simple check for null reference solves our issue. Is that the right way to get rid of the action bar? If yes, I can do a pull request with the change?

**Comment by bhariharan** [comment]
@emsto You're right - a null check is warranted there. I have fixed it [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1434/files#diff-00654ecc1155238a85af0ef1831eb307R237). Feel free to cherry-pick this change in your project. This will be a part of our next release.
