### ISSUE TITLE
com.salesforce.androidsdk.app.SalesforceSDKManager cannot be cast to com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager

### ISSUE THREAD

**Issue by EssenKh** [forcedotcom/SalesforceMobileSDK-Android#1435]
while using 
Please these instructions are from the documentation of SalesforceMobileSDK and from trailhead ( offline management module)

If someone doesn't think that is an issue, I don't know what to consider it as I followed all steps to implement SmartStore.

```
 SmartStoreSDKManager sdkManager = SmartStoreSDKManager.getInstance();
 SmartStore mSmartStore = sdkManager.getSmartStore();

```

Best Regards

**Comment by EssenKh** [comment]
@wmathurin 
I am building native android application. 
I am using the forcedroid package ( forcedroid create ) 
The versionof Mobile SDK is 5.1.0.
Best Regards

**Comment by wmathurin** [comment]
In MainApplication.java
Please replace
```Java
SalesforceSDKManager.initNative(getApplicationContext(), new NativeKeyImpl(), MainActivity.class);
```
With
```Java
SmartSyncSDKManager.initNative(getApplicationContext(), new NativeKeyImpl(), MainActivity.class);
```

@rwhitley we should probably indicate that in the trail

**Comment by EssenKh** [comment]
@wmathurin 
I didn't even use this instrution. It is not figured on the doc.
I already try it, but if I use this instruction I need a SmartStoreSDKManager to instanciate SmartStore 
` SmartStore mSmartStore = sdkManager.getSmartStore();`

**Comment by EssenKh** [comment]
@wmathurin 
How  can I use smartStore using this instruction ?

**Comment by rwhitley** [comment]
Will do @wmathurin.

**Comment by wmathurin** [comment]
Please open MainApplication.java, make the change I recommended above, and then it will work.

**Comment by rwhitley** [comment]
@EssenKh also be sure to add the following import statement to your files if you don't have it already:

`import com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager;`
