### ISSUE TITLE
no such remote ref ebe577be9afc4680b7125199e02617678bcf9ef5

### ISSUE THREAD

**Issue by lnpquang** [forcedotcom/SalesforceMobileSDK-Android#1443]
Please fill out the following details:

1. Version of Mobile SDK Used:  5.1
2. Issue found in Native App or Hybrid App: React Native iOS/Android 
3. OS Version: Mac OS 10.12.5
4. Device: 
5. Steps to reproduce: npm install
6. Actual behavior: can't install module
7. Expected Behavior: npm install should work correctly
8. Error Log:

WithNewModule SalesforceMobileSDK-Android@5.1.0 checking installable status
error git submodule -q update --init --recursive: error: no such remote ref ebe577be9afc4680b7125199e02617678bcf9ef5
error git submodule -q update --init --recursive: Fetched in submodule path 'external/react-native', but it did not contain ebe577be9afc4680b7125199e02617678bcf9ef5. Direct fetching of that commit failed.
silly fetchPackageMetaData Error: Command failed: git submodule -q update --init --recursive
silly fetchPackageMetaData error: no such remote ref ebe577be9afc4680b7125199e02617678bcf9ef5
silly fetchPackageMetaData Fetched in submodule path 'external/react-native', but it did not contain ebe577be9afc4680b7125199e02617678bcf9ef5. Direct fetching of that commit failed.
.....
silly fetchPackageMetaData  error for salesforcemobilesdk-ios@git+https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#v5.1.0 { Error: Command failed: git submodule -q update --init --recursive
silly fetchPackageMetaData error: no such remote ref ebe577be9afc4680b7125199e02617678bcf9ef5
silly fetchPackageMetaData Fetched in submodule path 'external/react-native', but it did not contain ebe577be9afc4680b7125199e02617678bcf9ef5. Direct fetching of that commit failed.
......

**Comment by wmathurin** [comment]
We are looking into it. Thanks.
Also in the next release, we will make sure that we do a shallow git clone (it will speed up app creation).

**Comment by wmathurin** [comment]
Please try again, it should work now.

**Comment by lnpquang** [comment]
Thanks for your help!
It works properly now.

Best regards,
LNPQuang
