### ISSUE TITLE
Forcedroid project creation failed

### ISSUE THREAD

**Issue by trustsantosh** [forcedotcom/SalesforceMobileSDK-Android#1447]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.1.0
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: Windows 10
4. Device: Laptop
5. Steps to reproduce:  Type command "forcedroid create" and after some time error occur "Command failed cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin --force
"
6. Actual behavior: Cordova project creation failed due to which connection to Salesforce via Connected App is not possible.
7. Expected Behavior: Cordova project to be created with no error
8. Error Log:

**Comment by bhariharan** [comment]
@trustsantosh I notice you filed [the same issue](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/317) in our plugin repo as well. Please avoid creating duplicates of the same issue across multiple repos. Thanks.
