### ISSUE TITLE
How to load data with offset

### ISSUE THREAD

**Issue by booker-laputa** [forcedotcom/SalesforceMobileSDK-Android#1448]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.1
2. Issue found in Native App or Hybrid App: Hybrid
3. OS Version: 4.4
4. Device: Simulator
5. Steps to reproduce: Load data from soup, scroll list to bottom
6. Actual behavior: load more data from soup without duplicate
7. Expected Behavior: nothing
8. Error Log:

**Comment by wmathurin** [comment]
This forum is for known bugs/issues in our code. Please use the [Google+ community](https://plus.google.com/communities/114225252149514546445) for everything else.

**Comment by NeliHarbuzava** [comment]
Hi, Google + is unavailable now. Where we can find info about how to make queries with OFFSET?

**Comment by bhariharan** [comment]
@NeliHarbuzava Please post your queries on `Salesforce Stack Exchange`.
