### ISSUE TITLE
Compatibility with React-Native to version 0.46.1

### ISSUE THREAD

**Issue by wincychan** [forcedotcom/SalesforceMobileSDK-Android#1451]
1. Version of Mobile SDK Used:  v5.1.0
2. Issue found in Native App or Hybrid App: React-Native App
3. OS Version: -
4. Device: -
5. Steps to reproduce:
I have tried to update react-native project by using [Forcedroid] (https://www.npmjs.com/package/forcedroid) which contain SalesforceMobileSDK-Android. I force update react-native version from 0.43.1 to 
0.46.1. It builds successfully but it crashed when I open it. Will SalesforceMobileSDK-Android have any update for react-native 0.46.1? Or any impact for the current version of SalesforceMobileSDK-Android when I update react-native version?

**Comment by bhariharan** [comment]
@wincychan We don't support `react-native@0.46.1` at the moment. Please use `0.43.1` with our plugin for now. We will upgrade this is a future release.
