### ISSUE TITLE
Suspicious OutOfIndexException in Encryptor#decrypt

### ISSUE THREAD

**Issue by LyndonChin** [forcedotcom/SalesforceMobileSDK-Android#1465]
In the code below, if paddingValue is 0, the initialization of local variable `compare` will cause an OutOfIndexException。

```java
byte[] padded = cipher.doFinal(meat, 0, meatLen);
byte[] result = padded;
byte paddingValue = padded[padded.length - 1];
if (0 <= paddingValue) {
    if (paddingValue < (byte) 16) {
        byte compare = padded[padded.length - paddingValue];
        if (compare == paddingValue) {
            result = new byte[padded.length - paddingValue];
            System.arraycopy(padded, 0, result, 0, result.length);
        }
    }
}
```

**Comment by wmathurin** [comment]
Thanks @LyndonChin 
We used to pad with the number of pad bytes then dropped that code from the encrypt method.
Somehow the code was left (and later patched incorrectly) in the decrypt code.
It's getting fixed with https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1487
