### ISSUE TITLE
Auth Token Failure

### ISSUE THREAD

**Issue by jayakrishnansalim** [forcedotcom/SalesforceMobileSDK-Android#1468]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.2.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 7.1.1
4. Device: Nexus 6P
5. Steps to reproduce: Login as one user, then logout, relogin as another user
6. Actual behavior: While relogin as a different user, 'android.accounts.AuthenticatorException: getAuthToken failed' issue is occurring and user is taken back to the login screen again and this repeats. When we relogin as the same user, there is no issue. Also when the app is killed from the background and launched again, there is successful login. Only issue is when we login as a separate user. 
7. Expected Behavior: User should be able to login
8. Error Log: 08-02 15:27:41.059 26934-26934/com.criticalsystems.inspectionops I/ClientManager: Found account of type com.criticalsystems.inspectionops.login
08-02 15:27:55.347 26934-26934/com.criticalsystems.inspectionops W/ClientManager: Exception thrown while creating rest client
                                                                                  android.accounts.AuthenticatorException: getAuthToken failed
                                                                                      at android.accounts.AccountManager.convertErrorToException(AccountManager.java:2220)
                                                                                      at android.accounts.AccountManager.-wrap0(AccountManager.java)
                                                                                      at android.accounts.AccountManager$AmsTask$Response.onError(AccountManager.java:2056)
                                                                                      at android.accounts.IAccountManagerResponse$Stub.onTransact(IAccountManagerResponse.java:69)
                                                                                      at android.os.Binder.execTransact(Binder.java:565)

**Comment by bhariharan** [comment]
@jayakrishnansalim Are you able to reproduce this with our sample app [SmartSyncExplorer](https://github.com/forcedotcom/SalesforceMobileSDK-Android/tree/master/native/NativeSampleApps/SmartSyncExplorer)? It looks like your app might be holding on to a cached `RestClient` instance. Did you use `forcedroid` to generate the app from our template?

**Comment by jayakrishnansalim** [comment]
@bhariharan I didn't check SmartSyncExplorer sample app. But I checked forcedroid generated sample app in which it was working well. I checked both codes but I didn't see much differences. Is there a way where I can clear the cached RestClient?

**Comment by jayakrishnansalim** [comment]
While relogin as a different user after logout, at first the authentication is successful it seems. And then for some reason onResume() method in SalesforceListActivity is called again and at that time, authentication is failing. Please see the below logs. 

08-03 14:45:17.492 4297-4297/com.criticalsystems.inspectionops E/Login options: Bundle[{oauthClientId=3MVG9rFJvQRVOvk7l.cRoNkzpcGepph.m9oBp2d0V8_QuqRVMobKjBxnb38qP9Azxd0eBtFg4eHZteYyrmQ.x, clientSecret=null, passcodeHash=null, jwt=null, oauthScopes=[Ljava.lang.String;@154d846, oauthCallbackUrl=trm://login/success, loginUrl=null}]
08-03 14:45:17.492 4297-4297/com.criticalsystems.inspectionops E/getRestClient: Account is there.
08-03 14:45:17.492 4297-4297/com.criticalsystems.inspectionops E/Account info: Account {name=jboudreaux@77demo.com (https://na52.salesforce.com) (InspectionOPS), type=com.criticalsystems.inspectionops.login}
08-03 14:45:17.492 4297-4297/com.criticalsystems.inspectionops I/ClientManager: Found account of type com.criticalsystems.inspectionops.login
08-03 14:45:17.536 4297-4297/com.criticalsystems.inspectionops D/ReportsListActivity: Inside Resume method
08-03 14:45:17.536 4297-4297/com.criticalsystems.inspectionops D/ReportsListActivity: Got RestClient
08-03 14:45:17.536 4297-4297/com.criticalsystems.inspectionops D/RestClient: RestClient: {
                                                                               ClientInfo: {
                                                                                  loginUrl: https://login.salesforce.com
                                                                                  identityUrl: https://login.salesforce.com/id/00Dd0000000gXlKEAU/005d0000001Hx8qAAC
                                                                                  instanceUrl: https://na52.salesforce.com
                                                                                  accountName: jboudreaux@77demo.com (https://na52.salesforce.com) (InspectionOPS)
                                                                                  username: jboudreaux@77demo.com
                                                                                  userId: 005d0000001Hx8qAAC
                                                                                  orgId: 00Dd0000000gXlKEAU
                                                                                  communityId: null
                                                                                  communityUrl: null
                                                                                  firstName: Jim
                                                                                  lastName: Boudreaux II
                                                                                  displayName: Jim Boudreaux II
                                                                                  email: info@inspectionops.com
                                                                                  photoUrl: https://c.na52.content.force.com/profilephoto/729d0000000E2Xu/F
                                                                                  thumbnailUrl: https://c.na52.content.force.com/profilephoto/729d0000000E2Xu/T
                                                                                  additionalOauthValues: null
                                                                               }
                                                                                timeSinceLastRefresh: -1
                                                                             }
08-03 14:45:17.554 4297-4297/com.criticalsystems.inspectionops E/Login options: Bundle[{oauthClientId=3MVG9rFJvQRVOvk7l.cRoNkzpcGepph.m9oBp2d0V8_QuqRVMobKjBxnb38qP9Azxd0eBtFg4eHZteYyrmQ.x, clientSecret=null, passcodeHash=null, jwt=null, oauthScopes=[Ljava.lang.String;@154d846, oauthCallbackUrl=trm://login/success, loginUrl=null}]
08-03 14:45:17.554 4297-4297/com.criticalsystems.inspectionops E/getRestClient: Account is there.
08-03 14:45:17.555 4297-4297/com.criticalsystems.inspectionops E/Account info: Account {name=jboudreaux@77demo.com (https://na52.salesforce.com) (InspectionOPS), type=com.criticalsystems.inspectionops.login}
08-03 14:45:17.555 4297-4297/com.criticalsystems.inspectionops I/ClientManager: Found account of type com.criticalsystems.inspectionops.login
08-03 14:45:17.620 4297-4297/com.criticalsystems.inspectionops W/ClientManager: Exception thrown while creating rest client
                                                                                android.accounts.AuthenticatorException: getAuthToken failed
                                                                                    at android.accounts.AccountManager.convertErrorToException(AccountManager.java:2220)
                                                                                    at android.accounts.AccountManager.-wrap0(AccountManager.java)
                                                                                    at android.accounts.AccountManager$AmsTask$Response.onError(AccountManager.java:2056)
                                                                                    at android.accounts.IAccountManagerResponse$Stub.onTransact(IAccountManagerResponse.java:69)
                                                                                    at android.os.Binder.execTransact(Binder.java:565)
08-03 14:45:17.908 4297-4375/com.criticalsystems.inspectionops D/EGL_emulation: eglMakeCurrent: 0xe0d13340: ver 2 0 (tinfo 0xe0d71a20)
08-03 14:45:17.968 4297-4375/com.criticalsystems.inspectionops D/EGL_emulation: eglMakeCurrent: 0xe0d13340: ver 2 0 (tinfo 0xe0d71a20)
08-03 14:45:18.007 4297-4297/com.criticalsystems.inspectionops W/ClientManager: Exception thrown while creating rest client
                                                                                android.accounts.AuthenticatorException: getAuthToken failed
                                                                                    at android.accounts.AccountManager.convertErrorToException(AccountManager.java:2220)
                                                                                    at android.accounts.AccountManager.-wrap0(AccountManager.java)
                                                                                    at android.accounts.AccountManager$AmsTask$Response.onError(AccountManager.java:2056)
                                                                                    at android.accounts.IAccountManagerResponse$Stub.onTransact(IAccountManagerResponse.java:69)
                                                                                    at android.os.Binder.execTransact(Binder.java:565)
08-03 14:45:18.340 4297-4297/com.criticalsystems.inspectionops D/ReportsListActivity: Inside OnCreate method
08-03 14:45:18.346 4297-4297/com.criticalsystems.inspectionops E/Login options: Bundle[{oauthClientId=3MVG9rFJvQRVOvk7l.cRoNkzpcGepph.m9oBp2d0V8_QuqRVMobKjBxnb38qP9Azxd0eBtFg4eHZteYyrmQ.x, clientSecret=null, passcodeHash=null, jwt=null, oauthScopes=[Ljava.lang.String;@154d846, oauthCallbackUrl=trm://login/success, loginUrl=null}]
08-03 14:45:18.347 4297-4297/com.criticalsystems.inspectionops E/getRestClient: Account null
08-03 14:45:18.347 4297-4297/com.criticalsystems.inspectionops I/ClientManager: No account of type com.criticalsystems.inspectionops.login found

In the sample app as well I saw the behaviour of calling onResume multiple times.

**Comment by jayakrishnansalim** [comment]
@bhariharan Do you have any idea why this issue is coming? Please help.

**Comment by wmathurin** [comment]
We recently released Mobile SDK 5.3 with a number of bug fixes. Could you try with it and see if your issue still exists?
Thanks.
