### ISSUE TITLE
Remove user from Android device account screen

### ISSUE THREAD

**Issue by Manish-Kr09** [forcedotcom/SalesforceMobileSDK-Android#1469]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.1
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: Latest
4. Device: Any
5. Steps to reproduce: NA
6. Actual behaviour: NA
7. Expected Behavior: NA
8. Error Log: NA

Hi All, 

We are having a SalesforceMobileSDK based mobile app running on both Android and iOS. We recently got a requirement from one of our client who is using MDM with Android for Work. 
While using MDM there is a restriction on the device which doesn't allow the app to modify Device Accounts which in turn doesn't allow MobileSDK to add/read Salesforce user entry from/to device accounts. 
With this restriction, the app is unable to launch and we are getting a blank screen. 

We have asked them to make the change in the policy but as per their team, they cannot make it. 

Is there something in mobile-SDK that can change this behaviour?

We are into production and it's very urgent. 

Any help is appreciated. 

Thanks
Manish Kumar

**Comment by bhariharan** [comment]
@Manish-Kr09 Unfortunately, there's nothing we can do. `AccountManager` is the recommended secure storage for credentials on `Android` and `Mobile SDK` relies on this for encrypted storage of tokens and any user account specific information. We are required to use this per our own security requirements. We need to be able to add `Salesforce` accounts, read existing `Salesforce` accounts, etc. There's no way to get around it.

**Comment by Manish-Kr09** [comment]
@bhariharan, 

We had a discussion with Google team on this as per them

" one suggestion is whether Salesforce can use a different API when adding accounts?  Specifically, the setting disallows modify accounts blocks the [addAccount](https://developer.android.com/reference/android/accounts/AccountManager.html#addAccount(java.lang.String,%20java.lang.String,%20java.lang.String%5B%5D,%20android.os.Bundle,%20android.app.Activity,%20android.accounts.AccountManagerCallback%3Candroid.os.Bundle%3E,%20android.os.Handler)) method from being called (this is the method used by the account settings app), but apps can still allow addition of accounts onto the device using [addAccountExplicitely](https://developer.android.com/reference/android/accounts/AccountManager.html#addAccountExplicitly(android.accounts.Account,%20java.lang.String,%20android.os.Bundle))"

Is it doable?

What should be the impact if we switch to this method around following
- login and logout process
- REST calls
- SmartStore access

Is there is anything that can be broken while switching to this method?

Regards,
Manish Kumar

**Comment by bhariharan** [comment]
@Manish-Kr09 The short answer is that we can't switch from `addAccount()` to `addAccountExplicitly()` because there are gaps between those 2 APIs. For example, there is no way to use `AbstractAccountAuthenticator` or a callback mechanism with `addAccountExplicitly()`. These gaps prevent us from switching to that API since we need to have a custom `Authenticator` for token management.
