### ISSUE TITLE
Not able to logout from RemoteHybrid App for Customer community

### ISSUE THREAD

**Issue by merajulhasan** [forcedotcom/SalesforceMobileSDK-Android#1475]
Hi 
I have created the RemoteHybrid app In which I am using Customer community where we have the logout button but that button is not working when we logout from the HybridApp weather it is android or iOS, I am not able to logout. And the same button working fine when we open this customer community in web browser.

I have tried following code by adding an external component using ‘cordova.force.js,cordova-2.3.0.js’ as static resource but still no luck

var sfOAuthPlugin = cordova.require("salesforce/plugin/oauth");
sfOAuthPlugin.logout();

Kindly give the solution how could I logout from the hybrid app.

**Comment by wmathurin** [comment]
What version of the mobile sdk are you on?

To logout simply do:
```
cordova.require("com.salesforce.plugin.sfaccountmanager").logout()
```

**Comment by merajulhasan** [comment]
I recently created this app by using forceios and forcedroid, this is a
remote hybrid app in which i am using salesforce customer community which
has a default logout link, doing click on this link i am being redirct to
the login screen again but without enyering creds i am again getting login
in if i open the app again or do forget password and do cancel.

I have also used the code which u shared by creating a lightning component,
used cordova.x.x.js, force.js as static resource but no luck.

**Comment by wmathurin** [comment]
Are you serving cordova.js from localhost (more info [here](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/hybrid_develop_hybrid_remote.htm)) otherwise make sure to also host the cordova_plugins folder. Are you waiting for the cordova ready event?

Anyway, github issues are for known bugs/issues in our code. Please use the [Google+ community](https://plus.google.com/communities/114225252149514546445) and our extensive [documentation](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/hybrid_develop_hybrid_remote.htm) for help on how to use the Mobile SDK or do hybrid development etc.

**Comment by merajulhasan** [comment]
Hi,
Salesforce community is already running on public link, there is nothing
like localhost, In remote hybrid app we generally mention the start url and
rest flow works same as on running web browser, what i did, I created a
lightening component in that i linked cordova, force.js as static resource.
This componet is rendering on my landing page but clicking on this nothing
happening, I also checked cordova and force.js plugin being downloaded on
the component.

Thanks for this quick response.

I.have searched a lot so many people facing this issue but solution is not
done till now.

**Comment by bhariharan** [comment]
@merajulhasan `Lightning` components are currently unsupported in `Mobile SDK` apps.

**Comment by merajulhasan** [comment]
Thanks for reply.

Can you please suggest any solution for this situation?

Or let me know what r the posible solutions for this situation.

I really appreciate u for this help.

**Comment by bhariharan** [comment]
Use `Visualforce` -> [Visualforce Developer Guide](https://developer.salesforce.com/docs/atlas.en-us.pages.meta/pages/pages_intro_what_is_it.htm).

**Comment by merajulhasan** [comment]
I really appreciate ur support and help.
I will try it, and Let you know if working fine.

Thanks

**Comment by merajulhasan** [comment]
Hi,
Thanks for your support...

My SDK version is 5.5.0, as you suggested I used the cordova.js, force.js but It not worked as expected, Then I used whole cordova plugin in which I am having sfAcountManager, oauth, push, exec, device etc. then It work on android platform not as expected but it is working some how and the same plugin does not respond in iOS.

When I logout from the this app in android then after logout it always not giving me login in the app in first attempt I have to do multiple attempts to login even I am coping and pasting the same credentials what could be the cause of this, I am new in this platform. 

I also facing so many error alert on normal web platforms for not finding the device when we open the web on our browser, could we avoid these alerts?

How this will get support on iOS?

**Comment by wmathurin** [comment]
(There is no Mobile SDK 5.5.0, I'm assuming you mean 5.2.0?)

It works fine on iOS, there are thousands of apps using it, but you need to include cordova.js and have the cordova_plugins folder with the javascript libraries for all the plugins also. 

Cordova uses prompt()  to communicate between javascript and native however it intercepts them from the native side so you should never seem them if everything is configured properly.

**Comment by merajulhasan** [comment]
Hi,
Your response is really appreciated, thanks a lot. 

I attached the screen shots in which I am seeing the versions. Are these not the mobileSDK versions then how could I get version of sdk?

I used npm command forceios/forcedroid version both showing 5.0.0. I feel you can better help me once I get the version of mobilesdk used by me.

I have not done any alteration in the code, this is the same code which is generated with CLI.

Today I again try to create the iOS app from CLI then let you know.



![screen shot 2017-08-16 at 11 00 54 am](https://user-images.githubusercontent.com/20186329/29348796-c33378fc-8273-11e7-8729-5ee8446c0f92.png)
![screen shot 2017-08-16 at 11 01 57 am](https://user-images.githubusercontent.com/20186329/29348805-ca9178d8-8273-11e7-8a8b-3c89604fd5d9.png)

**Comment by wmathurin** [comment]
Simply npm update forceios / forcedroid to the latest version (5.2.0).

**Comment by merajulhasan** [comment]
Hi 
Thank you very much for this support.

Updated sdk and created the iOS Hybrid Remote App for Salesforce Customer community again but for there is no luck I am not getting logout from iOS App.

The code which I used for logout in VF page is attached.
I have checked all the options which active or
[Logout.txt](https://github.com/forcedotcom/SalesforceMobileSDK-Android/files/1234064/Logout.txt)
 commented in the attachment.

**Comment by wmathurin** [comment]
I find it easier to develop hybrid apps locally and only make them "remote" apps once everything works.

I recommend you do the following:
- run forceios to create an hybrid local application
- modify the application to add a logout (should be as simple as adding a logout button that calls `cordova.require('com.salesforce.plugin.oauth').logout()`)

**Once you get that working**, bundle all the files you see in your-app/platforms/ios/www and upload them to the server. Turn index.html into you main apex page. Change the source includes to point the static resources.

You only need to source include cordova.js - you should not be including the plugin javascript files. It happens automatically when cordova.js loads, it expects to find a cordova_plugin.js and a plugins directory next to cordova.js - you need to make sure those are present.

**Comment by merajulhasan** [comment]
Friend, 
Thanks for help.
See I can not create localHybrid app for this app, A website is already running, this is a third party app, I can not do much changes in the running. This is salesforce customer community portel which actually gets build dynamically. There is no existence of any page for customer community.

Beside the VF page I also tried it with a html page and tried to host it on a location but that page keep getting reload again and again without any call. So can you suggest any other alternate because both these ways not working.

Please help.

**Comment by wmathurin** [comment]
Not the full app. Just get the logout to work in hybrid local. Then move all the assets to the server and it should continue working.
Issues on github are really about tracking bugs with the mobile SDK and not learning how to use it.
For that, I recommend you move the conversation to our [google+ community](https://plus.google.com/communities/114225252149514546445).

**Comment by merajulhasan** [comment]
I have tested it in local, it works but when i put it on vf page it stop working. Similarly when i put on a server then it keeps reloading itself and page goes to busy and gets hanged as I have mentioned in ealier comment.

I have mentioned the issue on google+ community but no one speaking on that. This is not a bug but issue , how to logout from the salesforce customer community' remote hybrid app.
