### ISSUE TITLE
Boolean in smartstore is not consistent with iOS

### ISSUE THREAD

**Issue by booker-laputa** [forcedotcom/SalesforceMobileSDK-Android#1477]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.1 
2. Issue found in Native App or Hybrid App: React-Native project (Android)
3. OS Version: 5.1.1
4. Device: Samsung Galaxy Tab A
5. Steps to reproduce: 
   Create a soup, upsert a record with boolean
   Load the record and log the boolean
   
6. Actual behavior: On Android it is a string ("true"/"false), on iOS it is ("1"/"0")
7. Expected Behavior: Two platforms should align
8. Error Log:

**Comment by wmathurin** [comment]
This is already discussed [here](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/238) - along with a workaround. 
Closing this issue since it's a duplicate.
