### ISSUE TITLE
Please help me for login session issue for Android SDK

### ISSUE THREAD

**Issue by abhijeetkokane** [forcedotcom/SalesforceMobileSDK-Android#1478]
Please fill out the following details:
1. Version of Mobile SDK Used: 4.3.1
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 5.0 above
4. Device: Samsung S4
5. Steps to reproduce:
Step 1 - After successful login on https://ABC.force.com from mobile app.
Step 2 - I am able to see this link https://ABC.force.com /customers/one/one.app in android native WebView
6. Actual behavior:
After 24 hours I am again seeing login screen.
7. Expected Behavior:
Login session should be maintain until user manually logged out from app

I have analyze with checking with iOS app. Please check this link Android : https://www.dropbox.com/s/gvwlyi3ozr8nnh3/android_screen.png?dl=0 
& iOS : https://www.dropbox.com/s/pv6tezrn4shy3t3/ios_screenshot.png?dl=0,
though consumer key is same  permissions are different.
Is this the bug or a mistake in my integration, please suggest.

**Comment by urthakkar** [comment]
what is the refresh token policy on your connected app on the platform.  from what it sounds like, you want the refresh policy to be set to never expire

**Comment by wmathurin** [comment]
Is it a native application or an hybrid application?
If it's a native application and you application is opening one.app in a web view, session will of course expires. If you need the Mobile SDK to manage the session for the web view, you need to use a hybrid remote application.

**Comment by wmathurin** [comment]
Regarding the questions about the permissions. The connected app defines permissions that can be requested. But the mobile apps might still be requesting different subset of the allowed permissions.

You want to check the oauthScopes value in bootconfig.json for the iOS and Android application and make sure it is the same value in both cases.

**Comment by wmathurin** [comment]
Did you try what I recommended a week ago?
Please re-open the issue if don't think the application was simply misconfigured.
