### ISSUE TITLE
Error:Failed to resolve: com.android.support:support-v4:24.0.0 

### ISSUE THREAD

**Issue by WadeLovell** [forcedotcom/SalesforceMobileSDK-Android#1503]
Please fill out the following details:

1. Version of Mobile SDK Used: forcedroid version 5.2.0
2. Issue found in Native App or Hybrid App: Both - Native Android today and last weekend on Hybrid
3. OS Version: Windows 10 Pro v1703
4. Device: HP i7 based laptop
5. Steps to reproduce: Open project from running Android Studio or Import project at start screen of Android Studio. Build fails
6. Actual behavior: Build failed
7. Expected Behavior: Build completed
8. Error Log: Error:Failed to resolve: com.android.support:support-v4:24.0.0
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:C:/Users/wadel/TrailheadAndroidTest/mobile_sdk/salesforcemobilesdk-android/libs/SmartSync/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':libs:SmartSync'.
      > Could not resolve all dependencies for configuration ':libs:SmartSync:_debugPublish'.
         > A problem occurred configuring project ':libs:SmartStore'.
            > Could not resolve all dependencies for configuration ':libs:SmartStore:_debugPublish'.
               > A problem occurred configuring project ':libs:SalesforceSDK'.
                  > Could not resolve all dependencies for configuration ':libs:SalesforceSDK:_debugPublishCopy'.
                     > Could not find com.android.support:support-v4:24.0.0.
                       Required by:
                           project :libs:SalesforceSDK > com.google.android.gms:play-services-gcm:10.2.0 > com.google.android.gms:play-services-basement:10.2.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.788 secs

Information:Gradle tasks [:app:generateDebugSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:generateDebugAndroidTestSources, :app:compileDebugSources, :app:compileDebugUnitTestSources, :app:compileDebugAndroidTestSources, :libs:SalesforceAnalytics:generateDebugSources, :libs:SalesforceAnalytics:generateDebugAndroidTestSources, :libs:SalesforceAnalytics:mockableAndroidJar, :libs:SalesforceAnalytics:prepareDebugUnitTestDependencies, :libs:SalesforceAnalytics:compileDebugSources, :libs:SalesforceAnalytics:compileDebugAndroidTestSources, :libs:SalesforceAnalytics:compileDebugUnitTestSources, :libs:SalesforceSDK:generateDebugSources, :libs:SalesforceSDK:generateDebugAndroidTestSources, :libs:SalesforceSDK:mockableAndroidJar, :libs:SalesforceSDK:prepareDebugUnitTestDependencies, :libs:SalesforceSDK:compileDebugSources, :libs:SalesforceSDK:compileDebugAndroidTestSources, :libs:SalesforceSDK:compileDebugUnitTestSources, :libs:SmartStore:generateDebugSources, :libs:SmartStore:generateDebugAndroidTestSources, :libs:SmartStore:mockableAndroidJar, :libs:SmartStore:prepareDebugUnitTestDependencies, :libs:SmartStore:compileDebugSources, :libs:SmartStore:compileDebugAndroidTestSources, :libs:SmartStore:compileDebugUnitTestSources, :libs:SmartSync:generateDebugSources, :libs:SmartSync:generateDebugAndroidTestSources, :libs:SmartSync:mockableAndroidJar, :libs:SmartSync:prepareDebugUnitTestDependencies, :libs:SmartSync:compileDebugSources, :libs:SmartSync:compileDebugAndroidTestSources, :libs:SmartSync:compileDebugUnitTestSources]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':libs:SmartSync'.
      > Could not resolve all dependencies for configuration ':libs:SmartSync:_debugPublish'.
         > A problem occurred configuring project ':libs:SmartStore'.
            > Could not resolve all dependencies for configuration ':libs:SmartStore:_debugPublish'.
               > A problem occurred configuring project ':libs:SalesforceSDK'.
                  > Could not resolve all dependencies for configuration ':libs:SalesforceSDK:_debugPublishCopy'.
                     > Could not find com.android.support:support-v4:24.0.0.
                       Required by:
                           project :libs:SalesforceSDK > com.google.android.gms:play-services-gcm:10.2.0 > com.google.android.gms:play-services-basement:10.2.0
Information:BUILD FAILED
Information:Total time: 3.788 secs
Information:1 error
Information:0 warnings
Information:See complete output in console

**Comment by bhariharan** [comment]
@WadeLovell It says it right here:
```
Error:Failed to resolve: com.android.support:support-v4:24.0.0
Install Repository and sync project
Open File
Show in Project Structure dialog
```
Please open up `SDK Manager` in `Android Studio` and install the required packages and tools.
