### ISSUE TITLE
Smartstore showing null pointer exception in salesforce android native SDK while syncdown data from salesforce to soup

### ISSUE THREAD

**Issue by vinod1988** [forcedotcom/SalesforceMobileSDK-Android#1504]
Please fill out the following details:

1. Version of Mobile SDK Used:  5.0.1
2. Issue found in Native App or Hybrid App: Android Native App
3. OS Version: 4.4
4. Device: Samsung note2
5. Steps to reproduce: While syncing the data from Salesforce to the soup.
6. Actual behavior: It should sync all data without showing the error
7. Expected Behavior: It should sync all data without showing the error
8. Error Log:
E/SmartStore.projIdxPaths: Unexpected error java.lang.NullPointerException at com.salesforce.androidsdk.smartstore.store.SmartStore.projectIndexedPath(SmartStore.java:1013) at com.salesforce.androidsdk.smartstore.store.SmartStore.projectIndexedPaths(SmartStore.java:983) at com.salesforce.androidsdk.smartstore.store.SmartStore.update(SmartStore.java:1112) at com.salesforce.androidsdk.smartstore.store.SmartStore.upsert(SmartStore.java:1204) at com.salesforce.androidsdk.smartsync.manager.SyncManager.saveRecordsToSmartStore(SyncManager.java:619) at com.salesforce.androidsdk.smartsync.manager.SyncManager.syncDown(SyncManager.java:569) at com.salesforce.androidsdk.smartsync.manager.SyncManager.access$000(SyncManager.java:72) at com.salesforce.androidsdk.smartsync.manager.SyncManager$1.run(SyncManager.java:261) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) at java.lang.Thread.run(Thread.java:841)

**Comment by wmathurin** [comment]
It looks like it doesn't like a null value in floating field. See https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/v5.0.1/libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java#L1013.

We'll have a look.

**Comment by wmathurin** [comment]
Having a second look at the code, we are logging a NPE but the method should still return successfully. Even though you see the errors in the log, it should not stop the sync. Are you observing a different behavior?
