### ISSUE TITLE
Mobile App that uses SmartSync & SmartStore cannot be used after revoking the OAuth access

### ISSUE THREAD

**Issue by mdudzinski** [forcedotcom/SalesforceMobileSDK-Android#1505]
1. Version of Mobile SDK Used: 
* SmartStore:5.3.0, SmartSync:5.3.0
* SmartStore:5.2.0, SmartSync:5.2.0
2. Issue found in Native App or Hybrid App:
* Both. Salesforce1 was used as a hybrid app.
3. OS Version:
* 5.1 & 6.0.1
4. Device:
* 5.1 AVD x86 
* 6.0.1 Sony D6603
5. Steps to reproduce:
* Log into a mobile app that uses SF SDK
* Revoke OAuth 2.0 access for the logged user. Either via Web UI (Apps -> Connected Apps -> "SalesforceMobileSDK Sample App" -> User count cell and revoke access) or using [REST API](https://help.salesforce.com/articleView?id=remoteaccess_revoke_token.htm&type=0) 
* Continue using the mobile app till you get logged out. For example by starting a sync or closing and opening again.
* Log again as the same user.
6. Actual behavior:
* Depending on how one uses SF SDK. It may crash or just stop displaying data and syncing. 
* When using Salesforce1, the app just stopped displaying some of the data. Very likely some of the data worked (like Contacts) because the app was re-creating soups after re-login. Example of screen that was empty (and kept throwing an exception in logcat): Today.
* When using SmartSyncExplorer sample, it stopped displaying list of contacts and kept throwing an exception in the background. When you try to add a new contact, the app crashes.
7. Expected Behavior:
* No crash. No need to re-create soups. App works the same way as before revoking the tokens. Previously created offline data are still available. Not sure if that's the case for Salesforce1 but it should work for custom apps as well as for SmartSyncExplorer.
8. Error Log:
* Salesforce1:

> 10-03 10:11:38.916 25160-27232/? W/StorePlugin.execute: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
>                                                         net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
>                                                             at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
>                                                             at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
>                                                             at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
>                                                             at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:83)
>                                                             at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:49)
>                                                             at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:42)
>                                                             at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1762)
>                                                             at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1727)
>                                                             at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2344)
>                                                             at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1091)
>                                                             at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1154)
>                                                             at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
>                                                             at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:129)
>                                                             at com.salesforce.androidsdk.smartstore.store.SmartStore.getDatabase(SmartStore.java:232)
>                                                             at com.salesforce.androidsdk.smartstore.store.SmartStore.hasSoup(SmartStore.java:703)
>                                                             at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.soupExists(SmartStorePlugin.java:323)
>                                                             at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.access$1500(SmartStorePlugin.java:79)
>                                                             at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin$1.run(SmartStorePlugin.java:159)
>                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>                                                             at java.lang.Thread.run(Thread.java:818)

and

> 10-03 10:11:38.849 25160-25272/? E/Database: Failed to setLocale() when constructing, closing the database
>                                              net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
>                                                  at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
>                                                  at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
>                                                  at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
>                                                  at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:83)
>                                                  at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:49)
>                                                  at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:42)
>                                                  at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1762)
>                                                  at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1727)
>                                                  at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2344)
>                                                  at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1091)
>                                                  at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1154)
>                                                  at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
>                                                  at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:129)
>                                                  at com.salesforce.androidsdk.smartstore.store.SmartStore.getDatabase(SmartStore.java:232)
>                                                  at com.salesforce.androidsdk.smartstore.store.SmartStore.lookupSoupEntryId(SmartStore.java:1250)
>                                                  at com.salesforce.aura.CookieSyncHelper.saveCSRFTokenToSmartStore(CookieSyncHelper.java:422)
>                                                  at com.salesforce.aura.CookieSyncHelper.saveCSRFTokenToSmartStore(CookieSyncHelper.java:492)
>                                                  at com.salesforce.aura.CookieSyncHelper$1.run(CookieSyncHelper.java:189)
>                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>                                                  at java.lang.Thread.run(Thread.java:818)
* SmartSyncExplorer
When one try to refresh data:

> 10-03 11:19:36.184 6039-12362/com.salesforce.samples.smartsyncexplorer:sync W/Encryptor: Error during decryption
>                                                                                          javax.crypto.BadPaddingException: pad block corrupted
>                                                                                              at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:854)
>                                                                                              at javax.crypto.Cipher.doFinal(Cipher.java:1375)
>                                                                                              at com.salesforce.androidsdk.analytics.security.Encryptor.decrypt(Encryptor.java:291)
>                                                                                              at com.salesforce.androidsdk.analytics.security.Encryptor.decrypt(Encryptor.java:154)
>                                                                                              at com.salesforce.androidsdk.analytics.security.Encryptor.decrypt(Encryptor.java:137)
>                                                                                              at com.salesforce.androidsdk.app.SalesforceSDKManager.decryptWithPasscode(SalesforceSDKManager.java:1113)
>                                                                                              at com.salesforce.androidsdk.accounts.UserAccountManager.buildUserAccount(UserAccountManager.java:429)
>                                                                                              at com.salesforce.androidsdk.accounts.UserAccountManager.getAuthenticatedUsers(UserAccountManager.java:231)
>                                                                                              at com.salesforce.samples.smartsyncexplorer.sync.ContactSyncAdapter.onPerformSync(ContactSyncAdapter.java:68)
>                                                                                              at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)

and when trying to add a new contact

> 10-03 11:23:33.317 14503-14503/com.salesforce.samples.smartsyncexplorer E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                                           Process: com.salesforce.samples.smartsyncexplorer, PID: 14503
>                                                                                           com.salesforce.androidsdk.smartstore.store.SmartStore$SmartStoreException: Soup: contacts does not exist
>                                                                                               at com.salesforce.androidsdk.smartstore.store.SmartStore.create(SmartStore.java:930)
>                                                                                               at com.salesforce.androidsdk.smartstore.store.SmartStore.create(SmartStore.java:914)
>                                                                                               at com.salesforce.samples.smartsyncexplorer.ui.DetailActivity.save(DetailActivity.java:244)
>                                                                                               at com.salesforce.samples.smartsyncexplorer.ui.DetailActivity.onOptionsItemSelected(DetailActivity.java:125)
>                                                                                               at android.app.Activity.onMenuItemSelected(Activity.java:2885)
>                                                                                               at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1133)
>                                                                                               at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
>                                                                                               at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
>                                                                                               at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
>                                                                                               at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
>                                                                                               at android.widget.ActionMenuView.invokeItem(ActionMenuView.java:587)
>                                                                                               at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:141)
>                                                                                               at android.view.View.performClick(View.java:4780)
>                                                                                               at android.view.View$PerformClick.run(View.java:19866)
>                                                                                               at android.os.Handler.handleCallback(Handler.java:739)
>                                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                                               at android.os.Looper.loop(Looper.java:135)
>                                                                                               at android.app.ActivityThread.main(ActivityThread.java:5254)
>                                                                                               at java.lang.reflect.Method.invoke(Native Method)
>                                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
>                                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
>                                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by wmathurin** [comment]
This issue has been fixed in the dev branch and will be in our next release (6.0).

**Comment by booker0108** [comment]
@wmathurin Could you tell which commit has fixed the issue?

For some reasons I have to stick with v5.3

**Comment by wmathurin** [comment]
I think the commit you want is https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1488/commits/93d75c54496ef3381f27955f430c790c89f23ef8
