### ISSUE TITLE
edit salesforce record using webview

### ISSUE THREAD

**Issue by rspl17** [forcedotcom/SalesforceMobileSDK-Android#1506]
Please fill out the following details:

1. Version of Mobile SDK Used: 4.3.1
2. Issue found in Native App or Hybrid App: Native
3. OS Version: all
4. Device:all
5. Steps to reproduce: 
6. Actual behavior:
7. Expected Behavior:
8. Error Log:

I have been using domain.visual.force.com/apex/GenericUpdate ... url with token to launch webview to edit salesforce record but it is asking for login all the time. even after login doesnt allow me to navigate to edit page

**Comment by wmathurin** [comment]
If you need a webview, you should generate an hybrid_local or hybrid_remote application.
Through a number of classes - see [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/tree/master/libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui) - Mobile SDK takes care of session management for the content in the web view.
It will not work if you simply show a webview in a native application.

**Comment by rspl17** [comment]
@wmathurin  But that should be maintain by mobile android native sdk not the hybrid sdk because native sdk also uses its webview for user login so the same webview should be used to maintain the session ?

**Comment by wmathurin** [comment]
The webview for login is a different webview - and there is no session management there.

**Comment by rspl17** [comment]
@wmathurin  Than please suggest if I want to use the webview to edit record using user's auth-token will it be possible ? using android-native sdk if not please suggest alternate solution

**Comment by wmathurin** [comment]
Please read our [doc](https://developer.salesforce.com/page/Developing_Hybrid_Apps_with_the_Salesforce_Mobile_SDK)

**Comment by rspl17** [comment]
Thanks but, the app is already developed under native sdk, its not a hybrid application. so is there a way to do it using native sdk or I have to create new hybrid app for only session management ?

**Comment by wmathurin** [comment]
You could borrow some of the code from our hybrid library.
You need to load your remote URL "through front-door" (see https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/ui/SalesforceDroidGapActivity.java#L471). That's the way to get all the session cookies setup in the webview when you have only an access token.

**Comment by maarcooliveira** [comment]
Also, make sure that on your bootconfig.xml, on oauthScopes, you have the "web" option:

`<string-array name="oauthScopes">
        <item>api</item>
        <item>web</item>
  </string-array>`

It took me a while to find out.
