### ISSUE TITLE
Facebook login page renders poorly using OAuth

### ISSUE THREAD

**Issue by agolden** [forcedotcom/SalesforceMobileSDK-Android#1510]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.3 (latest, as of writing)
2. Issue found in Native App or Hybrid App: Hybrid
3. OS Version: 7.0
4. Device: Nexus 5X
5. Steps to reproduce:
- Point SDK to a Salesforce login page w/ option for Facebook OAuth
- Launch app, enter login, and click 'Log in via Facebook' button
- Login page renders poorly (everything appears squished, as if page is not taking up full width of screen; see attached screenshot)
<img width="303" alt="screen shot 2017-10-12 at 12 31 40 pm" src="https://user-images.githubusercontent.com/6006212/31507728-ab46c336-af49-11e7-8c35-eb1d56b632e3.png">
6. Actual behavior:
Facebook login screen is virtually unusable
7. Expected Behavior:
Facebook login screen takes full width of screen and renders appropriately
8. Error Log: N/A

**Comment by bhariharan** [comment]
Fixed [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1513).
