### ISSUE TITLE
How to achieve cutsom login page with progress dialog and back button

### ISSUE THREAD

**Issue by harshitaahuja** [forcedotcom/SalesforceMobileSDK-Android#1518]
1. Version of Mobile SDK Used: 5.3
2. Issue found in Native App or Hybrid App: Native
3. OS Version: All
4. Device: All
5. Steps to reproduce: NA
6. Actual behavior: NA
7. Expected Behavior: NA
8. Error Log: NA

![screen shot 2017-10-16 at 4 04 06 pm](https://user-images.githubusercontent.com/3863417/31608110-b656a1ba-b28c-11e7-8aa4-a2e23a38c5c5.png)

How can we achieve this login page.
Marked the customised webpage area created on salesforce. 

Changes required are 
- Hide default action bar which shows url and server change options.
- Show loading progress bar until web page is loaded.
- Have functionality of back press to go to previous activity.

There is no documentation for customisation, and very restrictive login screen in SDK.
How can we achieve these points.

**Comment by bhariharan** [comment]
@harshitaahuja This can be done by subclassing `LoginActivity` and adding the customizations you require, such as hiding the nav bar or adding a back button on the nav bar. You should be able to override getActionBar()` and pass in your own `ActionBar`. When you `init()` the SDK in `SalesforceSDKManager`, make sure you pass in the custom subclass of `LoginActivity`. Please use our [Google+ community](https://plus.google.com/u/1/communities/114225252149514546445) for queries/discussions. This forum is reserved for issues with our code and/or bugs.
