### ISSUE TITLE
Salesforce Hybrid remote stucks on resuming app 

### ISSUE THREAD

**Issue by ramanRajSaxenaTry** [forcedotcom/SalesforceMobileSDK-Android#1526]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.2.0
2. Issue found in Native App or Hybrid App:Hybrid Remote
3. OS Version: windows 7
4. Device: android all
5. Steps to reproduce: configure to android studio then launch then minimize the app.
6. Actual behavior: screen gets white
7. Expected Behavior: last opened page should open
8. Error Log:No

Hi All,
I've made a hybrid remote app. its working fine but when i minimize it and then on resuming it the screen gets white and the user doesn't get logged out. the start page of the app is a entry page of the salesforce community and there is no code on client app.
Can anyone help me with this?

**Comment by bhariharan** [comment]
Could you post the stack trace from your device? Which version of `Android` are you running against?

**Comment by ramanRajSaxenaTry** [comment]
android version 7.1.1
yes I'm using the lightning components.

**Comment by bhariharan** [comment]
Lightning components are not supported within the Mobile SDK.
