### ISSUE TITLE
Support for Gradle 3.0 - buildToolsVersion '26.0.2' minimum required

### ISSUE THREAD

**Issue by harshitaahuja** [forcedotcom/SalesforceMobileSDK-Android#1530]
Please fill out the following details:

1. Version of Mobile SDK Used: 
2. Issue found in Native App or Hybrid App:
3. OS Version:
4. Device:
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:

**Comment by bhariharan** [comment]
We are aware of this issue. Support for `Android Studio 3.0` will be available in our upcoming release. #safeharbor

**Comment by wmathurin** [comment]
The change has been made in the dev branch. See [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1532).

**Comment by harshitaahuja** [comment]
When we will get a release for this change

**Comment by bhariharan** [comment]
End of this year. #safeharbor
