### ISSUE TITLE
SmartSync: Sync Up multiple records in one request

### ISSUE THREAD

**Issue by sysmei** [forcedotcom/SalesforceMobileSDK-Android#1636]
Version of Mobile SDK Used: 5.0
Issue found in Native App or Hybrid App: Hybrid
OS Version: Android 7.0
Device: Galaxy S6
Steps to reproduce: SyncUp records (with SmartSync)
Actual behavior: Slow performance
Expected Behavior: Is there option to sync multiple records

Hi!

I am using SmartSync/Smartstore to synchronize offline data with Salesforce.
I am noticing that all modified records are passed to SF with method syncUpOneRecord (in java code). That means one request to SF for each modified record.

Is there option to sync multiple records in one request?

**Comment by bhariharan** [comment]
Not in the default sync targets, since they use SOQL and SOQL is per object for updates and deletes. Also, this forum is reserved for issues with our code. For any other queries/discussions, please use our [Google+ community](https://plus.google.com/u/1/communities/114225252149514546445?cfem=1).

**Comment by wmathurin** [comment]
Valid point. SOQL is used on the way down - on the way up, we save the record one by one.
The code predates the force.com batch/composite REST APIs. But we could look into leveraging them to reduce the number of round trips to the server during sync up.

**Comment by wmathurin** [comment]
Batching sync up target added in dev (see https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1844). Will be in next version of Mobile SDK (7.1).
