### ISSUE TITLE
Login page is blank (Javascript is disabled)

### ISSUE THREAD

**Issue by slin1202** [forcedotcom/SalesforceMobileSDK-Android#1659]
1. SDK: Android SDK 26
2. Native
3. OS Version: Android 8.0
4. Device: Nexus 5x (Emulator)

My application file looks like this

``` package com.manulife.cea.zoom;

import android.app.Application;
import com.salesforce.androidsdk.smartsync.app.SmartSyncSDKManager;
import com.salesforce.androidsdk.ui.*;

public class ZoomApp extends Application {

    @Override
     public void onCreate() {
        super.onCreate();
        SmartSyncSDKManager.initNative(getApplicationContext(), SalesforceLoginActivity.class);
    }

}
```

And my activity that initiates the login flow is

``` import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.webkit.WebSettings;
import android.webkit.WebView;

import com.salesforce.androidsdk.rest.RestClient;
import com.salesforce.androidsdk.ui.SalesforceActivity;

public class SalesforceLoginActivity extends SalesforceActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login);
    }

    @Override
    public void onResume() {
        findViewById(R.id.activity_login).setVisibility(View.INVISIBLE);
        super.onResume();
    }

    @Override
    public void onResume(RestClient client) {
    }
}
```

When I go into SalesforceLoginActivity by clicking a button, the WebView opens up and a blank page appears. My logs show this however
```
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
W/cr_MediaCodecUtil: HW encoder for video/avc is not available on this device.
W/cr_MediaCodecUtil: HW encoder for video/avc is not available on this device.
D/EGL_emulation: eglCreateContext: 0x8f0bf740: maj 3 min 0 rcv 3
```

When I open the url in a webview that I create myself I get the same behaviour unless I enable javascript. I believe this might be the issue, how would I go about enabling it for the webview that Salesforce opens?

**Comment by wmathurin** [comment]
The log lines seems completely unrelated to your application or you SDK.
What version of the Mobile SDK are you using?
Did you create your application with `forcedroid`?

**Comment by slin1202** [comment]
The logs are possibly unrelated but when I searched the "Unsupported profile 4 for video/mp4v-es" error, it led to issues where the Webview was not able to load the url. Another important thing is that  when my client key is wrong the page is able to show me a page with "error=invalid_client_id&error_description=client%20identifier%20invalid" but this page does not need javascript to load. 

I am using Salesforce SDK version 6.1.0, I have imported it into my project through my gradle file with "compile 'com.salesforce.mobilesdk:SmartSync:6.1.0'".

I did not create my project through forcedroid however, I tried following the steps in the documentation that are required for the flow. I'd like to avoid using forcedroid if possible and was hoping someone had seen this issue before.

**Comment by wmathurin** [comment]
I don’t follow your code. Are you trying to customize the login activity - in that case you should subclass our LoginActivity. And you should pass it as the first argument here: https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SmartSync/src/com/salesforce/androidsdk/smartsync/app/SmartSyncSDKManager.java#L75
Also you still need a main activity. It doesn’t make sense for login to be the main activity of your application.

I strongly recommend you run forcedroid app once to generate a working app that you can then study / copy from.

We reserve GitHub issues for actual bugs. For other questions please post to our G+ community.
https://plus.google.com/communities/114225252149514546445

**Comment by slin1202** [comment]
Sorry I'll post the issue in the G+ community. However I did just create an app with forcedroid with my proper config set in bootconfig and my server in xml/servers.xml and I'm seeing the same issue so perhaps there is a bug? Is there any way to debug the Webview that Salesforce launches?

The full log is here 

```
D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true

                  [ 03-30 15:02:30.703 11327:11327 D/         ]
                  HostConnection::get() New Host Connection established 0xaa1d2100, tid 11327
I/OpenGLRenderer: Initialized EGL, version 1.4
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/EGL_emulation: eglCreateContext: 0xae414de0: maj 3 min 0 rcv 3
D/EGL_emulation: eglMakeCurrent: 0xae414de0: ver 3 0 (tinfo 0xae412f90)
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
D/EGL_emulation: eglMakeCurrent: 0xae414de0: ver 3 0 (tinfo 0xae412f90)
I/WebViewFactory: Loading com.android.webview version 44.0.2403.119 (code 246011910)
W/System: ClassLoader referenced unknown path: /system/app/webview/lib/x86
I/LibraryLoader: Time to load native libraries: 12 ms (timestamps 8111-8123)
I/LibraryLoader: Expected native library version number "",actual native library version number ""
V/WebViewChromiumFactoryProvider: Binding Chromium to main looper Looper (main, tid 1) {2fc4455}
I/LibraryLoader: Expected native library version number "",actual native library version number ""
I/chromium: [INFO:library_loader_hooks.cc(120)] Chromium logging enabled: level = 0, default verbosity = 0
I/BrowserStartupController: Initializing chromium process, singleProcess=true
W/art: Attempt to remove non-JNI local reference, dumping thread
E/SysUtils: ApplicationContext is null in ApplicationStatus
W/chromium: [WARNING:resource_bundle.cc(285)] locale_file_path.empty()
E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
D/EGL_emulation: eglCreateContext: 0xaa98ee80: maj 3 min 0 rcv 3
D/EGL_emulation: eglMakeCurrent: 0xaa98ee80: ver 3 0 (tinfo 0xaa991d10)
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
W/AudioManagerAndroid: Requires BLUETOOTH permission
E/DataReductionProxySettingListener: No DRP key due to exception:java.lang.ClassNotFoundException: com.android.webview.chromium.Drp
W/art: Attempt to remove non-JNI local reference, dumping thread
W/AwContents: onDetachedFromWindow called when already detached. Ignoring
D/LoginActivity: User agent login flow being triggered
I/Choreographer: Skipped 75 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation: eglMakeCurrent: 0xae414de0: ver 3 0 (tinfo 0xae412f90)
E/Surface: getSlotFromBufferLocked: unknown buffer: 0xa2496780
D/EGL_emulation: eglMakeCurrent: 0xae414de0: ver 3 0 (tinfo 0xae412f90)
W/chromium: [WARNING:data_reduction_proxy_config.cc(423)] SPDY proxy OFF at startup
D/EGL_emulation: eglCreateContext: 0xae416640: maj 3 min 0 rcv 3
D/EGL_emulation: eglMakeCurrent: 0xae416640: ver 3 0 (tinfo 0x9fe7faa0)
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008073
D/EGL_emulation: eglCreateContext: 0xae416760: maj 3 min 0 rcv 3
D/EGL_emulation: eglMakeCurrent: 0xae416760: ver 3 0 (tinfo 0x9fe7faa0)
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
W/BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 11327
W/BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 11327
D/EGL_emulation: eglMakeCurrent: 0xae416640: ver 3 0 (tinfo 0x9fe7faa0)
D/EGL_emulation: eglMakeCurrent: 0xae416760: ver 3 0 (tinfo 0x9fe7faa0)
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008073
D/EGL_emulation: eglMakeCurrent: 0xae416640: ver 3 0 (tinfo 0x9fe7faa0)
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5```

**Comment by wmathurin** [comment]
Was the forcedroid generated app working before you made any configurations changes?

**Comment by slin1202** [comment]
It is!

I was able to add `webView.setWebContentsDebuggingEnabled(true);` to LoginActivity.java and I saw that the issue is that the https protocol was missing in whatever url it redirects to, it's neither the login server url or the oauth redirect uri, so I suspect it's something that our backend devs configured in Salesforce so I will have a chat with them on Monday.

Thanks for your help!

**Comment by slin1202** [comment]
So it turns out the actual issue is in sf__login.xml, where the WebView is inside of a ScrollView and is using "wrap_content" for the layout_height attribute. Because of this, if the html has the height attribute set to 100%, it's calculated as 0px (https://stackoverflow.com/questions/32729416/html-height-100-ignored-by-webview). Using height 100% on the html tag is pretty common so I wonder if it is necessary for the WebView to be nested in the ScrollView and to have the layout_height as "wrap_content" instead of "match_parent".
