### ISSUE TITLE
Smartstore local fields are set to false after activity restart 

### ISSUE THREAD

**Issue by paderick-de** [forcedotcom/SalesforceMobileSDK-Android#1704]
1. Version of Mobile SDK Used: 6.0
2. Issue found in Native App or Hybrid App: Native Android
3. OS Version: API 26
4. Device: Emulated Pixel 2
5. Steps to reproduce:
restart activity without syncing after editing
6. Actual behavior:
Custom fields are set to custom values and \_\_local\_\* fields are set to false
7. Expected Behavior:
Custom fields are set to custom values and \_\_local\_\* fields are set to true
8. Error Log:  

After closing the activity without syncing I restarted the activity. The edited custom fields have correct values but the local fields are set to false.

**Comment by bhariharan** [comment]
@paderick-de Which activity are you referring to? There's no direct correlation between activities and `SmartStore` values. Reading and writing of `SmartStore` values should happen from a `Loader` or `ContentProvider`. Have you tried the sample app in our workspace, `SmartSyncExplorer` that demonstrates the usage of `SmartSync`?

**Comment by paderick-de** [comment]
@bhariharan okay. Now i used the Loader and it works fine. But why is the Loader essential?

**Comment by bhariharan** [comment]
@paderick-de Your question is unrelated to the Salesforce Mobile SDK, it's a general Android development question. Please review Google's documentation on Android and/or post on Android development forums. This forum is reserved for known issues with our code.
