### ISSUE TITLE
Unexpected network errors should show configured error page

### ISSUE THREAD

**Issue by alsocalledchris** [forcedotcom/SalesforceMobileSDK-Android#1712]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.1
2. Issue found in Native App or Hybrid App: Hybrid Remote
3. OS Version: Oreo
4. Device: Samsung S8+
5. Steps to reproduce: Have a custom error page specified in config. Have the App open in the background (not currently in focus), have a dodgy WiFi connection (seen as connected to the internet by Android but some requests fail.) Select the App to view - so brought into focus.
6. Actual behavior: On the App having the focus it sometimes shows the Android connection refused/page unavailable with the Android logo.
7. Expected Behavior: Specified error page should be shown on all connection issues (like it does when it knows there is no connection at all - e.g. no wifi and no data connection. 
8. Error Log: NA

**Comment by bhariharan** [comment]
@alsocalledchris We could take a look at making this better, but it is largely dependent on the value given to us by the Android OS for network connectivity. There could be instances where network connectivity might be slow and requests might time out, but the radio API would indicate that network connectivity is available. This typically happens in dodgy connections, while traveling through a tunnel, etc. There's not much we can do about those situations.

**Comment by alsocalledchris** [comment]
@bhariharan many thanks - I would say any connection error when it would show the generic Android connection error page should show the configured error page - and ideally with the ability to refresh to the start page to try again.

**Comment by wmathurin** [comment]
This issue is almost 4 years old. The code has changed a lot since then. 
Please open a new issue if you think it is still relevant today.
