### ISSUE TITLE
Maven repo down

### ISSUE THREAD

**Issue by AndrewBestbier** [forcedotcom/SalesforceMobileSDK-Android#1714]
Hi there, it seems as though your repo is down?

https://s3.amazonaws.com/salesforcesos.com/android/maven/release

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>android/maven/release</Key>
<RequestId>896E0EAA572C0851</RequestId>
<HostId>
2WD30dyKqGFWhkoep9hU99UD9tMBntcHmhCwN+Ze35NOdI6yR5KE71dhfhhPa52S/6thoLklwH8=
</HostId>
</Error>
```

The other one has its certificate expired.

**Comment by bhariharan** [comment]
Please post on the ServiceSDK repo. This is the incorrect repo.

**Comment by AndrewBestbier** [comment]
Thanks @bhariharan

**Comment by AndrewBestbier** [comment]
Just so I don't make another error, did you mean this one? https://github.com/forcedotcom/ServiceSDK-Android

**Comment by bhariharan** [comment]
Yes, I believe so.
