### ISSUE TITLE
WebView on LoginActivity not fill up full available space on view

### ISSUE THREAD

**Issue by marek-embiq** [forcedotcom/SalesforceMobileSDK-Android#1750]
1. Version of Mobile SDK Used: 6.1.0
2. Issue found in Native App or Hybrid App: native
3. OS Version: all
4. Device: all
5. Steps to reproduce: 
6. Actual behavior: I'am developing some app with integration of Authorisation feature by this SDK and all logic things works fine but, client (for which i work for) has this Login web site, which has some background and simple login/pass form for signing in and in my case the site is rendered not on full available space of view. I've done some digging and found that the webview (@+id/sf__oauth_webview) in android layout XML file got android:layout_height="wrap_content" 
7. Expected Behavior: We've test clients Login site with this layout but I've put match_parent value for layout_height param and it work as expected, So now I adjust webView height param in code at runtime in my LoginActivity which extends LoginActivity from SDK v6.1.0 and this works too. Maybe match_parent should be default value in that case or at least maybe it should be possible to set it up by some SDK method...
8. Error Log: there is no need...

**Comment by bhariharan** [comment]
@marek-embiq It appears that you're using an older version of the Mobile SDK. We are already using `match_parent` (see [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceSDK/res/layout/sf__login.xml#L10)).

**Comment by marek-embiq** [comment]
thank You, didn't notice the update from v6.1.0 to 6.2.0
