### ISSUE TITLE
Not passing additional language param to login flow in webview

### ISSUE THREAD

**Issue by marek-embiq** [forcedotcom/SalesforceMobileSDK-Android#1752]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.2.0
2. Issue found in Native App or Hybrid App: native
3. OS Version: all
4. Device: all
5. Steps to reproduce: I use this code

        HashMap params = new HashMap<String, String>() {{
           this.put("language","en");
        }};
        SalesforceSDKManager.getInstance().getLoginOptions().setAdditionalParameters(params);

to pass my additional param for login url
6. Actual behavior: the param isn't there, and finally loaded page has wrong language set up.
7. Expected Behavior: passing additional params through redirects that will occur I guess
8. Error Log:

**Comment by marek-embiq** [comment]
I guess this is not correct way to change language. Maybe someone know how to pass language param for login view to change the language?

**Comment by bhariharan** [comment]
@marek-embiq `additionalParameters` in this context is for keys specific to your connected app. Language settings are automatically picked up based on device settings and/or your org's language settings. This can't be passed as a param AFAIK - you need to configure it on your device or your org. For future reference, this forum is reserved for known bugs/issues with our code. Please post any other queries or discussions in our [community](https://plus.google.com/u/1/communities/114225252149514546445?cfem=1).
