### ISSUE TITLE
not supported browser on android

### ISSUE THREAD

**Issue by marek-embiq** [forcedotcom/SalesforceMobileSDK-Android#1756]
Hello,
1. Version of Mobile SDK Used: 6.2
2. Issue found in Native App or Hybrid App: native
3. OS Version: 5.0+
4. Device: all
5. Steps to reproduce: start login flow
6. Actual behavior: popup on login view informing that Current browser is not supported shows, 
first occur: July 19th.
![screen shot 2018-07-27 at 14 08 02](https://user-images.githubusercontent.com/7914502/43319839-7ed7b4c8-91a6-11e8-9296-e146b74704cd.png)
7. Expected Behavior: regular login form
8. Error Log:

How to solve this issue? Please help.

**Comment by bhariharan** [comment]
@marek-embiq Thanks for reporting this. This is not a client-side issue, we simply render the login page within a WebView. However, this is being addressed on the backend and should be resolved soon. #safeharbor Stay tuned!

**Comment by bhariharan** [comment]
@marek-embiq It should be live now.

**Comment by marek-embiq** [comment]
@bhariharan thank You very much for your involvement in this case. There is no popup's anymore, however we have one more problem with backend in login flow.
I've add a question on salesforce developer community page:
https://developer.salesforce.com/forums/ForumsMain?id=9060G0000005iA1QAI
but like in case of question for the "not supported browser on android" there was no feedback there.
Could You please help us with this one too?
In login flow there is some wrong condition code for recognising language set up on client device. I our case it is swedish, but only english version is loading. We know that there are some redirects when mobile (android and iOS) SDK's loads login view. In last request of embedded webview there is this "language=en_US" param in query string. We tried (on iOS) to override this last request to put there "language=sv" param and login view finally has wanted swedish language set up. This whole workaround is so crazy so I want to report this "situation" but I don't have an idea where should I send my report. Please point some support guys e-mail or some better way than salesforce community Q&A

Thank You once again for help in "not supported browsers" case 
Marek

**Comment by bhariharan** [comment]
@marek-embiq We don't control the language within the `WebView`, it defaults to the device or the org locale settings.

**Comment by marek-embiq** [comment]
@bhariharan I know that You don't control the language in webview, but I know that You know where I can commit my issue report for language control feature efficiently. And I know that there is something what should be checked. Please help me. I just need to load login view in swedish. As You wrote, I can't adjust it by this SDK , and the backend don't work well. We need to solve this issue and there is no way to report it and get any feedback. We are stack :(

**Comment by bhariharan** [comment]
@marek-embiq You could log a case with Salesforce and work with the appropriate team.
