### ISSUE TITLE
Enabling Browser-Based Authentication in Android Apps - does not work

### ISSUE THREAD

**Issue by alsocalledchris** [forcedotcom/SalesforceMobileSDK-Android#1757]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.1
2. Issue found in Native App or Hybrid App: Hybrid Remote
3. OS Version: Android 8
4. Device: Samsung S8+
5. Steps to reproduce:

a) Follow steps in https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/auth_android_browserbased.htm (note that manifest file did not have the mentioned commented out lines - the whole activity element was missing)
b) Open the updated app
c) Change the login URL to be the domain with the 'native browser login' switched on
d) Use salesforce credentials to login
e) Allow the connected App

6. Actual behavior:

User can 'allow' the connected app but the app gets stuck on the next navigation page: /_ui/identity/oauth/ui/AuthorizationPage and the page hangs here

7. Expected Behavior:

User is taken to the App home screen

8. Error Log:
NA

**Comment by bhariharan** [comment]
@alsocalledchris I have verified with `Mobile SDK 6.2.0` that this works fine. Please upgrade to `6.2.0`.
