### ISSUE TITLE
Android users cannot login on Hybrid Remote Apps

### ISSUE THREAD

**Issue by alsocalledchris** [forcedotcom/SalesforceMobileSDK-Android#1758]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.1
2. Issue found in Native App or Hybrid App: Hybrid Remote
3. OS Version: Android 8
4. Device: Samsung S8+
5. Steps to reproduce:

- Try and login on a Hybrid Remote on a production org
- Enter credentials and allow the connected app
- Enter a pin

6. Actual behavior:

After entering the PIN, the user is taken out of the App to the device's native browser (?!!) and the login page is shown again with a ?ec=302&startUrl={the start page} (the login page is showing as the custom domain for the Org)

7. Expected Behavior:

User is shown the app start page within the App. This works fine on iOS and only affects Android. Is also fine in branch and other demo Orgs - just affects production Orgs (I have a feeling it is something to do with the custom domains that production Orgs get assigned...?)

8. Error Log: NA

This works fine for iOS. I have tried using the Chrome browser to get around this issue but this solution breaks in a different way.

**Comment by alsocalledchris** [comment]
@bhariharan would be good to get your opinion on this as this is very strange behaviour only seen in production and on Android. thanks

**Comment by bhariharan** [comment]
@alsocalledchris Could you generate a new hybrid remote app using `forcehybrid@6.2.0` and try this? If it's something unique to an org, it's outside the control of the container itself and probably has something to do with the org configuration.

**Comment by alsocalledchris** [comment]
@bhariharan I've done this with no joy and I'm currently debugging the Android code (is not just one org reporting this error now - all production orgs) - I think it is the way it is handling the non-instance url - it seems to think it has got to the confirmed home page and tries to show it, however there is still a 302 to come on that URL and this is what is popping the URL out of the App into the native browser (with the ec=302 URL.) The logs from the app are showing the navigation as:

D/CordovaWebViewImpl: onPageDidNavigate(https://{mydomain}--c.documentforce.com/secur/contentDoor?startURL=
D/CordovaWebViewImpl: onPageFinished(https://{mydomain}--c.documentforce.com/secur/contentDoor?startURL=
D/CordovaWebViewImpl: onPageDidNavigate(https://{mydomain}.my.salesforce.com/apex/{mynamespace}__{visualForcePage})
D/CordovaWebViewImpl: onPageDidNavigate(https://{mydomain}--{mynamespace}.visualforce.com/apex/{mynamespace}__{visualForcePage})
D/CordovaWebViewImpl: showWebPage(https://{mydomain}--{mynamespace}.visualforce.com/apex/{visualForcePage}), true, false, HashMap)
D/CordovaActivity: Paused the activity.
D/CordovaWebViewImpl: onPageFinished(https://{mydomain}--{mynamespace}.visualforce.com/apex/{visualForcePage})

The next action is the native browser showing login page a with the home page url above as the start URL. 

Any help greatly appreciated as this is looking like it doesn't work at all for hybrid remote solution and Android (it works fine with iOS)

**Comment by bhariharan** [comment]
This seems to be unique to your custom domain. It's worrying that `startURL` is empty. Also, it shouldn't pop out to the browser for `302`, it should refresh and reload the page. But if `startURL` is empty, it won't know what to reload.

**Comment by alsocalledchris** [comment]
@bhariharan - sorry, the startURL is not empty (I just removed its contents) - it has the right URL in it. Agreed it shouldn't pop out but it does and is not a Org specific thing.

**Comment by bhariharan** [comment]
By org specific, I mean something specific to that configuration, because I can't reproduce it with a couple of my orgs with expired credentials.

**Comment by alsocalledchris** [comment]
Thanks for looking - try activated the Salesforce critical update: 'Remove Instance Names From URLs for Visualforce, Community Builder, Site.com Studio, and Content Files' on your Org - this was how I reproduced in my demo org (and note the destination page is in a managed package in a namespace).

**Comment by bhariharan** [comment]
Okay, so it is org-config specific. :-) I'm not sure we can support that checkbox because without the `instanceURL`, the redirection through `frontdoor.jsp` might fail.

**Comment by alsocalledchris** [comment]
@bhariharan this is standard functionality isn't it? Production orgs don't have instance names do they? - they have a custom domain with no instance in them - I was just updating my demo org to mimic the production environment (the production orgs don't have that setting switched on and replicating the URL requests in the browser does take the user to the ec 302 page, so it's just very odd and specific to Android that it doesn't work - this does work on iOS)

**Comment by alsocalledchris** [comment]
@bhariharan OK, I've found the problem and solution - it's a whitelist issue. The following files need updating:

SalesforceHybrid/res/xml/config.xml
app/res/xml/config.xml

Need to add in the allow-navigation / access domains for other salesforce domains - e.g. documentforce and visualforce (and other used Salesforce domains...) I can do a PR for the SalesforceHybrid file change - will this update the app specific one?

**Comment by bhariharan** [comment]
@alsocalledchris Good find! I don't think we should add it to `SalesforceHybrid` across the board. Adding it in your app should suffice.
