### ISSUE TITLE
Login with single sign-on

### ISSUE THREAD

**Issue by lpongetti** [forcedotcom/SalesforceMobileSDK-Android#1761]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.2
2. Issue found in Native App or Hybrid App: React Native
3. OS Version: Android  API 25
5. Steps to reproduce: 

Hi, i setted my login in salesforce with SAML single sign-on.

![image](https://user-images.githubusercontent.com/6831116/43635524-9f7bb116-970f-11e8-8f6f-91e1267def95.png)

![image](https://user-images.githubusercontent.com/6831116/43635581-cace10ca-970f-11e8-9348-f49481d69528.png)

And my AndroidManifest.xml:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.test">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">

      <!-- Login activity -->
      <activity android:name="com.salesforce.androidsdk.ui.LoginActivity"
        tools:replace="android:theme"
        android:theme="@android:style/Theme.Black.NoTitleBar.Fullscreen" />

      <!-- <activity android:name="com.salesforce.androidsdk.ui.PasscodeActivity"
        tools:replace="android:theme"
        android:theme="@android:style/Theme.Black.NoTitleBar.Fullscreen" /> -->

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
          <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>

      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>

```

Login with salesforce page works perfectly but if i choose federation its give me a 401 error.

![image](https://user-images.githubusercontent.com/6831116/43635733-42323ed4-9710-11e8-9085-a74ba422d9a1.png)

![image](https://user-images.githubusercontent.com/6831116/43635749-4f06f92e-9710-11e8-9af6-95db8b9f8955.png)

If i check "Use the native browser for user authentication on Android" and i insert the intent in AndroidManifest it works, but i want use the webview inside the app.

How can i solve this?
Thanks

**Comment by bhariharan** [comment]
@lpongetti How did you generate your app? Did you use `forcedroid`? Could you run our sample app, `SmartSyncExplorer` out of the box from [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/tree/master/native/NativeSampleApps/SmartSyncExplorer/src/com/salesforce/samples/smartsyncexplorer) and attempt to login with your credentials?
