### ISSUE TITLE
Build error on Android 9 (API level 28)

### ISSUE THREAD

**Issue by amrboxit4me** [forcedotcom/SalesforceMobileSDK-Android#1765]
Please fill out the following details:

1. Version of Mobile SDK Used: 
6.2.0
2. Issue found in Native App or Hybrid App:
Native
3. OS Version:
Mac OS

4. Device:
Emulator SDK 28

5. Steps to reproduce:
Just upgrade the project to     
```
    compileSdkVersion 28
    buildToolsVersion '28.0.2'

```
6. Actual behavior:
Build fails

7. Expected Behavior:
To build the project

8. Error Log:
I got an error in the build 
"values.xml:1133 is     `<item name="sos_key_shift_state" type="id">com.salesforce.android.sos.TAG_SHIFT_STATE</item>`"

Android resource compilation failed
Output: 

```
/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1133: error: <item> inner element must either be a resource reference or empty.

Command: /.gradle/caches/transforms-1/files-1.1/aapt2-3.3.0-alpha05-4916870-osx.jar/ea48450db7dec454fc0619990bfc23af/aapt2-3.3.0-alpha05-4916870-osx/aapt2 compile --legacy \
        -o \
        /app/build/intermediates/res/merged/debug \
        /app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
Daemon:  AAPT2 aapt2-3.3.0-alpha05-4916870-osx Daemon #0
```

**Comment by bhariharan** [comment]
We don't support `API 28` yet. Stay tuned for support.
