### ISSUE TITLE
Chat record or case is not created automatically at sales force chat agent side or user record is not showing

### ISSUE THREAD

**Issue by AndyKD** [forcedotcom/SalesforceMobileSDK-Android#1766]
Please fill out the following details:

1. A version of Mobile SDK Used: 3.1.0
2. Issue found in Native App or Hybrid App:
3. OS Version: 26.01
4. Device: All Devices
5. Steps to reproduce: Initiate a chat with Agent, as chat connects automatically chat client record should be created with the case number, we are sending the detail in pre-chat form and pre-chat entity but still chat agent is not able to see the detail and chat case number is not created.
6. Actual behavior:  Case/Record number is not created automatically and the chat agent is not able to see the user data.
7. Expected Behavior: Case number should be created automatically as well as chat connects with a chat agent.
8. Error Log: No exactly

**Comment by bhariharan** [comment]
This is not the right repository for the `Chat` product.

**Comment by AndyKD** [comment]
Can you please post the link of right repository?

Thanks.

**Comment by brandonpage** [comment]
@AndyKD https://github.com/forcedotcom/ServiceSDK-Android
