### ISSUE TITLE
Case/Record is not created automatically in Sales force chat agent side in live chat.

### ISSUE THREAD

**Issue by AndyKD** [forcedotcom/SalesforceMobileSDK-Android#1767]
Please fill out the following details:

1. Version of Mobile SDK Used: 3.1.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: All
4. Device: All
5. Steps to reproduce: **Start a chat with a live agent, case/record is not created on the agent side. Agent is not able to get any information of the chat client by using chat entity method of SDK**
6. Actual behavior: **Chat agent should side shown with the auto-generated case/record of the user and later on agent should be able to update the case number**
7. Expected Behavior: **Chat agent should be shown with auto-generated case number, when chat connects with the agent.**
8. Error Log:

Please let us know where we are doing wrong.
ChatEntity caseEntity = new ChatEntity.Builder().linkToTranscriptField("CaseId")
        .showOnCreate(true)
        .addChatEntityField(
                new ChatEntityField.Builder()
                        .doFind(true)
                        .isExactMatch(true)
                        .doCreate(true)
                        .build(Sp_Constants.KEY_SUBJECT, new ChatUserData(Sp_Constants.KEY_SUBJECT)))
        .build("Case");

// create chat entity fields for contact details
// add user name. we are using the first name for both name and first name
ChatUserData nameData = new ChatUserData(Sp_Constants.KEY_NAME, data.getFirst_name(), true, Sp_Constants.KEY_NAME);
ChatEntityField name = new ChatEntityField.Builder().doFind(true).isExactMatch(true).doCreate(true).build(Sp_Constants.KEY_NAME, nameData);

// add first name
ChatUserData fNameData = new ChatUserData(Sp_Constants.KEY_FIRST_NAME, data.getFirst_name(), true, Sp_Constants.KEY_FIRST_NAME);
ChatEntityField fname = new ChatEntityField.Builder().doFind(true).isExactMatch(true).doCreate(true).build(Sp_Constants.KEY_FIRST_NAME, fNameData);

//add last name
ChatUserData lNameData = new ChatUserData(Sp_Constants.KEY_LAST_NAME, data.getLast_name(), true, Sp_Constants.KEY_LAST_NAME);
ChatEntityField lName = new ChatEntityField.Builder().doFind(true).isExactMatch(true).doCreate(true).build(Sp_Constants.KEY_LAST_NAME, lNameData);

// add email
ChatUserData emailData = new ChatUserData(Sp_Constants.KEY_EMAIL, data.getEmail(), true, Sp_Constants.KEY_EMAIL);
ChatEntityField email = new ChatEntityField.Builder().doFind(true).isExactMatch(true).doCreate(true).build(Sp_Constants.KEY_EMAIL, emailData);

// add customerId 
ChatUserData customerIdData = new ChatUserData(Sp_Constants.KEY_CUSTOMER_ID, ((Sp_LandingActivity) context).getxCloudId(), true, Sp_Constants.KEY_CUSTOMER_ID);
ChatEntityField customerId = new ChatEntityField.Builder().doFind(true).isExactMatch(true).doCreate(true).build(Sp_Constants.KEY_CUSTOMER_ID, customerIdData);

// add chat category
ChatUserData chatCatData = new ChatUserData(Sp_Constants.KEY_CHAT_CATEGORY, data.getChat_category(), true, Sp_Constants.KEY_CHAT_CATEGORY);
ChatEntityField category = new ChatEntityField.Builder().doFind(true).isExactMatch(true).doCreate(true).build(Sp_Constants.KEY_CHAT_CATEGORY, chatCatData);

//add language
ChatUserData languageData = new ChatUserData(Sp_Constants.KEY_LANGUAGE, Sp_Constants.KEY_CHAT_LANG, true, Sp_Constants.KEY_LANGUAGE);
ChatEntityField language = new ChatEntityField.Builder().doFind(true).isExactMatch(true).doCreate(true).build(Sp_Constants.KEY_LANGUAGE, languageData);

// add phone number
ChatEntityField phoneNo = new ChatEntityField.Builder().doFind(true).isExactMatch(true).doCreate(true).build(Sp_Constants.KEY_PHONE, new ChatUserData(Sp_Constants.KEY_PHONE, data.getPhone_no(), true, Sp_Constants.KEY_PHONE));

// add product detail
ChatEntityField product = new ChatEntityField.Builder().doFind(true).isExactMatch(true).doCreate(true).build(Sp_Constants.KEY_PRODUCT, new ChatUserData(Sp_Constants.KEY_PRODUCT, productItem.getProduct(), true, Sp_Constants.KEY_PRODUCT));

// add purchase date
ChatEntityField purchaseDate = new ChatEntityField.Builder().doFind(true).isExactMatch(true).doCreate(true).build(Sp_Constants.KEY_PURCHASE_DATE, new ChatUserData(Sp_Constants.KEY_PURCHASE_DATE, data.getPurchase_date(), true, Sp_Constants.KEY_PURCHASE_DATE));

// add product's serial number
ChatEntityField serialNo = new ChatEntityField.Builder().doFind(true).isExactMatch(true).doCreate(true).build(Sp_Constants.KEY_SERIAL_NO, new ChatUserData(Sp_Constants.KEY_SERIAL_NO, data.getSerial_number(), true, Sp_Constants.KEY_SERIAL_NO));

// add registration number
ChatEntityField regNo = new ChatEntityField.Builder().doFind(true).isExactMatch(true).doCreate(true).build(Sp_Constants.KEY_REGISTRATION_ID, new ChatUserData(Sp_Constants.KEY_REGISTRATION_ID, productItem.getRegistration_ID(), true, Sp_Constants.KEY_REGISTRATION_ID));

ChatEntity.Builder contactEntity = new ChatEntity.Builder().linkToTranscriptField("ContactId")    // linktotranscriptfield is equal to savetotranscript
        .showOnCreate(true).linkToAnotherSalesforceObject(caseEntity, "CaseId");

if (name != null) {
    contactEntity.addChatEntityField(name).build(Sp_Constants.KEY_NAME);
}
if (fname != null) {
    contactEntity.addChatEntityField(fname).build(Sp_Constants.KEY_FIRST_NAME);
}
if (lName != null) {
    contactEntity.addChatEntityField(lName).build(Sp_Constants.KEY_LAST_NAME);
}
if (email != null) {
    contactEntity.addChatEntityField(email).build(Sp_Constants.KEY_EMAIL);
}
if (customerId != null) {
    contactEntity.addChatEntityField(customerId).build(Sp_Constants.KEY_CUSTOMER_ID);
}
if (category != null) {
    contactEntity.addChatEntityField(category).build(Sp_Constants.KEY_CHAT_CATEGORY);
}
if (language != null) {
    contactEntity.addChatEntityField(language).build(Sp_Constants.KEY_LANGUAGE);
}
if (phoneNo != null) {
    contactEntity.addChatEntityField(phoneNo).build(Sp_Constants.KEY_PHONE);
}
if (purchaseDate != null) {
    contactEntity.addChatEntityField(purchaseDate).build(Sp_Constants.KEY_PURCHASE_DATE);
}
if (serialNo != null) {
    contactEntity.addChatEntityField(serialNo).build(Sp_Constants.KEY_SERIAL_NO);
}
if (product != null) {
    contactEntity.addChatEntityField(product).build(Sp_Constants.KEY_PRODUCT);
}
if (regNo != null) {
    contactEntity.addChatEntityField(regNo).build(Sp_Constants.KEY_REGISTRATION_ID);
}
// Specify your Live Agent Chat org settings. (orgId, buttonId, deploymentId, liveAgentProdId)
ChatConfiguration.Builder chatConfBuilder = new ChatConfiguration.Builder(orgId, buttonId, deploymentId, liveAgentProdId);
ChatUI.configure(ChatUIConfiguration.create(chatConfBuilder.chatEntities(contactEntity.build("Contact"), caseEntity).build()))
        .createClient(context).onResult(new Async.ResultHandler<ChatUIClient>() {
            @Override
            public void handleResult(Async<?> operation,
                             @NonNull final ChatUIClient chatUIClient) {
                
                chatUIClient.startChatSession(getActivity());
            }
        });
Also adding the keys that we are using for data:-
public static final String KEY_NAME = "Name";
public static final String KEY_FIRST_NAME = "FirstName";
public static final String KEY_LAST_NAME = "LastName";
public static final String KEY_EMAIL = "Email";
public static final String KEY_CUSTOMER_ID = "CustomerId";
public static final String KEY_LANGUAGE= "Language";
public static final String KEY_CHAT_CATEGORY = "ChatCategory";
public static final String KEY_PRODUCT = "Product";
public static final String KEY_PURCHASE_DATE = "PurchaseDate";
public static final String KEY_SERIAL_NO = "SerialNumber";
public static final String KEY_REGISTRATION_ID = "RegistrationId";
public static final String KEY_PHONE = "Phone";

**Comment by bhariharan** [comment]
LiveAgent is a different product. Please use the appropriate repository for that product.

**Comment by AndyKD** [comment]
Please, can you give me correct repo?

Would be really appreciated.

Thanks.

*With Regards,*

Deepak Kumar

Sr. Engineer (SW)

VVDN Technologies Pvt. Ltd.

*Cell : *+91 9878022035 (Ind.)|+1408-796-8596 (US) | *Skype :
deepak.kumar3038*

http://www.vvdntech.com/





On Sun, Aug 12, 2018 at 9:06 PM, Bharath Hariharan <notifications@github.com

**Comment by brandonpage** [comment]
@AndyKD https://github.com/forcedotcom/ServiceSDK-Android
