### ISSUE TITLE
How to sync the attachment object which was locally created ?

### ISSUE THREAD

**Issue by Murugan1778** [forcedotcom/SalesforceMobileSDK-Android#1780]
Hi all ,
    I am developing native android application using sales force mobile SDK 5.3.0, where i am using attachment object to upload the images to server .If network available attachment object synced to server successfully but there is no network the attachment object stored in the smart store locally.While trying  to sync the locally created attachment object to server it returns the response of bad request.Now i want to know about how to sync the attachment object which was locally created?

**Comment by wmathurin** [comment]
It is not supported out of the box. You will have to create a custom sync target. https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/entity_framework_native_custom_up_targets.htm
