### ISSUE TITLE
LoginActivity doesn't support orientation change

### ISSUE THREAD

**Issue by Fritte7** [forcedotcom/SalesforceMobileSDK-Android#1781]
Can we have the possibility to restrict the orientation screen for login activity?
Or at least manage the orientation change and retain information.

1. Version of Mobile SDK Used: 6.3
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: P
4. Device: Pixel 2
5. Steps to reproduce: Launch the login screen, add login+pwd and turn the screen, you lose everything
Same thing when you need to add the code security, if the orientation change, you need to re-do all the process

**Comment by bhariharan** [comment]
This is by design. The Android OS rebuilds the screen when screen rotation occurs. You're welcome to subclass `LoginActivity` and lock it down if you like. The screens are extensible.

**Comment by Fritte7** [comment]
OK Thanks for your answer...
Just fyi 
https://developer.android.com/guide/topics/resources/runtime-changes
Have a nice day.
