### ISSUE TITLE
SoqlSyncDownTarget with subquery issue

### ISSUE THREAD

**Issue by jpttrindade** [forcedotcom/SalesforceMobileSDK-Android#1787]
1. Version of Mobile SDK Used: 6.0.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: Android 8.0 
4. Device: Moto G6

5. Steps to reproduce: 
i) Create a soql syncdown to any object (like Opportunity) with a subquery as filter.   
Sample: SELECT Id where OwnerId in (select Id from Account)
ii) run resync
iii) run cleanResyncGhosts from SyncManager to this object

6. Actual behavior:
A error of "MALFORMED_QUERY" occurs because the handler of filter(subquery in this case). 
At the SoqlSyncDownTarget class and his getSoqlForRemoteIds methods, the 'split' in atcual query not support subquery sintaxe because put away part of subquery that contains  'from' string;
```
Sample:  
array =  "select X from Y where a = (select M from N)".split('from') will to return a array with 3 values
1. array[0] = 'select X '
2. array[1] =  ' Y where a = (select M '
3. array[2] = ' N)'
 and method get only array[1] to build final query to request:
```

**SNAPSHOT:**
```
final StringBuilder soql = new StringBuilder("SELECT ");
        soql.append(getIdFieldName());
        soql.append(" FROM ");
        final String[] fromClause = getQuery(0).split("([ ][fF][rR][oO][mM][ ])");
        soql.append(fromClause[1]);
        return soql.toString();
```

7. Expected Behavior:
At the SoqlSyncDownTarget class and his getSoqlForRemoteIds methods the query split should result e only 2 parts, where only first 'from' is handled to support subqueries.

```
(...) final String[] fromClause 
 = getQuery(0).split("([ ][fF][rR][oO][mM][ ])", 2); // note second parameter
where, fromClause is:
fromClause[0] =  'select X '
fromClause[1] = ' Y where a = (select M from N)'

// fromClause[1] is entire second part of query.
```

8. Error Log:

```
{
        "message": "\nAccount WHERE Id in (SELECT AccountId\n                                    ^\nERROR at Row:1:Column:52\nunexpected token: '<EOF>'",
        "errorCode": "MALFORMED_QUERY"
      }
```

**Comment by wmathurin** [comment]
Fixing with https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1873
NB: SOQL only subquery on the select side (see https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select.htm)

**Comment by wmathurin** [comment]
[Fix](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1873/files) will be in next release.
