### ISSUE TITLE
PIN challenge does not work on Samsung running Android 8 devices if less than 10 minutes

### ISSUE THREAD

**Issue by alsocalledchris** [forcedotcom/SalesforceMobileSDK-Android#1797]
Please fill out the following details:

1. Version of Mobile SDK Used: 6.1 & 6.2
2. Issue found in Native App or Hybrid App: Hybrid
3. OS Version: Android 8
4. Device: Samsung S8, and other Samsung devices running Android 8
5. Steps to reproduce:

- Set the connected App to use a PIN challenge with a timeout of less than 10 minutes.
- Log into the App, navigate to a different App and then leave the phone
- Come back to the phone and re-open the App

6. Actual behavior:
- PIN challenge is not shown unless the device is left for longer than 10 minutes
- All other tested Android devices running different versions (including Samsung running less and greater than Android 8) are fine

7. Expected Behavior:

- PIN challenge should be shown if the App has been left for longer than the timeout and the timeout is set to 1 or 4 minutes on Samsung devices running Android 8.

8. Error Log: NA

**Comment by brandonpage** [comment]
Hi @alsocalledchris,

Did you logout of the app after changing the timeout length on the connected app?  The SDK does not proactively retrieve those values so they will remain whatever the values were when the user logged in initially.  It is possible to periodically fetch and update passcode length and timeout but it is not something we force.

Thanks,
Brandon

**Comment by alsocalledchris** [comment]
That’s exactly it, many thanks!
