### ISSUE TITLE
error=invalid_scope

### ISSUE THREAD

**Issue by achinverma** [forcedotcom/SalesforceMobileSDK-Android#1802]
Hi , I have creted a connected app and i have created a native app from [](https://trailhead.salesforce.com/en/content/learn/modules/mobile_sdk_native_android/mobilesdk_android_getting_started
)it is working fine with the default 
```
remoteAccessConsumerKey 
oauthRedirectURI
```

but when i placed my connected app 
remoteAccessConsumerKey and 
oauthRedirectURI , 
i am getting below error, please guide me 

`error=invalid_scope&error_description=the%20requested%20scope%20is%20not%20available`

1. Version of Mobile SDK Used: 27
2. Issue found in Native App or Hybrid App: native 
3. OS Version: 7.0
4. Device: Nexus 7 tablet

**Comment by bhariharan** [comment]
@achinverma This is not a client side issue. You need to update the scopes on your connected app (on the server side) to match the scopes declared on the client side.

**Comment by achinverma** [comment]
@bhariharan , thanks for the reply,
i have checked in my demo, my scopes are same defined in connected app.

This is my Consumer Key and call back url, please let me know if you can help me
```
<string name="remoteAccessConsumerKey">3MVG9YDQS5WtC11oGQJP_eA2Z02CKjh4IcAALGkLknMIoxv6sr7s4Y06bFgb2RelOFCs3rLYi1JoyHOq_wsNu</string>
    <string name="oauthRedirectURI">https://dev1.saleschap.localhost/cp/callback</string>
```
