### ISSUE TITLE
Live Chat  session and Case creation 

### ISSUE THREAD

**Issue by JinTiloganart** [forcedotcom/SalesforceMobileSDK-Android#1804]
Please fill out the following details:

1. SDK version: 214.0.2Live agent chat version: 3.1.0
2. Issue found in Native App or Hybrid App: Native app
3. OS Version: Android 9
4. Device: Google Pixel 2 XL
5. Steps to reproduce:
1) Customer with existing account in Salesforce initiate chat from Android device. Chat is routed to Agent A
2) From Agent A side, Live Chat Transcript 01 is created, Case 01 is popped up next to Live chat transcript chat. Live Chat Transcript 01 is automatically associated with Case 01
3) Agent ends the chat.
4) The same customer initiate another chat from Android device.
6) Chat is routed to Agent B
7) From Agent side, Live Chat Transcript 02 is created, Case 01 is popped up next to Live chat transcript chat. Live Chat Transcript 02 is ALSO associated with Case 01
 
6. Actual behavior:  Live Chat Transcript initiated by the same customer is added to the same existing case.
7. Expected Behavior: When a new chat session is initiated (Live Chat Transcript02), it should always create a new case (Case 02) and associate Live Chat transcript to it.
 
8. Error Log:
 
9. Additional info:
- Version of your developer tool: Android Studio 3.2
- What language they are using: Kotlin

**Comment by bhariharan** [comment]
This is not the right forum to post issues with the SnapIns SDK. Mobile SDK is a different product.
