### ISSUE TITLE
Multiple Live Agent thumbnail

### ISSUE THREAD

**Issue by JinTiloganart** [forcedotcom/SalesforceMobileSDK-Android#1805]
Please fill out the following details:

1. SDK version: 214.0.2, Live agent chat version: 3.1.0
2. Issue found in Native App or Hybrid App: Native app
3. OS Version: Android 9
4. Device: Google Pixel 2 XL
5. Steps to reproduce:

1) Customer Initiate a chat and is connected to Live Agent 
2) Agent click 'End chat' 
3) On customer side, 'Chat session ended by agent' appear on the screen
4) Customer minimize chat page, chat icon is grey with 'Chat Ended' under icon
5) Click on 'Live Agent' again to initiate a chat, without closing the existing chat icon is not initiated.
6) New thumbnail popped up, the old thmbnail is still present

6. Actual behavior: New thumbnail is created, old one is still existing
7. Expected Behavior: Only one thumbnail is present at a time
8. Error Log:

**Comment by bhariharan** [comment]
This is not the right forum to post issues with the SnapIns SDK. Mobile SDK is a different product.
