### ISSUE TITLE
Receiving ChatID and CaseID via Android SDK

### ISSUE THREAD

**Issue by JinTiloganart** [forcedotcom/SalesforceMobileSDK-Android#1806]
After every chat ends, we would like to direct customer to a rating page, in which after customer has rated us, the result will be sent back to be associated with chat/case raised by customer.

To do so, caseID and chatID is needed to correctly link result and its case, however, right now the SDK only know agentID.

1. Version of Mobile SDK Used:  SDK version: 214.0.2, Live agent chat version: 3.1.0
2. Issue found in Native App or Hybrid App: Native

**Comment by bhariharan** [comment]
This is not the right forum to post issues with the SnapIns SDK. Mobile SDK is a different product.
