### ISSUE TITLE
Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

### ISSUE THREAD

**Issue by amg** [forcedotcom/SalesforceMobileSDK-Android#1820]
Please fill out the following details:

1. Version of Mobile SDK Used: 
  6.2.0
2. Issue found in Native App or Hybrid App: 
  Used in native app
3. OS Version:
  9.0
4. Device:
  Pixel 2
5. Steps to reproduce:
  Unknown, reported via Firebase Crashlytics
6. Actual behavior:
  Crash
7. Expected Behavior:
  No Crash
8. Error Log:

Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

java.net.URI$Parser.parse (URI.java:3086)
java.net.URI. (URI.java:583)
com.salesforce.androidsdk.rest.ClientManager.peekRestClient (SourceFile:233)
com.salesforce.androidsdk.analytics.AILTNPublisher.com.salesforce.androidsdk.rest.ClientManager.peekRestClient (SourceFile:1139)
com.salesforce.androidsdk.analytics.AILTNPublisher.publish (SourceFile:98)
com.salesforce.androidsdk.analytics.SalesforceAnalyticsManager.publishEvents (SourceFile:316)
com.salesforce.androidsdk.analytics.SalesforceAnalyticsManager.publishAllEvents (SourceFile:275)
com.salesforce.androidsdk.analytics.AnalyticsPublisherService.handleActionPublish (SourceFile:1075)
android.support.v4.app.JobIntentService$CommandProcessor.doInBackground$10299ca (SourceFile:2391)
android.os.AsyncTask$2.call (AsyncTask.java:333)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:764)

**Comment by bhariharan** [comment]
@amg This shouldn't crash the app in any way. If the service fails, the exception might show up in the logs, but won't affect the app. If you are seeing the app crashing, feel free to reopen.

**Comment by amg** [comment]
Thanks @bhariharan, will keep an eye on it

**Comment by amg** [comment]
Hi @bhariharan, confirming crash observed in one of our customers/employees happening.
Happening on first launch after not using the app for a while. Please reopen the issue. Same log as above

Thanks,
Alex

**Comment by bhariharan** [comment]
@amg Could you try with our latest release `7.0.0-rc` from [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/tree/v7.0.0-rc)? We've fixed quite a few bugs in this release.

**Comment by amg** [comment]
@bhariharan unfortunately cannot reproduce easily so it would be more of a prod test.
When is the release planned for 7.0.0?

Also looking through the code of the ClientManager it looks like maybe one of the URL creations fails because `loginServer` or `idUrl` are null? Only URISyntaxException is caught at that stage. Could you please verify?

Thanks,
Alex

**Comment by bhariharan** [comment]
@amg The release candidate is out [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/tree/v7.0.0-rc). Also, `loginServer` and `idUrl` should never be `null`. If it is, there's something wrong with the project setup.

**Comment by amg** [comment]
@bhariharan Could be an issue with AccountManager? People here: https://stackoverflow.com/questions/28691847/android-accountmanager-getuserdata-returns-null (and link inside) reported it happening to them. 
Any way we could handle this more gracefully? It's clearly happening because some values are null.

Cheers,
Alex

**Comment by bhariharan** [comment]
We've already added checks for this [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/dev/libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ClientManager.java#L220). If the values don't exist, an exception will be thrown that is handled at a higher level.
