### ISSUE TITLE
How to close a case 

### ISSUE THREAD

**Issue by AndyKD** [forcedotcom/SalesforceMobileSDK-Android#1833]
Version of Mobile SDK Used: 3.1.0
Issue found in Native App or Hybrid App: Native App
OS Version: All
Device: All
Steps to reproduce: We have some opened cases, which we want if user wants can close it anytime.
Actual behavior: Closing a case
Expected Behavior: To close a case using SDK
Error Log: No logs required.

**Comment by bhariharan** [comment]
@AndyKD This is not the right repository for `SnapIns`/`ServiceSDK`. This forum is reserved for issues with `Mobile SDK`.

**Comment by AndyKD** [comment]
I am talking about SDK only. In the SDK if this is supported.

**Comment by bhariharan** [comment]
If it's related to Mobile SDK, this forum is reserved for bugs/issues with our code. For general queries and other inquiries, please use our community [here](https://plus.google.com/u/1/communities/114225252149514546445?cfem=1).
