### ISSUE TITLE
Improve Logging options

### ISSUE THREAD

**Issue by superfell** [forcedotcom/SalesforceMobileSDK-Android#184]
Currently the SDK logs various things though the standard Android log classes with a variety of different tags, this makes it hard to use the tag filtering capabilities of adb to see all your app specific logging.

it'd be nice if
a) I could tell the SDK a specific tag to use for all its logging
and/or
b) route log calls to something the SDK consumer can override (perhaps to route the logging to a different framework)

**Comment by wmathurin** [comment]
I don't think there is any plans of doing that work.

**Comment by bhariharan** [comment]
We did end up creating a new logging framework after all - [pull request](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1419). This should be a part of `Mobile SDK 5.2`.
