### ISSUE TITLE
File attachment in the case creation

### ISSUE THREAD

**Issue by AndyKD** [forcedotcom/SalesforceMobileSDK-Android#1841]
A version of Mobile SDK Used: 3.1.0
Issue found in Native App or Hybrid App: Native App
OS Version: All
Device: All
Steps to reproduce: We have some opened cases, which we want if user wants can close it anytime.
Actual behavior: Closing a case
Expected Behavior: To close a case using SDK
Error Log: No logs required.

I want to attach a file like jpg, png, pdf, the doc at the time of case creation, could you please let me know if you have any demo or source code available to help. Would be really appreciated.

**Comment by wmathurin** [comment]
Are you really using Salesforce Mobile SDK 3.1 (https://www.npmjs.com/package/forcedroid/v/3.1.0 or https://github.com/forcedotcom/SalesforceMobileSDK-Android/tree/v3.1.0)? Or are you talking about a different SDK?

We strongly recommend you use the latest version (7.0).

**Comment by bhariharan** [comment]
Also, this forum is reserved for known bugs/issues with our code. Please use our forum [here](https://plus.google.com/u/1/communities/114225252149514546445?cfem=1) for other queries.
