### ISSUE TITLE
InActive and Freeze Users [Android Native]

### ISSUE THREAD

**Issue by majidalik** [forcedotcom/SalesforceMobileSDK-Android#1847]
Once user logged in app, He is still able to use app when we have unchecked the check "Active" from users.
Is there any way to can i check that is user active or inactive? In android

**Comment by wmathurin** [comment]
The identity service returns that information.

It looks like we don't parse it out on Android like we do on iOS (see https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java#L491) so it's not available on the UserAccount object at this point.

Until we fix that, you could do the request yourself. The following should do the trick:
```java
public boolean isUserActive(UserAccount user) throws JSONException {
    RestClient restClient = SalesforceSDKManager.getInstance().getClientManager().peekRestClient(user)
    RestResponse response = restClient.sendSync(new RestRequest(RestMethod.GET, user.getIdUrl()));
    return response.asJSONObject().getBoolean("active");
}
```

**Comment by majidalik** [comment]
@wmathurin Thanks a lot, Its working perfect for me.

**Comment by wmathurin** [comment]
The workaround we proposed seems to have been sufficient. Closing issue.
