### ISSUE TITLE
Refresh Credentials | Re-login

### ISSUE THREAD

**Issue by majidalik** [forcedotcom/SalesforceMobileSDK-Android#1848]
If any user is already logged in then how can we re-authenticate a user in background?

**Comment by wmathurin** [comment]
On login, you get a refresh token and an access token. The access token is used to access APIs (that require authentication). The access token is only valid for a certain amount of time (defined by an org setting).

The refresh token is used to get a new access token when the existing one expires. It is simply a call against the token end point: no user interaction is needed, authentication credentials (username / password) don't need to be provided.
