### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by majidalik** [forcedotcom/SalesforceMobileSDK-Android#1857]
How can i restrict outsider users login, I want to allow only whose belongs to my connected app.
I am using consumer_key & consumer_name of a app But I noticed salesforce also allowing those users who are not from mine connected app.

**Comment by wmathurin** [comment]
To control what user profiles has access to a connected app, see the steps [here](https://help.screensteps.com/m/salesforce/l/149551-assign-user-profiles-to-your-connected-app-in-salesforce).
