### ISSUE TITLE
Parameters & Custom Fields

### ISSUE THREAD

**Issue by majidalik** [forcedotcom/SalesforceMobileSDK-Android#1862]
I want to fetch some data from user object, But parameters are missing in user object.
1. Title, Manager, Role and Custom fields.
Can you please help how can i fetch above params from user object without SOQL.

**Comment by wmathurin** [comment]
Github issues are meant for reporting (suspected) bugs in the Salesforce Mobile SDK.
You are asking how to use SOQL.
Please refer to the [SOQL documentation](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_sosl_intro.htm) and please refer to the [documentation on the User object](https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_user.htm) to figure out the available fields.

**Comment by majidalik** [comment]
@wmathurin  I am not asking for SOQL.
I am unable to find following data from user object [SalesforceMobileSDk], Can you plz help where can find out following params?
Title, Manager, Role and Custom fields.

**Comment by wmathurin** [comment]
I understand your question now. The UserAccount object only contains identity/authentication related data for the current user (whatever the identity service gives us). The fields you want are available on the standard User object. To get them do a SOQL query or better do a Rest API retrieve.

ˋˋˋJava
RestRequest request = RestRequest.getRequestForRetrieve(apiVersion, "User", userId, listOfFields) ;

RestResponse response = restClient.sendSync(request);

ˋˋˋ
