### ISSUE TITLE
Remove Menu Option

### ISSUE THREAD

**Issue by majidalik** [forcedotcom/SalesforceMobileSDK-Android#1885]
How can i disable or remove setting/menu option from login page. I want to restrict the user he/she should not change server url.
![Salesforce](https://user-images.githubusercontent.com/43138839/55855290-92e60380-5b80-11e9-9ebc-effbd8c1d707.png)

**Comment by majidalik** [comment]
I resolved it passing custom login_activity class.

**Comment by smithaaron** [comment]
My iOS colleagues tell me that this can be configured in the iOS SDK. I don't believe it should be necessary to create a custom LoginActivity just to disable this. @majidalik can you reopen this issue so that it can (hopefully) be fixed in the Android SDK?

**Comment by majidalik** [comment]
@smithaaron Just reopened.

**Comment by bhariharan** [comment]
@smithaaron @majidalik This is working as per design for now on `Android`. We can consider enhancing in the future, but the pattern we're encouraging on the `Android SDK` is to provide your own sub-class implementation for any overrides you may need.
