### ISSUE TITLE
Can I use Salesforce Android SDK 7.0 if my project requires android SDK 27 or lower?

### ISSUE THREAD

**Issue by bryonCatalyst** [forcedotcom/SalesforceMobileSDK-Android#1888]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.0
2. Issue found in Native App or Hybrid App: React Native
3. OS Version: macOS 10.14.4
4. Device: MacBook Pro
5. Steps to reproduce: React native Android project with many third party dependencies will not build after upgrading to Salesforce SDK v. 7.0.  It seem that if my project will not build with Android SDK 28 (and AndroidX libraries), that I cannot upgrade my Android app to 7.0 yet.  I mostly just want to verify that this is true. 
6. Actual behavior: Various build errors related to unavailable support libraries, class path issues, etc.
7. Expected Behavior: 
8. Error Log:
As you can see, our app has a lot of dependencies, some of which don't support Android SDK 28 yet.

![Screen Shot 2019-04-11 at 10 16 05 AM](https://user-images.githubusercontent.com/49171610/55969351-3dbef600-5c43-11e9-8159-da8a317143b3.png)

Should we wait for these libraries to support Android 28 before upgrading to Salesforce SDK 7.0 for Android?

**Comment by bhariharan** [comment]
@bryonCatalyst The problem is not `API 28`, it's because some of the libraries you use don't support `AndroidX` yet. You need to file issues with those libraries to add `AndroidX` support.
