### ISSUE TITLE
 java.lang.SecurityException: Permission Denial: starting Intent

### ISSUE THREAD

**Issue by Ranjit7373** [forcedotcom/SalesforceMobileSDK-Android#1893]
1. Version of Mobile SDK Used: 7.0.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 8.1
4. Device: Redmi Note 5 pro
5. Steps to reproduce: Install Two Android apps which have salesforce SDK Integrated
6. Actual behavior: First Install Android App Works fine but second app shows blank screen
7. Expected Behavior: Both app should work properly
8. Error Log: 

I am developing two native android applications with Salesforce SDK.
when single  app is installed they work properly as i expected but when i install both app then first app is work properly but second app gives me following exception.  

com.example.appOne W/Binder: Caught a RuntimeException from the binder stub implementation.
    java.lang.SecurityException: Permission Denial: starting Intent { flg=0x20000000 pkg=com.example.appTwo cmp=com.example.appTwo/com.salesforce.androidsdk.ui.LoginActivity (has extras) } from ProcessRecord{4293c6 28457:com.example.appOne /u0a544} (pid=28457, uid=10544) not exported from uid 10541  

Can any one help me for working two apps properly on same device or suggest any solution if i am doing any mistake.

**Comment by bhariharan** [comment]
```
com.example.appOne W/Binder: Caught a RuntimeException from the binder stub implementation.
java.lang.SecurityException: Permission Denial: starting Intent { flg=0x20000000 pkg=com.example.appTwo cmp=com.example.appTwo/com.salesforce.androidsdk.ui.LoginActivity (has extras) } from ProcessRecord{4293c6 28457:com.example.appOne /u0a544} (pid=28457, uid=10544) not exported from uid 10541
```
This basically sums up the issue. You're attempting to launch the login screen of `appOne` from `appTwo`. On generated apps, you need to change the `account_type` and package names to be unique to avoid this issue (I suspect they're clashing at the moment). For example, running multiple sample apps that we provide simultaneously will not cause problems.

**Comment by Ranjit7373** [comment]
Thanks @bhariharan, it works for me i just change the account_type and it works.

**Comment by nglauber** [comment]
Just adding a comment for future references: the `account_type` should be declared in `strings.xml`
```
<string name="account_type">com.mycompany.myapp</string>
```
https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_android.meta/service_sdk_android/android_authentication_mobilesdk.htm
