### ISSUE TITLE
Account is being logged in Account Settings in user's device (Android) 

### ISSUE THREAD

**Issue by johndcclm** [forcedotcom/SalesforceMobileSDK-Android#1899]
We have an application does not directly interact with the Android framework AccountManager in any way.

The application authenticates with Salesforce by extending the provided OAuthWebviewHelper class. This class ends up calling the Salesforce SDK's ClientManager which calls AccountManager.addAccountExplicitly. This results in account details showing up in device system settings.

Is there is a way to avoid the app from accessing AccountManager.addAccountExplicitly which causes the issue.
![android](https://user-images.githubusercontent.com/50223417/57421062-e1002c80-723c-11e9-8498-3c5345ef41e2.png)

**Comment by bhariharan** [comment]
@johndcclm There is no way to avoid this. The `Mobile SDK` uses Android's `AccountManager` to store account data, per their recommendation. So, this is by design.
