### ISSUE TITLE
*.visualforce.com and *.documentforce.com Need to be Whitelisted

### ISSUE THREAD

**Issue by homerlex** [forcedotcom/SalesforceMobileSDK-Android#1910]
We ran into the same issue mentioned in #1758 .

I had to add the following to the config.xml:
```
    <allow-navigation href="https://*.documentforce.com" />
    <allow-navigation href="https://*.visualforce.com" />
```

These are domains we're being redirected through during the login process.  I don't know why you wouldn't update the source to include these.

**Comment by bbirman** [comment]
This should be resolved with #1926 and forcedotcom/SalesforceMobileSDK-CordovaPlugin#460
