### ISSUE TITLE
Hybrid Remote: First login doesn't work properly (for some orgs)

### ISSUE THREAD

**Issue by homerlex** [forcedotcom/SalesforceMobileSDK-Android#1921]
Please fill out the following details:

1. Version of Mobile SDK Used:  7.0.0
2. Issue found in Native App or Hybrid App: Hybrid (remote)
3. OS Version:
4. Device:  Nexus 9 (7.1.1), Samsung Galaxy Tab 3 (8.0.0)
5. Steps to reproduce:
Created a hybrid_remote app with the following startPage: /home/home.jsp

Here is my bootconfig:
```
{
    "remoteAccessConsumerKey": "3MVG9Iu66FKeHhINkB1l7xt7kR8czFcCTUhgoA8Ol2Ltf1eYHOU4SqQRSEitYFDUpqRWcoQ2.dBv_a1Dyu5xa",
    "oauthRedirectURI": "testsfdc:///mobilesdk/detect/oauth/done",
    "oauthScopes": ["web", "api"],
    "isLocal": false,
    "startPage": "/home/home.jsp",
    "errorPage": "error.html",
    "shouldAuthenticate": true,
    "attemptOfflineLoad": false,
    "androidPushNotificationClientId": ""
}
```

6. Actual behavior:

Run the app on a tablet (can't repro in any emulators that I've tried).  After logging in the app "minimizes" (but is still running).  When pulling the app back into view the login activity appears.  Here is a video showing the behavior:
https://www.screencast.com/t/cf7NFuER9

If I kill the app and start it up again I can see that I was actually logged in:
https://www.screencast.com/t/Di3TYJDHXm

NOTE: I have not seen this happen when logging into all orgs.  I duplicated against a production org and scratch org.  I haven't been able to determine what the difference is in orgs that work and ones that do not.

8. Error Log:
After hitting the "Allow" button the following is what appears in the console:
```
D/ViewRootImpl@6cfe8f8[LoginActivity]: ViewPostIme pointer 0
D/ViewRootImpl@6cfe8f8[LoginActivity]: ViewPostIme pointer 1
D/InputMethodManager: HSIFW - flag : 0 Pid : 7246
D/InputMethodManager: HSIFW - flag : 0 Pid : 7246
I/zygote64: Background concurrent copying GC freed 35436(1796KB) AllocSpace objects, 6(128KB) LOS objects, 49% free, 3MB/6MB, paused 362us total 138.670ms
I/zygote64: Do partial code cache collection, code=503KB, data=309KB
            After code cache collection, code=503KB, data=309KB
            Increasing code cache capacity to 2MB
I/SfDroidGapActivity: authenticate callback triggered with actual client
D/ViewRootImpl@6cfe8f8[LoginActivity]: MSG_WINDOW_FOCUS_CHANGED 0
D/OpenGLRenderer: eglDestroySurface = 0x74fd3a03c0
D/ViewRootImpl@6cfe8f8[LoginActivity]: Relayout returned: old=[0,0][1536,2048] new=[0,0][1536,2048] result=0x5 surface={valid=false 0} changed=true
D/ViewRootImpl@6cfe8f8[LoginActivity]: Relayout returned: old=[0,0][1536,2048] new=[0,0][1536,2048] result=0x1 surface={valid=false 0} changed=false
D/ViewRootImpl@6cfe8f8[LoginActivity]: dispatchDetachedFromWindow
D/InputEventReceiver: channel 'a46f9b6 com.login.tester/com.salesforce.androidsdk.ui.LoginActivity (client)' ~ Disposing input event receiver.
                      channel 'a46f9b6 com.login.tester/com.salesforce.androidsdk.ui.LoginActivity (client)' ~NativeInputEventReceiver.
D/InputEventReceiver: channel 'a46f9b6 com.login.tester/com.salesforce.androidsdk.ui.LoginActivity (client)' ~NativeInputEventReceiver.
I/SfDroidGapActivity: setSidCookies called
I/SfDroidGapActivity: getAuthCredentials called
E/cr_WebContentsImpl: UserDataHost can't be found
```

If you are unable to duplicate please let me know how I can help you debug this.

**Comment by wmathurin** [comment]
In the first video, what if you let the app loads (it looks like you minimized the app while login was completing)?

**Comment by homerlex** [comment]
@wmathurin - The app "minimizes" itself after I hit the Allow button.  I have to manually bring it back up to see that its back to the login activity.

**Comment by wmathurin** [comment]
We have not seen the "app minimizing itself following login". How did you create your application.
Did you use [forcehybrid](https://www.npmjs.com/package/forcehybrid)?

**Comment by homerlex** [comment]
Yes, I just did a `forcehybrid create` with `hybrid_remote`.   Like I mentioned, I've seen the behavior logging in to some orgs but not others.  If you have suggestions for me to help you debug this I am happy to help.

**Comment by wmathurin** [comment]
Do you mind installing the latest forcehybrid (7.1.1) and trying it again?

**Comment by homerlex** [comment]
@wmathurin - I just upgraded to 7.1 and created a new app.  I got the same (bad) result.

Here is the console output after I hit the Allow button from my 7.1 app:
```
D/ViewRootImpl@6cfe8f8[LoginActivity]: ViewPostIme pointer 0
D/ViewRootImpl@6cfe8f8[LoginActivity]: ViewPostIme pointer 1
D/InputMethodManager: HSIFW - flag : 0 Pid : 24992
D/InputMethodManager: HSIFW - flag : 0 Pid : 24992
I/zygote64: Do full code cache collection, code=502KB, data=362KB
I/zygote64: After code cache collection, code=492KB, data=297KB
I/zygote64: Do partial code cache collection, code=492KB, data=300KB
I/zygote64: After code cache collection, code=492KB, data=300KB
    Increasing code cache capacity to 2MB
I/SfDroidGapActivity: authenticate callback triggered with actual client
V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@c41c8a7 nm : com.tester711 ic=null
I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
D/ViewRootImpl@6cfe8f8[LoginActivity]: MSG_WINDOW_FOCUS_CHANGED 0
D/OpenGLRenderer: eglDestroySurface = 0x74e66b3140
D/ViewRootImpl@6cfe8f8[LoginActivity]: dispatchDetachedFromWindow
D/InputEventReceiver: channel 'e3cbf1e com.tester711/com.salesforce.androidsdk.ui.LoginActivity (client)' ~ Disposing input event receiver.
    channel 'e3cbf1e com.tester711/com.salesforce.androidsdk.ui.LoginActivity (client)' ~NativeInputEventReceiver.
I/SfDroidGapActivity: setSidCookies called
I/SfDroidGapActivity: getAuthCredentials called
E/cr_WebContentsImpl: UserDataHost can't be found
    UserDataHost can't be found
E/cr_WebContentsImpl: UserDataHost can't be found
```

**Comment by homerlex** [comment]
@wmathurin - Do you want me to email you creds to my scratch org so you can try duplicating?

**Comment by brandonpage** [comment]
@homerlex Is this still an issue?

**Comment by homerlex** [comment]
@brandonpage - I'm not sure.  I won't have time to try reproducing the problem this week.  Maybe next week.

**Comment by mjmasn** [comment]
We're seeing this occasionally on some Android devices on SDK 8.3.0 (and have been for some time so not limited to this version I don't think). This is with a React Native app.

**Comment by wmathurin** [comment]
Old issue. Never got more details.
