### ISSUE TITLE
Application not working with SSO using SDK 7.1.0

### ISSUE THREAD

**Issue by Jas05** [forcedotcom/SalesforceMobileSDK-Android#1934]
Please fill out the following details:

1. Version of Mobile SDK Used: 
Salesforce Mobile SDK 7.1.0

2. Issue found in Native App or Hybrid App:
Hybrid App

3. OS Version:
Android 8.0, 9.0

4. Device:
Samsung S8, S9, S10

5. Steps to reproduce:
-> on Login page 
-> click on the menu at top right hand side
 -> Change server
-> Add connection 
-> Enter the name and url of your server -> Apply
-> The app will show your SSO login page.
-> Enter the credentials
-> Create and Verify passcode
-> App loads start page
 
6. Actual behavior:
The app is showing black and white screens. App gets into a loop of continually loading a web page

The app should show you the start page of your Org  but instead the app is showing black and white screens (of it trying to load a webpage and then restarting to load the web page).

Looking at the logs in Android studio it looks like the app is going into a loop and not able to come out.

7. Expected Behavior:
The App should show the start page for your Org.

8. Error Log:
D/CordovaWebViewImpl: onPageDidNavigate(https://{mydomain}.content.force.com/secur/contentDoor?startURL="")
D/CordovaWebViewImpl: onPageFinished(https://{mydomain}.content.force.com/secur/contentDoor?startURL="")
I/SfDroidGapActivity: refresh called
I/SfDroidGapActivity: refresh callback - refresh succeeded
I/SfDroidGapActivity: setSidCookies called
W/System: A resource failed to call end. 
D/CordovaWebViewImpl: >>> loadUrl(https://{mydomain}/secur/frontdoor.jsp?&sid=)
D/PluginManager: init()
D/FileUtils: Unrecognized extra filesystem identifier: assets
D/ViewRootImpl@53207be[SalesforceDroidGapActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 490327576576} changed=false

D/CordovaWebViewImpl: onPageDidNavigate(https://{mydomain}.content.force.com/secur/contentDoor?startURL=""
D/CordovaWebViewImpl: onPageFinished(https://{mydomain}.content.force.com/secur/contentDoor?startURL=""
I/SfDroidGapActivity: refresh called
I/SfDroidGapActivity: refresh callback - refresh succeeded
I/SfDroidGapActivity: setSidCookies called
D/CordovaWebViewImpl: >>> loadUrl(https://{mydomain}/secur/frontdoor.jsp?&sid=)
D/PluginManager: init()
D/FileUtils: Unrecognized extra filesystem identifier: assets
I/Choreographer: Skipped 44 frames!  The application may be doing too much work on its main thread.
D/ViewRootImpl@53207be[SalesforceDroidGapActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 490327576576} changed=false
I/OpenGLRenderer: Davey! duration=816ms; Flags=1, IntendedVsync=44681434204845, Vsync=44682167538149, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=44682171506309, AnimationStart=44682171655617, PerformTraversalsStart=44682193511771, DrawStart=44682243091348, SyncQueued=44682245674501, SyncStart=44682245807617, IssueDrawCommandsStart=44682245982155, SwapBuffers=44682247965771, FrameCompleted=44682250897732, DequeueBufferDuration=628000, QueueBufferDuration=902000, 

D/CordovaWebViewImpl: onPageDidNavigate(https://{mydomain}.content.force.com/secur/contentDoor?startURL="")
D/CordovaWebViewImpl: onPageFinished(https://{mydomain}.content.force.com/secur/contentDoor?startURL=)
I/SfDroidGapActivity: refresh called
I/SfDroidGapActivity: refresh callback - refresh succeeded
I/SfDroidGapActivity: setSidCookies called
D/CordovaWebViewImpl: >>> loadUrl(https://{mydomain}/secur/frontdoor.jsp?&sid=)
D/PluginManager: init()
D/FileUtils: Unrecognized extra filesystem identifier: assets
D/ViewRootImpl@53207be[SalesforceDroidGapActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 490327576576} changed=false

(startUrl removed but did contain the correct start page URL)

**Comment by wmathurin** [comment]
Thank you we will investigate.

**Comment by alsocalledchris** [comment]
@wmathurin do we have an update on this? Thanks

**Comment by wmathurin** [comment]
We can't repro (in 7.3). Please re-open if you still have the issue.
