### ISSUE TITLE
Chat UI End Session Alert Dialog not following app theme color

### ISSUE THREAD

**Issue by Maxwell6635** [forcedotcom/SalesforceMobileSDK-Android#1946]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.1.2 , ChatUI 3.5.0
2. Issue found in Native App or Hybrid App: End Chat Session Alert Dialog Color is not following App Theme Color.
3. OS Version: Android 7 (Nougat)
4. Device: Huawei P9 Plus

5. Steps to reproduce: Start A Live Agent Chat, minimise ] the live chat session and press cross button it will prompt end session alert dialog and the button background for cancel and ok button is white color

6. Actual behavior:  alert dialog and the button background for cancel and ok button is white color 
![Screenshot_20190711-102534](https://user-images.githubusercontent.com/12591474/61018716-59fd3b00-a3ca-11e9-8ab1-5dbade5e248b.png)

7. Expected Behavior: alert dialog and the button background for cancel and ok button should follow our app theme color
![Screenshot_20190711-104452](https://user-images.githubusercontent.com/12591474/61018720-5d90c200-a3ca-11e9-96f7-c87efa962f48.png)

8. Error [Log:]

**Comment by brandonpage** [comment]
Hi @Maxwell6635, this looks like an Embedded Service issue.  Please post your issue [here](https://github.com/forcedotcom/ServiceSDK-android) where the correct team will see it.  

Thanks!

**Comment by sinnavj** [comment]
@Maxwell6635 Did you able to resolve this?
