### ISSUE TITLE
Login back issue - Unable to close login Activity

### ISSUE THREAD

**Issue by tarunpatel004** [forcedotcom/SalesforceMobileSDK-Android#1956]
Please fill out the following details:

1. Version of Mobile SDK Used: v7.1.2 
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: All
4. Device: All
5. Steps to reproduce: I have created one Activity and extended SalesforceActivity it will jump to the login screen of the SDK. when i press back button and try to finish SDK's login activity it's not closing activity.
6. Actual behavior: Back button of hardware does nothing, when i override onDestroy and try to kill LoginActivity then it again start activity.
7. Expected Behavior: it should allow me to go back if i don't want to login then 
8. Error Log:

---------Code------------
1. public class MainAtivity extends SalesforceActivity  [I have override **SalesForceActivity**]
2. In com.salesforce.androidsdk.ui.LoginActivity I have changed code like below: 

@Override
	public boolean onKeyDown(int keyCode, KeyEvent event) {

		// This allows sub classes to override the behavior by returning false.
		if (fixBackButtonBehavior(keyCode)) {
			return true;
		}
		return super.onKeyDown(keyCode, event);
	}

	protected boolean fixBackButtonBehavior(int keyCode) {
		if (keyCode == KeyEvent.KEYCODE_BACK) {

            finish();
            return true;
		}
		return false;
	}

This was working in earlier version of SDK's. Please help. 
Thanks

**Comment by brandonpage** [comment]
Hi @tarunpatel004,

This behavior is by design.  The default behavior for the SDK is that login is required for the app to function, as this is true for the vast majority of our customers.  If login is optional for your application then a little setup is required to defer login.  Please see the documentation here: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/android_native_deferred_login.htm

If you have issues after implementing deferred login please let me know.

**Comment by tarunpatel004** [comment]
Hi @brandonpage , 

I have reviewed the document that you have provided but that is for to create a screen before the authentication flow right? 

_But now assume that i have two screen in app:_ 
**Screen A** -> Before authentication
**Screen B** -> Login, which extends SalesforceActivity. 
I jump from A to B and now i want to go back to the Screen A then? 

Can you help me on this. because i have tried to kill the activity but it again and again resume Login activity. 

Thanks!
