### ISSUE TITLE
app crashes after authentication

### ISSUE THREAD

**Issue by riquier** [forcedotcom/SalesforceMobileSDK-Android#1958]
Our React Native Android app crashes since upgrading to 7.2.0 with a null pointer exception (as below). We have resolved the problem temporarily by reverting the following commits locally:
- https://github.com/forcedotcom/SalesforceMobileSDK-Android/commit/088c3590d52736fdf20e1a49c4d4dac3fc37cd38#diff-4857125ec18fbaef2a971a21e7b3e0fa
- https://github.com/forcedotcom/SalesforceMobileSDK-Android/commit/931a33ad014db6f7af5c2816e79387765d3dd015#diff-4857125ec18fbaef2a971a21e7b3e0fa
- https://github.com/forcedotcom/SalesforceMobileSDK-Android/commit/f5e0c8507ceed232fb3a307b89265448e5926054#diff-4857125ec18fbaef2a971a21e7b3e0fa

1. Version of Mobile SDK Used: **7.2.0**
2. Issue found in **React Native App**
3. OS Version: **Android**
4. Device: **Various**
5. Steps to reproduce: 
-- Open app, redirects to the Salesforce login screen
-- Complete login flow (password, 2FA etc)
6. Actual behavior: upon redirecting back to our app the app crashes with a null pointer exception and does not retain the login or open the app.
7. Expected Behavior: The app opens with authentication as provided.
8. Error Log: There was a null pointer exception at `SalesforceSDK/src/com/salesforce/androidsdk/secruity/SalesforceKeyGenerator.java` at line 103: `CACHED_ENCRYPTION_KEYS.put(name, encryptionKey);`

**Comment by bhariharan** [comment]
Thanks for reporting, @riquier. I'll take a look. Could you please post the full stack trace of the crash?

**Comment by bhariharan** [comment]
@riquier [This PR](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1962) should fix it. It'll be in our next release, `Mobile SDK 7.3`.

**Comment by riquier** [comment]
Thanks @bhariharan
