### ISSUE TITLE
Uncaught "No value for Id" error when syncing up a newly created Contact

### ISSUE THREAD

**Issue by Aequitas737** [forcedotcom/SalesforceMobileSDK-Android#1974]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.2
2. Issue found in Native App or Hybrid App: Hybrid
3. OS Version: 8, 5, 7, 9
4. Device: S6, Galaxy Tab A, Galaxy Tab (2016)
5. Steps to reproduce:
Create a new contact with lastname set to anything and ensuring local and locally created flags are set to true. Use `syncUp` to sync up to Salesforce.
6. Actual behavior:
Since it's a new Contact you shouldn't need to provide an Id but an error gets thrown saying 'No value for Id'. If you add an Id, such as 'asdf' then it seems to work correctly.
7. Expected Behavior:
Shouldn't need to assign a temporary Id to create a contact.
8. Error Log:
```
08-29 10:54:52.387 31935 32119 E SyncTask: org.json.JSONException: No value for Id
08-29 10:54:52.387 31935 32119 E SyncTask:     at org.json.JSONObject.get(JSONObject.java:389)
08-29 10:54:52.387 31935 32119 E SyncTask:     at org.json.JSONObject.getString(JSONObject.java:550)
08-29 10:54:52.387 31935 32119 E SyncTask:     at com.salesforce.androidsdk.smartsync.target.BatchSyncUpTarget.syncUpRecords(BatchSyncUpTarget.java:118)
08-29 10:54:52.387 31935 32119 E SyncTask:     at com.salesforce.androidsdk.smartsync.manager.AdvancedSyncUpTask.syncUp(AdvancedSyncUpTask.java:73)
08-29 10:54:52.387 31935 32119 E SyncTask:     at com.salesforce.androidsdk.smartsync.manager.SyncUpTask.runSync(SyncUpTask.java:60)
08-29 10:54:52.387 31935 32119 E SyncTask:     at com.salesforce.androidsdk.smartsync.manager.SyncTask.run(SyncTask.java:80)
08-29 10:54:52.387 31935 32119 E SyncTask:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-29 10:54:52.387 31935 32119 E SyncTask:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-29 10:54:52.387 31935 32119 E SyncTask:     at java.lang.Thread.run(Thread.java:762)
```

It seems that this is caused by the change to default to `androidImpl: "com.salesforce.androidsdk.smartsync.target.BatchSyncUpTarget"` if you set `androidImpl` to: `androidImpl: "com.salesforce.androidsdk.smartsync.target.SyncUpTarget"` then there is also no issue.

The issue seems to stem from: https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SmartSync/src/com/salesforce/androidsdk/smartsync/target/BatchSyncUpTarget.java

In method: `syncUpRecords`:

```
    JSONObject record = records.get(i);
    String id = record.getString(getIdFieldName());

    if (id == null) {
```

It seems that it's expected that getString would return null if the `Id` field didn't exist, but it actually throws an exception instead: (https://developer.android.com/reference/org/json/JSONObject.html#getString(java.lang.String))

**Comment by wmathurin** [comment]
Good catch.
Fixed with https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1975
