### ISSUE TITLE
Query - Push Silent Notifications

### ISSUE THREAD

**Issue by geekandt** [forcedotcom/SalesforceMobileSDK-Android#1976]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.2
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: Android 7 up
4. Device: All Devices

Hi Team, 
Our devs need to know:
1. Does the SF SDK push silent notifications to the app and under what conditions, when does this happen? 
2. And additionally can it be removed?

**Comment by wmathurin** [comment]
Yes they are. Just build a notification with the right payload.
It should be something like
```
{
    "aps" = {
        "content-available" : 1,
        "sound" : ""
    };
    // You can add custom key-value pair here...
}
```
For more on
