### ISSUE TITLE
Query: Salesforce SDK need notifications to work?

### ISSUE THREAD

**Issue by geekandt** [forcedotcom/SalesforceMobileSDK-Android#1986]
Please fill out the following details:

Version of Mobile SDK Used: 7.2
Issue found in Native App or Hybrid App: Hybrid App
OS Version: Android 7 up
Device: All Devices
Hi Team,
Our devs need to know:

1. Does Salesforce SDK need notifications to work or is it not compulsory?
2. If it is compulsory, then in what way is it used?

**Comment by bhariharan** [comment]
@geekandt Push notifications are not required by the framework. Push notification registration only occurs if the developer has configured a valid PN ID in `bootconfig`. This forum is reserved for bugs/issues with our code. Please post general queries on `Salesforce Stack Exchange` instead.

**Comment by geekandt** [comment]
@bhariharan thank you. Noted. we'll post general queries on Salesforce Stack Exchange. Thanks
