### ISSUE TITLE
Upgrading van v6.2 to 7.2. If older version has passcode, after upgrade mobile policy is not cleared

### ISSUE THREAD

**Issue by lchnnl** [forcedotcom/SalesforceMobileSDK-Android#1987]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.2
2. Issue found in Native App or Hybrid App: Native and Hybrid
3. OS Version: All
4. Device: All
5. Steps to reproduce:
- Install SDK v6.2. Enable passcode. And register a new passcode.
- Close the app. Do **not** remove the app
- Install the upgraded app v 7.2.
- During installation older version of the app will be overwritten
- Start the upgraded app
- App will redirect to the screen to enter the passcode
In the passcode screen I can not go back / forth and no way to login the app again.

6. Actual behavior:
- the old passcode (registered with sdk v6.2) is not recognized.
- Some elements on the layout is also not rendered correctly (passcodefield.java)
- Verify button is not shown
The current screen does not show anything. No button to go back or to log out.
Closing the app does not work
Only way to fix this issue is to uninstall the complete app and reinstall upgraded version 7.2
Afterwards app behaves correctly. 

7. Expected Behavior:
The passcode that was entered with v6.2 can be reused in v7.2. Or logout the user to force the user to recreate the password / mobile policy.
Either way there should be a flow the user can follow to log into the upgrade app again, without uninstall and reinstalling again.

8. Error Log:
In Passcodemanager.java I fixed
// this parameter was not set yet.
line 264: passcodeLengthKnown = true;
// default should be true and not false
Line 276: passcodeLengthKnown = sp.getBoolean(KEY_PASSCODE_LENGTH_KNOWN, true);

**Comment by brandonpage** [comment]
Hi @lchnnl, I just double checked going from 6.2 to 7.2 and 7.3 and in both causes I could not reproduce the error.   Can you provide any additional details about this?  Have you customized the passcode screen in the past? 

I see this:
![](https://user-images.githubusercontent.com/28540387/66218027-35d59100-e67d-11e9-9c7c-543e4ad827f4.png)

**Comment by brandonpage** [comment]
Also setting ` passcodeLengthKnown = true;` by default is a very bad idea.  That variable is there so that we we get the one time UX shown in my previous comment, the goal of which is to attain the length of the passcode.   If you default it to true and the users's passcode is longer than the minimum length the user will not be able to unlock the device.

**Comment by lchnnl** [comment]
Hi Brandon... Thank you for coming back to me. Much appreciated!

That is strange... The screen I see is the following:
![image](https://user-images.githubusercontent.com/3322365/66233011-95b65100-e6ea-11e9-8c18-4524877623ab.png)
In my case the verifyButton does not appear. 

As for my analysis...
in v6.2. I start the app, and create a new passcode. I will eventually reach the storeMobilePolicy method. This method only stores 2 values:
    private void storeMobilePolicy(Context context) {

        // Context will be null only in test runs.
        if (context != null) {
            final SharedPreferences sp = context.getSharedPreferences(MOBILE_POLICY_PREF,
            		Context.MODE_PRIVATE);
            Editor e = sp.edit();
            e.putInt(KEY_TIMEOUT, timeoutMs);
            e.putInt(KEY_PASSCODE_LENGTH, minPasscodeLength);
            e.commit();
        }
    }

I close the app (do not remove). So the mobile policy remain on the device.
Then I install an app of v7.2. When starting the app itself, I will eventually reach PasscodeActivity.java, around line 180 I reach the following part of the code:

if (passcodeManager.isPasscodeChangeRequired()) {
            setMode(PasscodeMode.Change);
        } else {
            **if (passcodeManager.hasStoredPasscode(this)) {
                PasscodeMode mode = passcodeManager.biometricEnabled() ? PasscodeMode.BiometricCheck : PasscodeMode.Check;
                setMode(mode);**
            } else {
                setMode(PasscodeMode.Create);
            }
        }

Since the mobile policy is not reset, I will eventually reach the code 'passcodeManager.hasStoredPasscode(this)' this will evaluate to true. Biometric was not Enabled, variable 'mode' will be set to 'PasscodeMode.Check'. Eventually I will jump into the setMode method. I dont think the mobilePolicy is updated in the meantime or whatsoever.

Within the setMode, I reach the following part of the code for rendering the layout.
case Check:
            title.setText(getString(R.string.sf__passcode_enter_title));
            title.setVisibility(View.VISIBLE);
            instr.setText(getString(R.string.sf__passcode_enter_instructions));
            instr.setVisibility(View.VISIBLE);
            passcodeBox.setVisibility(View.VISIBLE);
            passcodeField.setVisibility(View.VISIBLE);

            **if (passcodeManager.getPasscodeLengthKnown()) {
                verifyButton.setVisibility(View.VISIBLE);
            }**
            showKeyboard();
            sendAccessibilityEvent(instr.getText().toString());
            break;

At this point the instance of passcodeManager is still the same, and the property passcodeLengthKnown was not updated and is still 'false'. So when the method 'passcodeManager.getPasscodeLengthKnown()' is called, it would evaluate to false, and hence the verifyButton is not visible at my end.

I hope my explanation is not too cryptic. Thansk

**Comment by brandonpage** [comment]
Did you modify PasscodeActivity.java line 239?  

```
if (!passcodeManager.getPasscodeLengthKnown()) {
     verifyButton.setVisibility(View.VISIBLE);
}
```

[Source control shows the condition has always been *not* length known](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/8017d4d7e14ed37bd0af385a71c5df9bdbdf4de2/libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/PasscodeActivity.java#L239)

**Comment by lchnnl** [comment]
Brandon, you're absolutely right... Not sure how i could have overlooked that. Thank you for your support!

**Comment by brandonpage** [comment]
No problem.  So everything works as expected now?  You should only see the verify button once upon upgrade to 7.1+ and never on a new login from 7.1+.  

Otherwise you should see the new Passcode screen:
![Screen Shot 2019-10-04 at 1 16 20 PM](https://user-images.githubusercontent.com/28540387/66237279-8d89f180-e6a9-11e9-85f3-9f1984e8a305.png)

**Comment by lchnnl** [comment]
yes everything works as expected now. Thanks again for your support!
