### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by Aequitas737** [forcedotcom/SalesforceMobileSDK-Android#1988]
I've been trying to upgrade my app to 7.3 but I am encountering an issue I can't seem to get past.

1. Version of Mobile SDK Used: 7.3
2. Issue found in Native App or Hybrid App: react native
3. OS Version: Android 7.0
4. Device: Samsung Galaxy s6
5. Steps to reproduce: Open app
6. Actual behavior: App crashes; Android's "your app has stopped" modal with option to open again. Will crash every time. The Salesforce page does load behind the modal though, so the activities may be separate?
7. Expected Behavior: app opens without crashing, get the Salesforce login page and able to login to view the app.
8. Error Log:

```
ClientManager: No user account found
ClientManager: com.salesforce.androidsdk.rest.ClientManager$AccountInfoNotFoundException: No user account found
ClientManager: 	at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:155)
ClientManager: 	at com.salesforce.androidsdk.rest.ClientManager.peekRestClient(ClientManager.java:139)
ClientManager: 	at com.salesforce.androidsdk.reactnative.ui.SalesforceReactActivity.onResume(SalesforceReactActivity.java:104)
ClientManager: 	at com.salesforce.androidsdk.ui.SalesforceActivityDelegate.onResume(SalesforceActivityDelegate.java:103)
ClientManager: 	at com.salesforce.androidsdk.reactnative.ui.SalesforceReactActivity.onResume(SalesforceReactActivity.java:97)
ClientManager: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1277)
ClientManager: 	at android.app.Activity.performResume(Activity.java:7088)
ClientManager: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3768)
ClientManager: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3832)
ClientManager: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
ClientManager: 	at android.os.Handler.dispatchMessage(Handler.java:102)
ClientManager: 	at android.os.Looper.loop(Looper.java:154)
ClientManager: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
ClientManager: 	at java.lang.reflect.Method.invoke(Native Method)
ClientManager: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
ClientManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
SFReactActivity: onResumeNotLoggedIn - should authenticate/online - authenticating
SFReactActivity: login called
ClientManager: No account of type com.company.mobile.login found
```

I've ensured that  `<string name="account_type">com.company.mobile.login</string>` is in strings.xml and compared my project to the sample apps and the app created by `forcereact create` but can't find any potential issues.

Thanks in advance for your help.

**Comment by bhariharan** [comment]
@Aequitas737 The stack trace above simply indicates that login isn't complete, and hence there's no user account found. This will happen if a call is made to `peekRestClient()` or `getRestClient()` as an attempt to fetch an auth token before authentication. It shouldn't cause a crash by itself.

How did you generate the app? If you use `forcereact` to generate an app and run the generated app, does that work as expected?

**Comment by Aequitas737** [comment]
Thanks for the reply @bhariharan , I updated by using `forcereact create` and then manually moving the changes into the files of an existing project running the 7.2 sdk.

I've gotten it to work by using android studio to sync and build, previously I had just been using the command line.

Thanks for your help in resolving this.
