### ISSUE TITLE
Recommended way to vary the server.xml contents based on Android build variant 

### ISSUE THREAD

**Issue by bryonCatalyst** [forcedotcom/SalesforceMobileSDK-Android#1989]
Please fill out the following details:

Not really a bug, more of a question - I would like to be able to set the customer login url based on the build variant in Android Studio.  The current functionality appears to be driven by the value in server.xml, but I would like to avoid editing it if possible and have that value set based on the variant at build time.

1. Version of Mobile SDK Used: 7.3
2. Issue found in Native App or Hybrid App: React Native + Android
3. OS Version:  
4. Device:
5. Steps to reproduce: I would like to be able to have the SERVER_NAME and SERVER_URL be set at build time based on the build variant so that I don't have to manually edit the file when switching from QA to User Acceptance and to Production.
6. Actual behavior: Is this possible?
7. Expected Behavior: If it is not possible, can you give me some ideas on how best to modify the Android SDK code so that I can do this?
8. Error Log: Thank you!

**Comment by wmathurin** [comment]
Couldn't you use different server.xml for different [build variants](https://developer.android.com/studio/build#sourcesets)?

**Comment by bryonCatalyst** [comment]
That's what I was thinking, but the SDK is looking for the servers.xml in a specific directory, so how can I tell the sdk which server.xml file to use based on the variant we are building for?  Do you see what I mean?  

I appreciate any ideas you may have.

**Comment by bryonCatalyst** [comment]
I'll take a look at the link - thanks!

**Comment by bryonCatalyst** [comment]
I just finished configuring and testing for 4 different build variants - thanks for your help!
