### ISSUE TITLE
Application not working with SSO using SDK 7.3.0 and 8.1.0

### ISSUE THREAD

**Issue by Jas05** [forcedotcom/SalesforceMobileSDK-Android#1990]
Please fill out the following details:

1. Version of Mobile SDK Used: 
SalesforceMobile SDK 7.3.0

2. Issue found in Native App or Hybrid App:
Hybrid

3. OS Version:
Android 8.0, 9.0

4. Device:
Samsung S10, One Plus 7 Pro

5. Steps to reproduce:

-> on Login page
-> click on the menu at top right hand side
-> Change server
-> Add connection
-> Enter the name and url of your server -> Apply
-> The app will show your SSO login page.
-> Enter the credentials
-> Create and Verify passcode
-> App loads start page

6. Actual behavior:
The app is showing black and white screens. App gets into a loop of continually loading a web page

The app should show you the start page of your Org but instead the app is showing black and white screens (of it trying to load a webpage and then restarting to load the web page).

Looking at the logs in Android studio it looks like the app is going into a loop and not able to come out.

7. Expected Behavior:
The App should show the start page for your Org.

8. Error Log:
```
D/CordovaWebViewImpl: onPageDidNavigate(https://{mydomain}.content.force.com/secur/contentDoor?startURL="")
D/CordovaWebViewImpl: onPageFinished(https://{mydomain}.content.force.com/secur/contentDoor?startURL="")
I/SfDroidGapActivity: refresh called
I/SfDroidGapActivity: refresh callback - refresh succeeded
I/SfDroidGapActivity: setSidCookies called
W/System: A resource failed to call end.
D/CordovaWebViewImpl: >>> loadUrl(https://{mydomain}/secur/frontdoor.jsp?&sid=)
D/PluginManager: init()
D/FileUtils: Unrecognized extra filesystem identifier: assets
D/ViewRootImpl@53207be[SalesforceDroidGapActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 490327576576} changed=false

D/CordovaWebViewImpl: onPageDidNavigate(https://{mydomain}.content.force.com/secur/contentDoor?startURL=""
D/CordovaWebViewImpl: onPageFinished(https://{mydomain}.content.force.com/secur/contentDoor?startURL=""
I/SfDroidGapActivity: refresh called
I/SfDroidGapActivity: refresh callback - refresh succeeded
I/SfDroidGapActivity: setSidCookies called
D/CordovaWebViewImpl: >>> loadUrl(https://{mydomain}/secur/frontdoor.jsp?&sid=)
D/PluginManager: init()
D/FileUtils: Unrecognized extra filesystem identifier: assets
I/Choreographer: Skipped 44 frames! The application may be doing too much work on its main thread.
D/ViewRootImpl@53207be[SalesforceDroidGapActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 490327576576} changed=false
I/OpenGLRenderer: Davey! duration=816ms; Flags=1, IntendedVsync=44681434204845, Vsync=44682167538149, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=44682171506309, AnimationStart=44682171655617, PerformTraversalsStart=44682193511771, DrawStart=44682243091348, SyncQueued=44682245674501, SyncStart=44682245807617, IssueDrawCommandsStart=44682245982155, SwapBuffers=44682247965771, FrameCompleted=44682250897732, DequeueBufferDuration=628000, QueueBufferDuration=902000,

D/CordovaWebViewImpl: onPageDidNavigate(https://{mydomain}.content.force.com/secur/contentDoor?startURL="")
D/CordovaWebViewImpl: onPageFinished(https://{mydomain}.content.force.com/secur/contentDoor?startURL=)
I/SfDroidGapActivity: refresh called
I/SfDroidGapActivity: refresh callback - refresh succeeded
I/SfDroidGapActivity: setSidCookies called
D/CordovaWebViewImpl: >>> loadUrl(https://{mydomain}/secur/frontdoor.jsp?&sid=)
D/PluginManager: init()
D/FileUtils: Unrecognized extra filesystem identifier: assets
D/ViewRootImpl@53207be[SalesforceDroidGapActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 490327576576} changed=false
```
(startUrl removed but did contain the correct start page URL)

**Comment by bhariharan** [comment]
@Jas05 A few questions:
- Are you able to reproduce this issue with a freshly generated hybrid app using `forcehybrid`?
- Is this specific to the devices mentioned, or does it occur on an emulator as well?
- Are you able to reproduce this issue with any other credentials that you may have, i.e. a DE org or a CS org, for instance?

**Comment by Jas05** [comment]
Hello Bhariharan

- Yes this is happening on the newely create forcrhybrid as well, it works fine on mobileSDK android v6.2.0 and on mobileSDK iOS all versions.

- The same thing also happens on other android devices and emulators

- Tried this on multiple orgs same issue

**Comment by Jas05** [comment]
Hello @bhariharan  
Any update on this?
If needed I can DM you my Test org details.

**Comment by Jas05** [comment]
Hello @bhariharan, @wmathurin  
I tried this on Mobile SDK version 8.0.0, but the issue still exists.
This a show stopper for us, Can you please help?

**Comment by Jas05** [comment]
Hello @bhariharan @wmathurin any update on this?

**Comment by alsocalledchris** [comment]
@bhariharan  @wmathurin  any update on this - seems a pretty large bug? thanks

**Comment by bhariharan** [comment]
@Jas05 Have you tried a different org or looked into your SSO configuration? I suspect this has something to do with the SSO config in your org. The login flow is a black box to Mobile SDK - we simply load the login URL and wait for the login process to complete within the webview and trigger the callback URL, which we monitor. We have many apps deployed on various orgs with SSO/SAML enabled, and we haven't encountered issues elsewhere. I recommend evaluating your SSO configuration in your org and ensure that it works with a OAuth User Agent flow.

**Comment by Jas05** [comment]
@bhariharan thanks for your response, The 6.2.0 version works perfect with SSO but the version after that are crashing. I tried this on multiple orgs also on different SSO, I also created a new connected incase any thing got changed.
But i cant get SSO to work. I am happy to share the details of my trial org if you can have a look?

**Comment by Jas05** [comment]
@bhariharan  Hello bariharan just to furthur clarify steps:

- Open App, Menu -> Change Server, - > Add connection -> Enter the custom domain Url 
- Enter SSO username and password.
- User Successfully Authenticated - I can see the user session getting created in Salesforce org.
- Approve Connected App use 
- Set PIN 
- Set use Fingerprint 
- See loop of showing white and black screens with app trying to load our start URL but failing

We feel as the session is created successfully the SSO and connected app are working fine
