### ISSUE TITLE
JUnit is included in non-test builds.

### ISSUE THREAD

**Issue by jstefanowski** [forcedotcom/SalesforceMobileSDK-Android#2014]
SalesforceSDK has JUnit added to every type of build but it should be included only in the test builds.

https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/8017d4d7e14ed37bd0af385a71c5df9bdbdf4de2/libs/SalesforceSDK/build.gradle#L22

**Comment by bhariharan** [comment]
It is required by the library for [this helper class](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceSDK/src/com/salesforce/androidsdk/util/test/JSONTestHelper.java#L32).
