### ISSUE TITLE
App never logout on revoked refresh token

### ISSUE THREAD

**Issue by jaygauten** [forcedotcom/SalesforceMobileSDK-Android#2016]
1. Version of Mobile SDK Used: **7.3.0**
2. Issue found in Native App or Hybrid App: **Hybrid App**
3. OS Version: 9.0
4. Device: **Samsung Galaxy S10**
5. Steps to reproduce:
     **5.1. Login to the app
     5.2. Revoke token from the org via Users > oauth connected apps
     5.3. try to fetch any data ie. SObjects**
6. Actual behavior: **the app just returns error message "Could not refresh token" and never goes to the login screen**
7. Expected Behavior: **expected the app to logout and display login screen**
8. Error Log: no error log reported

additional Info:
when debugging, the native code reaches `SalesforceSDKManager.getInstance().logout(null, false);` ClientManager.java:551 but it never displays the login screen even if i set the `showLoginPage` to true

**Comment by frankvlocity** [comment]
The current behavior of this problem is even after oauth token expired. The user will still navigate around the app but always show an error popup. The user is supposed to be logout from the app. So please help.

**Comment by brandonpage** [comment]
Thank you for reporting this.  We will fix it asap.

**Comment by brandonpage** [comment]
The default behavior for the Android SDK has always been to not assume we know the context or state of the app.  The app could only be not reliant on Salesforce authentication to function or you may not want to show the login screen if another user is still logged in.  The default action is to do nothing, however you can easily achieve the behavior you desire by adding the following code to whatever class extends `SalesforceActivity`:

```
@Override
public void onLogoutComplete() {
	if (!isChild()) {
		recreate();
	}
}
```

More context for the behavior can be found here: https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1461
