### ISSUE TITLE
java.util.UnknownFormatConversionException: Conversion: l

### ISSUE THREAD

**Issue by ruiluo18** [forcedotcom/SalesforceMobileSDK-Android#2017]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.3
2. Issue found in Native App or Hybrid App: React Native
3. OS Version: Android 6.0, API level 23
4. Device: Android emulator
5. Steps to reproduce: 
  Use forcereact 7.3 to create a new React Native project
  Add smart store, create a record into the soup
  adb logcat *:W
  Run the app in emulator and sync up with the created record
  Observe the exception: java.util.UnknownFormatConversionException: Conversion: l
6. Actual behavior:
7. Expected Behavior:
  The newly created record should sync up without error
8. Error Log:
E SyncTask: Exception thrown running sync
E SyncTask: java.util.UnknownFormatConversionException: Conversion: l
E SyncTask:      at java.util.Formatter$FormatToken.unknownFormatConversionException(Formatter.java:1399)
E SyncTask:      at java.util.Formatter$FormatToken.checkFlags(Formatter.java:1336)
E SyncTask:      at java.util.Formatter.transform(Formatter.java:1442)
E SyncTask:      at java.util.Formatter.doFormat(Formatter.java:1081)
E SyncTask:      at java.util.Formatter.format(Formatter.java:1042)
E SyncTask:      at java.util.Formatter.format(Formatter.java:1011)
E SyncTask:      at java.lang.String.format(String.java:1554)
E SyncTask:      at java.lang.String.format(String.java:1528)
E SyncTask:      at com.salesforce.androidsdk.smartsync.target.BatchSyncUpTarget.syncUpRecords(BatchSyncUpTarget.java:123)
E SyncTask:      at com.salesforce.androidsdk.smartsync.manager.AdvancedSyncUpTask.syncUp(AdvancedSyncUpTask.java:73)
E SyncTask:      at com.salesforce.androidsdk.smartsync.manager.SyncUpTask.runSync(SyncUpTask.java:60)

The issue seems laying at BatchSyncUpTarget.java:123:
// create local id - needed for refId
id = String.format("local_%ld", record.getLong(SmartStore.SOUP_ENTRY_ID));

A few internet searches seems suggest the %ld should be %d.

**Comment by wmathurin** [comment]
This is fixed in dev (see https://github.com/forcedotcom/SalesforceMobileSDK-Android/commit/6bfed0d8dcfbcacb7851dd05f54a8d32ab0fec6a). It will be in our upcoming release (Mobile SDK 8.0) scheduled for later this month.
