### ISSUE TITLE
Firebase Cloud Messaging authentication error

### ISSUE THREAD

**Issue by ayonsaha-metacube** [forcedotcom/SalesforceMobileSDK-Android#2021]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.3 and 8.0
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: 9+
4. Device: Samsung

Error from Salesforce Admin 
![Screen Shot 2019-12-26 at 5 49 51 PM](https://user-images.githubusercontent.com/59254069/71475912-7837e580-2808-11ea-8670-f397fdafcdfe.png)

steps are follow as - https://developer.salesforce.com/docs/atlas.en-us.pushImplGuide.meta/pushImplGuide/pns_client_app_hybrid.htm

**Comment by bhariharan** [comment]
@ayonsaha-metacube This forum is reserved for client side issues with `Mobile SDK`. Please open a case with Salesforce Support for backend issues such as yours.
