### ISSUE TITLE
Error: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception:

### ISSUE THREAD

**Issue by vamsiandroid** [forcedotcom/SalesforceMobileSDK-Android#2027]
Please fill out the following details:

1. Version of Mobile SDK Used: 222.1.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Windows 10
4. Device: 
5. Steps to reproduce: Added com.salesforce.service:servicesdk:222.1.0 dependency to app.gradle
6. Actual behavior: 
7. Expected Behavior: Build is failing 
8. Error Log:  AGPBI: {"kind":"error","text":"error: duplicate value for resource \u0027attr/strokeWidth\u0027 with config \u0027\u0027.","sources":[{"file":"C:\\Users\\vnelli\\.gradle\\caches\\transforms-1\\files-1.1\\appcompat-v7-28.0.0.aar\\83d66e1747a1e9630f2a5bb34a9e3166\\res\\values\\values.xml","position":{"startLine":1268,"startColumn":4,"startOffset":69028,"endColumn":68,"endOffset":69092}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource previously defined here.","sources":[{"file":"C:\\Users\\vnelli\\.gradle\\caches\\transforms-1\\files-1.1\\design-28.0.0.aar\\ed221836a17383ac53f17a44e577ff00\\res\\values\\values.xml","position":{"startLine":17,"startColumn":4,"startOffset":920,"endColumn":49,"endOffset":965}}],"original":"","tool":"AAPT"}
:app:mergeInfinitiDebugResources
Error: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: AAPT2 error: check logs for details
:app:mergeInfinitiDebugResources FAILED

FAILURE: Build failed with an exception.

**Comment by bhariharan** [comment]
This isn't the right forum for `ServiceSDK` issues. Please contact Salesforce support directly.
