### ISSUE TITLE
How to use custom ReactRootView  ?

### ISSUE THREAD

**Issue by jiwansvmx** [forcedotcom/SalesforceMobileSDK-Android#2031]
Is there a way to extend `SalesforceReactActivityDelegate` so that you can override `createRootView` from `ReactActivityDelegate` to provide a custom `ReactRootView` ? It's not possible right now because it has a package level private constructor. Can it be changed to either `protected` or `public` and do the same as well for `reactActivityDelegate` property of `SalesforceReactActivity`  so that you can do something like ?
```java
class MyActivityDelegate extends SalesforceReactActivityDelegate {
        ActivityDelegate(SalesforceReactActivity activity, String mainComponentName) {
            super(activity, mainComponentName);
        }

        @Override
        protected ReactRootView createRootView() {
            return new RNGestureHandlerEnabledRootView(this.getContext());
        }
    }

    @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
        reactActivityDelegate = new MyActivityDelegate(this, getMainComponentName());
        return reactActivityDelegate;
    }

```

It's useful since libraries like React-Native-Gesture-Handler, which is one of the popular libraries, in RN ecosystem need to be able to create their own `ReactRootView`.
https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html

Please fill out the following details:

1. Version of Mobile SDK Used: 8.0.0
2. Issue found in Native App or Hybrid App: React Native

**Comment by rsmilne** [comment]
@jiwansvmx were you able to resolve this in any way?  I am running into the same issue both for react-native-gesture-handler as for expo modules.
