### ISSUE TITLE
Cannot launch different action on launchCasePublisher

### ISSUE THREAD

**Issue by geekandt** [forcedotcom/SalesforceMobileSDK-Android#2042]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.2
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: Android 7 and up
4. Device: All Devices

We have a different scenario where we need to add pre-defined values to the fields in the action.
Thus, we need a different global action for the case.

However, we cannot add another action when launching the launchCasePublisher. 
Please be advise. Or do you have any sample implementation of using different actions in launchCasePublisher.

**Comment by wmathurin** [comment]
@geekandt This is not the right repository for SnapIns/ServiceSDK. This forum is reserved for issues with Mobile SDK.
