### ISSUE TITLE
App upgrade from 6.0 to 8.1 shows blank screen

### ISSUE THREAD

**Issue by Manjeetmetacube** [forcedotcom/SalesforceMobileSDK-Android#2053]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.1
2. Issue found in Native App or Hybrid App: hybrid App
3. OS Version:
4. Device: All android device
5. Steps to reproduce: App based on (6.0) upgrade to app on 8.1. App shows blank screen
6. Actual behavior: After app uprgade app shows blank screen
7. Expected Behavior: Should able to update properly and user should be able to access the app.
8. Error Log:

Hi ,

As in 6.0 the user can setup biometric(if available on device) but not required to setup passcode. But in 8.1 passcode is also required for biometric devices. So when a user upgrades 6.0 based app to new app which is on 8.1 and launch the app shows blank screen. 

My guess for issue is : 
As the user is authenticated and 8.1 looks for both passcode + biometric which fails and then it shows blank screen.

Is there any workaround for same ? Or some temporary fix which we can put ?

**Comment by bhariharan** [comment]
It looks like you may be missing upgrade steps by skipping a whole major version release, i.e. `7.x`. You'll need to build those upgrade steps in to your app or jump one major version at a time. The other workaround is to force-logout the application on upgrade and start with a clean slate.
