### ISSUE TITLE
SalesforceActivity should extend AppCompatActivity rather than Activity

### ISSUE THREAD

**Issue by jstubing** [forcedotcom/SalesforceMobileSDK-Android#2063]
SalesforceActivity currently extends Activity rather than AppCompatActivity. This limits backwards compatibility and crashes the app when using the navigation component. Solution is to have SalesforceActivity extend AppCompatActivity instead of Activity.

1. Version of Mobile SDK Used: 8.1.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Android 10
4. Device: OnePlus 7 Pro
5. Steps to reproduce:
    Start a new project which includes the navigation component library. Add a NavHostFragment to MainActivity's layout file:

    `<fragment
        android:id="@+id/nav_host_fragment"
        android:name="androidx.navigation.fragment.NavHostFragment"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:defaultNavHost="true"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:navGraph="@navigation/nav_graph" />`

    Have MainActivity extend SalesforceActivity. Run the app.

6. Actual behavior: App crashes while inflating MainActivity's layout
7. Expected Behavior: MainActivity inflates its layout without crashing
8. Error Log:
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mycompany.myproject/com.mycompany.MainActivity}: android.view.InflateException: Binary XML file line #9 in com.mycompany.myproject:layout/activity_main: Binary XML file line #9 in com.mycompany.myproject:layout/activity_main: Error inflating class fragment
...
Caused by: android.app.Fragment$InstantiationException: Trying to instantiate a class androidx.navigation.fragment.NavHostFragment that is not a Fragment`

**Comment by bhariharan** [comment]
@jstubing This is by design because we don't want to depend on `AppCompat` from the SDK. You can easily replicate what's in `SalesforceActivity` by creating your own subclass of `AppCompatActivity`. `SalesforceActivity` is a convenience class for those apps that want to use `Activity` directly.

**Comment by zeeshanaslam78** [comment]
I wonder who uses `Activity` directly in 2021. Please give us the idea about those who uses it. 
Thanks!
