### ISSUE TITLE
Is there a native (non-WebView) based sign in for Android?

### ISSUE THREAD

**Issue by jstubing** [forcedotcom/SalesforceMobileSDK-Android#2064]
Just a question, not an issue.

Is there a way to implement sign in without using the WebView based approach from the SDK? I was thinking something more native such as creating a form with native Android views and widgets, then forwarding the username/password to a REST API. Does the SDK provide any support for something like that?

Thanks!

**Comment by bhariharan** [comment]
Not at this time. For security reasons, the Salesforce platform does not support sending back a refresh token without using a webview for authentication.

**Comment by zeeshanaslam78** [comment]
Salesforce is also not sending back a refresh token using webview for authentication in Android. SDK library gives error.
