### ISSUE TITLE
Chromium crash after login

### ISSUE THREAD

**Issue by jstubing** [forcedotcom/SalesforceMobileSDK-Android#2065]
1. Version of Mobile SDK Used: 8.1.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Android 10
4. Device: OnePlus 7 Pro and also Pixel 3A emulator
5. Steps to reproduce:
Login to an account with 2 factor authentication. Enter the auth code. At the last step of the login process, it will ask you to allow access. Click "Allow".
6. Actual behavior: App intermittently crashes at this point. Fairly rare reproduction rate (rough guess: every 1/10 logins)
7. Expected Behavior: App doesn't crash
8. Error Log:
No stack trace is present for the crash, just a single chromium line:
E/chromium: [ERROR:aw_browser_terminator.cc(125)] Renderer process (18474) crash detected (code -1)

**Comment by wmathurin** [comment]
This looks like a Chrome crash/bug. Have you searched Chromium forums for possible solutions?

**Comment by jstubing** [comment]
Closing this because I just managed to reproduce the crash without getting the chromium error. But still no stack trace. The app just disappears. I'll open another issue if/when I get more details.
