### ISSUE TITLE
Is it possible to hide the overflow menu on the login screen?

### ISSUE THREAD

**Issue by jstubing** [forcedotcom/SalesforceMobileSDK-Android#2067]
Not an issue, just a question.

Is it possible to hide the overflow menu at the upper right of the login screen? It seems like the iOS SDK has an option to hide this (via showSettingsIcon function) but I couldn't find anything similar in the Android SDK.

Thanks!

**Comment by bhariharan** [comment]
You should be able to override it through the XML layout file and a subclass of `LoginActivity` where you hide the gear icon.
