### ISSUE TITLE
UserId vs. FullUserId (iOS and Android parity)

### ISSUE THREAD

**Issue by luonglegs** [forcedotcom/SalesforceMobileSDK-Android#2071]
### Please fill out the following details:
On iOS's sdk, it seems like a user account has 2 properties related to `userId`. There's a `currentUser.userId` but there's also something like `currentUser.fullUserId`.

On Android's sdk, we only have `currentUser.userId` but it returns the `currentUser.fullUserId` value. Is there any way on android we can have the shortened `userId` value?

1. Version of Mobile SDK Used: 8.1.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 29
4. Device: Pixel 3 XL
5. Steps to reproduce: Access the currentUser's userId property
6. Actual behavior: currentUser.userId returns fullUserId, and there's no currentUser.fullUserId
7. Expected Behavior: currentUser.userId returns short user id, currentUser.fullUserId returns full user id
8. Error Log: N/A

**Comment by luonglegs** [comment]
Yes, exactly! I wasn't sure if there was a char limit difference on those id's. So those are predetermined to be 15 and 18 characters for `userId` and `fullUserId` respectively? If by design, we're supposed to be using the 18 char userId, then iOS might need an update?

We're put in an interesting position since iOS has been using the 15 char version of the `userId` for analytics, we have to adhere to this same pattern or it'd ruin our results. My issue with this is that there's only 1 id value coming from the Android SDK while the iOS SDK has 2.

I think if the userId's will always be predetermined lengths of 15 and 18 we can have a work around for now. However it'd be nice if the iOS and Android SDK had parity on this.

**Comment by luonglegs** [comment]
I'm sorry it seems I was a little bit misinformed about how iOS returns those values. I hope this might shed some more light on what I'm looking for.

### iOS
```
userAccount.accountIdentity.userId = 15 char
userAccount.idData.userId = 18 char
```

### Android
```
currentUser. ? = 15 char
currentUser.userId = 18 char
```

**Comment by bhariharan** [comment]
@luonglegs Thanks for bringing this to our attention. Would you mind closing this issue and creating an issue in our `iOS` repo linked to this? I agree with you - we should standardize on `18-char` on `iOS` as well. FYI @bbirman
