### ISSUE TITLE
Nullpointer for Live Chat UI

### ISSUE THREAD

**Issue by mrmichaelmoreau** [forcedotcom/SalesforceMobileSDK-Android#2076]
Hi All

I am reporting a crash that has occurred in our production application after implementing the Salesforce LiveChat UI. I have attached a screenshot of the Firebase Crashlytics stacktrace. Is this a known issue and when can a fix be expected if it also known. Thank you in advance.

1. Version of Mobile SDK Used: 
'com.salesforce.service:chat-ui:4.1.1'

2. Issue found in Native App or Hybrid App: 
Native

3. OS Version: 
Android 10

4. Device: 
Galaxy Note 9

5. Steps to reproduce:

6. Actual behavior:

7. Expected Behavior:

8. Error Log: See attached image

![stacktrace](https://user-images.githubusercontent.com/47559836/83957656-c83dcc80-a8bd-11ea-9e35-c390f5bae0c2.png)

**Comment by bhariharan** [comment]
`ServiceSDK` is a different product. This is not the right forum for posting issues with that SDK. Please open a case with `Salesforce` instead.

**Comment by mrmichaelmoreau** [comment]
Hi @bhariharan - do you have a link for me to direct me to the correct channel please?

**Comment by bhariharan** [comment]
@mrmichaelmoreau Nope - you need to reach out to your `Salesforce` rep directly.

**Comment by mrmichaelmoreau** [comment]
@bhariharan thank you.
