### ISSUE TITLE
App crashing in background

### ISSUE THREAD

**Issue by murilodag** [forcedotcom/SalesforceMobileSDK-Android#2077]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.1.0
2. Issue found in Native App or Hybrid App: native
3. OS Version: multiple (9, 10)
4. Device: multiple (galaxy note 10+, w30)
5. Steps to reproduce: Happens in the background
6. Actual behavior: App crash in background
7. Expected Behavior: App should not crash in background
8. Error Log: 

```
Caused by java.lang.RuntimeException
Applications need to call SalesforceSDKManager.init() first.
com.salesforce.androidsdk.app.SalesforceSDKManager.getInstance (SalesforceSDKManager.java:198)
com.salesforce.androidsdk.accounts.UserAccountManager.<init> (UserAccountManager.java:123)
com.salesforce.androidsdk.accounts.UserAccountManager.getInstance (UserAccountManager.java:114)
com.salesforce.androidsdk.analytics.AnalyticsPublisherService.handleActionPublish (AnalyticsPublisherService.java:72)
com.salesforce.androidsdk.analytics.AnalyticsPublisherService.onHandleWork (AnalyticsPublisherService.java:63)
androidx.core.app.JobIntentService$CommandProcessor.doInBackground (JobIntentService.java:392)
androidx.core.app.JobIntentService$CommandProcessor.doInBackground (JobIntentService.java:383)
android.os.AsyncTask$2.call (AsyncTask.java:333)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:764)

```
![image](https://user-images.githubusercontent.com/2996649/84059243-3e0e6a80-a988-11ea-8e02-efc7b2458722.png)

**Comment by bhariharan** [comment]
@murilodag Where are you calling `SalesforceSDKManager.initNative()` from in your app? It should be called from your `Application` class to prevent this from happening. Did you generate your app from one of our templates?

**Comment by murilodag** [comment]
Thanks @bhariharan , you are right. I moved and it should fix it.
