### ISSUE TITLE
Local hybrid app stuck at allow screen after login and initial rest taking a lot of time.

### ISSUE THREAD

**Issue by rahuljangid19** [forcedotcom/SalesforceMobileSDK-Android#2081]
Hi
We have a Salesforce mobile sdk based hybrid app using cordova. The app stuck at allow screen, it takes a lot of time to enter into app and after then initial rest are taking a lot time. After then the apps seems to work fine. We observed the issue in plain sdk app also.

1. Version of Mobile SDK Used: 8.1.0
2. Issue found in Native App or Hybrid App: Local Hybrid
3. OS Version: Android 9
4. Device: Samsung M30s
5. Steps to reproduce: 
6. Actual behavior: App gets stuck at allow screen and initial rest taking a lot of time.
7. Expected Behavior: App should not get stuck
8. Error Log:

**Comment by bhariharan** [comment]
@rahuljangid19 We don't control rendering of the content within the login webview. The time it takes to finish loading could depend on various factors including network connectivity speed, type of device you're running on, and backend login configuration (number of redirects, SSO/SAML, etc.). This forum is reserved for known issues/bugs with the client side library code.
