### ISSUE TITLE
error selecting from soup

### ISSUE THREAD

**Issue by riquier** [forcedotcom/SalesforceMobileSDK-Android#2082]
Please fill out the following details:

1. Version of Mobile SDK Used: 7.2
2. Issue found in Native App or Hybrid App: React Native
3. OS Version: Various
4. Device: Various
5. Steps to reproduce: Have not been able to reproduce locally yet, however we have 5K logs of this error happening to our customers in production since releasing our latest version. Error occurs after the app attempts to select from a table which has had a new soup column added.
6. Actual behavior: Error is thrown
7. Expected Behavior: It to return the values for the query
8. Error Log: `com.salesforce.androidsdk.smartstore.store.SmartSqlHelper$SmartSqlException: leave does not have an index on enrtcr__Status__c at character 63`

**Comment by bhariharan** [comment]
@riquier Have you tried upgrading to the latest version, `8.1.0`?

**Comment by wmathurin** [comment]
It looks like the soup is missing an index (like the error shows).
Are you registering your soups through a config file (https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/offline_config_files.htm) or through code?
Are you changing indices on existing soup after they were created (https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/offline_soup_change_index_specs.htm)?

**Comment by riquier** [comment]
Thanks for your response, turns out we where not updating the index after one of the devs added a new column to the soup, thanks for your responses 😄
