### ISSUE TITLE
Upload file crash 

### ISSUE THREAD

**Issue by tracybai7989** [forcedotcom/SalesforceMobileSDK-Android#2094]
Please fill out the following details:

1. Version of Mobile SDK Used: com.salesforce.service:chat-ui:3.5.0
2. Issue found in Native App or Hybrid App:Native App
3. OS Version: Android 10
4. Device: Galaxy Note9
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:

Caused by java.lang.IllegalArgumentException
Unexpected char 0x6708 at 38 in Content-Disposition value: form-data; name="file"; filename="14 7月 2020 18:58:28 -0500.png"
okhttp3.Headers.checkValue (Headers.java:272)
okhttp3.Headers.of (Headers.java:224)
com.salesforce.android.chat.core.internal.filetransfer.FileUploadRequestComposer.createRequestBody (FileUploadRequestComposer.java:114)
com.salesforce.android.chat.core.internal.filetransfer.FileUploadRequestComposer.createRequest (FileUploadRequestComposer.java:121)
com.salesforce.android.chat.core.internal.filetransfer.InternalFileTransferAssistant.buildFileUploadRequest (InternalFileTransferAssistant.java:150)
com.salesforce.android.chat.core.internal.filetransfer.InternalFileTransferAssistant.uploadFile (InternalFileTransferAssistant.java:131)
com.yamibuy.yamiapp.setting.livechat.CustomerChatActivity.uploadImage (CustomerChatActivity.java:743)
com.yamibuy.yamiapp.setting.livechat.CustomerChatActivity.onActivityResult (CustomerChatActivity.java:712)
android.app.Activity.dispatchActivityResult (Activity.java:8294)
android.app.ActivityThread.deliverResults (ActivityThread.java:5335)
android.app.ActivityThread.handleSendResult (ActivityThread.java:5383)
android.app.servertransaction.ActivityResultItem.execute (ActivityResultItem.java:51)
android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2270)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:237)
android.app.ActivityThread.main (ActivityThread.java:8125)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)

**Comment by wmathurin** [comment]
Looking at the stack trace, it does not look like Mobile SDK.
ServiceSDK is a different product. This is not the right forum for posting issues with that SDK. Please open a case with Salesforce instead.
