### ISSUE TITLE
java.lang.OutOfMemoryError during force api call

### ISSUE THREAD

**Issue by akshayajeevan** [forcedotcom/SalesforceMobileSDK-Android#2098]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.0.0
2. Issue found in Native App or Hybrid App: Hybrid
3. OS Version: Android 9
4. Device: Samsung Galaxy Tab Active2
5. Steps to reproduce: While syncing data with Salesforce using force.js apis
6. Actual behavior: App crash
7. Expected Behavior: should not crash
8. Error Log: 

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 14282384 byte allocation with 5828680 free bytes and 5MB until OOM, max allowed footprint 201326592, growth limit 201326592
       at java.lang.StringBuilder.toString(StringBuilder.java:410)
       at org.json.JSONStringer.toString(JSONStringer.java:430)
       at org.json.JSONObject.toString(JSONObject.java:693)
       at org.apache.cordova.PluginResult.<init>(PluginResult.java:55)
       at org.apache.cordova.CallbackContext.success(CallbackContext.java:70)
       at com.salesforce.androidsdk.phonegap.plugin.SalesforceNetworkPlugin$1.onSuccess(SalesforceNetworkPlugin.java:142)
       at com.salesforce.androidsdk.rest.RestClient$1.onResponse(RestClient.java:354)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

We are working on finding out the data and reduce its size.

Is there any other way we can handle this error here?

**Comment by bhariharan** [comment]
This does not look like a bug in `Mobile SDK`, this looks like a large payload that is exceeding the allowed memory footprint while crossing the native-hybrid bridge. You should probably use an API that has pagination to limit the size of data transferred at one time.

**Comment by shahdeep1989** [comment]
Hi @bhariharan or @akshayajeevan ,

I am facing same issue. App is crashing. Please find details below:

- Hybrid app using cordova plugin.

- Device
Brand:CONKER
Model:SX50
Orientation: Portrait
RAM free: 1.89 GB
Disk free: 50 GB

- Operating System
Version:Android 10
Orientation: Portrait
Rooted:No

- Here I am providing firebase crashlytics logs:
Fatal Exception: java.lang.OutOfMemoryError
Failed to allocate a 431789576 byte allocation with 6291456 free bytes and 301MB until OOM, target footprint 226881392, growth limit 536870912

java.util.Arrays.copyOf (Arrays.java:3257)

java.lang.StringBuilder.append (StringBuilder.java:137)
com.salesforce.androidsdk.smartstore.store.SmartStore.runQuery (SmartStore.java:908)
com.salesforce.androidsdk.smartstore.store.SmartStore.queryAsString (SmartStore.java:848)
com.salesforce.androidsdk.smartstore.store.StoreCursor.getDataSerialized (StoreCursor.java:95)
com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.runQuery (SmartStorePlugin.java:528)
com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.querySoup (SmartStorePlugin.java:491)
com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.access$700 (SmartStorePlugin.java:79)
com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin$1.run (SmartStorePlugin.java:159)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)

java.lang.Thread.run (Thread.java:919)

**Comment by wmathurin** [comment]
Can you tell us more about the query you are running (e.g. how much data is it pulling at once)?

**Comment by wmathurin** [comment]
Are you trying to hold all that data in memory at once?

**Comment by shahdeep1989** [comment]
Yes, I believe app is trying to process that much data at once.
App is storing that much data offline. So whether there is no internet, app can work offline.

**Comment by wmathurin** [comment]
You can have that much data in the store / on disk. Are you trying to have that much data in memory at once?
Are you using MobileSync?

**Comment by shahdeep1989** [comment]
Yes, we are using MobileSync.

**Comment by wmathurin** [comment]
The original post was a OOM when doing a network call (probably fetching too much data at once from the server).
@shahdeep1989 post as a OOM when doing a smartstore call. 
Do you need all that data in memory or could you fetch it on demand? Instead of having all the data in memory in the webview, could you go back to the database when it needs to be shown?
