### ISSUE TITLE
Crash on com.salesforce.service:sos OkHttp Version

### ISSUE THREAD

**Issue by mike14u** [forcedotcom/SalesforceMobileSDK-Android#2103]
Please fill out the following details:

1. Version of Mobile SDK Used: 
- com.salesforce.service:sos:4.0.9
2. Issue found in Native App or Hybrid App: 
- Native App
3. OS Version:
- Mostly on Android 8 / 9
4. Device:
- Any Device
5. Steps to reproduce:
- Unable to reproduce in my personal device, but I'll place crash log
6. Actual behavior:
- I think the SDKs OkHttp version is outdated is being overridden by the version our app uses and that shouldn't be the case.
7. Expected Behavior:
- Not to crash the app?
8. Error Log:
```
Fatal Exception: java.lang.NullPointerException
value for name x-liveagent-session-key == null

okhttp3.Headers.checkValue (Headers.java:268)
okhttp3.Headers$Builder.add (Headers.java:312)
okhttp3.Request$Builder.addHeader (Request.java:196)
com.salesforce.android.service.common.http.okhttp.SalesforceOkHttpRequest$Builder.addHeader (SalesforceOkHttpRequest.java:127)
com.salesforce.android.sos.liveagent.request.CreateSosRequest.build (CreateSosRequest.java:135)
com.salesforce.android.service.common.liveagentclient.LiveAgentClient.createRequest (LiveAgentClient.java:245)
com.salesforce.android.service.common.liveagentclient.LiveAgentClient.sendUsingHttpClient (LiveAgentClient.java:226)
com.salesforce.android.service.common.liveagentclient.LiveAgentClient.send (LiveAgentClient.java:141)
com.salesforce.android.service.common.liveagentclient.LiveAgentSession.onRequestPending (LiveAgentSession.java:186)
com.salesforce.android.service.common.liveagentclient.integrity.LiveAgentQueue.attemptToSend (LiveAgentQueue.java:157)
com.salesforce.android.service.common.liveagentclient.integrity.LiveAgentQueue.add (LiveAgentQueue.java:132)
com.salesforce.android.sos.liveagent.LiveAgentSosSession.createSosSession (LiveAgentSosSession.java:313)
com.salesforce.android.sos.liveagent.LiveAgentSosSession.onSessionStateChanged (LiveAgentSosSession.java:165)
com.salesforce.android.service.common.liveagentclient.SessionListenerNotifier.onSessionStateChanged (SessionListenerNotifier.java:68)
com.salesforce.android.service.common.liveagentclient.LiveAgentSession.onStateChanged (LiveAgentSession.java:212)
com.salesforce.android.service.common.liveagentclient.LiveAgentSession.onStateChanged (LiveAgentSession.java:62)
com.salesforce.android.service.common.utilities.lifecycle.LifecycleEvaluator.stateChanged (LifecycleEvaluator.java:305)
com.salesforce.android.service.common.utilities.lifecycle.LifecycleStateWatcher$1.run (LifecycleStateWatcher.java:79)
```
This is a similar issue: [https://salesforce.stackexchange.com/questions/282350/android-sdk-live-agent-crash-issues-headers-java-line-268-okhttp3-headers-checkv](https://salesforce.stackexchange.com/questions/282350/android-sdk-live-agent-crash-issues-headers-java-line-268-okhttp3-headers-checkv)

**Comment by bhariharan** [comment]
`ServiceSDK` is a different product, and this isn't the right forum for reporting issues on that product. Please open a case with `Salesforce` instead.

**Comment by mike14u** [comment]
Do you mean this? https://github.com/forcedotcom/ServiceSDK-Android the issue section is not even open. Where can I file this?

**Comment by saldanhacl** [comment]
We had the same issue, that was related to pro-guard. Adding [this](https://developer.salesforce.com/docs/atlas.en-us.service_sdk_android.meta/service_sdk_android/android_apk.htm?q=okhttp) to `proguard-rules.pro` solved the issue.
