### ISSUE TITLE
Exception in SmartStoreSDKManager during getDatabase() call 

### ISSUE THREAD

**Issue by nestlefsl** [forcedotcom/SalesforceMobileSDK-Android#2108]
We have been experiencing crash in app at launch time. The crash is happening only in some of our testing devices. But in those devices it is 100% reproducible.
Crash happens when we uninstall any older working version and install a new version fresh into the device.
If an older working version of app is already present in the device , and then if we are installing the new version No app crash is observed.
If the apk is made using the last released VersionCode number or lower (35 or lesser in our case) no crash is observed!!!!
1.	Version of Mobile SDK Used: 8.0.0
2.	Issue found in Native App or Hybrid App:Native
3.	OS Version:8.1.0
4.	Device: Zebra Device TC57HO
5.	Steps to reproduce:
•	Uninstall any version of app which is already present in device
•	Install new apk fresh in the device.
•	Launch the app. App crashes with below exception.
6.	Actual behavior: App crashes
7.	Expected Behavior: App should not crash
8.	Error Log:
```
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: FATAL EXCEPTION: main
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: Process: com.nestle.waters.outstream, PID: 22082
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.nestle.waters.outstream.NestleWatersApplication: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count() from sqlite_master;
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5768)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at android.app.ActivityThread.-wrap1(Unknown Source:0)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1669)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:106)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at android.os.Looper.loop(Looper.java:164)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6528)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: Caused by: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count() from sqlite_master;
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at net.sqlcipher.database.SQLiteCompiledSql.(SQLiteCompiledSql.java:64)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at net.sqlcipher.database.SQLiteProgram.(SQLiteProgram.java:89)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at net.sqlcipher.database.SQLiteQuery.(SQLiteQuery.java:48)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:2012)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1898)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2647)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2577)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1243)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1318)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:166)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:135)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:131)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at com.salesforce.androidsdk.smartstore.store.SmartStore.getDatabase(SmartStore.java:226)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at com.salesforce.androidsdk.smartstore.store.SmartStore.hasSoup(SmartStore.java:697)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at com.salesforce.androidsdk.smartstore.config.StoreConfig.registerSoups(StoreConfig.java:125)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.setupGlobalStoreFromDefaultConfig(SmartStoreSDKManager.java:385)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at com.nestle.waters.outstream.NestleWatersApplication.onCreate(NestleWatersApplication.java:14)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5765)
07-24 21:38:08.959 10259 22082 22082 E AndroidRuntime: ... 8 more
[bugreport-TC57-01-12-01.00-OG-U16-STD-2020-07-24-21-40-07.zip](https://github.com/forcedotcom/SalesforceMobileSDK-Android/files/5030824/bugreport-TC57-01-12-01.00-OG-U16-STD-2020-07-24-21-40-07.zip)
```

**Comment by bhariharan** [comment]
@nestlefsl It looks like the app is trying to open the database with the wrong encryption key. Have you tried using the latest version of `Mobile SDK` -> `8.2.0`?

**Comment by nestlefsl** [comment]
@bhariharan Yes. We tried after updating the versions to 'com.salesforce.mobilesdk:SalesforceSDK:8.2.0'
    &  'com.salesforce.mobilesdk:SmartStore:8.2.0'. The app crashed. 

Just FYI.. I cannot do a factory reset. But we did a clean up using apps available in playstore like google files. It did not fix the problem.

**Comment by bhariharan** [comment]
@nestlefsl Are you experiencing this on a specific device, or for a specific user? Are you able to reproduce this issue on a fresh installation of the app on the device? it's likely that wiping the app's files causes this issue, since that would have removed files required by the SDK to retrieve the correct encryption key that's required.

**Comment by nestlefsl** [comment]
@bhariharan  This is happening in 2 of the 10 devices we have used for testing. 
As mentioned in 1st comment, The issue is reproducible only if we are doing a fresh installation in these devices , If we are doing the installation of app on top of an already existing working version of app _( ie. without performing an uninstall)_ then there are no issues. Everything works perfectly. 

The cause of concern is, as of now very limited devices are being used for testing. And we observed this issue in 2. Soon the app will be installed in a big number of devices as **fresh installations**. If the app crash happens in the rate of 2/10 devices , the number is going to be huge !!!

**Comment by bhariharan** [comment]
@nestlefsl Could you install our sample app, `MobileSyncExplorer` (available [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/tree/dev/native/NativeSampleApps/MobileSyncExplorer)), on those 2 devices, and check if you get the same exception while running that app? If not, I suspect it might have something to do with how your app is interacting with `SmartStore`. Also, what device models are these 2 devices? Have you tried a hardware reset on these 2 test devices?

**Comment by nestlefsl** [comment]
@bhariharan We tested the sample app and it is not crashing in our device. 

From android side only 2 calls are executed before the exception happens.

 _SmartStoreSDKManager.initNative(this, MainActivity.class);
 SmartStoreSDKManager.getInstance().setupGlobalStoreFromDefaultConfig();_ 
In the application class. 

The 2nd line causes the exception in the salesforce mobile sdk and the app crashes. 

Is there anything wrong in the way we are doing these calls ?

**Comment by bhariharan** [comment]
@nestlefsl 

```
SmartStoreSDKManager.getInstance().setupGlobalStoreFromDefaultConfig();
```
The above line of code is not meant to be placed in an `Application` class. This should be in your data provider/adapter layer, or in your `Activity/Fragment` class. Take a look at our sample app, `MobileSyncExplorer` as an example.

**Comment by nestlefsl** [comment]
@bhariharan Thanks for the info. I moved the setupGlobalStoreFromDefaultConfig() call from application class to data provider class and the exception is not happening anymore. Will test in other devices also and close the issue.

**Comment by Joefrancisjohn** [comment]
@bhariharan The Crash problem has re appeared in same device again. 
Same apk and same device used for testing , and the same exception is happening again for SmartStoreSDKManager.getInstance().setupGlobalStoreFromDefaultConfig(); call.

As suggested by you, we had moved the call out of Application class and is now in Activity. This had fixed the problem initially but now has reappeared.

**Comment by bhariharan** [comment]
@Joefrancisjohn Is this on a fresh installation of the app, or an upgrade? If it's an upgrade, which version are you upgrading from?

**Comment by Joefrancisjohn** [comment]
@bhariharan It happens only if the installation is fresh. If am updating on an already existing apk version, there are no issues.

**Comment by bhariharan** [comment]
@Joefrancisjohn There appears to be something going on with the keys - perhaps you're trying to access the DB before SDK initialization? If that happens, you could get such an error? Are you able to reproduce this with an app generated from `forcedroid`? Also, could you set breakpoints in the DB initialization code and check what causes it to fail?
