### ISSUE TITLE
#2110  Push-notification react-native

### ISSUE THREAD

**Issue by VSoull** [forcedotcom/SalesforceMobileSDK-Android#2111]
@bhariharan  with 'com.google.firebase:firebase-messaging:20.1.0' we get the same error, can you provide me a link to your documentation page or an example? i don t find any info regarding android push notification firebase versions sdk etc on your salesforce docs, using react-native-firebase version 5 we get other issues on iOS and it s already deprecated:
This is what we use on react native now: 
 "@react-native-firebase/app": "^8.3.0",
    "@react-native-firebase/messaging": "^7.6.1",

and for build.gradle:  
   
    implementation 'com.google.firebase:firebase-analytics:17.2.2'
    implementation 'com.google.firebase:firebase-messaging:20.1.0'

Thank you

PS - for  'com.google.firebase:firebase-messaging:20.1.0' firebase has issued this  Warning: This version of firebase-iid (v20.1.0) has known issues involving silent failures and should not be used. A fix for these issues was released on March 03, 2020. https://firebase.google.com/support/release-notes/android#iid_v20-1-0

_Originally posted by @VSoull in https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/2110#issuecomment-671265971_

**Comment by bhariharan** [comment]
@VSoull I'm guessing `ReactNative` pulls in a newer version behind the scenes that'e breaking this. For now, please use Gradle excludes to exclude the version of `Firebase` that's coming from `ReactNative` and use this version instead. We will upgrade the version of `Firebase` in a future release.

**Comment by bhariharan** [comment]
Also, our sample apps are in this repo (`MobileSyncExplorer` and `RestExplorer`), and we have templates in this repo (like this `Kotlin` [sample app](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/tree/dev/AndroidNativeKotlinTemplate)).

**Comment by VSoull** [comment]
Hi @bhariharan   can you provide us more details when the fix will be pushed on salesforce android sdk side? we opened a ticket on salesforce side #27286695 and they mention to connect with your team regarding this fix, as for downgrade it will mean to go back 2 major react-native-firebase versions (update from december 09, 2019 , where Firebase Bill of Materials it s 24.3.0), the info regarding examples you provided it s for native android development  the code  from example it s in kotlin and to create our project we have used you salesforce tool https://www.npmjs.com/package/forcereact where the project it s with java .

**Comment by bhariharan** [comment]
@VSoull I'm not suggesting you downgrade the version of `React Native`, I'm suggesting that you override the version of `Firebase` being used in your generated project. This has nothing to do with `Java` or `Kotlin`. In the project generated using `forcereact`, there will be a `build.gradle`, like [this](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/dev/MobileSyncExplorerReactNative/android/app/build.gradle). In the section that outlines the dependencies (see [this](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/dev/MobileSyncExplorerReactNative/android/app/build.gradle#L143)), you can exclude the group `com.google.firebase` from within the `React Native` piece that pulls `Firebase` in, and explicitly add the following line:
```
api 'com.google.firebase:firebase-messaging:20.2.4'
```
This ensures that the version that's compatible with both projects is used.

**Comment by VSoull** [comment]
@bhariharan thank you for the info, we'll try your solution and keep an eye for a future release with the latest changes for firebase.
