### ISSUE TITLE
Chat dismiss dialog not using right color attributes

### ISSUE THREAD

**Issue by adityashri7** [forcedotcom/SalesforceMobileSDK-Android#2112]
Please fill out the following details:

1. Version of Mobile SDK Used: chat-ui:4.1.1'
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Android 10
4. Device: Pixel 3
5. Steps to reproduce: Minimize chat window, and hit close on the icon.
6. Actual behavior: The alert dialog box doesn't use the correct color attributes for the buttons. Because of that the buttons are hardly visible.
7. Expected Behavior: It should use the same attributes as that of the dialog that comes from hitting the close icon when on the full screen chat window.
8. Error Log: No log necessary. See the attached picture.
<img width="393" alt="Screen Shot 2020-08-10 at 10 23 25 PM" src="https://user-images.githubusercontent.com/16389886/89860362-20ac7700-db58-11ea-95a0-830299c5bdde.png">

**Comment by bhariharan** [comment]
This forum is reserved for `Mobile SDK` issues/bugs. The product you're referring to is a different product.
