### ISSUE TITLE
Support of React Native 0.63.2 because of major iOS 14 issue in RN 0.62.2

### ISSUE THREAD

**Issue by NeliHarbuzava** [forcedotcom/SalesforceMobileSDK-Android#2113]
**1. Version of Mobile SDK Used:** 8.2.0
**2. Issue found in Native App or Hybrid App:**
iOS 14 does not show images at all in React Native. RN of version 0.63.2 fixes this issue (https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0632). But the file [./libs/SalesforceReact/build.gradle#L29](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/dev/libs/SalesforceReact/build.gradle#L29) provides exact version of RN as 0.62.2 which in iOS 14 devices has mentioned major bug. We need a new version of SDK with the specified new version of RN, or to not specify it at all like:
`api 'com.facebook.react:react-native:0.63.2'`
or
`api 'com.facebook.react:react-native:+'`
**3. OS Version:**
**4. Device:**
**5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:**

**Comment by wmathurin** [comment]
We will fix any issues running on iOS 14 in our next release (SDK 8.3). Upgrading React Native will be part of it.

**Comment by wmathurin** [comment]
The fix is in dev (see https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/197). Will be in our next version of Mobile SDK (8.3).
