### ISSUE TITLE
Android: Live chat is not getting converted into the local device language

### ISSUE THREAD

**Issue by AndyKD** [forcedotcom/SalesforceMobileSDK-Android#2121]
Please fill out the following details:

1. Version of Mobile SDK Used:  com.salesforce.service:chat-ui:3.4.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Android 10
4. Device: Android Google Pixel 3
5. Steps to reproduce: Start the chat in different language except for english
6. Actual behavior: The device language is Germen (de) but the chat is still showing in English
7. Expected Behavior: The chat shall be converted to the local language of the device.
8. Error Log: NA

**Comment by wmathurin** [comment]
ServiceSDK is a different product, and this isn't the right forum for reporting issues on that product. Please open a case with Salesforce instead.
