### ISSUE TITLE
Parent Child Sync error

### ISSUE THREAD

**Issue by as8703** [forcedotcom/SalesforceMobileSDK-Android#2123]
I am not able to set up parent child sync in android native app

 implementation 'com.salesforce.mobilesdk:SalesforceSDK:8.2.0'
implementation 'com.salesforce.mobilesdk:MobileSync:8.2.0'

Issue found in Native App

{"_soupEntryId":1,"type":"syncUp","name":"UpSync_BRS_Flight","target":{"androidImpl":"com.salesforce.androidsdk.mobilesync.target.ParentChildrenSyncUpTarget","idFieldName":"Id","modificationDateFieldName":"LastModifiedDate","parent":{"soupName":"BRS_Flight__c","sobjectType":"BRS Flight","idFieldName":"Id","modificationDateFieldName":"LastModifiedDate"},"children":{"soupName":"BRS_Bag__c","sobjectType":"BRS Bag","idFieldName":"Id","modificationDateFieldName":"LastModifiedDate","sobjectTypePlural":"BRS Bags","parentIdFieldName":"Flight__c"},"childrenCreateFieldlist":["Flight__c","Bagtag_Number__c"],"childrenUpdateFieldlist":["Flight__c","Bagtag_Number__c"],"relationshipType":"MASTER_DETAIL"},"options":{"mergeMode":"LEAVE_IF_CHANGED"},"soupName":"BRS_Flight__c","status":"FAILED","progress":0,"totalSize":2,"maxTimeStamp":-1,"startTime":1600866639732,"endTime":1600866639883,"error":"Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference"}

![Screenshot from 2020-09-23 18-41-39](https://user-images.githubusercontent.com/18522583/94017018-82553780-fdcc-11ea-9263-f279b1343471.png)

[userstore.txt](https://github.com/forcedotcom/SalesforceMobileSDK-Android/files/5268349/userstore.txt)

[usersyncs.txt](https://github.com/forcedotcom/SalesforceMobileSDK-Android/files/5268354/usersyncs.txt)

**Comment by wmathurin** [comment]
Did you run our config validator on your configurations?
See https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/offline_config_validator.htm

**Comment by as8703** [comment]
@wmathurin No, please help how to check with android native app.  Now I tried to check see in screenshot
![Screenshot from 2020-09-24 10-38-40](https://user-images.githubusercontent.com/18522583/94103372-2af9aa80-fe52-11ea-85ce-6a1ce583c7de.png)

**Comment by wmathurin** [comment]
The tool to run is `forcedroid` not forceandroid. You should have it (it's the tool to generate applications with mobile sdk).

**Comment by as8703** [comment]
I have used gradel dependency to use sdk
implementation 'com.salesforce.mobilesdk:SalesforceSDK:8.2.0'
implementation 'com.salesforce.mobilesdk:MobileSync:8.2.0'

**Comment by wmathurin** [comment]
Simply `npm -g install forcedroid` and use it to check your config or use any json schema validator of your choice to check your config against the [schema for syncs config](https://raw.githubusercontent.com/forcedotcom/SalesforceMobileSDK-Package/master/shared/syncs.schema.json).

**Comment by wmathurin** [comment]
Also look at our sync config examples in https://github.com/forcedotcom/SalesforceMobileSDK-Package/blob/dev/shared/example.usersyncs.json

**Comment by as8703** [comment]
@wmathurin will you please do more help than providing the links. I am getting this error  

"__last_error__": "{\"body\":[{\"errorCode\":\"PROCESSING_HALTED\",\"message\":\"Invalid reference specified. No value for 1601918113512.id found in 1601918113512\"}],\"httpHeaders\":{},\"httpStatusCode\":400,\"referenceId\":\"1601918113512\"}"
    }

**Comment by as8703** [comment]
I found  solution.

**Comment by as8703** [comment]
I found solution.
