### ISSUE TITLE
App crash when UnauthenticatedRestClient is used

### ISSUE THREAD

**Issue by KunalChaubal** [forcedotcom/SalesforceMobileSDK-Android#2131]
### Version of Mobile SDK Used: 
8.3.0
### Issue found in Native App or Hybrid App: 
Native App
### OS Version: 
Android 10
### Device: 
OnePlus 5
### Steps to reproduce: 
1. Make API call with UnauthenticatedRestClient.
2. This is the RestRequest constructor that I used:
`val restRequest = RestRequest(RestMethod.POST, _URL_, _JSON_OBJECT_)` 
### Crash Log

`FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.kunal.example, PID: 4280
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.URI.toString()' on a null object reference
        at okhttp3.HttpUrl.get(HttpUrl.java:928)
        at com.salesforce.androidsdk.rest.RestClient$OAuthRefreshInterceptor.intercept(RestClient.java:664)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`
### Observations
1. The same code works fine with v8.2.0

**Comment by bhariharan** [comment]
@KunalChaubal How are you using `UnauthenticatedRestClient`, as in, for what type of requests are you using it? Are you using this to make requests to an authenticated endpoint that returns `401`? `UnauthenticatedRestClient` should never trigger the refresh flow or `OAuthRefreshInterceptor`. Either way, I have fixed this corner case [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2130/files#diff-3b911bfb801ca5a5b11e52f33952dd8dR660), and this will be a part of our next release. Feel free to apply the same change in your fork of the SDK in the meanwhile.

**Comment by KunalChaubal** [comment]
I'm using Unauthenticated client to make requests to APIs that do not need user authentication - 'User sign up' for example and as I said, the same code works fine in v8.2.0.
Since I have added it as a Gradle dependency, I will move back to 8.2.0 for now and wait until the next build is released. Thank you for all the help, I appreciate it.

**Comment by vishnu-jangid** [comment]
hi @bhariharan @KunalChaubal i am using Deferred template is not working with doesNotRequireAuthentication.

let records = { q: 'SELECT Id, Name FROM User' }
      net.sendRequest('/services/data', '/v55.0/query',
          (response) => {
              console.log("fetchData : response", response);
          },
          (error) => {
              console.log("fetchData : error", error);
          }, 'GET', records, {
          "Content-Type": "application/json",
          Authorization: `${access_token}`
      },
          null, false, true);
          
          please help.

**Comment by wmathurin** [comment]
Why would you use the unauthenitcated client for a call that requires authentication?
What error are you getting?
