### ISSUE TITLE
Can we do language translate using the Snap-Ins SDK

### ISSUE THREAD

**Issue by AndyKD** [forcedotcom/SalesforceMobileSDK-Android#2135]
Please fill out the following details:

1. Version of Mobile SDK Used: 3.4.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Android 10
4. Device: Google Pixel
5. Steps to reproduce: I want to convert/translate the outgoing messages from chatUI to the salesforce agent  
6. Actual behavior: ChatCore.sendMessage() is also not working as expected
7. Expected Behavior: The chat messages shall be converted and shall be sent in a control manner
8. Error Log: NA

We have a requirement for example we have to assign a chat in a language in which language the chat agents are available. For example user is having a device language "french" but the chat agent is available in English. We want to control the outgoing message by converting the message into English before sending it to agent. 

Do we have any way to control the chatUI messages. Any suggestion would be really appreciated. 

Thanks.

**Comment by bhariharan** [comment]
@AndyKD `SnapIns` is a different product from `Mobile SDK`. This forum is for `Mobile SDK` issues.
