### ISSUE TITLE
Exclude MobileSync, SmartStore, Analytics?

### ISSUE THREAD

**Issue by rpander93** [forcedotcom/SalesforceMobileSDK-Android#2157]
Hi there,

We're using the SDK in a React Native app. I was hoping to exclude the MobileSync, SmartStore & Analytics package from being included in the app since we're only using the SDK for the login screen and making calls to Apex controllers. Excluding them from settings.gradle gives me a bunch of errors. How can this be done?

1. Version of Mobile SDK Used:  8.3
2. Issue found in Native App or Hybrid App: Hybrid
3. OS Version: Android 11
4. Device: Nexus 5P
5. Steps to reproduce: Remove MobileSync, SmartStore & Analytics includes in settings.gradle
6. Actual behavior: assemble fails
7. Expected Behavior: assemble works
8. Error Log:

**Comment by bhariharan** [comment]
@rpander93 This is currently not possible since the libraries have an inheritance model of dependency. `MobileSync -> SmartStore -> SalesforceSDK -> SalesforceAnalytics`. Each library is tiny in size, so having them shouldn't cause any concerns.

**Comment by wmathurin** [comment]
We have a nice picture about it in the documentation. See https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/android_project_files.htm

**Comment by rpander93** [comment]
Thanks. The picture is missing SalesforceReact. Should I assume its the same as SalesforceHybrid?

Indeed, the libraries are small fortunately, but shipping them to each of our users everytime we publish an update is a waste nonetheless.

**Comment by bhariharan** [comment]
Yes, it's similar to `SalesforceReact`. With Gradle dependencies, they're pulled in automatically.

**Comment by jake-moritz-trifecta** [comment]
I would find something like this useful as a possible workaround for https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/2158. Disabling SmartStore and any database calls may be useful here
