### ISSUE TITLE
Salesforce Chat SDK performs abnormally in Android App

### ISSUE THREAD

**Issue by ajaymohanv** [forcedotcom/SalesforceMobileSDK-Android#2161]
Please fill out the following details:

1. Version of Mobile SDK Used:  4.1.2
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 9
4. Device: Samsung Galaxy S10+
5. Steps to reproduce: Call the chat code 
6. Actual behavior: Chat should be contained inside the app
7. Expected Behavior: Chat behaves as a separate application
8. Error Log:

Main Issue : After integrating the Salesforce Chat SDK in my android application, I noticed that, after the chat was initiated, it behaves as a separate application rather than working inside my application.
When I select the The Recents screen (also referred to as the Overview screen, recent task list, or recent apps), I see my application and the chat as two different apps. For the same implementation in IOS, the chat comes inside the app. Due to this behaviour, when I kill my application, the Chat will not end. It continues in the background. Can you help fix this?

**Comment by wmathurin** [comment]
ServiceSDK is a different product, and this isn't the right forum for reporting issues on that product. Please open a case with Salesforce instead.
