### ISSUE TITLE
Salesforce Chat Orientation Control not available

### ISSUE THREAD

**Issue by ajaymohanv** [forcedotcom/SalesforceMobileSDK-Android#2162]
Please fill out the following details:

1. Version of Mobile SDK Used: 4.1.2
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 9
4. Device: Samsung Galaxy S10+
5. Steps to reproduce: Call the chat code
6. Actual behavior: Chat orientation changes as per device orientation
7. Expected Behavior: Chat orientation should be similar to app orientation
8. Error Log:
We are unable to set the display orientation of the Chat. We have a fixed landscape orientation for our app. But the Chat changes orientation as the Mobile does. Can you help fix this?

**Comment by wmathurin** [comment]
ServiceSDK is a different product, and this isn't the right forum for reporting issues on that product. Please open a case with Salesforce instead.
