### ISSUE TITLE
Incorrect null handling (inconsistent with iOS SDK)

### ISSUE THREAD

**Issue by mjmasn** [forcedotcom/SalesforceMobileSDK-Android#2167]
Please fill out the following details:

1. Version of Mobile SDK Used: 8.3.0
2. Issue found in Native App or Hybrid App: React Native
3. OS Version: n/a
4. Device: n/a
5. Steps to reproduce: For an object with a field that is nillable: false, defaultedOnCreate: true, setting no value for that field when inserting to SmartStore from ReactNative causes it to be given a `null` value on sync up, when it should be skipped entirely.
For example given Foo is a picklist field that is non-nillable but defaulted on create to 'Bar':
```ts
smartstore.upsertSoupEntries(
  false,
  'FooSoup',
  [
    { Id: '123', Name: 'Test', Foo: 'Something' },
    { Id: '456', Name: 'Test 2' }
  ],
  () => {},
  () => {}
)
```
6. Actual behavior: On Android, a `REQUIRED_FIELD_MISSING` error is generated for 'Foo'. On iOS no error occurs and the objects are created on the server with default values populated.
7. Expected Behavior: Only sync up fields with explict values, don't replace missing values with `null`.
8. Error Log: n/a

It looks like this feature was implemented deliberately so it would be interesting to know the reasoning for that. To me it seems vital to preserve the `JSONObject.NULL` vs `null` distinction as they have very different meanings in this context. For example on a sync up you may want to not sync up a field that will be defaulted (`null`) or you might want to explicitly update the value of a field to null (`JSONObject.NULL`).

https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/95429cf8bbea3913e1fb83d576401e4a4b7529c0/libs/SalesforceSDK/src/com/salesforce/androidsdk/util/JSONObjectHelper.java#L44-L58

This quick diff does seem to resolve the issue but I'm not sure what other impacts that might have.

```diff
diff --git a/mobile_sdk/SalesforceMobileSDK-Android/libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/SyncUpTarget.java b/mobile_sdk/SalesforceMobileSDK-Android/libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/SyncUpTarget.java
index 8806507fa..a36aa6176 100644
--- a/mobile_sdk/SalesforceMobileSDK-Android/libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/SyncUpTarget.java
+++ b/mobile_sdk/SalesforceMobileSDK-Android/libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/SyncUpTarget.java
@@ -409,7 +409,12 @@ public class SyncUpTarget extends SyncTarget {
         Map<String,Object> fields = new HashMap<>();
         for (String fieldName : fieldlist) {
             if (!fieldName.equals(idFieldName) && !fieldName.equals(modificationDateFieldName)) {
-                fields.put(fieldName, SmartStore.project(record, fieldName));
+                Object fieldValue = SmartStore.project(record, fieldName);
+                if (fieldValue == JSONObject.NULL) {
+                    fields.put(fieldName, null);
+                } else if (fieldValue != null) {
+                    fields.put(fieldName, fieldValue);
+                }
             }
         }
         return fields;
@@ -428,4 +433,4 @@ public class SyncUpTarget extends SyncTarget {
             this.isDeleted = isDeleted;
         }
     }
-}
\ No newline at end of file
+}
diff --git a/mobile_sdk/SalesforceMobileSDK-Android/libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java b/mobile_sdk/SalesforceMobileSDK-Android/libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
index 5f6654cdf..20a89d5da 100644
--- a/mobile_sdk/SalesforceMobileSDK-Android/libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
+++ b/mobile_sdk/SalesforceMobileSDK-Android/libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java
@@ -1594,14 +1594,14 @@ public class SmartStore  {

 			if (jsonObj instanceof JSONObject) {
 				JSONObject jsonDict = (JSONObject) jsonObj;
-				Object dictVal = JSONObjectHelper.opt(jsonDict, pathElement);
+				Object dictVal = jsonDict.opt(pathElement);
 				result = project(dictVal, pathElements, index+1);
 			}
 			else if (jsonObj instanceof JSONArray) {
 				JSONArray jsonArr = (JSONArray) jsonObj;
 				result = new JSONArray();
 				for (int i=0; i<jsonArr.length(); i++) {
-					Object arrayElt = JSONObjectHelper.opt(jsonArr, i);
+					Object arrayElt = jsonArr.opt(i);
 					Object resultPart = project(arrayElt, pathElements, index);
 					if (resultPart != null) {
 						((JSONArray) result).put(resultPart);
```

**Comment by wmathurin** [comment]
Thanks @mjmasn, we will take a look.

**Comment by aureosouza** [comment]
This is really critical for our current application, we have in SF custom relationship by external id with optional value, in the format:
```
{FirstParam__r:  { PG_RetXCore__ExternalId__c: "foo" }}
```
When we syncUp iOS does **not** try to send this field, in case of android it tries to populate with `null` 
```
FirstParam__r: null
```
Which is actually causing an error response in POST request to SF on syncUp:

```
"errorCode":"INVALID_FIELD_FOR_INSERT_UPDATE"
```

When can we expect a fix for this @mjmasn? Thanks!

**Comment by wmathurin** [comment]
The fix will be in our next release (9.2). See https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2240

**Comment by aureosouza** [comment]
That's great @wmathurin, is there an estimation on when it should be deployed? Thanks a lot!

**Comment by wmathurin** [comment]
Probably next week.
