### ISSUE TITLE
Push messages not displaying on the device banner

### ISSUE THREAD

**Issue by llyrProximity** [forcedotcom/SalesforceMobileSDK-Android#2178]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.0.0
2. Issue found in Native App
3. 10/11
4. Device: Samsung Tab A7

I'am trying to send push notification from Salesforce to Android native app.
When i send messages from Salesforce they always come through as a data message type. 

e.g.
{
    "data":{
      "Name" : "John Jones",
      "body" : "You have a task assigned to you",
      "store" : "London"
    }
}

I would like these messages to go into the devices notification banner. To do this, it seems FCM is expecting a notification type message to come through.
e.g
{
   "notification": {
       "title" : "New task",
       "text": "You have a task assigned to you",
       "icon": "ic_notification"
    }
}

How can I achieve this? I don't want to create a Notification using Notification Builder as this wont work when the app isn't running.

**Comment by wmathurin** [comment]
Here is the relevant documentation: https://developer.salesforce.com/docs/atlas.en-us.pushImplGuide.meta/pushImplGuide/connected_app_custom_push_payload_android.htm
