### ISSUE TITLE
Bintray Migration

### ISSUE THREAD

**Issue by sdneko** [forcedotcom/SalesforceMobileSDK-Android#2184]
Hi, as bintray is to be sunset soon, will the salesforce mobile sdk libraries be available somewhere else such as maven central?

**Comment by bhariharan** [comment]
@sdneko We are considering our options, but for now, consuming via source from our open source repo is the recommended option.

**Comment by wmathurin** [comment]
We have just released [Mobile SDK 9.1.1](https://github.com/forcedotcom/SalesforceMobileSDK-Android/releases/tag/v9.1.1) and it is available on Maven Central.
