### ISSUE TITLE
RefreshTokenRevokedException

### ISSUE THREAD

**Issue by saniola410** [forcedotcom/SalesforceMobileSDK-Android#2185]
https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/0244aa65c7a1693a6f2edfbc2fe64e7e3d68a852/libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestClient.java#L775

Could you please help and explain how to handle this exception? This exception occurs very often and I can't find in code some callback or something like that.

Just one comment:
https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/0244aa65c7a1693a6f2edfbc2fe64e7e3d68a852/libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/manager/SyncTask.java#L88

**Comment by bhariharan** [comment]
@saniola410 If the refresh failed and throws this exception, that means it's a non-network related failure in the refresh flow, and the user should be logged out and taken to the login screen at this point. To investigate why the refresh failed, you should look into the server side configuration on that org for that user profile.
