### ISSUE TITLE
Language Switcher support

### ISSUE THREAD

**Issue by AndreiSakolchyk** [forcedotcom/SalesforceMobileSDK-Android#2186]
Hi, 

We want to customize Login Screen so that the user will be able to select a language and this selection is saved for the next login.
How can we use the Salesforce Mobile SDK to accomplish this? What does Mobile SDK provide for this?

Thanks in advance!

**Comment by AndreiSakolchyk** [comment]
Our use case is that: before and after login users need to be able to select or change the preferred language of the application. The application starts from the login page (Salesforce Mobile SDK webview renders custom Community page) which should be rendered in user's preferred language which has been selected/changed by the user being logged in into the application.

We are looking for which abilities Salesforce Mobile SDK provides to accomplish this scenario, namely
1. Go through login flow in a preferred language
2. Pass user's preferences from login flow (for instance selected language) to use it for the application

**Comment by wmathurin** [comment]
Once you are login, you can get the language/locale from the identity data on the current user.
To get the identity data do the following
```objective-c
SFIdentityData *idData = [SFUserAccountManager sharedInstance].currentUser.idData
```
The fields of interest on SFIdentityData are [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/v9.0.0/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/Identity/SFIdentityData.h#L191).
