### ISSUE TITLE
Hide CustomTab/ActionBar in LoginActivity

### ISSUE THREAD

**Issue by fm-eb** [forcedotcom/SalesforceMobileSDK-Android#2188]
Please fill out the following details:

1. Version of Mobile SDK Used: 
'com.salesforce.mobilesdk:SalesforceSDK:9.0.0'
'com.salesforce.mobilesdk:MobileSync:9.0.0'

2. Issue found in Native App or Hybrid App:
How is it possible to hide the CustomTab/ActionBar of the LoginActivity?
I see that iOS has a few options to customize the login screen by overriding the LoginViewController. But I can't find a similar API for that on Android. I dug into the code and was able to hide it by calling `getActionBar().hide()` in the SDKs `LoginActivity`, but I assume that this should also be possible from the outside.

3. OS Version: every Android version

4. Device: every Android device

5. Steps to reproduce: extend an Activity  from `SalesforceActivity` and open the SDKs `LoginActivity` by starting the extending Activity.

6. Actual behavior: A blue CustomTab/ActionBar is visible to the end-user who should not be able to see the server URL nor to change the server settings. Aside from that, the blue color does not fit at all into the apps design.

7. Expected Behavior: The SDK should provide a way to hide this CustomBar.

8. Error Log: none

**Comment by brandonpage** [comment]
Hello @fm-eb,

If you would like to customize or hide the action bar you should create a class that extends `LoginActivity`.  From there you can call `getActionBar().hide()` and/or any other customization you would like.  Then simply add that .class to the SDK Manager's `initNative` call to replace our login activity.
