### ISSUE TITLE
Unable to Login  while using credentials via copy paste method 

### ISSUE THREAD

**Issue by prince-singh07** [forcedotcom/SalesforceMobileSDK-Android#2208]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.0.0
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: Android 11
4. Device: Samsung Galaxy M30s
5. Steps to reproduce: Try logging by copy paste method for username and password
6. Actual behavior: Unable to Login  while using credentials via copy paste method 
7. Expected Behavior: App should get logged in to salesforce account
8. Error Log:

**Comment by brandonpage** [comment]
I have tested this and copy/paste changes nothing on the login page.  Whether you paste or type if you enter your credentials correctly login will work.
