### ISSUE TITLE
Unable to send push notification from one 'connected app' for android and Ios Plotforms 

### ISSUE THREAD

**Issue by Kmullapudi22** [forcedotcom/SalesforceMobileSDK-Android#2209]
Dear team,

Can anyone help me on this i wants to send push notifications to Android and IOS  platforms by using one 'connected app' please share how can it possiable.

**Comment by wmathurin** [comment]
Have you read the relevant documentation: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/push_intro.htm

**Comment by bhariharan** [comment]
@Kmullapudi22 Each connected app is meant to be used for a specific platform, i.e. Android or iOS. You need separate connected apps for different platforms.
