### ISSUE TITLE
Connected App identification

### ISSUE THREAD

**Issue by Kmullapudi22** [forcedotcom/SalesforceMobileSDK-Android#2210]
Hi team,

Can anyone suggest based on the 'consumer Key' how can we identify the 'Connected app' in salesforce without manual checking please suggest .

**Comment by brandonpage** [comment]
What do you mean when you say "identify the Connected app"?  You set the connected app in XML and it should never change through the lifetime of the app.

**Comment by wmathurin** [comment]
We recommend you check out our [Salesforce Mobile SDK Basics trailhead module](https://trailhead.salesforce.com/content/learn/modules/mobile_sdk_introduction?trail_id=mobile_sdk_intro). In particular the [Understand Security and Authentication](https://trailhead.salesforce.com/en/content/learn/modules/mobile_sdk_introduction/mobilesdk_intro_security?trail_id=mobile_sdk_intro) section talks about OAuth and connected app.
