### ISSUE TITLE
Push notifications crash with 'Default FirebaseApp is not initialized in this process'

### ISSUE THREAD

**Issue by ronaldtb** [forcedotcom/SalesforceMobileSDK-Android#2224]
**Version of Mobile SDK Used:** 
9.1.1

**Issue found in Native App or Hybrid App:** 
React Native

**OS Version:**
Android 6.0.1

**Device:**
Motorola Moto G3

**Steps to reproduce:**
Follow steps from [Salesforce Mobile Notifications Implementation Guide](https://developer.salesforce.com/docs/atlas.en-us.232.0.pushImplGuide.meta/pushImplGuide/pns_client_app_android.htm) and 
[Using Push Notifications in Android](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/push_android_code.htm) to modify the code.  

Send a test notification using Firebase Cloud Messaging with title 'This is a test' and text 'Test'.

**Actual behavior:**
App crashes in all states (foreground, background, closed).

**Expected Behavior:**
The push notification should be shown.

**Error Log:**
```
2021-09-03 07:43:23.113 14511-14618/<anonimized>.app.ACC E/AndroidRuntime: FATAL EXCEPTION: Firebase-SFDCFcmListenerService
    Process: <anonimized>.app.ACC, PID: 14511
    java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process <anonimized>.app.ACC. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@19.3.0:184)
        at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.0:120)
        at com.google.firebase.messaging.zzo.zza(com.google.firebase:firebase-messaging@@20.1.0:1)
        at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.0:50)
        at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.0:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:818)
```

**Additional information:**
I don't use a `google-services.json`.
And I've tried to see if [disabling](https://firebase.googleblog.com/2017/03/take-control-of-your-firebase-init-on.html) the `FirebaseInitProvider` solves the problem but it didn't.

There are no Firebase/Google related dependency differences between my app and the React Native TypeScript template used to setup the project.

Push notifications for iOS work without any problems.

**Comment by bhariharan** [comment]
@ronaldtb This happens if you use a newer version of the `Firebase` library. Please ensure that you're using `20.1.0`, and remove your `google-services.json`.
```
api 'com.google.firebase:firebase-messaging:20.1.0'
```
This should fix the issue.

**Comment by ronaldtb** [comment]
@bhariharan thank you for the quick response. I ran a `./gradlew app:dependencies` and I'm already using `com.google.firebase:firebase-messaging:20.1.0`.

I also don't have a `google-services.json` file in my project.

I've worked around the problem by manually initialising FirebaseApp using the `[DEFAULT]` app name. See the snippet below from `MainApplication.java`.

```java
String appName = FirebaseApp.DEFAULT_APP_NAME;
final String pushClientId = BootConfig.getBootConfig(context).getPushNotificationClientId();
final FirebaseOptions firebaseOptions = new FirebaseOptions.Builder().
        setGcmSenderId(pushClientId).setApplicationId(context.getPackageName()).build();

/*
 * Ensures that Firebase initialization occurs only once for this app. If an exception
 * isn't thrown, this means that the initialization has already been completed.
 */
try {
    FirebaseApp.getInstance(appName);
} catch (IllegalStateException e) {
    SalesforceSDKLogger.w("MainApplication", "Firebase hasn't been initialized yet");
    FirebaseApp.initializeApp(context, firebaseOptions, appName);
}
```
