### ISSUE TITLE
Chat sdk does not honor darkmode setting

### ISSUE THREAD

**Issue by magnub** [forcedotcom/SalesforceMobileSDK-Android#2226]
Please fill out the following details:

1. Version of Mobile SDK Used: 4.2.0 (chat-ui)
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 11
4. Device: Samsung galaxy S20 FE
5. Steps to reproduce: Integrate chat-ui sdk into app, start a chat when darkmode is enabled (background etc in salesforce chat ui is white should have some dark color)
6. Actual behavior: Background etc in salesforce chat ui is white should have some dark color
7. Expected Behavior: Background is set to darker color 
8. Error Log:

**Comment by bhariharan** [comment]
This is not the right forum for issues with the `Chat SDK`, that's a different product from `Mobile SDK`.
