### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Android#2229]
This is not an issue, I just have a question. How do I bypass Webview logins? I want to do some automation, but I cannot test it because I'm using Webview for the login. @bhariharan

**Comment by wmathurin** [comment]
We have a file called test_credentials.json which contains a valid refresh token (it is not checked in to github but instead is generated on CI from environment variables). Then we have TestCredentials.java to read the value from that file. In tests, we setup the user using the values obtained from TestCredentials.java.

To see test credentials use, have a look at the commit that brought it to the repo: https://github.com/forcedotcom/SalesforceMobileSDK-Android/commit/f656d0b5ac103ff1b742f2b5afafd190338835d2

To generate the test credentials file easily, you can use: https://github.com/forcedotcom/SalesforceMobileSDK-Shared/tree/dev/credshelper

**Comment by johnjeremih** [comment]
@wmathurin is this for Android native?

**Comment by wmathurin** [comment]
It is used across the board for native (and hybrid and react native tests).
Maybe the PR (https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1877) will make more sense than the commit I provided above.
