### ISSUE TITLE
Minimize the App between Login Flow ( User Logged in state is not maintaining )

### ISSUE THREAD

**Issue by adnan-rolustech** [forcedotcom/SalesforceMobileSDK-Android#2230]
Version of Mobile SDK Used: 9.1.1
Issue found in Native App
OS Version: 11
Device: All Android Devices
App Created by using **forcedroid**

**Steps to reproduce issue:**
1 - Open the app ( Without logged in user / Un-authenticated )
2 - Proceed to login flow
3 - Enter the credentials
4 - Press the login button
5 - During the process press the back button or minimize the app.

**Expected Behavior:**
The App should resumed where it was minimized

**App Behavior:**
The App shows the login screen again and again even if we provide the user credentials again and again. The App goes into background, even if we logged in successfully.
Also if we kill the app and then came back the app shows that the user is already logged in.

Kindly provide a solution regarding this behavior.
Thank You

**Comment by wmathurin** [comment]
We created a bug in our internal bug tracking system.

**Comment by wmathurin** [comment]
I believe the issue is now resolved (in 11.1). See https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2484/files
