### ISSUE TITLE
[Android Native] - Login flow is not working in a device with MDM installed

### ISSUE THREAD

**Issue by Lajesh** [forcedotcom/SalesforceMobileSDK-Android#2233]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.0.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 11
4. Device: In devices where MDM is installed
5. Steps to reproduce: Open the application, click on the Login button, then we see a blank screen instead of the actual login page
6. Actual behavior: Blank screen is shown instead of the Salesforce login page
7. Expected Behavior: Salesforce login page should be shown without any issues
8. Error Log:

We are building a native android application which is uses the SalesforceMobile SDK for android and we have deferred login in the application. The application works fine on emulators and devices where MDM is not installed. But when we tried the application in some devices where MDM has been installed, instead of Login screen we see a blank screen.

Based on our investigation, we found that the Mobile SDK is using Android's native account manager and some of the MDMs will have policies to disallow the account management. If so, is there any solution for this ? Is there any way we can get rid of the native account manager dependency from Salesforce Mobile SDK

Appreciate your quick response as we are going live soon.

**Comment by gkotula** [comment]
Closing due to thread inactivity.
