### ISSUE TITLE
KeyStoreWrapper: Could not retrieve private key | Caused by: android.security.KeyStoreException: Invalid key blob

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Android#2244]
Please fill out the following details:

1. Version of Mobile SDK Used: 
9.0.0
2. Issue found in Native App or Hybrid App:
Native
3. OS Version:
API 27
4. Device:
Running an Emulador on a Pixel 5
5. Steps to reproduce:
They way I reproduce is just trying to get the user Accound Id

`            if (userAccountManager !=null){
            final String userId = userAccountManager.getCurrentUser().getUserId();`

6. Actual behavior:
Current implementation
![image](https://user-images.githubusercontent.com/4177453/136951812-1a86dc16-3ec2-4d7a-af49-27894b822f19.png)

![image](https://user-images.githubusercontent.com/4177453/136949610-98d8d9c3-efd4-49ab-9ca4-88d28502fea5.png)

![image](https://user-images.githubusercontent.com/4177453/136950193-fb2404a3-5f99-4047-b381-62d7b75b39bc.png)

![image](https://user-images.githubusercontent.com/4177453/136950372-cdbc5f69-f364-4510-80da-05efe1bfee29.png)

https://user-images.githubusercontent.com/4177453/136942983-d3291ef0-0c82-48c5-a1df-e7120783a503.mov

7. Expected Behavior:
8. Error Log:

**Comment by wmathurin** [comment]
Could you try with the latest Mobile SDK (9.2)?

**Comment by johnjeremih** [comment]
@wmathurin it didn't solve the problem. Now I see that version 9.2.0 requires the user to have a passcode established in the phone. What about if the user doesn't want to do that?

**Comment by gkotula** [comment]
Hi @johnjeremih Regarding the passcode, if a connected app requires a PIN, we now handle it through the OS locking mechanism.  Users will have to set up a device PIN in order to use the app.

Concerning the original issue, did the upgrade to 9.2 (or the latest release) fix the exception?

**Comment by gkotula** [comment]
Closing due to lack of response.

**Comment by johnjeremih** [comment]
@gkotula  I'm sorry I didn't see your answer. Since I updated to 10.1.1 I haven't seen the problem anymore.
     "com.salesforce.mobilesdk:SalesforceSDK:10.1.1"
