### ISSUE TITLE
Problem creating a forcedroid

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Android#2249]
I created a new forcedroid project and ran into a problem where I cannot create environments the right way because the folder structure is not the same as a regular project. This makes it difficult to create variant classes, meaning Dev, QA, Prod, etc.

here is the forcedroid project

![image](https://user-images.githubusercontent.com/4177453/141559620-2ab27b56-9e91-43f7-a736-62d064972f30.png)

here is a regular project
![image](https://user-images.githubusercontent.com/4177453/141560564-45bb1c44-99c0-4906-9dfe-51ed789a152b.png)

![image](https://user-images.githubusercontent.com/4177453/141569900-488f1c76-f82e-4924-b33a-9f0be0f9854e.png)

forcedroid
![image](https://user-images.githubusercontent.com/4177453/141597178-816c7651-cafd-4cdd-985d-e431c1fb28ad.png)

Regular project
![image](https://user-images.githubusercontent.com/4177453/141597192-46680a14-326f-4e21-8f05-d29f9142a01f.png)

**Comment by wmathurin** [comment]
Once the app is created, you can reorganize it anyway you want.

**Comment by johnjeremih** [comment]
@wmathurin  I tried, it doesn't work. The app won't compile. I had to create a new project and just add the implementation instead.

**Comment by wmathurin** [comment]
We are fixing that in our next release (MSDK 12.0) - see https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/390
