### ISSUE TITLE
Sync functionality is not working

### ISSUE THREAD

**Issue by vickyvora** [forcedotcom/SalesforceMobileSDK-Android#2267]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.2.1
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: Android 10
4. Device: Nokia 5.1 Plus
5. Steps to reproduce: I have created project from cmd and logged in via salesforce user, after that I have stored 2 contacts' last name in smartStore DB and after that I am using sync up method that is provided in MobileSyncExploer.
6. Actual behavior: I can't able to sync locally stored contacts to web. 
7. Expected Behavior: Contacts should be sync if I have done same things those have done in MobileSyncExploer. Also I am not able to run this sample project "MobileSyncExploer" in my Android Studio.
8. Error Log: I am getting "Done" status in sync but not able to sync my locally stored contacts (Stored in smartStore DB).

**Comment by brandonpage** [comment]
Hi @vickyvora,

What API's are you calling to sync the contacts up the cloud?

What error do you get running the MobileSyncExplorer in Android Studio?
