### ISSUE TITLE
Blank screen after login when "Use the native browser for user authentication on Android" on the My Domain

### ISSUE THREAD

**Issue by aanobile** [forcedotcom/SalesforceMobileSDK-Android#2268]
1. Version of Mobile SDK Used:   **9.1.1**
2. Issue found in Native App or Hybrid App:  **Native** 
3. OS Version:  **Android 11**
4. Device:  **All** 
5. Steps to reproduce:

- Download and build the sample app https://github.com/forcedotcom/SalesforceMobileSDK-Templates/tree/dev/AndroidNativeKotlinTemplate 
- Configure the app to connect to a Salesforce org
- Enable the flag "Use the native browser for user authentication on Android" on the My Domain Page
- Try to login in the custom app 
- After the login process, a blank screen appears
![login-blankscreen](https://user-images.githubusercontent.com/97608628/149150362-729925ae-598f-4f09-9b1c-3cc6376a3f4b.PNG)

6. Actual behavior: **blank screen appears**
7. Expected Behavior:  **successful login**

**Comment by aanobile** [comment]
Sorry. I found this that solves the issue: 
https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/auth_android_advanced.htm

**Comment by JHeyland** [comment]
Any other ideas of things to try?
