### ISSUE TITLE
ObjectWatcher was watching this because com.salesforce.androidsdk.auth.AuthenticatorService received Service#onDestroy() callback and Service not held by ActivityThread

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Android#2285]
Please fill out the following details:
    ┬───
    │ GC Root: System class
    │
    ├─ com.salesforce.androidsdk.auth.AuthenticatorService class
    │    Leaking: NO (a class is never leaking)
    │    ↓ static AuthenticatorService.AUTHENTICATOR
    │                                  ~~~~~~~~~~~~~
    ├─ com.salesforce.androidsdk.auth.AuthenticatorService$Authenticator instance
    │    Leaking: UNKNOWN
    │    Retaining 688 B in 10 objects
    │    context instance of com.salesforce.androidsdk.auth.AuthenticatorService
    │    mContext instance of com.salesforce.androidsdk.auth.AuthenticatorService
    │    ↓ AuthenticatorService$Authenticator.context
    │                                         ~~~~~~~
    ╰→ com.salesforce.androidsdk.auth.AuthenticatorService instance
    ​     Leaking: YES (ObjectWatcher was watching this because com.salesforce.androidsdk.auth.AuthenticatorService
    ​     received Service#onDestroy() callback and Service not held by ActivityThread)
    ​     Retaining 640 B in 8 objects
    ​     key = d37ee8bb-67b5-4501-82b7-bce297957eda
    ​     watchDurationMillis = 25262
    ​     retainedDurationMillis = 20259
    ​     mApplication instance of com.gg.nativeandroid.Application
    ​     mBase instance of android.app.ContextImpl
    
    METADATA
    
    Build.VERSION.SDK_INT: 26
    Build.MANUFACTURER: samsung
    LeakCanary version: 2.7
    App process name: com.gg.nativeandroid.uat
    Stats: LruCache[maxSize=3000,hits=1536,misses=39681,hitRate=3%]
    RandomAccess[bytes=1974802,reads=39681,travel=13270186035,range=11436088,size=14793008]
    Heap dump reason: user request
    Analysis duration: 58551 ms

any idea how this is happening ?

**Comment by bhariharan** [comment]
We do have a static instance of `AuthenticatorService` that we hold on to in our singleton state manager, `SalesforceSDKManager`. Even though this is flagged by this tool, it's a bit of a false positive. We need that for auth-related requests that can come in during some flows, like deferred authentication. I don't think it's a real leak.
