### ISSUE TITLE
App automatically closes after logging into the SF by clicking the allow button

### ISSUE THREAD

**Issue by Dinagar94** [forcedotcom/SalesforceMobileSDK-Android#2287]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.2.1
2. Issue found in Native App or Hybrid App: Native
3. OS Version: any version
4. Device: any device
5. Steps to reproduce: Login with some credentials and in the next page allow and deny button shown once I clicked the allow button the app automatically closes
6. Actual behavior: the app automatically closes after clicking the allow button in the login steps
7. Expected Behavior: the app should not be closed after clicking the allow button, it should be redirected inside my application for next activities
8. Error Log: No Error Log Found

**Comment by johnjeremih** [comment]
@Dinagar94 can you please share the implementation that you are using on the Application class and home activity? This will make it easier to identify the problem.

**Comment by gkotula** [comment]
Closing due to lack of OP response.
