### ISSUE TITLE
Android 12 Fingerprint and FaceID configuration

### ISSUE THREAD

**Issue by meeramanesh** [forcedotcom/SalesforceMobileSDK-Android#2289]
1. Version of Mobile SDK Used: 9.0.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Android 12
4. Device: Samsung Galaxy S20
5. Steps to reproduce:1)  show finger unlock screen with enable and cancel button to configure.
                                     2) Click Enable button. It will show two options: finger print, face.
                                     
               
6. Actual behavior: The user is opting Fingerprint to configure, where as both the options are displaying.
7. Expected Behavior: The user is opting Fingerprint to configure, only fingerprint should be displayed.
8. Error Log:

**Comment by brandonpage** [comment]
@meeramanesh Please update to the latest (Mobile SDK 10.0) as we have [completely rewritten the passcode system in 9.2.0](https://developer.salesforce.com/docs/atlas.en-us.noversion.mobile_sdk.meta/mobile_sdk/android_passcodes.htm).
