### ISSUE TITLE
OAUTH_DISALLOWED_SCOPES: the requested scope is not allowed

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Android#2290]
Please fill out the following details:

1. Version of Mobile SDK Used:  9.2.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version:
4. Device: All devices
5. Steps to reproduce: upgrading from version 9.0.0 to 9.2.0
6. Actual behavior:
I'm getting this error when login in
![image](https://user-images.githubusercontent.com/4177453/159788772-ff874f63-066a-4858-b98e-51e7948e2b19.png)
7. Expected Behavior:
I tried another app and it works fine, so I think that it is something in the connected apps, but no idea which option do I need to set up.
8. Error Log:

**Comment by wmathurin** [comment]
The scopes you request from the client (as defined in your bootconfig) need to match the scopes supported by the connected app.
Please review [this documentation](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/oauth_scope_parameter_values.htm) (and the surrounding pages) for more information.
