### ISSUE TITLE
Login Activity not falling back to app on back press and login success if   Sales force login activity is chosen from recent apps.

### ISSUE THREAD

**Issue by SanjivPatel2020** [forcedotcom/SalesforceMobileSDK-Android#2298]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.00 and 10.00 both
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: Android 11, 12
4. Device: Nokia 5.4, Pixel 5A 5G
5. Steps to reproduce:
> 1st Scenario
> - Start Sales Force Login Activity
> - Press Home button of device
> - Resume the Login Activity from Recent app
> - Press Back button

> 2nd Scenario
> - Start Sales Force Login Activity
> - Press Home button of device
> - Resume the Login Activity from Recent app
> - Enter credentials and perform login, on success it navigates to Device home screen instead of falling back to app's last screen.
> - When we tap on app icon it launches the app in logged in state but when we choose it from recent app it open the same login screen even though  user is logged in already. 

7. Actual behavior:

-  On Back press app it is navigating to device home screen instead of falling back to app's last screen when the login Sales force sdk login activity had been started from.
- On login success, it again navigates to device home screen instead of falling back to app. Also after login success, choosing from recent app it open the login page instead of logged in state app.

9. Expected Behavior:

- On Back press it should fallback to the app's screen where login page had been started from.
- On login success also it should fallback to the app' screen where login page has been started from.

11. Error Log: NA

**Comment by brandonpage** [comment]
Hi @SanjivPatel2020.  It sounds like your app is [deferring login](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/android_native_deferred_login.htm), is that correct?

**Comment by bhariharan** [comment]
@SanjivPatel2020 This is by design, in order to support a large matrix of login use cases. Apps can customize back button behavior by overriding [this method](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/dev/libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java#L270) in your app.
