### ISSUE TITLE
Performing CRUD operations on list of records in one transaction using forcereact. Major dependency

### ISSUE THREAD

**Issue by arshadaxolt** [forcedotcom/SalesforceMobileSDK-Android#2325]
How do i use react.force.net.js to perform CRUD with list of records, currently it only supports single at a time.

for example:
net.create('contact', {FirstName: 'test', LastName: 'test'});

it only allows me to create a single record.

I want to be able to create list of contacts at once.

Please assist on this or any alternative for perform bulk CRUD operations.

Thanks

**Comment by wmathurin** [comment]
Looks like a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/282.
Closing this one, we will track progress on the enhancement on the other one.
