### ISSUE TITLE
REST API fails after enabling Enhanced Domain

### ISSUE THREAD

**Issue by amuyeed** [forcedotcom/SalesforceMobileSDK-Android#2339]
Please fill out the following details:

1. Version of Mobile SDK Used: 10.1.0
2. Issue found in Native App or Hybrid App: Native app
3. OS Version: 6.0.1
4. Device: Samsung Tab E SM T377A
5. Steps to reproduce: 
     a) Login into the Org as a Community user with Enhanced Domain disabled. 
     b) Make REST API calls (works as expected). 
     c) Enable Enhanced Domain in the Org.
     d) Make REST API by interacting with the app
     e) Error is throw with 403 FORBIDDEN and sometimes with the HTML page source as the respone
6. Actual behavior: 403 FORBIDDEN and sometimes with the HTML page source as the respone
7. Expected Behavior: Either throw RefreshTokenRevoked Exception or 401 Unauthorized error.
8. Error Log:

**Comment by wmathurin** [comment]
Does it work if you logout the user (either in the mobile app or by revoking their refresh token from the server) then logs back in?

**Comment by amuyeed** [comment]
Hi Mathurin, the app doesn't have the logout functionality. the refresh token is set to "Never expired until revoked". If i revoke the token from server it does trigger Revoke Exception. We have another issue with relogin without application restart. On revocation, SDK logout API is called and the account is deleted. 
After logout, when we try to create a new account with new login credentials, unfortunately Webview fails to load. If i restart the application after revocation and create the account with new credentials it works.
Any suggestion would be much appreciated on how to do we trigger login flow without restarting the app.

**Comment by wmathurin** [comment]
In step 5 d) "Make Rest API by interactnig with the app", what end point are you hitting and how?

**Comment by amuyeed** [comment]
The user is a community user and communicates with the sever via Connected App. The data is exposed via RESTful API which are written in Apex classes. During login the scope is defined for Web, API and Refresh token.

**Comment by wmathurin** [comment]
Please check if the user profile has API access enabled. External users and community users have API access disabled by default.

**Comment by amuyeed** [comment]
It is enabled. Like i said application was working as expected until Enhanced Domain was enabled. The problem is with the HTML response and 403 code.

**Comment by amuyeed** [comment]
![image](https://user-images.githubusercontent.com/35420484/190430980-a5792537-0ac7-4f71-8a5a-e56ad61a952c.png)
Attached is screenshot for reference.

**Comment by bhariharan** [comment]
If it started failing after enhanced domains was enabled, it's most likely caused by an incorrect base URL for the REST request. Could you print out the base URL being used for the REST request you're making and verify if that's the correct community URL?

**Comment by amuyeed** [comment]
Hi Hariharan, the base URL is old community URL. I'm talking about the response code of the REST API. In SDK 7.0.0 when Enhanced Domain is enabled the REST API response would throw RefreshTokenRevokedException with HTTP response code of 401. However in the latest SDK, we don't see this exception because of which we cannot force logout the user.

**Comment by bhariharan** [comment]
@amuyeed This is because the behavior for `403` response code has changed within our REST API library between `7.0.0` and our most recent version. In the past we were treating `403` as a token revocation event. However, there are other scenarios where `403` might occur. Hence, we don't treat `403` as token revocation anymore, and we surface it to the app layer instead. At the app layer, you can call the `logout()` API for `403` in this scenario.
