### ISSUE TITLE
OAUTH_DISALLOWED_SCOPES: The requested scope is not allowed

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Android#2343]
Please fill out the following details:

1. Version of Mobile SDK Used:  9.2.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 12
4. Device:
Pixel 6a
5. Steps to reproduce:
When trying to log in
6. Actual behavior:
7. Expected Behavior:
8. Error Log:
<img width="437" alt="Screen Shot 2022-09-08 at 10 52 17 AM" src="https://user-images.githubusercontent.com/4177453/189154977-1d4f7cb3-80d4-4e3b-9f6a-658744df5048.png">

Any Idea on how to solve this ? On version 9.0.0 works fine

**Comment by wmathurin** [comment]
The scopes you request in your mobile application (defined in the bootconfig file) must match the one that were configured for the connected application on the server (or be a subset of the scopes the connected app has).
Could you check your bootconfig and your connected app settings?

**Comment by johnjeremih** [comment]
Thank you so much I forgot to add "web" on the oauthScopes
![image](https://user-images.githubusercontent.com/4177453/189227453-f1b6bee9-cee9-4a98-924f-5864e5eca09b.png)
