### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Android#2344]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.2.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Android 12
4. Device: Pixel 6a
5. Steps to reproduce: after I loging in I get the error on step 9. this is because "com.google.firebase:firebase-messaging" not being up to date.
6. Actual behavior:
7. Expected Behavior:
8. Error Log:
9. 
 ```
  Caused by: java.lang.IllegalArgumentException: com.mi.nativeandroid.dev: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
```

 Now, if I update it to the latest version of "com.google.firebase:firebase-messaging" "23.0.8" I get this error when logging out
` Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId" on path: DexPathList[[zip file "/data/app/~~0GwGhvsxeX9Aic0mngG80A==/com.programproductions.nativeandroid.dev-XtCj0A6S5hZ0UoiOI3rIkA==/base.apk"],nativeLibraryDirectories=[/data/app/~~0GwGhvsxeX9Aic0mngG80A==/com.programproductions.nativeandroid.dev-XtCj0A6S5hZ0UoiOI3rIkA==/lib/arm64, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)`

**Comment by bhariharan** [comment]
@johnjeremih The `PendingIntent` flags warning issue has been fixed [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2257). Please upgrade to the latest version of Mobile SDK to consume this fix. We don't support newer versions of `Firebase` at this time - please use the version that comes with Mobile SDK until we start supporting the newer version.

**Comment by johnjeremih** [comment]
@bhariharan it worked! thank you. I updated to version 10.1.1
