### ISSUE TITLE
PIN security not working for Android devices.

### ISSUE THREAD

**Issue by ruchiranavishka** [forcedotcom/SalesforceMobileSDK-Android#2345]
Please fill out the following details:

1. Version of Mobile SDK Used: 10.1.1
2. Issue found in Native App or Hybrid App: Android 
3. OS Version: Android 12
4. Device: Samsung s10+
5. Steps to reproduce: PIN security not working at app launch and all the other time. _Working fine on IOS_
6. Actual behavior: PIN Security not working for the sandbox
7. Expected Behavior: user should have a pin security prompt when launching the app
8. Error Log: no error logs.

**Comment by gkotula** [comment]
Hi @ruchiranavishka, sorry to hear you're having this issue.  Could you try a couple of troubleshooting steps to see if any of these fix the issue?

1. Log out and log back in to see if that gets the passcode to appear.
1. Log out and clear cache for the app, then try logging in again.
1. Reinstall the app and log in.

Please let us know if any of those things fix the issue, thanks!

**Comment by ruchiranavishka** [comment]
checked. Issue is there as the same. We have just enabled PIN protect from connected app settings. Do we have to enable anything from the android app? IOS working fine

**Comment by gkotula** [comment]
Hi, could you sanity check that both your Android and iOS connected apps have the same PIN settings?  Also, could you double check that the Android app is using the correct Android connected app client ID in the bootconfig?  That is a common source of confusion when setting up PIN settings between Android and iOS.

**Comment by ruchiranavishka** [comment]
yes all of those settings are same. And we are using reactnative sdk for the mobile sdk.

**Comment by ruchiranavishka** [comment]
Checked and all are the same as ios.

**Comment by gkotula** [comment]
Hi, apologies for taking a while to respond.  I was able to use `forcedroid create` to create a new native Android test project with `v10.1.1`, and upon first login to a connected app with PIN protect enabled the lock screen showed itself as expected.  

There are two things that should be checked:
1.  Can you confirm that a new project does or does not show the lock screen when using your connected app?
2. If a new project does _not_ show the lock screen with your connected app, try creating a new test connected app and enable PIN for that.

If a fresh project and/or a fresh connected app have PIN working, then it is likely an issue unrelated to the Mobile SDK.

**Comment by brandonpage** [comment]
@ruchiranavishka We fixed an issue that sounds exactly like what you are describing in Mobile SDK version 10.2.  Can you please check if they issue has been resolved?  Thanks

**Comment by wmathurin** [comment]
Closing for lack of response. Please re-open an issue if you are still having the problem.
