### ISSUE TITLE
Availability of source for com.salesforce.android per Gradle ref com.salesforce.service:servicesdk:224.2.3

### ISSUE THREAD

**Issue by HeinrichGlover** [forcedotcom/SalesforceMobileSDK-Android#2363]
Please fill out the following details:

1. Version of Mobile SDK Used:  10.1.1
2. Issue found in Native App or Hybrid App: Increase in size after reference is added
3. OS Version: 12
4. Device: Samsung Galaxy
5. Steps to reproduce: Add reference com.salesforce.service:servicesdk:224.2.3
6. Actual behaviour: the APK size increase by 18Mb after added the ref.
7. Expected Behaviour: Apk size would only increase by a couple 100kb
8. Error Log:  N/A

Is it possible for SalesForce to Share the source of com.salesforce.android. I would like to build it self and inject as a lib .aar for fixing the 18Mb increase in size.

**Comment by bhariharan** [comment]
This forum isn't for `ServiceSDK` issues, that happens to be a different Salesforce product.
