### ISSUE TITLE
Not able to compile the project with Salesforce Mobile SDK(version 8.0.0) for android

### ISSUE THREAD

**Issue by suhasmannarcs** [forcedotcom/SalesforceMobileSDK-Android#2368]
Please fill out the following details:

1. Version of Mobile SDK Used: com.salesforce.mobilesdk:SalesforceSDK:8.+
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: Android 7.0 (Nougat) and above
4. Device:
5. Steps to reproduce: Not able to compile the android project 
6. Actual behavior: Getting the error "Could not resolve com.salesforce.mobilesdk:SalesforceSDK:8.+." during compilation of the project
7. Expected Behavior: The project has to compile properly
8. Error Log:   Execution failed for task ':app:dataBindingMergeDependencyArtifactsNonProdDebug'. 
                        > Could not resolve all files for configuration ':app:nonProdDebugCompileClasspath'.   
                        > Could not resolve com.salesforce.mobilesdk:SalesforceSDK:8.+.      
                        Required by:          
                        project :app       
                        > Skipped due to earlier error

**Comment by brandonpage** [comment]
All Mobile SDK 8.X versions are over two years old.  Please upgrade to the latest.  Only major versions (9.0.0 and 10.0.0) contain breaking changes, of which there are very few.
