### ISSUE TITLE
Retrigger Firebase registration on failure  

### ISSUE THREAD

**Issue by sidrabasit** [forcedotcom/SalesforceMobileSDK-Android#2369]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.0.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Android 10
4. Device: Samsung Galaxy A9
5. Steps to reproduce: 
Login to the application 
6. Actual behavior:
 Sometimes token registration fails
7. Expected Behavior: 
Is there a way from the SDK to retrigger the Firebase registration if token registration fails? 
8. Error Log:

**Comment by sidrabasit** [comment]
Please can you provide any update on this.
If you need any other information, let us know.

**Comment by gkotula** [comment]
Hi @sidrabasit, getting the error logs from Logcat would greatly help us in diagnosing this issue.

**Comment by gkotula** [comment]
@sidrabasit Could you try upgrading your Mobile SDK version to the latest and see if that resolves your issue?

**Comment by sidrabasit** [comment]
@gkotula  A token registration failure is not a problem since it does not happen every single time. If token registration fails, we would like to know if it can be retriggered.

**Comment by gkotula** [comment]
@sidrabasit We are planning on updating the Firebase libraries with our next major release, and that may fix this issue.  We will keep this issue in mind when implementing it, and we will circle back to you when it is released to see if we need to investigate further.

In the meantime, when your app detects that the Firebase registration has failed, you can call `PushMessaging.register(Context, UserAccount)` to manually retry the registration.

**Comment by sidrabasit** [comment]
Thanks we were able to fix the issue by invoking  PushMessaging.register(Context, UserAccount) method

**Comment by gkotula** [comment]
Glad to hear you could find a resolution!  Closing this as completed.
