### ISSUE TITLE
How to get Mobile Number from Sales Force SDK in Android

### ISSUE THREAD

**Issue by abhiforgithub** [forcedotcom/SalesforceMobileSDK-Android#2373]
Please fill out the following details:

1. Version of Mobile SDK Used:    com.salesforce.mobilesdk:SalesforceSDK:8.+
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 
4. Device: Redmi Note 5 pro
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:

**Comment by gkotula** [comment]
Salesforce Mobile SDK GitHub issues are for reporting bugs, errors, undesirable behavior, etc.  GitHub issues are not the correct place to ask "how-to" questions like this.  I recommend asking this question on the [Salesforce Stack Exchange](https://salesforce.stackexchange.com/search?q=salesforcemobilesdk%5D)
