### ISSUE TITLE
Soft logout feature in Salesforce mobile SDK

### ISSUE THREAD

**Issue by sidrabasit** [forcedotcom/SalesforceMobileSDK-Android#2374]
Please fill out the following details:

1. Version of Mobile SDK Used: 9.0.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Android 13
4. Device: Samsung Galaxy Note 20
5. Steps to reproduce: 
1. Login to the application
2. Enables biometric unlock
3. Logout of the application
4. Click on the Login button again
5. The user has to enter the user name and password again
6. Actual behavior: Currently, when we logout a user using SDK’s methods, all his details are removed from the app and only way to login is by entering credentials into webview.
7. Expected Behavior: User should be able to see the screen with username/ID and authenticate using biometric to login back like many banking applications support this way of login. Screenshot attached
8. Error Log:
![Screenshot_20221223_145340](https://user-images.githubusercontent.com/56905994/209324076-e9ed2813-37db-4b09-9cd5-2ff7d6ff7599.png)

**Comment by bbirman** [comment]
This is currently working as designed, appreciate the feedback for future enhancements!

**Comment by wmathurin** [comment]
The feature (soft logout / biometric authentication) is coming in our next version of Mobile SDK (11.0) scheduled for late spring or early summer.
It's already implemented in dev (see https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2394).
