### ISSUE TITLE
Loading indicator when login page is loading in webview

### ISSUE THREAD

**Issue by sidrabasit** [forcedotcom/SalesforceMobileSDK-Android#2375]
1. Version of Mobile SDK Used: 9.0.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Android 13
4. Device: Samsung Galaxy Note 20
5. Steps to reproduce: 
1. Tap the login button in the application.
2.  A slight delay occurs when loading the login screen in the webview.
3.  A blank screen appears during this delay.
6. Actual behavior:
There is a slight delay when the login page is loading in the webview. During this time, there is no indication that the screen is loading.
7. Expected Behavior:
While the login page is loading in the webview, the user should be able to see a loading indicator. Let us know if there is any method we can override to show a loading indicator.
8. Error Log:

**Comment by sidrabasit** [comment]
Please can you provide any update on this.
If you need any other information, let us know.

**Comment by wmathurin** [comment]
The fix will be in our next release (see https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2425).
