### ISSUE TITLE
Text on live chat close dialog is unreadable

### ISSUE THREAD

**Issue by leewapadmi** [forcedotcom/SalesforceMobileSDK-Android#2381]
1. Version of Mobile SDK Used: **4.3.4**
2. Issue found in Native App or Hybrid App: **Native**
3. OS Version: **Android 13**
4. Device: **Pixel 5 (emulator)**
5. Steps to reproduce: **Open a salesforce live chat window with an agent, minimize the window, and click 'X' to dismiss, bringing up a dialog to confirm the user wants to end the chat session.**
6. Actual behavior: **Text on dialog buttons is white on a white background, making it very difficult to read**
7. Expected Behavior: **Text on dialog buttons should be easily legible for users**
8. Error Log: N/A

See screenshot
![Screenshot 2023-01-24 at 14 41 28](https://user-images.githubusercontent.com/115650324/214328304-5b64451f-04aa-4c30-9dcf-b79ac14d92f4.png)

NB: This bug is not resolved by modifying the Salesforce UI colors in the XML resources. This appears to have no effect on the dialog.

**Comment by bhariharan** [comment]
Live Chat is a different product from the Salesforce Mobile SDK. Please open a case with Salesforce Support for Live Chat issues.
