### ISSUE TITLE
Allow Authorisation Code and Credentials Flows

### ISSUE THREAD

**Issue by nzsrini** [forcedotcom/SalesforceMobileSDK-Android#2387]
Please fill out the following details:

1. Version of Mobile SDK Used:  10.2.0
2. Issue found in Native App or Hybrid App:Native
3. OS Version: IOS 16
4. Device:
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:

Do we need to enable : **Allow Authorisation Code and Credentials Flows** for Identify provider functionality with connected apps?

**Comment by gkotula** [comment]
Hi @nzsrini, it is a little unclear to me what exactly you are trying to achieve.  I see you mention Identity Providers, and we have an entire suite of help articles about IDP:  https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/auth_identity_providers.htm .

**Comment by nzsrini** [comment]
Thanks for the documentation.

**Comment by nzsrini** [comment]
We have figured the issue after going through the documentation.
