### ISSUE TITLE
Flutter can't receive response from the ChatFeedActivity on SDK side after integrate with SDK version 224.2.3

### ISSUE THREAD

**Issue by kullawattana** [forcedotcom/SalesforceMobileSDK-Android#2390]
**1. Version of Mobile SDK Used:** com.salesforce.service:servicesdk:224.2.3, com.salesforce.mobilesdk.SalesforceSDK:9.2.0
from https://github.com/forcedotcom/ServiceSDK-Android
**2. Issue found in Native App or Hybrid App:** I have to integrate SDK with the flutter platform by method channel and build a release version to test it. Since I started SDK, ChatFeedActivity is nullPointerException and not responding. Flutter can't receive a response from the SDK.
**3. OS Version:** Android 13
**4. Device:** Samsung Galaxy A71
**5. Steps to reproduce:** I have to build debug version its works fine, but I have to make a release version it's not working. It can't start ChatFeedActivity is not responding on the release version. I am not sure possible to require who flutter specializes in resolving this issue.
**6. Actual behavior:** I can make a debug version.
**7. Expected Behavior:** I want to make a release version with compatible flutter. and please help check we wonder if Salesforce SDK not working when building the application package via Flutter obfuscate code or not. 
**8. Error Log:**

**Null pointer exception** 
![null pointer exception](https://user-images.githubusercontent.com/3391151/225207949-8af365ce-abd0-43c8-9dce-597f78feea0e.png)

**Waiting time for rendering by ChatFeedActivity until error**
![Runtime error](https://user-images.githubusercontent.com/3391151/225207976-adde642e-0c31-414d-a20b-97a0c382c76e.png)

@[colinmacdonald](https://github.com/forcedotcom/ServiceSDK-Android/commits?author=colinmacdonald)

**Comment by paultiarks** [comment]
@kullawattana This actually looks like an issue with the ServiceSDK, which is a different Salesforce product which is not supported in this repo. Can you go through help.salesforce.com to get your issue with the ServiceSDK addressed?
