### ISSUE TITLE
Not an issue: how to enter login information on the login screen to test the app with expresso.

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Android#2391]
how to enter login information on the login screen to test the app with expresso. I want to test the app with a UI test, but I don't know how to do that. any ideas? I thought about using a fake API with Postman, but I don't know if there is a better way. How do you guys do automation testing?

**Comment by paultiarks** [comment]
@johnjeremih There isn't currently a solution in place for this. 

You can see in our integration tests a refresh token is provided via test_credentials.json to bypass the login screen. We also have UI tests that actually login. Both of those solutions use actual network requests, though, and it sounds like you're looking for an offline test which does not actually hit the network.

**Comment by wmathurin** [comment]
Closing the issue. Hopefully the responses above gave you some ideas.
For "How do I do ..." questions, please post on our [stackexchange](https://salesforce.stackexchange.com/) and tag mobilesdk.
