### ISSUE TITLE
In Android Tablet : When external browser authentication setting is turned on and user tries to log in, allow authorization screen is visible repeatedly

### ISSUE THREAD

**Issue by meta-krishna-meghwal** [forcedotcom/SalesforceMobileSDK-Android#2413]
Please fill out the following details:

1. Version of Mobile SDK Used: 10.2
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: MacOS Ventura
4. Device: Android Tablet (Target SDK 33)
5. Steps to reproduce:

-  At My Domain Settings in salesforce, check the check box for login through external browser
- Open app and change server
- Add new connection 
- Add  org URL and apply
- Tap on back button and User will automatically redirected to login screen in external browser
- Login and tap on allow  
-
6. Actual behavior: After tapping on Allow user get redirected to app screen and then instantly gets redirected back to allow authorization screen and after tapping on allow again it show  inavalid client id error
7. Expected Behavior: User should not get redirected to allow authorization screen

This behaviour is specific to the Android Tablet, In Android Phone it is working fine.
![Screenshot_20230530-132301_Chrome](https://github.com/forcedotcom/SalesforceMobileSDK-Android/assets/79202243/b180676c-5221-43be-97f8-19d52b6f4a95)

**Comment by point8290** [comment]
It is not selected.

**Comment by meta-krishna-meghwal** [comment]
"Require Secret for Web Server Flow." checkbox is not selected.

**Comment by wmathurin** [comment]
Does it fail across the board or only for some users? What kind of users are you trying to login with?

**Comment by meta-krishna-meghwal** [comment]
It fails across the board, I have tried it with Standard Platform User, System Administrator User.

**Comment by wmathurin** [comment]
Thanks for the info, but the same app / configuration etc works from a different device (phone)?

**Comment by meta-krishna-meghwal** [comment]
Yes, It is working on Phone, the issue is specific to Android Tablet.

**Comment by wmathurin** [comment]
We have just released Mobile SDK 11.0. Among other changes, we now use Web Server Flow (with PKCE) for advanced authentication. Please git it a try and re-open an issue if you are still having problems.
