### ISSUE TITLE
After the user logs out app takes more than two minutes to load the login page.

### ISSUE THREAD

**Issue by NewTech2000** [forcedotcom/SalesforceMobileSDK-Android#2426]
1. Version of Mobile SDK Used:  10.2.0
2. Issue found in Native App or Hybrid App: Hybrid App (React-native-salesforce)
3. OS Version: Android 12.0
4. Device: All Andriod Devices
5. Steps to reproduce: log out from the app, and log out from the auth.
6. Actual behavior: After the user logout from the app takes more than two minutes to load the login page, within two minutes it displays an empty dark screen after that appear the logging page after two minutes. this issue is only in the Android app.
7. Expected Behavior: After the user logout from the app, the logging page should be visible to the user as soon as possible (within 3 or 4 seconds)
8. Error Log: no error logs

**Comment by wmathurin** [comment]
We have not observed slow logouts in any of our apps or orgs. 
Are you still having the issue? Is it happening all the time or occasionally?

**Comment by NewTech2000** [comment]
Now it is happening occasionally

**Comment by wmathurin** [comment]
Closing - the occasional slowness if it is still happening is a server side issue we cannot address from a client side library.
