### ISSUE TITLE
Clear Locations won't pass Null but Keeps the existing Values in Geo Location Fields.

### ISSUE THREAD

**Issue by ruchiranavishka** [forcedotcom/SalesforceMobileSDK-Android#2445]
Please fill out the following details:

1. Version of Mobile SDK Used:  10.1.1 and 10.2.0
2. Issue found in Native App or Hybrid App: Hybrid app
3. OS Version: 12.0.0 
4. Device: All android devices
5. Steps to reproduce: When clearing location fields, passing Null value to a already existing values on Geo coordinates.
6. Actual behavior: When clearing locations the form field value should be empty when passing null instead it keeps the existing values. This worked as expected in SDK for IOS.
7. Expected Behavior: Empty the geo coordinates when lat long fields set to Null.
8. Error Log: No error logs .But Form field Lat Long won't pass the value when set to Null. Same scenario goes with Double values.

**Comment by brandonpage** [comment]
Hi @ruchiranavishka can you please further explain what exactly you are doing?  The Mobile SDK does not maintain a location field on user account or any other native object.  Is the issue that you are trying to send null for a location value on a rest call?  If so what is the endpoint?

**Comment by ruchiranavishka** [comment]
We are sending it through smartstore. See

export const saveInSoup = (data, soupName, idPath = defaultIdPath) =>
  new Promise((resolve, reject) => {
    smartstore.upsertSoupEntriesWithExternalId(
      storeConfig,
      soupName,
      data,
      idPath,
      (res) => resolve(res),
      (err) => reject(err)
    );
  });

data = Object fields form with values. Where Location field set to Null

**Comment by wmathurin** [comment]
That is odd because upsert does not do a merge between old record and the provided one, it simply replaces the old record with the provided one. Could it be that the external id / external id path does not match the existing record, causing the upsert to actually create a new entry?

**Comment by wmathurin** [comment]
Could you inspect the store to see what is happening? You can use the [SmartStore inspector](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/offline_inspector.htm) for that.

**Comment by wmathurin** [comment]
Closing for lack of response from customer.

**Comment by NewTech2000** [comment]
Hi @wmathurin, the issue same as @ruchiranavishka posted. When clearing the Location field value should be empty when passing null instead it keeps the existing values. This worked as expected in SDK for IOS

**Comment by NewTech2000** [comment]
@wmathurin Any update regarding this issue ?

**Comment by wmathurin** [comment]
Closing for lack of details.
If you are still struggling with the same issue, please open a new issue.
What is that location field? Are you referring to [custom geo location field](https://help.salesforce.com/s/articleView?id=platform.custom_field_geolocate_overview.htm&type=5)? How are you setting it to null? Are you using Mobile Sync?
