### ISSUE TITLE
Native App Authentication Fails - invalid_client:invalid client credentials

### ISSUE THREAD

**Issue by akshayajeevan** [forcedotcom/SalesforceMobileSDK-Android#2468]
We have created a new android native app with SDK v11.0.1 using forcedroid to replace our forcehybrid app. The app fails when user submits username & password with error message - invalid_client:invalid client credentials
The connected app details - consumer key, callback uri, scopes are all set correctly.

Can you please help us with this error.

Please fill out the following details:

1. Version of Mobile SDK Used: 11.0.1
2. Issue found in Native App or Hybrid App: Native
3. OS Version: Android 10
4. Device: OnePlus
5. Steps to reproduce: Create a native app project using forcedroid. Update bootconfig.xml and servers.xml
6. Actual behavior: Standard Login failed with error message - `invalid_client:invalid client credentials`
The token request is failing with `status code 400`
7. Expected Behavior: Successful standard login
8. Error Log:
```
Exception occurred while making token request
com.salesforce.androidsdk.auth.OAuth2$OAuthFailedException: invalid_client:invalid client credentials
   at com.salesforce.androidsdk.auth.OAuth2.makeTokenEndpointRequest(OAuth2.java:409)
   at com.salesforce.androidsdk.auth.OAuth2.exchangeCode(OAuth2.java:289)
   at com.salesforce.androidsdk.ui.OAuthWebviewHelper$CodeExchangeEndpointTask.doInBackground(OAuthWebviewHelper.java:642)
   at com.salesforce.androidsdk.ui.OAuthWebviewHelper$CodeExchangeEndpointTask.doInBackground(OAuthWebviewHelper.java:630)
   at android.os.AsyncTask$3.call(AsyncTask.java:378)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
```

**Comment by wmathurin** [comment]
Starting in 11.0, Salesforce Mobile SDK uses Web Server Flow by default. Before it was using User Agent flow.
You have to make sure the “Require Secret for Web Server Flow” checkbox is deselected in your connected app.
Alternatively you can opt out and keep using User Agent flow.

For more information: https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/oauth_web_server_flow.htm

**Comment by akshayajeevan** [comment]
@wmathurin - Deselecting the “Require Secret for Web Server Flow” checkbox in the connected app fixed this issue.
Thank you so much for quick help.
