### ISSUE TITLE
how to override click event in slaesforcebutton ? like ChatendsessionAlertDialog click event 

### ISSUE THREAD

**Issue by ramasamy11** [forcedotcom/SalesforceMobileSDK-Android#2473]
Please fill out the following details:

1. Version of Mobile SDK Used: 
2. Issue found in Native App or Hybrid App:
3. OS Version:
4. Device:
5. Steps to reproduce:
6. Actual behavior:
7. Expected Behavior:
8. Error Log:

**Comment by wmathurin** [comment]
This forum isn't for ServiceSDK issues, that happens to be a different Salesforce product.
