### ISSUE TITLE
overlay screen not getting removed and is stuck after sdk upgrade to 11.1.0

### ISSUE THREAD

**Issue by hitesh-baid** [forcedotcom/SalesforceMobileSDK-Android#2489]
Please fill out the following details:

1. Version of Mobile SDK Used:  11.1.0
2. Issue found in Native App or Hybrid App: React Native 
3. OS Version: Android version 13
4. Device: Google Pixel 7a
5. Steps to reproduce: upgrade to sdk and try running the app with mobile sync explorer.
6. Actual behavior: The overlay screen and permission is not getting removed, stays on the screen
7. Expected Behavior: The overlay warning/message should go away or should be closed.
8. Error Log:
<img width="337" alt="Screenshot 2023-11-10 at 7 43 54 PM" src="https://github.com/forcedotcom/SalesforceMobileSDK-Android/assets/141221195/1fbe96cc-317d-46f0-b798-d73a93cfbde0">

After investigating the code seems like the message is coming from shouldAskOverlayPermission() method in class SalesforceReactActivity.java, after removing this check and testing locally the app works fine.

**Comment by wmathurin** [comment]
In debug build, you need to grant overlay permission to your application.
Go to Setting --> Select Apps ---> Special App Access ---> Display over other apps ---> Pick you app and enable "Allow display over other apps"

**Comment by hitesh-baid** [comment]
Tried that but the app is not coming under the special app access list

**Comment by wmathurin** [comment]
Could you try again with the latest version of Mobile SDK (12.0) that was just released?

**Comment by wmathurin** [comment]
Please re-open, if you can reproduce the issue with the latest Mobile SDK (12.0.1). We are unable to repro it here.
