### ISSUE TITLE
Android device authentication

### ISSUE THREAD

**Issue by ryukooo** [forcedotcom/SalesforceMobileSDK-Android#2498]
I posted it on the Trailblazer Community, but I'll also post it here.
https://trailhead.salesforce.com/ja/trailblazer-community/feed/0D54V00007StX3hSAF
Please fill out the following details:

1. Version of Mobile SDK Used: 11.0.1
2. Issue found in Native App or Hybrid App:Native
3. OS Version:14
4. Device:Pixel 7
5.Steps to reproduce:
I am using SalesforceMobileSDK-AndroidV11.0.1,
Enable connected application lock on Android 14,
I think that the device authentication starts after logging in on the Android device.
If you close the application from the application history and start it up, the device authentication may not start up sometimes.
6. Actual behavior:
Sometimes the lock screen does not appear and transitions to the application
7. Expected Behavior:
I would like to improve this as it is a security issue.Do you have any knowledge?
The same thing happened with the Salesforce Android app, but if the unlock screen did not appear, the Salesforce logo screen was displayed and the process did not proceed.
Is there a way to get if the same is unlocke
8.Error Log:
Attached is the occurrence screen for the Salesforce app distributed on the Store.
![Screenshot_20231205-155539 (1)](https://github.com/forcedotcom/SalesforceMobileSDK-Android/assets/28751562/a7be4c70-32e3-4f75-b3b5-fa33452197df)

**Comment by ryukooo** [comment]
Thankyou @brandonpage,
>When you say "Enable connected application lock" do you mean the "Implements Screen Locking & PIN Protection" Connected App option? And does the issue not occur if that option is deselected?
yes. Occurs only if enabled.
>Is the login page you are using the standard Android webview or advanced authentication via a Chrome Custom Tab?
This will be the standard Android web view.
>How frequently does this happen?
Occurs in about 1 minute

We apologize for the inconvenience, but please check.

**Comment by brandonpage** [comment]
Hi @ryukooo, is there any additional information you can provide about this?  If you can reproduce this in a Mobile SDK app you have built can you provide debug logs produced by the SDK?  Is there anything else special about this setup?  Have you disabled biometric or the device screen lock?  

I have been trying on and off to reproduce this over the last several weeks on Pixel 6 Pro, Fold and 8 Pro but haven't seen it once.

**Comment by brandonpage** [comment]
I was never able to reproduce this issue.
