### ISSUE TITLE
Header Display Issue after Updating SDK to 11.0.1 on Android

### ISSUE THREAD

**Issue by TamirYakov1** [forcedotcom/SalesforceMobileSDK-Android#2500]
Hi there,

Recently, I updated the SDK version of my Android application to 11.0.1, and I encountered an unexpected issue. Following the update, a URL header appeared above my login page, which was not present before.

In my AndroidManifest.xml file, I have the following code:

```
<activity
            android:name="com.salesforce.androidsdk.ui.LoginActivity"
            android:theme="@style/Theme.AppCompat.NoActionBar"
            tools:replace="android:theme" />

```

Previously, this code helped in hiding the URL header. However, after the update, it seems ineffective, and the header persists. Notably, this issue is observed on certain Android devices, such as Samsung Galaxy A20 and Samsung Galaxy S20, and potentially more devices.

I have not tested it on other devices, but I suspect the problem may be more widespread.

Any insights or suggestions on resolving this issue would be greatly appreciated.

Thank you.

**Comment by wmathurin** [comment]
Before we dig further, could you try the latest version of the Mobile SDK (11.1) ?

**Comment by TamirYakov1** [comment]
sorry for my typo.
Im using 11.1.0
@wmathurin

**Comment by brandonpage** [comment]
@TamirYakov1 What version did you come from?  10.x or 11.0? 

We updated the LoginActivity to a extend `AppCompatActivity` in 11.0, that could be the source of theming changes.

**Comment by TamirYakov1** [comment]
I updated from 10.x

**Comment by TamirYakov1** [comment]
Hi, any updates?

**Comment by wmathurin** [comment]
We just released Mobile SDK 12.2. Could you try and see if the issue has been resolved?

**Comment by TamirYakov1** [comment]
solved.
Thank you

**Comment by srdr-ppi** [comment]
@TamirYakov1, I wonder using v12.2.0 and including following in your Android Manifest fixes the issue?
```
<activity
            android:name="com.salesforce.androidsdk.ui.LoginActivity"
            android:theme="@style/Theme.AppCompat.NoActionBar"
            tools:replace="android:theme" />
```

I'm doing the same thing and still seeing the toolbar/header in LoginActivity. I wonder if you guys are doing some extra things to avoid header?
