### ISSUE TITLE
invalid_client:invalid client credentials

### ISSUE THREAD

**Issue by johnjeremih** [forcedotcom/SalesforceMobileSDK-Android#2502]
Please fill out the following details:

1. Version of Mobile SDK Used: 11.1.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 12
4. Device: Pixel 6a
5. Steps to reproduce: I just updated it to version 11.1.0 from 10.0.0
6. Actual behavior:
7. Expected Behavior:
I want to be able to log in 
8. Error Log:

![image](https://github.com/forcedotcom/SalesforceMobileSDK-Android/assets/4177453/7228bd98-322f-4ebf-82fb-76949517fa63)

**Comment by brandonpage** [comment]
Hi @johnjeremih, is this issue reproducible for you?  Or a one off occurrence?  It seems very odd as an `invalid client credentials` error on token exchange implies that the server gave us the wrong credentials.  

As a potential temporary workaround (and datapoint to help diagnose what is happening) please try [opting out of the new Web Server Flow](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/oauth_web_server_flow.htm) and report the results.

**Comment by johnjeremih** [comment]
I reverted back and I updated the gradle to 34 and then updated the SDK and now I'm getting this error
![image](https://github.com/forcedotcom/SalesforceMobileSDK-Android/assets/4177453/f3144fd5-cba7-4013-869b-f6ac79a731a3)

**Comment by brandonpage** [comment]
Where does that code exist?  I don't think our SDK uses `SupportSQLiteDatabase`.

**Comment by brandonpage** [comment]
I believe deselecting the `Require Secret for Web Server Flow` box fixes the original issue.  If not we reopen this issue.

**Comment by johnjeremih** [comment]
@brandonpage For some reason it is conflicting with my database class
<img width="942" alt="image" src="https://github.com/forcedotcom/SalesforceMobileSDK-Android/assets/4177453/3e1cafce-9137-4a55-95d3-56263cdda266">
