### ISSUE TITLE
How to access Custom Attributes in Android

### ISSUE THREAD

**Issue by nzsrini** [forcedotcom/SalesforceMobileSDK-Android#2503]
Please fill out the following details:

1. Version of Mobile SDK Used: 11.1.0
2. Issue found in Native App or Hybrid App:Native APP

In IOS we acesss the custom attribute using the following method UserAccountManager.shared.currentUserAccount?.idData.customAttributes?["xx"]
Please can you help us how to access customAttribute in Android?

**Comment by wmathurin** [comment]
Custom attributes are captured from the id service response [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/dev/libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java#L518).
They are saved as preferences [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/dev/libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.kt#L961).

To get a custom attribute simply call `getPref` on `AdminSettingsManager`.
```kotlin
SalesforceSDKManager.getInstance().adminSettingsManager.getPref(customAttributeKey, userAccount);
```
