### ISSUE TITLE
issue Android screen  after login 

### ISSUE THREAD

**Issue by alexanderak-bbd** [forcedotcom/SalesforceMobileSDK-Android#2536]
![Screenshot 2024-04-01 at 9 13 56](https://github.com/forcedotcom/SalesforceMobileSDK-Android/assets/154340682/343750e6-634f-4008-9062-65405ffefbbe)
Please fill out the following details:

1. Version of Mobile SDK Used:  11.1.0
2. Issue found in Native App or Hybrid App:  Hybrid App
3. OS Version: android 
4. Device:   samsung
5. Steps to reproduce: after login to the app 
6. Actual behavior:   show screen black screen with get post delet api and scroll tabs 
7. Expected Behavior: show regular screen  screen 
8. Error Log:

**Comment by wmathurin** [comment]
RestExplorer is a sample app contained within the Mobile SDK repository that we use for testing.  Unfortunately, Android Studio lists the run configuration for all apps within the project by default.  All you need to do is change the configuration  to "app" to run your generated app.

For more details see https://trailhead.salesforce.com/trailblazer-community/feed/0D54V00007bLWiCSAW
