### ISSUE TITLE
Jetifier requirement should be removed

### ISSUE THREAD

**Issue by mig35** [forcedotcom/SalesforceMobileSDK-Android#2544]
Hey, I'm not entirely sure if I used the corrected project, but if not - give me the correct link where to write.

We try to optimize the build time and we find out that `com.salesforce.service:chat-ui:4.3.6` (the latest version) is still using `com.android.support:support-annotations:28.0.0`. correct replacement should be from androidx library.

<img width="1020" alt="Screenshot 2024-04-05 at 11 17 41" src="https://github.com/forcedotcom/SalesforceMobileSDK-Android/assets/5335395/927f6f92-30ab-4ae8-ad55-33fa5990b7e8">

Please fill out the following details:

1. Version of Mobile SDK Used: com.salesforce.service:chat-ui:4.3.6
2. Issue found in Native App or Hybrid App: native
3. OS Version: Android
4. Device: any
5. Steps to reproduce: see above details
6. Actual behavior: outdated support-annotations is used
7. Expected Behavior: androidx library should be used
8. Error Log:

**Comment by wmathurin** [comment]
This isn't the right forum for ServiceSDK issues - that is a different product. Please open an investigation with Salesforce.
