### ISSUE TITLE
Upgrade by adding new fields to  usestore.json & usersyncs.json

### ISSUE THREAD

**Issue by nzsrini** [forcedotcom/SalesforceMobileSDK-Android#2578]
Please fill out the following details:

1. Version of Mobile SDK Used: 11.1.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version:
4. Device:
5. Steps to reproduce:
    Upgraded issue: 
We added a new field to usestore.json and usersynch.json during the app upgrade. How can we update usersynch and usestore to reflect this change in the local database without requiring users to re-log in? This will ensure that the new field and data are visible in the local database through the store.

Any recommended methodologies ?

7. Actual behavior:
8. Expected Behavior:
9. Error Log:

**Comment by wmathurin** [comment]
There is no automatic upgrade. If you change the userstore.json and/or usersync.json, it will only take effect on newly logged in users. In other cases, you need to programmatically do the upgrade.

Here are the recommended steps:
- update userstore.json and usersyncs.json,
- after your call to setupUserStoreFromDefaultConfig, check your soups with [getSoupIndexSpecs](https://developer.salesforce.com/docs/platform/mobile-sdk/guide/offline-soup-retrieve-index-specs.html), and programmatically adjust them using [alterSoup](https://developer.salesforce.com/docs/platform/mobile-sdk/guide/offline-soup-change-index-specs.html),
- after your call to setup setupUserSyncsFromDefaultConfig, check your syncs, if outdated, delete them and recreate them by calling setupUserSyncsFromDefaultConfig again.

**Comment by ghamuirev** [comment]
Hey, cheers for that reply.
So we have reIndexed the soup store which is great, however we don't fully understand how to check our sync target content... and thus how to conditionalise the deletion of a syncName.
We see that there are SyncManager api's for getting the status, existence and deletion of a sync, but no way to check its query or fieldlist - and thus if the current config version contains this added field or not.

Is there something we are missing in order for us to determine if the sync in then config is outdated?

**Comment by wmathurin** [comment]
If the sync is not running and your code does not invoke syncs by id then it won't hurt deleting it and recreating it (even if it has not changed). So for the syncs, you could just delete the syncs that changed in usersyncs.json before calling setupUserSyncsFromDefaultConfig. 

You could add some kind of version number statically defined in the code but also saved to a user preference file to drive your upgrade logic.

**Comment by ghamuirev** [comment]
Ok thanks for the help, really appreciate it!
