### ISSUE TITLE
Token request error: invalid_grant:cannot perform hybrid grant with jwts enabled

### ISSUE THREAD

**Issue by LuoShao** [forcedotcom/SalesforceMobileSDK-Android#2590]
Please fill out the following details:

1. Version of Mobile SDK Used: 11.0.1
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 14
4. Device: Huawei P20
5. Steps to reproduce: After clicking the login button, token error
6. Actual behavior: Token request error
7. Expected Behavior: Successfully entered the app
8. Error Log: Token request error: invalid_grant:cannot perform hybrid grant with jwts enabled

<img width="383" alt="Screenshot 2024-07-03 at 15 32 42" src="https://github.com/forcedotcom/SalesforceMobileSDK-Android/assets/20217641/5566d022-4200-46af-9cfd-334c331b1e0e">
<img width="357" alt="Screenshot 2024-07-03 at 15 33 03" src="https://github.com/forcedotcom/SalesforceMobileSDK-Android/assets/20217641/02248da8-99c3-4544-a89d-8efd69ccf443">

**Comment by LuoShao** [comment]
In the connect app, select JWT-Based Access Token Settings for Named Users

**Comment by brandonpage** [comment]
@LuoShao I am able to reproduce this issue, despite the fact that my connected app configuration is correct.  This appears to be a regression on the server that is unfortunately out of our control.  

I will reach out to the Authentication team internally, but if this is a blocking issue for you I suggest you contact Salesforce support through the standard channels as the issue may be resolved more quickly that way.

**Comment by brandonpage** [comment]
@LuoShao Apologies for not getting back to you sooner.  In case you have not resolved this, the server does not yet support Hybrid auth codes with JWT-based access tokens.  For the time being please set `useHybridAuthentication` (or `setUseHybridAuthentication` in Java) to `false` in SalesforceSDKManager _or_ configure your connected app to use the standard opaque access tokens if you need a hybrid code.
