### ISSUE TITLE
After Adding SalesforceSDKManager.getInstance().setUseWebServerAuthentication(false) App stays white screen on Offline App launch

### ISSUE THREAD

**Issue by NewTech2000** [forcedotcom/SalesforceMobileSDK-Android#2591]
Please fill out the following details:

1. Version of Mobile SDK Used: 12.0.0
2. Issue found in Native App or Hybrid App: Hybrid app
3. OS Version: 10
4. Device: Huawei Nova 5t
5. Steps to reproduce: add this configuration to the Main application.java `SalesforceReactSDKManager.getInstance().setUseWebServerAuthentication(false);` launch the app without logging and offline mode.
6. Actual behavior: when adding this configuration in MainApplication.java File `SalesforceReactSDKManager.getInstance().setUseWebServerAuthentication(false);` when launching the app offline the app stays on the white screen without any action. without adding this line the logging is not working and when the user inputs the user name and password the user will again be redirected to the logging page with the authentication fail message.
7. Expected Behavior: The User Should navigate to the logging page or another offline error screen without staying on a white screen. currently, we are handling that state from our React native code but now it is not working.
8. Error Log: No Error Logs

**Comment by brandonpage** [comment]
Please test this scenario again, I see the same "Webpage is not available" either way.  

Wether the app uses the User Agent flow or the Web Server flow has no impact on how the login page is rendered.

**Comment by NewTech2000** [comment]
@brandonpage After Adding SalesforceReactSDKManager.getInstance().setUseWebServerAuthentication(false); to the MainApplication.java file.

steps to reproduce 
Could you add the above code configuration to the MainApplication.java file
and close the app?
relaunch the app turn off your data and wifi connection.
the app stays on a white screen and shows the "Should authenticate but offline cannot proceed" message.

![Screenshot_1720461478](https://github.com/forcedotcom/SalesforceMobileSDK-Android/assets/47728873/c316bd88-8cea-470c-a57f-33264c6ccaab)

**Comment by brandonpage** [comment]
Okay, I did some more testing and can reproduce part of this.  I did not realize this was a React Native app, I am not able to reproduce this with a Cordova (what we typically refer to as "hybrid") or native app.  Honestly I more am a bit surprised to see the login activity behave differently between these app types.  Also I see the behavior above whether the Web Sever flow is used or not, as I said before that should have no impact.  

This isn't high priority but I will create an internal work item for it.

**Comment by NewTech2000** [comment]
@brandonpage it is a react-native Hybrid App
Here is my MainApplication.java file.
`package com;

import android.app.Application;

import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;
import com.salesforce.androidsdk.BuildConfig;
import com.salesforce.androidsdk.reactnative.app.SalesforceReactSDKManager;

import java.util.List;

/**
 * Application class for our application.
 */
public class MainApplication extends Application implements ReactApplication {

	private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
		@Override
		public boolean getUseDeveloperSupport() {
			return BuildConfig.DEBUG;
		}

		@Override
		protected List<ReactPackage> getPackages() {
			@SuppressWarnings("UnnecessaryLocalVariable")
			List<ReactPackage> packages = new PackageList(this).getPackages();
			// Packages that cannot be autolinked yet can be added manually here, for example:
			// packages.add(new MyReactNativePackage());
			packages.add(SalesforceReactSDKManager.getInstance().getReactPackage());
			return packages;
		}


		@Override
		protected String getJSMainModuleName() {
			return "index";
		}
	};

	@Override
	public ReactNativeHost getReactNativeHost() {
		return mReactNativeHost;
	}

	@Override
	public void onCreate() {
		super.onCreate();
		SoLoader.init(this, /* native exopackage */ false);
		SalesforceReactSDKManager.initReactNative(getApplicationContext(), MainActivity.class);

		// Set to use web server authentication
		SalesforceReactSDKManager.getInstance().setUseWebServerAuthentication(false);
		
	}
}
`

If we don't add 
	SalesforceReactSDKManager.getInstance().setUseWebServerAuthentication(false); this Line there is an authentication failure message after allowing a popup and again redirecting to the login page with the Invalid client credentials or Invalid token. after adding the above configuration user can log into the app without any issue.

**Comment by wmathurin** [comment]
Starting in Mobile SDK 11.0, web server flow is used by default - but apps can opt out by calling `setUseWebServerAuthentication(false)`.
For web server flow to work, you have to make sure your connected app is configured to NOT require secret for web server flow.
For more information see https://developer.salesforce.com/docs/platform/mobile-sdk/guide/oauth-web-server-flow.html
