### ISSUE TITLE
When the user logs out and attempts to log back in, they cannot log in.

### ISSUE THREAD

**Issue by NewTech2000** [forcedotcom/SalesforceMobileSDK-Android#2634]
Please fill out the following details:

1. Version of Mobile SDK Used: 12.0.0
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: Every Android OS Version
4. Device: All Android Devices
5. Steps to reproduce: Log in to the app once logged out, and again try to log back into the app.
6. Actual behavior: When a user tries to log back into the app once logged out, the user can't log in, and is redirected to the login page after the successful login and after clicking allowing the permission popup. again, without entering a username and password when the app closes and reopens the app then the app is authenticated and redirected to the home page without asking fingerprint or password. 
7. Expected Behavior: Once the user logs out and then tries to log in to the app again. the user should be able to log in to the app after unlocking the biometric password manager password without redirecting to the login page again.
8. Error Log: SalesforceOauthReactBridge.logoutCurrentUser failed: "SalesforceReactActivity not found"

**Comment by brandonpage** [comment]
@NewTech2000  Are you using Hybrid (Cordova) or React Native?  And it sounds like you are using [Biometric Authentication](https://developer.salesforce.com/docs/platform/mobile-sdk/guide/biometric-auth.html) feature?

**Comment by NewTech2000** [comment]
> @NewTech2000 Are you using Hybrid (Cordova) or React Native? And it sounds like you are using [Biometric Authentication](https://developer.salesforce.com/docs/platform/mobile-sdk/guide/biometric-auth.html) feature?

Yes, I use biometric authentication, and the app is a React Native app

**Comment by brandonpage** [comment]
@NewTech2000 Sorry for the delay.  I was able to reproduce this issue with Mobile SDK `12.0.1` but not with `12.2.0`.  Please update to the latest and let me know if the issue persists.  Thanks!

**Comment by brandonpage** [comment]
If you are still experiencing this issue with `12.2.0` we can reopen and investigate this issue.  Thanks!
