### ISSUE TITLE
How to Refresh Access Token Within SDK Without Losing Session 

### ISSUE THREAD

**Issue by imransiddiquirn** [forcedotcom/SalesforceMobileSDK-Android#2636]
Hi team,

I’m looking for a way to refresh the access token directly within the Salesforce Mobile SDK for react-native-force to avoid session loss. Currently, I’m manually refreshing the token by calling the API endpoint for token refresh (/services/oauth2/token) using the stored refresh token and updating the local state with the new access token.

Issue: After refreshing the token this way, the SDK doesn’t seem to recognize the new token, resulting in a lost session and forcing the user to reauthenticate.

Request: Is there a method within the SDK to renew the access token, or a recommended approach for refreshing it internally without disrupting the session?

Thank you!

**Comment by wmathurin** [comment]
There is a `refreshToken` exposed on [UserAccountManager](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/dev/libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccountManager.java#L684). You should use that.
