### ISSUE TITLE
When trying to upgrade the app installed from playstore with an APK,  it throws an "App not installed as package conflicts with an existing package"

### ISSUE THREAD

**Issue by hemantsumanmetacube** [forcedotcom/SalesforceMobileSDK-Android#2641]
Please fill out the following details:

1. Version of Mobile SDK Used: 12.0.1
2. Issue found in Native App or Hybrid App: Hybrid

App throws an error message "App not installed as package conflicts with an existing package", when the user tries to update the Play Store build with an APK.

I have matched the signature from both the apps and they are identical.

**Comment by brandonpage** [comment]
This is a device issue and not related to the Mobile SDK.
