### ISSUE TITLE
smartsync.js support for linked objects

### ISSUE THREAD

**Issue by zetxek** [forcedotcom/SalesforceMobileSDK-Android#423]
We are using the SalesForce Mobile SDK with Javascript, in a hybrid HTML5 app, using Smartsync to create, store and send the data between our HTML5 application and the Salesforce backend.

We have created, and downloaded objects with our application. We can download information existing in the server, and we can also create or modify objects locally and send them back to SF.

We problem we are finding is: is it possible to create relationships between the object instances BEFORE sending them to SF, in OFFLINE MODE?

To be clear, we give an example: we have two models: Worker and Relative, in a master-detail relationship.

We have been able to:
- create one worker and send it to the server
- create one relative and send it to the server
- download one worker, modify in, and send the changes to the server

We are not able to:
- WHILE OFFLINE: create a new worker. Create a new relative, linked to the newly created worker. Send it to the server. The expected behaviour is:
-- worker is created
-- relative is created, with a relationship with its parent object (the newly created worker)

Any help while using the smartsync or smartstore API will be appreciated.

**Comment by wmathurin** [comment]
We are not going to enhance smartsync.js. We recommend that you use the smartsync cordova plugin instead which leverages the native smartsync library. (It doesn't support saving graph of objects either, but if we ever add support for it, it would be there).
