### ISSUE TITLE
SmartstoreExplorer fails aapt utility

### ISSUE THREAD

**Issue by Filikin** [forcedotcom/SalesforceMobileSDK-Android#430]
Hi,
I am trying to figure out why the SmartStoreExplorer fails the "aapt dump badging" command with the error:
ERROR getting 'name' attribute: attribute is not a string value

The reason being that my own app, which is an Android Hybrid that uses the Smartstore fails the Google Play upload process for exactly the same reason, yet the ContactExplorer passes this test.

Is it a problem with the SmartStore library?

**Comment by Nemisis** [comment]
Is it possible to remove that in the `AndroidManifest.xml` file? I mean, I didn't know it was an issue and spent time trying to figure it out. If it's a known issue with Google, why include it in your SDK?

**Comment by bhariharan** [comment]
@Nemisis It is included in the SDK because there is no way to know the package name in advance. The alternative is that the app developer has to manually add those lines to the app's manifest, in order for push notifications to work. The idea was to automate as much of the manifest merging as possible to make it easy for developers to consume it.

**Comment by hamroune** [comment]
bravo it works for me, juste replace @string/app_package by "com.salesforce.androidsdk" in cordova plugin in my case

**Comment by toddhalfpenny** [comment]
Hi all, I'm also seeing this error, but my AndroidManifest does not have that string ref in it.

I'm trying to package an android hybrid app using the steps here https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin.

Has anyone managed to build a hybrid app and have it pass the aapt checks?

Here is what my AndroidManifest.xml looks like

```xml
<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="1" android:versionName="0.0.1" package="net.todd.biz001" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <application android:debuggable="true" android:hardwareAccelerated="true" android:icon="@drawable/icon" android:label="@string/app_name" android:manageSpaceActivity="com.salesforce.androidsdk.ui.ManageSpaceActivity" android:name="com.salesforce.androidsdk.smartsync.app.HybridAppWithSmartSync">
        <activity android:alwaysRetainTaskState="true" android:exported="true" android:launchMode="singleInstance" android:name="com.plugin.gcm.PushHandlerActivity" />
        <receiver android:name="com.plugin.gcm.CordovaGCMBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="net.me.biz001" />
            </intent-filter>
        </receiver>
        <service android:name="com.plugin.gcm.GCMIntentService" />
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/app_name" android:name="com.salesforce.androidsdk.ui.sfhybrid.SalesforceDroidGapActivity" android:theme="@android:style/Theme.Black.NoTitleBar">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:exported="true" android:name="com.plugin.gcm.PushHandlerActivity" />
    </application>
    <uses-sdk android:minSdkVersion="17" android:targetSdkVersion="21" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <permission android:name="net.me.biz001.permission.C2D_MESSAGE" android:protectionLevel="signature" />
    <uses-permission android:name="net.me.biz001.permission.C2D_MESSAGE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
</manifest>
```

All help/guidance very much appreciated.

**Comment by hamroune** [comment]
go to plugins/com.salesforce.androidsdk/...../SalesForceSDK/AndroidManifest.xml
and replace @string/app_package by "com.salesforce.androidsdk"

**Comment by toddhalfpenny** [comment]
Ahhh... the AndroidManifest.xml **in** the plugin folder... sorry I missed that. I'll give that a whirl and will update you,

**Comment by toddhalfpenny** [comment]
I have obviously misread something down the line and haven't been paying attention to the AndroidManifest .xml files inside the plugins dir. After modifying these my app builds fine and also passes the aapt test. Thanks!

**Comment by stephano88** [comment]
Hi I had the same problem of ERROR getting 'name' attribute: attribute is not a string value,

I am using the SalesoforceSDK to build a project, the App build and runs fine, but just fails the aapt dump badging command.
Can someone please help: androidManifest below

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="examaple.aru.wear.ticketsalesandmembershippush" android:versionName="x1">
    <uses-feature android:name="android.hardware.type.watch" />
    <supports-screens
        android:anyDensity="true"
        android:largeScreens="true"
        android:normalScreens="true"
        android:resizeable="true"
        android:smallScreens="true" />


    <uses-permission android:name="examaple.aru.wear.ticketsalesandmembershippush.restexplorer.C2D_MESSAGE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.VIBRATE"/>
    <uses-permission android:name="android.permission.MANAGE_ACCOUNTS"/>
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="examaple.aru.wear.ticketsalesandmembershippush.permission.RECEIVE" />
    <uses-permission android:name="com.android.launcher.permission.INSTALL_SHORTCUT" />

    <permission android:name="examaple.aru.wear.ticketsalesandmembershippush.permission.C2D_MESSAGE"
        android:protectionLevel="signature" />
    <permission android:name="android"></permission>
    <uses-permission android:name="examaple.aru.wear.ticketsalesandmembershippush.permission.C2D_MESSAGE" />

    <application android:name=".PushNotificationApp" android:allowBackup="true" android:icon="@drawable/arusmall" android:label="@string/app_name" android:theme="@style/AppTheme">
        <activity
            android:name=".PushNotificationSetUp"
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <meta-data android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
    </application>
</manifest>

**Comment by toddhalfpenny** [comment]
@stephano88 Can you confirm you also don't see the string ref for app_package in any of the AndroidManifest.xml files inside the plugins dir?

**Comment by stephano88** [comment]
Actually, i tried it, and it can be seen from my application. Is there
there a way to block / restrict the scope?

**Comment by stephano88** [comment]
The app_package and app_name can be seen from my project AndroidManifest, I guess it's inheriting from the Cordova or SalesforceSDK library.

I guess the only way to fix this is modifying the AndroidManifest of these libraries? thanks for help. Much appreciated as we are now approaching some deadlines this week.

**Comment by bhariharan** [comment]
@stephano88 See my comment [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/921) on how to overcome this error.

**Comment by harsha973** [comment]
For me, I have replaced "@string/app_package" in Salesforcemanifest with ${applicationId}. It worked.

**Comment by bhariharan** [comment]
@harsha973 Yes, we are aware of this. We have fixed this in our ```unstable``` branch and will be a part of our next release.
