### ISSUE TITLE
Android re-login fails after logging out with API call

### ISSUE THREAD

**Issue by pbenschop** [forcedotcom/SalesforceMobileSDK-Android#432]
In my hybrid Android app built with the Salesforce SDK, quite often (but not always), a subsequent login after the app logs out using the API  -- var sfOAuthPlugin = cordova.require("salesforce/plugin/oauth"); sfOAuthPlugin.logout(); -- fails. It is not only my app, I can easily reproduce this problem with the stock ContactExplorer sample from the SDK. The problem occurs more often when you logout and then subsequently login with a different login name. Problem description:
1. Enter name and password
2. In 2nd screen grant permission by tapping Allow
3. After a few seconds, the first screen comes back up with name and password empty

Again, the problem is not consistent; sometimes I can re-login over and over. I tried with the 2.06 and 2.1 version of the SDK, and on a 2013 Nexus 7 with the latest Android 4.4.2 and emulators with Android 4.3 (they all show the problem). The ContactExplorer sample is built on Windows 7 with the latest SDK from Github without any changes on my part. Typically, re-installing the app (after first explicitly un-installing it) solves the problem but here again, not consistently. I have not tested this functionality for a while so I cannot tell you when the problem crept in. Let me provide you with the logs and the ContactExplorer that I built.

Also, once the problem is present, re-installing the app (with ADB), without explicitly un-installing it (with e.g. ADB or Settings), does not resolve the problem. An explicit un-install typically clears the problem.

When you have a chance, please take a look at the problem. Since I am close to shipping my app, I am hoping you will be able to reproduce this problem so it can be fixed in the next SDK release. If you need me to do some more expirementation, let me know.

Thanks
Peter

https://dl.dropboxusercontent.com/u/40554620/Logs/contact-explorer-login-after-logout.txt

https://dl.dropboxusercontent.com/u/40554620/Logs/contact-explorer-logout.txt

https://dl.dropboxusercontent.com/u/40554620/Logs/ContactExplorer.apk

**Comment by PhamQuangThinh** [comment]
Hello All,
I have the same problem and I haven't been able to fix it yet.  
My app is Android native, use Salesforce SDK 3.3.0
Sometimes( not always) I login successfully but it goes back login page from Allow/Deny page.
Do anyone have any suggestions ?
Thank you
Thinh

**Comment by GaneshSawant** [comment]
Hello @bhariharan, 
I am still facing this issue.
Trying to build hybrid remote app for our community implementation.
current versions used
Cordova - 5.4.1
forcedroid version - 4.3.1
