### ISSUE TITLE
Hybrid refresh/replay is not working

### ISSUE THREAD

**Issue by khawkins** [forcedotcom/SalesforceMobileSDK-Android#783]
- Authenticate with the AccountEditor sample app.
- Click the button to go offline, and make a local account edit.
- Wait for the session to time out (or manually kill it in the Session Management admin section).
- Click the button to go back online.
- Click the button to process the local record.

This should refresh the expired/removed session in the background, and pass the new credentials from the OAuth plugin call back to the consumer, to complete the original request.  Instead, while the session is refreshed in the background, the OAuth plugin is sending back the original credentials, so forceTk's replay is failing as well.

**Comment by bhariharan** [comment]
This has been fixed in ```unstable``` and will be in our next release.
