### ISSUE TITLE
Missing User Account Parameters

### ISSUE THREAD

**Issue by Nemisis** [forcedotcom/SalesforceMobileSDK-Android#786]
Hello, 

I am creating an application that requires getting the full name from the Salesforce Org. This is present in the iOS SDK, but I do not see a way to do so with the Android SDK. Is there plans to add this in the future or am I missing something? 

[iOS SFUserAccount Docs](http://forcedotcom.github.io/SalesforceMobileSDK-iOS/Documentation/SalesforceSDKCore/SFUserAccount_h/Classes/SFUserAccount/index.html#HeaderDoc_props)
[Android UserAccount Docs](http://forcedotcom.github.io/SalesforceMobileSDK-Android/com/salesforce/androidsdk/accounts/UserAccount.html)

**Comment by bhariharan** [comment]
@Nemisis You are correct - currently, we're not fetching additional information such as full name on ```Android```. However, this information can be fetched in your application using the REST API on the current user object.

**Comment by bhariharan** [comment]
We will look at adding this in by default in a future release.

**Comment by bhariharan** [comment]
We have added additional user fields in our ```unstable``` branch. This will be a part of our upcoming release (```4.0```).
