### ISSUE TITLE
Issue with httpcore-4.3.2-modified.jar when Proguard is enabled

### ISSUE THREAD

**Issue by karsrini1973** [forcedotcom/SalesforceMobileSDK-Android#795]
We have an Android native app that makes use of Salesforce Mobile SDk.

We have run into an issue when we tried to upgrade our app to use the latest version of the SDK (3.0). The latest SDK includes a modified httpcore library (httpcore-4.3.2-modified.jar). 

When we generate a signed apk with Proguard turned on for obfuscation, the resultant APK is unable to make an HTTPS request to our salesforce org. We make use of the HttpAccess class and a <username,password> based authentication. Following is the code snippet and the resulting exception details. The issue seems to be related to conflicts in the obfuscation of org.apache.http.* classes. The same code was working fine with earlier SDK and works fine in debug mode without obfuscation. 
  
requestparams.add(new BasicNameValuePair("client_id", settingsHelper.getClientId(mContext)));

requestparams.add(new BasicNameValuePair("client_secret", settingsHelper.getClientSecret(mContext)));

requestparams.add(new BasicNameValuePair("username", settingsHelper.getUsername(mContext)));

requestparams.add(new BasicNameValuePair("password", settingsHelper.getPassword(mContext)));

UrlEncodedFormEntity requestEntity = new UrlEncodedFormEntity(requestparams, "UTF-8");

Execution exec = getHttpAccess().doPost(idHeaders, new URI(settingsHelper.getURLToken(mContext)), requestEntity);
 
The code fails when we try to create a new UrlEncodedFormEntity instance. We get a class cast exception. Looks like we are hitting issues because we potentially land up with 2 instances of org.apache.http.* - one that is part of android (older version of the library) and a modified recent version of the same that is now part of the Salesforce mobile SDK. 
 
Following is the exception trace from logcat: 
 
W/System.err( 4191): java.lang.ClassCastException: b.a.c.b.h cannot be cast to org.apache.http.NameValuePair
W/System.err( 4191):    at org.apache.http.client.utils.URLEncodedUtils.format(URLEncodedUtils.java:160)
W/System.err( 4191):    at org.apache.http.client.entity.UrlEncodedFormEntity.<init>(UrlEncodedFormEntity.java:57)
 
 
The obfuscated class b.a.c.b.h corresponds to BasicNameValuePair. Also, we find that the interface NameValuePair has also been obfuscated. However, the trace shows the NameValuePair without obfuscation indicating possible conflict/issue due to availability of the same interface in two libraries (??). 
 
Are there any suggestions on how this can be resolved? Any help on this would be greatly appreciated as we are unable to upgrade to the latest SDK because of this issue.

**Comment by bhariharan** [comment]
The ```httpcore-4.3.2-modified.jar``` library is only used for file uploads by the Mobile SDK. If you don't use file uploads in your app, you can follow the following steps as a workaround.

* Navigate to ```libs/SalesforceSDK```.
* Remove ```httpcore-4.3.2-modified.jar``` in the ```libs``` sub-folder.
* Edit  ```build.gradle``` and remove the entry for ```httpcore-4.3.2-modified.jar```.
* Edit ```.classpath``` and remove the entry for ```httpcore-4.3.2-modified.jar```.
* Open ```FileRequests.java``` in the ```com.salesforce.androidsdk.rest.files``` package and delete the ```uploadFile()``` method, and remove the unused imports.
5) Clean and recompile.

We will look into implementing the file upload API in a different manner to remove the dependency on ```httpcore```, in our next release, which should fix the problem too.

**Comment by bhariharan** [comment]
Let me know if the above steps work for you.

**Comment by MatteoSomensi** [comment]
Hi,
I'm trying to include SalesForce SDK to create a native app. But I get this error:

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lorg/apache/http/Consts;
at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
at com.android.dx.command.dexer.Main.run(Main.java:246)
at com.android.dx.command.dexer.Main.main(Main.java:215)
at com.android.dx.command.Main.main(Main.java:106)

Someone knows how to help me?

Thanks

**Comment by bhariharan** [comment]
We have removed the dependency on ```httpcore``` with [this](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/885) pull request. This issue shouldn't exist anymore on our ```unstable``` branch.
