### ISSUE TITLE
ClassNotFoundException: Didn't find class "com.salesforce.androidsdk.smartsync.app.HybridAppWithSmartSync"

### ISSUE THREAD

**Issue by ramsabarish** [forcedotcom/SalesforceMobileSDK-Android#828]
Hi , I have created a hybrid_local project using forcedroid.

My  Eclipse  ADT version is 23.0.2 . 
  
I have installed  Android SDK Build-tools  21.1.2   &  Android 5.0.1 (API 21) .

When I  imported the projects into Eclipse there were more than 100 errors. Then I configured the build path for SalesForceSDK, SmartStore and SmartSync to add  CordovaApp-CordovaLib.jar , and after rebuilding the errors were gone.

When I run it on my device I got the below error ...

Kindly Help me out ......

LogCat

02-17 16:33:04.938: E/AndroidRuntime(7395): FATAL EXCEPTION: main
02-17 16:33:04.938: E/AndroidRuntime(7395): Process: com.logiquad.apps.ios.logiquadsalesforce, PID: 7395
02-17 16:33:04.938: E/AndroidRuntime(7395): java.lang.RuntimeException: Unable to instantiate application com.salesforce.androidsdk.smartsync.app.HybridAppWithSmartSync: java.lang.ClassNotFoundException: Didn't find class "com.salesforce.androidsdk.smartsync.app.HybridAppWithSmartSync" on path: DexPathList[[zip file "/data/app/com.logiquad.apps.ios.logiquadsalesforce-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.logiquad.apps.ios.logiquadsalesforce-2, /vendor/lib, /system/lib]]
02-17 16:33:04.938: E/AndroidRuntime(7395): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:507)
02-17 16:33:04.938: E/AndroidRuntime(7395): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4382)
02-17 16:33:04.938: E/AndroidRuntime(7395): 	at android.app.ActivityThread.access$1500(ActivityThread.java:139)
02-17 16:33:04.938: E/AndroidRuntime(7395): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1270)
02-17 16:33:04.938: E/AndroidRuntime(7395): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-17 16:33:04.938: E/AndroidRuntime(7395): 	at android.os.Looper.loop(Looper.java:136)
02-17 16:33:04.938: E/AndroidRuntime(7395): 	at android.app.ActivityThread.main(ActivityThread.java:5086)
02-17 16:33:04.938: E/AndroidRuntime(7395): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-17 16:33:04.938: E/AndroidRuntime(7395): 	at java.lang.reflect.Method.invoke(Method.java:515)
02-17 16:33:04.938: E/AndroidRuntime(7395): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
02-17 16:33:04.938: E/AndroidRuntime(7395): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
02-17 16:33:04.938: E/AndroidRuntime(7395): 	at dalvik.system.NativeStart.main(Native Method)
02-17 16:33:04.938: E/AndroidRuntime(7395): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.salesforce.androidsdk.smartsync.app.HybridAppWithSmartSync" on path: DexPathList[[zip file "/data/app/com.logiquad.apps.ios.logiquadsalesforce-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.logiquad.apps.ios.logiquadsalesforce-2, /vendor/lib, /system/lib]]
02-17 16:33:04.938: E/AndroidRuntime(7395): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
02-17 16:33:04.938: E/AndroidRuntime(7395): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
02-17 16:33:04.938: E/AndroidRuntime(7395): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
02-17 16:33:04.938: E/AndroidRuntime(7395): 	at android.app.Instrumentation.newApplication(Instrumentation.java:998)
02-17 16:33:04.938: E/AndroidRuntime(7395): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
02-17 16:33:04.938: E/AndroidRuntime(7395): 	... 11 more

**Comment by bhariharan** [comment]
What version of the Mobile SDK are you using? You need to import the ```Cordova``` library project into ```Eclipse``` to build, since ```SalesforceSDK``` depends on ```Cordova```. The ```JAR``` approach won't work.

**Comment by ramsabarish** [comment]
How can I check the version of the Mobile SDK ?

I have checked its manifest file that says Version Code is 40  and  Version Name is 3.1.0  .

**Comment by BharathC** [comment]
Hi , I am getting the same Error .
- ADT version 23.0.6.XX
- Android SDK version 24.0.2
- Android 5.1 (API 22)
- cordova version -> 4.3
- SF Mobile SDK version -> 3.1.2 ,
 After creating  android hybrid project using " forcedroid create " command the following projects are created 
 - MainActivity-CordovaLib
 - SalesforceSDK
 - Sampleproj (my sample project)
 - SmartStore
 - SmartSync

On  viewing the properties of  SalesforceSDK project  shows a broken reference to missing project ( ..\..\external\cordova\framework) .I have added MainActivity-CordovaLib in the reference section after this Error disappeared but while on running as Android project I got Above mentioned Error

Attached SalesforceSDK project  properties image 

![salesforcesdk properties](https://cloud.githubusercontent.com/assets/2478525/6946455/fe636994-d8bd-11e4-80e6-0e1da2a4e351.PNG)


Please need help.

**Comment by bhariharan** [comment]
@BharathC You'll need to click the ```Remove``` button and remove the incorrect path to ```Cordova```, and click the ```Add...``` button, navigate to your library and add the ```Cordova``` library project.

**Comment by ramsabarish** [comment]
Okay, I will tell you what worked for me.

1. Check  java Build Path of your project. Ensure that in Libraries  the below given jar files are correctly added. If any jar file is missing you can find it in its bin folder and add it, like if smartsync.jar is missing you can find it under SmartSync -> bin.   

![screen shot 2015-04-02 at 1 30 27 pm](https://cloud.githubusercontent.com/assets/10074524/6960212/f98d653e-d93d-11e4-9139-c7abd163a4ca.png)


2. Then check Order and Export in your Java Build Path. 

![screen shot 2015-04-02 at 1 30 48 pm](https://cloud.githubusercontent.com/assets/10074524/6960247/3678ab98-d93e-11e4-869b-940098f1b6aa.png)

**Comment by saikumar100** [comment]
Hi, I m trying to develop salesforce hybrid_local app.
My cordova version@5.4.1
eclipse ADT 23.0.2
When ever i run my app in android device getting crashed.
Exception:03-14 17:39:19.268: E/AndroidRuntime(1236): java.lang.RuntimeException: Unable to instantiate application com.salesforce.androidsdk.phonegap.app.HybridApp: java.lang.ClassNotFoundException: Didn't find class "com.salesforce.androidsdk.phonegap.app.HybridApp" on path: DexPathList[[zip file "/data/app/com.test-8.apk"],nativeLibraryDirectories=[/data/app-lib/com.test-8, /vendor/lib, /system/lib]]

**Comment by vipinmpd08** [comment]
any solution to this problem yet ?

**Comment by wmathurin** [comment]
@vipinmpd08 There is no issue. Just npm install the latest version of [forcehybrid](https://www.npmjs.com/package/forcehybrid) and generate an application.

**Comment by vipinmpd08** [comment]
not really..with the latest version of Android Studio somehow the dependent modules wasn't getting imported.  I tried including the dependency modules in settings.gradle in the below order. Restarted AD, Sync the changes and make the project worked for me! thanks anyways.

include ":"
include ":CordovaLib"
include ":app"
include ":SalesforceAnalytics"
include ":SalesforceSDK"
include ":SmartStore"
include ":SmartSync"
include ":SalesforceHybrid"
