### ISSUE TITLE
Not able to create new account...

### ISSUE THREAD

**Issue by sachintiwari054** [forcedotcom/SalesforceMobileSDK-Android#831]
HI,
I am trying to figure out how we are passing name field in the account editor to the server while creating a new account record. Name field specifically i am talking about as its the mandatory field for creating a object and till now i didnt got to see where we actually are passing our parameters while creating a new account using the application. Please help at soonest..

**Comment by wmathurin** [comment]
Looking at https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/master/samples/accounteditor/AccountEditor.html
Line 442: we populate the model with the value entered in the view
Line 486: we save the local model back to the server, 
Line 170: we decide the set of fields to send back to the server on save
Of course the actual saving happens inside https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/master/libs/smartsync.js

**Comment by sachintiwari054** [comment]
Hi,
I am trying to save data for Opportunity, there i am passing fieldset as:
  sobjectType: "Opportunity",
    fieldlist: function(method) { 
        return method == "read" 
            ? ["Id", "Name", "StageName", "CloseDate", "Owner.Name", "LastModifiedBy.Name", "LastModifiedDate"]
            : ["Id", "Name","CloseDate", "StageName"];
    },

but when i am running the app and doing a save action cvreating a new opportunity, its giving me an error in log cat :
![error log](https://cloud.githubusercontent.com/assets/7971798/6282862/a259fc20-b901-11e4-983d-86d8283a83ee.png)


any suggestions on this why am getting errorcb called in place of successcb?

Any help appreciated.. Thanks...

**Comment by wmathurin** [comment]
What error is passed to the error callback?

Did you try debugging in a browser? With AccountEditor.html, uncomment the <script/> tags that follow . 

Next start chrome with same origin policy disabled (see http://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome) and open up file:// ... /<path to your .html>. Make sure to allow popups. You will get a popup to login then you should be able to step through the code or inspect network calls etc.

**Comment by sachintiwari054** [comment]
Hi,
I am trying with the method which you provided , in the meanwhile can you please elaborate more on offline online functionality of account editor app. I mean does this app detects offline mode by itself once the phone looses its internet connection or the user manually needs to switch to that mode using offline button?
Another query of mine is:

Is there any way of  getting the same data type displayed on the app same as salesforce. I mean can we show pick-list on the app itself like we have in salesforce? Please reply once you get this.. Thanks

**Comment by sachintiwari054** [comment]
Have tried using the local testing but not able to do so. There was nothing to display in the page nor i got any popup , tried steps mentioned by you. Do i need to manipulate any file other then bootconfig.json , accounteditor.html and cordova.force.js ... because i have only made changes in these files and few changes in css properties file. PLeas revert back on this. Thanks

**Comment by wmathurin** [comment]
Online/offline detection is at line 224 in https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/master/samples/accounteditor/AccountEditor.html
As for your second question, the Salesforce Mobile SDK doesn't provide UI components (at this point). We focus on the functions below (identity, authentication, secure storage, models -- with smartsync.js -- etc).

**Comment by wmathurin** [comment]
You need to run your browser with same origin policy disabled (see http://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome).

**Comment by wmathurin** [comment]
We would like to reserve the GitHub issues forum for known bugs in the Mobile SDK's codebase. 
We should continue that conversation on the Salesforce Developer Discussion Forums, where you are likely to get more suggestions from users. Thanks!

**Comment by sachintiwari054** [comment]
HI,
Thanks for your help i have figured out my errors and now i am able to do operations using Opportunity object as well.
What i will suggest that can your provide any forums link where your reply regularly as i am having few doubts understanding the flow.  I would love to hear from you about my queries. I highly appreciate your replies here and they have helped me alot. Thanks.
