### ISSUE TITLE
Getting OperationCanceledException after I login to the Hybrid Android app

### ISSUE THREAD

**Issue by Robin123goyal** [forcedotcom/SalesforceMobileSDK-Android#835]
I have created a hybrid app and after I login to the app i am getting OperationCanceledException. Below is the error message i am getting:

02-24 10:48:59.852: W/AccMgrCallback:run(31986): android.accounts.OperationCanceledException
02-24 10:48:59.852: W/AccMgrCallback:run(31986): 	at android.accounts.AccountManager$AmsTask.internalGetResult(AccountManager.java:1503)
02-24 10:48:59.852: W/AccMgrCallback:run(31986): 	at android.accounts.AccountManager$AmsTask.getResult(AccountManager.java:1531)
02-24 10:48:59.852: W/AccMgrCallback:run(31986): 	at android.accounts.AccountManager$AmsTask.getResult(AccountManager.java:1452)
02-24 10:48:59.852: W/AccMgrCallback:run(31986): 	at com.salesforce.androidsdk.rest.ClientManager$AccMgrCallback.run(ClientManager.java:440)
02-24 10:48:59.852: W/AccMgrCallback:run(31986): 	at android.accounts.AccountManager$11.run(AccountManager.java:1427)
02-24 10:48:59.852: W/AccMgrCallback:run(31986): 	at android.os.Handler.handleCallback(Handler.java:730)
02-24 10:48:59.852: W/AccMgrCallback:run(31986): 	at android.os.Handler.dispatchMessage(Handler.java:92)
02-24 10:48:59.852: W/AccMgrCallback:run(31986): 	at android.os.Looper.loop(Looper.java:150)
02-24 10:48:59.852: W/AccMgrCallback:run(31986): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
02-24 10:48:59.852: W/AccMgrCallback:run(31986): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-24 10:48:59.852: W/AccMgrCallback:run(31986): 	at java.lang.reflect.Method.invoke(Method.java:525)
02-24 10:48:59.852: W/AccMgrCallback:run(31986): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
02-24 10:48:59.852: W/AccMgrCallback:run(31986): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
02-24 10:48:59.852: W/AccMgrCallback:run(31986): 	at dalvik.system.NativeStart.main(Native Method)
02-24 10:48:59.852: I/SalesforceDroidGapActivity.authenticate(31986): authenticatedRestClient called with null client
02-24 10:48:59.892: D/AndroidRuntime(31986): Shutting down VM
02-24 10:48:59.892: W/dalvikvm(31986): threadid=1: thread exiting with uncaught exception (group=0x42e4f500)
02-24 10:48:59.892: E/AndroidRuntime(31986): FATAL EXCEPTION: main
02-24 10:48:59.892: E/AndroidRuntime(31986): java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
02-24 10:48:59.892: E/AndroidRuntime(31986): 	at com.salesforce.androidsdk.app.SalesforceSDKManager.removeAccount(SalesforceSDKManager.java:848)
02-24 10:48:59.892: E/AndroidRuntime(31986): 	at com.salesforce.androidsdk.app.SalesforceSDKManager.logout(SalesforceSDKManager.java:809)
02-24 10:48:59.892: E/AndroidRuntime(31986): 	at com.salesforce.androidsdk.app.SalesforceSDKManager.logout(SalesforceSDKManager.java:770)
02-24 10:48:59.892: E/AndroidRuntime(31986): 	at com.salesforce.androidsdk.app.SalesforceSDKManager.logout(SalesforceSDKManager.java:746)
02-24 10:48:59.892: E/AndroidRuntime(31986): 	at com.salesforce.androidsdk.ui.sfhybrid.SalesforceDroidGapActivity$1.authenticatedRestClient(SalesforceDroidGapActivity.java:318)
02-24 10:48:59.892: E/AndroidRuntime(31986): 	at com.salesforce.androidsdk.rest.ClientManager$AccMgrCallback.run(ClientManager.java:451)
02-24 10:48:59.892: E/AndroidRuntime(31986): 	at android.accounts.AccountManager$11.run(AccountManager.java:1427)
02-24 10:48:59.892: E/AndroidRuntime(31986): 	at android.os.Handler.handleCallback(Handler.java:730)
02-24 10:48:59.892: E/AndroidRuntime(31986): 	at android.os.Handler.dispatchMessage(Handler.java:92)
02-24 10:48:59.892: E/AndroidRuntime(31986): 	at android.os.Looper.loop(Looper.java:150)
02-24 10:48:59.892: E/AndroidRuntime(31986): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
02-24 10:48:59.892: E/AndroidRuntime(31986): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-24 10:48:59.892: E/AndroidRuntime(31986): 	at java.lang.reflect.Method.invoke(Method.java:525)
02-24 10:48:59.892: E/AndroidRuntime(31986): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
02-24 10:48:59.892: E/AndroidRuntime(31986): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
02-24 10:48:59.892: E/AndroidRuntime(31986): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by Nidhee** [comment]
I was also getting the same crash on login to the Native Android app which I was able to solve, may be you can try the same solution on your side. 
On my side,in Salesforce developer console when creating connecting app. I didn't select all the OAuth scopes so may be it was not getting some permissions on the connected android application.
Just - "Selected all available OAuth scopes". These scopes refer to permissions given by the user running the connected app.
Dont know whether this is exact solution, but this worked for me.

**Comment by Robin123goyal** [comment]
Thanks for the reply. I solved this issue by changing the auth token. I was using the wrong auth token. :)

**Comment by daveespo** [comment]
I don't think this is right, even if you were able to work around the problem with configuration changes. It look like 633df0559103d739ebb8db49fc802c18d4015752 authored by @bhariharan in January changed this code -- on a clean run of the VFConnector sample app, it crashes out because the accMgr.getAccountsByType(getAccountType()) (SalesforceSDKManager.java:843) returns an empty array, not a null value .. and the code on line 848 tries to access an index of the empty array
