### ISSUE TITLE
How to perform bulk DML operations in salesforce hybrid app ?

### ISSUE THREAD

**Issue by ramsabarish** [forcedotcom/SalesforceMobileSDK-Android#839]
I have created a salesforce hybrid app using Forcedroid and I'm able to perform the CRUD operations using forcetk client instance .

Now I want to perform mass update on salesforce objects but I didn't find any running example code to do so.

For 2 days I have searched for topics like BULK API, SmartSync , JSForce but I don't understand how to implement them.

Kindly share a code to perform Bulk DML operations like mass update , mass delete through salesforce hybrid app.

Kindly Help me out ....

**Comment by khawkins** [comment]
Please submit your question to our [Google Plus Community](http://sfdc.co/mobilesdkcommunity).  We reserve the Issues site(s) for bug reporting.  Thank you!
