### ISSUE TITLE
Not able to run Account Editor Hybrid App using salesforce sdk 3.1

### ISSUE THREAD

**Issue by sachintiwari054** [forcedotcom/SalesforceMobileSDK-Android#840]
HI,
I have been developing applications using sdk version 2.2 but now i am trying to migrate my app to 3.1 as i wanted to implement push notification in my app. I am facing issues while doing the same in 2.2, so here i thought of first trying to run a sample app but i am facing few errors while doing the same. Here i am attaching a snapshot of the error which you can see. Also i have added hierarchy of my project the dependencies which needed to be put in to run the account editor app. Can you help me with this where i am failing
![error2](https://cloud.githubusercontent.com/assets/7971798/6505451/72f6e3d2-c368-11e4-9c64-d56560742732.png)
![error 3](https://cloud.githubusercontent.com/assets/7971798/6505459/90a6c906-c368-11e4-900d-435f4507e5ca.png)

? any suggestion.

**Comment by bhariharan** [comment]
What is the ```targetApi``` and ```minApi``` in ```AndroidManifest.xml``` for the libraries and your sample apps?

We reserve this forum for known Mobile SDK bugs. Please post questions in our Google+ community [here](https://plus.google.com/communities/114225252149514546445).
