### ISSUE TITLE
Uncatchable Exception inside Android SDK

### ISSUE THREAD

**Issue by androidNttdata** [forcedotcom/SalesforceMobileSDK-Android#842]
Hello,

I am using the sync down mechanism as described in the SmartSyncExplorer sample application!

Unfortunately there seems to be an issue with the methods running inside the SalesforceSDK project. If the syncDown method of the SDK is called and an Exception is thrown at any point the application crashes. Even if I put the syncMngr.syncDown(...) method inside a try catch block!
Does the syncDown method run in a different Android process?

Can anyone help me solving this issue?

Below you find the code block that is implemented:

try {
SyncState syncState = syncMgr.syncDown(target, options, ContactObject.CONTACT_SOUP, new SyncManager.SyncUpdateCallback() {
@Override
public void onUpdate(SyncState sync) {
handleSyncUpdate(sync);
}
});
} catch (Exception e) {
e.printStackTrace();
}

**Comment by bhariharan** [comment]
The ```syncDown``` and ```syncUp``` operations are asynchronous. You'll need to catch the exception inside the ```onUpdate``` method in the callback. This forum is reserved for known bugs in the Mobile SDK. Please post questions is our Google+ community [here](https://plus.google.com/communities/114225252149514546445).

**Comment by androidNttdata** [comment]
Thank you!
Putting the try and catch block inside the onUpdate method seems to handle exceptions!
