### ISSUE TITLE
Servers.xml File is not Changing the URL

### ISSUE THREAD

**Issue by Nemisis** [forcedotcom/SalesforceMobileSDK-Android#843]
I am attempting to change the login server and noticed in the documentation the following: 

> In Android, login hosts are known as server connections. Prior to Mobile SDK v. 1.4, server connections for Android apps were hard-coded in the SalesforceSDK project. In v. 1.4 and later, the host list is defined in the res/xml/servers.xml file. The SalesforceSDK library project uses this file to define production and sandbox servers.You can add your servers to the runtime list by creating your own
res/xml/servers.xml file in your application project. The root XML element for this file is <servers>. This root can contain any number of <server> entries. Each <server> entry requires two attributes: name (an arbitrary human-friendly label) and url (the web address of the login server.)

    <?xml version="1.0" encoding="utf-8"?>
    <servers>
        <server name="XYZ.com Login" url="https://<username>.cloudforce.com"/> 
    </servers>

I add the following (as an example): 

    <?xml version="1.0" encoding="utf-8"?>
    <servers>
        <server name="Test" url="https://test.login.com"/>
    </servers>

Unfortunately, when I run this, it does not switch the login environment and goes directly into https://login.salesforce.com. Note, I am using Android Studio and pulled the library into my project and it is sitting in "libs/SalesforceSDK". I have my servers.xml in the following directory: 

    app/src/main/res/xml/servers.xml

Am I doing something wrong? Does this just not work with Android Studio? Note: The `bootconfig.xml` file is correctly overriding and it is in the following directory: 

    app/src/main/res/values/bootconfig.xml`

**Comment by Nemisis** [comment]
Hmm...Looks as though I have solved this myself. Looking into the code, it seems to only fetch from the servers.xml file on first launch (from an initial install) and then caches it in the SharedPreferences. As such, if you change the URL, you will need to either uninstall or clear the data. 

As such, if this is released in the Play Store and then we want to change the login URL, how would we go about updating it without forcing the user to clear the data and/or uninstall?

**Comment by wmathurin** [comment]
You are right with your analysis. That's the current behavior.
A work around would be to programmatically update or clear that shared preferences file at app startup.

**Comment by Nemisis** [comment]
Thanks. Closing.
