### ISSUE TITLE
where is native/SalesforceSDK file ? 

### ISSUE THREAD

**Issue by hanaw1** [forcedotcom/SalesforceMobileSDK-Android#858]
According to this guide - https://developer.salesforce.com/page/Developing_Hybrid_Apps_with_the_Salesforce_Mobile_SDK -in step  :"Creating a Hybrid App Project for Android"
when I import the file I get a lot of errors. 
anyone got this too?
And there is suppose to be a reference to native/SalesforceSDK - but there isnt in this project.
Its missing.
Can anyone help me pls? 
Thanks

**Comment by bhariharan** [comment]
Please post your question on our Google+ community [here](https://plus.google.com/communities/114225252149514546445). This forum is reserved for reporting of known bugs/issues with the Mobile SDK.
