### ISSUE TITLE
Hybrid app crash (ArrayIndexOutOfBoundsException) when OAuth scopes aren't defined to match bootconfig.json

### ISSUE THREAD

**Issue by daveespo** [forcedotcom/SalesforceMobileSDK-Android#862]
If you don't include the proper scopes when setting up your Connected App, rather than getting "1804: the requested scope is not allowed" upon Login, the app crashes with:

````
04-06 14:21:56.398      322-322/com.salesforce.samples.vfconnector E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.salesforce.samples.vfconnector, PID: 322
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
            at com.salesforce.androidsdk.app.SalesforceSDKManager.removeAccount(SalesforceSDKManager.java:848)
            at com.salesforce.androidsdk.app.SalesforceSDKManager.logout(SalesforceSDKManager.java:809)
            at com.salesforce.androidsdk.app.SalesforceSDKManager.logout(SalesforceSDKManager.java:770)
            at com.salesforce.androidsdk.app.SalesforceSDKManager.logout(SalesforceSDKManager.java:746)
````

AccountManager returns an empty array if there are no accounts, never null so that should be the test (#835 is this same bug, just in different words)

The offending code was introduced in 633df05

**Comment by bhariharan** [comment]
@daveespo Thanks for reporting this issue - I'll take a look.

**Comment by daveespo** [comment]
PR attached ;-)

**Comment by bhariharan** [comment]
Could you send a pull request to the ```unstable``` branch?

**Comment by daveespo** [comment]
Yep, sorry about that .. didn't notice the request for 'unstable' until it was too late

Hopefully I got it right this time ;-)

**Comment by bhariharan** [comment]
:+1:
