### ISSUE TITLE
mobile sdk android hybrid app (remote or local) does not launch

### ISSUE THREAD

**Issue by testintegration** [forcedotcom/SalesforceMobileSDK-Android#870]
Hi I followed these steps based on the new instructions in mobile sdk.pdf on windows.
1. npm install forcedroid –g
2. npm -g install cordova
3. forcedroid create
4. Build the project in Eclipse based on the instructions in the command line
5. modify bootconfig to use the Consumer key for the remote app in my developer org
set callback to same which is testsfdc:///mobilesdk/detect/oauth/done

The project builds fine in Eclipse (Luna). I run the project by selecting run or run an android app by selecting an AVD I added in the virtual device manager, which is Andoird TV ARM(armeabi-v7a) and target is Android 5.1.1(API Level 22), I tried other AVDs too.  I only see a black screen with controls on the right side, but on the left side, it's blank and eventually displays "Android". I don't get the salesforce login window. Do you know what might be the reason for this? Does it have anything to do with Ant? I've seen it mentioned as prerequisite. I have 1.9.4 installed on my pc. But I didn't have to use any Ant command for building the android project.

**Comment by bhariharan** [comment]
@testintegration Looks like you're unable to launch the ```Android``` emulator successfully. This has nothing to do with the ```Salesforce Mobile SDK```. Please use this forum to report bugs/issues with the ```Mobile SDK``` code.
