### ISSUE TITLE
Use of AccountManager causing memory leak

### ISSUE THREAD

**Issue by Nemisis** [forcedotcom/SalesforceMobileSDK-Android#882]
I added [LeakCanary](https://github.com/square/LeakCanary) to my project that uses the android SDK, and I receive a notification of a memory leak after every screen. The following is the memory leak: 

    05-11 08:54:26.451  27157-28173/com.my.app.debug D/LeakCanary﹕ In com.my.app.debug:1.0.0_debug:3.
    * com.my.app.ui.ActivityHome has leaked:
    * GC ROOT android.accounts.AccountManager$AmsTask$Response.this$1
    * references android.accounts.AccountManager$7.mActivity (anonymous class extends android.accounts.AccountManager$AmsTask)
    * leaks com.my.app.ui.ActivityHome instance
    * Reference Key: 177d2905-d065-4eb3-b9ff-e7012a72e487
    * Device: Genymotion generic Google API - Nexus 5 - 5.0.0 - API 21 - 1080x1920 vbox86p
    * Android Version: 5.0 API: 21
    * Durations: watch=5011ms, gc=114ms, heap dump=482ms, analysis=3251ms

I cannot track down exactly where this is happening, but I did notice that if I comment out the code that instantiates the `ClientManager`, my app does not leak any activities. I am not sure if this is something that you guys would add a fix for, if this is a memory leak inside of the Android SDK.

**Comment by pyricau** [comment]
See here: https://code.google.com/p/android/issues/detail?id=173689

**Comment by bhariharan** [comment]
I'm closing this issue, since this is not an issue specific to the ```Salesforce Mobile SDK```. We will monitor the bug filed with AOSP for updates.
