### ISSUE TITLE
You should replace icon value in default AndroidManifest.xml

### ISSUE THREAD

**Issue by VinceFINET** [forcedotcom/SalesforceMobileSDK-Android#920]
Please fix the default AndroidManifest.xml file at line 5.

    <application android:hardwareAccelerated="true" android:icon="@drawable/sf__icon" android:label="@string/app_name" android:manageSpaceActivity="com.salesforce.androidsdk.ui.ManageSpaceActivity" android:name="com.salesforce.androidsdk.smartsync.app.HybridAppWithSmartSync">

I get this error:
...\platforms\android\AndroidManifest.xml:5: error: Error: No resource found that matches the given name (at 'icon' with value '@drawable/sf__icon').

You should replace "@drawable/sf__icon" with "@drawable/icon"

Thanks!!

Vincent

**Comment by wmathurin** [comment]
We are not getting that error.
Are you building a native or an hybrid app? What version of the SDK are you using?

**Comment by wmathurin** [comment]
No reproducible here. Re-open if you still have the problem but provide more details please.

**Comment by VinceFINET** [comment]
Hi,

I'm creating an android hybrid application.
SDK v33 used

**Comment by wmathurin** [comment]
Did you create the app using forcedroid or did you use the cordova command line tools directly?

**Comment by AndreeWille** [comment]
I have the same issue. I created a android native app with forcedroid as described in the Trailhead module. Afterwards I get this error message in AndroidManifest.xml:

`android\TrailAndroidApps\MyTrailNative\AndroidManifest.xml:9: error: Error: No resource found that matches the given name (at 'icon' with value '@drawable/sf__icon').`

**Comment by kchitalia** [comment]
@AndreeWille I followed the instructions to build a native android app using the Trailhead videos here: 

https://developer.salesforce.com/trailhead/mobile_sdk_native_android/mobilesdk_android_getting_started

and I was able to launch the template app and get to the login screen.

**Comment by AndreeWille** [comment]
Now it works for me as well. I needed to add the cordova and salesforcesdk project as a library to my android project. Right click on my project -> Properties -> Android -> under Library add those 2 projects.

Thx @kchitalia for trying to reproduce it.

**Comment by breakingbalance** [comment]
Hi I'm facing the same error. i used forcehybrid to create the app. it was running fine. later i had to use cordova-plugin-firebase plugin for push notification. post installation of that plugin this issue pops up.
