### ISSUE TITLE
ERROR getting 'name' attribute: attribute is not a string value

### ISSUE THREAD

**Issue by stephano88** [forcedotcom/SalesforceMobileSDK-Android#921]
Hi I had the same problem of ERROR getting 'name' attribute: attribute is not a string value,

I am using the SalesoforceSDK to build a project, the App build and runs fine, but just fails the aapt dump badging command.
Can someone please help: androidManifest below

<?xml version="1.0" encoding="utf-8"?>
package="examaple.aru.wear.ticketsalesandmembershippush" android:versionName="x1">

android:anyDensity="true"
android:largeScreens="true"
android:normalScreens="true"
android:resizeable="true"
android:smallScreens="true" />

<uses-permission android:name="examaple.aru.wear.ticketsalesandmembershippush.restexplorer.C2D_MESSAGE" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.VIBRATE"/>
<uses-permission android:name="android.permission.MANAGE_ACCOUNTS"/>
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.GET_ACCOUNTS" />
<uses-permission android:name="android.permission.WAKE_LOCK" />
<uses-permission android:name="examaple.aru.wear.ticketsalesandmembershippush.permission.RECEIVE" />
<uses-permission android:name="com.android.launcher.permission.INSTALL_SHORTCUT" />

<permission android:name="examaple.aru.wear.ticketsalesandmembershippush.permission.C2D_MESSAGE"
    android:protectionLevel="signature" />
<permission android:name="android"></permission>
<uses-permission android:name="examaple.aru.wear.ticketsalesandmembershippush.permission.C2D_MESSAGE" />

<application android:name=".PushNotificationApp" android:allowBackup="true" android:icon="@drawable/arusmall" android:label="@string/app_name" android:theme="@style/AppTheme">
    <activity
        android:name=".PushNotificationSetUp"
        android:label="@string/app_name" >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />

            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
    </activity>

    <meta-data android:name="com.google.android.gms.version"
        android:value="@integer/google_play_services_version" />
</application>

**Comment by bhariharan** [comment]
@stephano88 This is not a ```Mobile SDK``` bug, it is an ```Android``` bug. I have filed a bug with the ```AOSP``` project. Meanwhile, you can replace ```@string/app_name``` with your app name to unblock yourself for now.

**Comment by stephano88** [comment]
Hi , you mean replace it in the AndroidManifest ?

**Comment by bhariharan** [comment]
Yes

**Comment by stephano88** [comment]
I even change it to @string/app_name1 , and I still get the same error when doing the aapt dump badging

**Comment by bhariharan** [comment]
You'll need to replace all indirect resource references, and then clean and rebuild.

**Comment by stephano88** [comment]
that is only in my project ? because i cannot find the libraries AndroidManifest files.

**Comment by stephano88** [comment]
@bhariharan  , Still same issue,  do I need to replace everywhere ? layouts etc ? @drawable etc and other references ?

**Comment by bhariharan** [comment]
@stephano88 Nope - not layouts, or anything else for that matter. Only ```AndroidManifest.xml``` (including the manifest file for the ```SalesforceSDK``` library project, since that's where the offending string is).

**Comment by stephano88** [comment]
How can i access the salesforcesdk androidmanifest, its not a jar, and is
added by gradle, when i drilll down i cant find it
Do you have any idea?

**Comment by bhariharan** [comment]
What IDE are you using? ```Eclipse``` or ```Android Studio```? Search for the ```SalesforceSDK``` directory in the filesystem, and navigate to ```AndroidManifest.xml``` within that directory.

**Comment by stephano88** [comment]
Android Studio

**Comment by bhariharan** [comment]
Navigate to the ```Projects``` dropdown on the left tab, find the ```SalesforceSDK``` project, and navigate to ```AndroidManifest.xml``` under that project.

**Comment by stephano88** [comment]
in my file system I can see it in my project folder at 

...\build\intermediates\exploded-aar\com.force\SalesforceSDK\2.3.0

May be it's that one , I will try again in Android Studio

**Comment by bhariharan** [comment]
@stephano88 That's the generated binary, you'll need the source. This forum is reserved for known bugs in ```Mobile SDK```. Please continue this discussion by posting in our community [here](https://plus.google.com/u/1/communities/114225252149514546445).

**Comment by stephano88** [comment]
so I should replace @string/app_package with com.salesforce.androidsdk ?

**Comment by stephano88** [comment]
Hi again, 

this is what I can see , no Android manifest 

![error](https://cloud.githubusercontent.com/assets/1208820/8712126/c682eb9a-2b9b-11e5-899a-96152be38d4f.png)

**Comment by bhariharan** [comment]
You should replace ```@string/app_package``` with your app's package name. Again, your screenshot is pointing to the built version, not the source. Besides, you're using ```Mobile SDK 2.3.0```, which is unsupported right now (it's a very old version). You should upgrade to the latest (```Mobile SDK 3.3.0```).

As I mentioned already, please post on our community. This forum is not for discussions, it's for bugs in the SDK.

**Comment by stephano88** [comment]
I just posted there.

**Comment by stephano88** [comment]
![error1](https://cloud.githubusercontent.com/assets/1208820/8712229/11cdce52-2b9d-11e5-9e4c-d2accf6e4f6a.png)
