### ISSUE TITLE
AuthFailure while fetching data after successful login

### ISSUE THREAD

**Issue by Joisar** [forcedotcom/SalesforceMobileSDK-Android#922]
In TemplateApp inside Native app samples.

I have logged in using my salesforce account credentials and I got logged in successfully, I have granted application access request.

Now,
When I click "Fetch Accounts" button and send RestRequest to fetch accounts, it displays toast having following error:

An error has occured:
com.android.volley.AuthFailureError
Please try again

Thanks,
Mehul.

**Comment by wmathurin** [comment]
We have never seen this issue. You need to provide us more details (version of the SDK, login host etc).

**Comment by Joisar** [comment]
It was due to configuration. I've solved.
