### ISSUE TITLE
SyncManager#reSync not working as expected

### ISSUE THREAD

**Issue by randalln** [forcedotcom/SalesforceMobileSDK-Android#932]
From the Javadoc: "Re-run sync but only fetch new/modified records"

I'm adding custom local field to my soup.  The original SyncOptions included MergeMode.LEAVE_IF_CHANGED, but after the reSync, the custom fields are gone.  This seems contrary to the documented functionality, unless I'm missing something.

**Comment by wmathurin** [comment]
Did you mark the locally modified fields as modified? That's how smartsync now to leave locally updated record alone during a sync or re-sync.
For an example look at the save method in: https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/native/SampleApps/SmartSyncExplorer/src/com/salesforce/samples/smartsyncexplorer/ui/DetailActivity.java
