### ISSUE TITLE
 Why always add REFRESH_TOKEN within method computeScopeParameter of OAuth.java

### ISSUE THREAD

**Issue by JamesKarl** [forcedotcom/SalesforceMobileSDK-Android#936]
Before I commented out the bold statement   **scopesSet.add(REFRESH_TOKEN);**, it always failed to authorize for scope mismatch. After I commented out it, It succeed. I want to ask why always add REFRESH_TOKEN?

private static String computeScopeParameter(String[] scopes) {
        final List<String> scopesList = Arrays.asList(scopes == null ? new String[]{} : scopes);
        Set<String> scopesSet = new TreeSet<String>(scopesList); // sorted set to make tests easier
        **scopesSet.add(REFRESH_TOKEN);**
        return TextUtils.join(" ", scopesSet.toArray(new String[]{}));
    }

**Comment by JamesKarl** [comment]
The required parameters for **User-Agent OAuth Authentication Flow** are as below:
**response_type**: Must be token for this authentication flow
 **client_id**: The Consumer Key from the connected app definition. 
** redirect_uri **: The Callback URL from the connected app definition.

The following parameters are optional:
**display**
**scope**
**scope**

**refresh_token** is not mentioned here. So why always add **refresh_token**?

**Note**:
Please reference the official document **apex_rest.pdf**

**Comment by wmathurin** [comment]
Users don't expect to have to re login every time they open an application on their mobile device.
Without refresh_token, the user will be logged out as soon as their session expires.
With refresh_token, the oauth flow gives us back a refresh token that the SDK uses to get a new access token when the session expires.
