### ISSUE TITLE
Usage of the Apache HTTP Package and Android 6.0 Marshmallow

### ISSUE THREAD

**Issue by Nemisis** [forcedotcom/SalesforceMobileSDK-Android#938]
As you can see from the [Behavior Changes](https://developer.android.com/preview/behavior-changes.html#behavior-apache-http-client) site, the Apache HTTP client has been removed from the Android SDK. As a result, the networking components of the SalesforceMobileSDK will no longer compile. The SDK should be updated to one of the following: 

 * Switch to `OkHttp`
 * Switch to `HttpUrlConnection`
 * Add `org.apache.http.legacy.jar` file to the list of libs (found in **Android/Sdk/platforms/android-23/optional**)

**Comment by wmathurin** [comment]
Thanks for reporting this bug. We will make sure to address it in our upcoming release.

**Comment by bhariharan** [comment]
We have fixed this in the ```unstable``` branch. This will be a part of our next release.
