### ISSUE TITLE
Using TLS v1.1 or v1.2 in apps built on top of Android Mobile SDK

### ISSUE THREAD

**Issue by karsrini1973** [forcedotcom/SalesforceMobileSDK-Android#953]
Hi, 
As per the link below, Salesforce will be disabling TLS v1.0 support in its orgs in 2016.
https://help.salesforce.com/apex/HTViewSolution?urlname=Salesforce-disabling-TLS-1-0&language=en_US&eid=singlesend&d=70130000000NIyh

We have Android native apps running on 4.4.2 where TLS v1.1/v1.2 are not enabled by default. All access to Salesforce is via the mobile SDK (which in turn uses Android volley). How do we ensure that our app instances running on 4.4.2 will not be broken once Salesforce disables TLS v1.0 support? 

PS: I have raised this in the community forum as well. Link - https://developer.salesforce.com/forums/?id=906F0000000BXTmIAO

Regards,
Karthik

**Comment by wmathurin** [comment]
We should probably provide a fix in our upcoming release.
In the meantime, you could create a SSLSocketFactory with TLS v1.1/v1.2 enabled (see http://blog.dev-area.net/2015/08/13/android-4-1-enable-tls-1-1-and-tls-1-2/ for example code), and set that factory on the http url connection in createHttpUrlConnection in https://github.com/wmathurin/SalesforceMobileSDK-Android/blob/master/libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/HttpAccess.java

Cc: @bhariharan

**Comment by karsrini1973** [comment]
Thanks. Can you please let me know when the next release is expected? That
will help me decide whether we have to put in a temporary patch or wait for
the SDK upgrade.

Regards,
Karthik

**Comment by bhariharan** [comment]
@karsrini1973 Our next release is expected in the Nov/Dec timeframe. #safeharbor

**Comment by bhariharan** [comment]
@karsrini1973 We have a fix for this issue [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/981). This will be in our upcoming release. If you need it sooner, you can cherry-pick the pull request and apply it on your fork of Mobile SDK.

**Comment by karsrini1973** [comment]
Thanks. I had already made changes in our fork - will see if I can quickly
align them with the actual commit.

**Comment by karsrini1973** [comment]
One more question:
Are there plans to allow the app to control the TLS version(s) that can be
used for negotiation?
For e.g. if we want to force usage of only TLS 1.2 - it will be nice to
have a mechanism to support it.

**Comment by bhariharan** [comment]
@karsrini1973 Not at this time. This is a low level protocol that's usually controlled by the OS. We don't anticipate the need for apps to override this setting, since it could lead to unpredictable behavior based on the Salesforce endpoint that's being hit. [Here](https://rwhitleysfdc.wordpress.com/2015/11/04/disabling-tls-1-0-preparing-mobile-sdk-apps-for-the-big-change/) is our blog post on how to handle this change.
