### ISSUE TITLE
Null pointer exception when trying to logout with push notifications registered and device is offline

### ISSUE THREAD

**Issue by karsrini1973** [forcedotcom/SalesforceMobileSDK-Android#954]
We are encountering a Null pointer exception while using Push messaging in the following scenario: 
a) Our Android app is registered for using push messaging
b) Based on end user action, at some point in the app, we call SalesforceSDKManager.logout
c) If there is no connectivity in the device when logout is called, we encounter a null pointer exception inside PushService in Salesforce Mobile SDK. 

On further analysis, we noticed that in this case (no connectivity), the following happens:
a) We hit handleUnregistrationError in PushService.java. It in turn calls unregisterSFDCPushNotification which returns false.
b) However, the return value is ignored. 
c) An UNREGISTERED_ATTEMPT_COMPLETE_EVENT is broadcast which is handled in SalesforceSDKManager (unregisterPush) and a removeAccount is initiated. 
d) However, along with the broadcast, the handleUnregistrationError method also calls scheduleGCMRetry which triggers another call to PushMessaging.unregister
c) By the time the unregister request is processed, the account is already removed. However, as no check is made related to account validity, this results in a null pointer exception within PushService/PushMessaging.

This is an edge case but in our app we are supposed to handle offline scenarios effectively. Any pointers/workarounds would be useful... 

PS: Have raised this in the developer forum as well - no responses yet. Link: https://developer.salesforce.com/forums/?id=906F0000000BTUuIAO

regards,
Karthik

**Comment by wmathurin** [comment]
Could you tell us what version of the Mobile SDK you are using and whether it is a native or hybrid application?

**Comment by karsrini1973** [comment]
Hi,
Ours is a native android application. We are currently using 3.0.0. But I
also looked at the latest github code and looks like the behavior is still
the same.

Regards,
Karthik

**Comment by kchitalia** [comment]
If this issue is still reproducible in our latest Mobile SDK, please re-open this.
