### ISSUE TITLE
Cordova build error with Salesforce MobileSDK - Element activity#com.plugin.gcm.PushHandlerActivity duplicated in AndoidManifest.xml

### ISSUE THREAD

**Issue by RichardClarkeDW** [forcedotcom/SalesforceMobileSDK-Android#970]
If the only plugin is cordova-plugin-whitelist projects build without error
Including those in the Salesforce MobileSDK samples

These launch fine in the emulator running cordova emulate android

The call to 
var oauthPlugin = cordova.require("com.salesforce.plugin.oauth");
fails because that plugin is not loaded (which makes sense)

So I add the latest Salesforce Mobile SDK plugin as per https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin

Then the build fails because the Element activity#com.plugin.gcm.PushHandlerActivity duplicated in AndoidManifest.xml

I can see this is duplicated

        <activity android:exported="true" android:launchMode="singleTop" android:name="com.plugin.gcm.PushHandlerActivity" />
        <activity android:exported="true" android:name="com.plugin.gcm.PushHandlerActivity" />

But I can't work out how to fix it

Any suggestions?

Thanks

Richard

**Comment by bhariharan** [comment]
@RichardClarkeDW What versions of ```Mobile SDK```, ```Cordova platform```, and ```Cordova CLI``` are you using? ```Cordova CLI >= 5.0``` is not currently supported, and ```cordova-plugin-whitelist``` doesn't exist for ```CLI < 5.0``` and ```Cordova platform < 4.0```.

**Comment by RichardClarkeDW** [comment]
Cordova and Cordova lib are current so 5.3.3.  I can't see how to check the version of the Mobile SDK but I pulled it from Git last week, so it should be the current one 3.3.1 or 3.3.2.  So it sounds like I need to uninstall the current Cordova and pull a version prior to 5.0...

**Comment by RichardClarkeDW** [comment]
The confusion for me is the latest Mobile SDK (https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/master/doc/mobile_sdk.pdf) which is version 3.3 has steps in it to download forcedroid 3.3.1 which is OK, but on page 117 it says to run "npm -g install cordova"

That grabs the latest cordova which is 5.5.3 - the top of page 117 points out the SDK hybrid container is set up to with Cordova 3.6.4 for Android.

Seems to me the SDK (and trailhead https://developer.salesforce.com/trailhead/mobile_sdk_intro/mobile_sdk_hybrid/mobilesdk_hybrid_getting_started) download instructions for Cordova should be changed to reference the older Cordova version.  Assuming the latest v 5.5.3 is why I am having problems.

Reviewing https://git-wip-us.apache.org/repos/asf?p=cordova-cli.git;a=tags I can see version 3.6.3 is from 13 months ago.  3.6.4 which is recommended in the SDK for Android does not appear as a release.

Trying to install Cordova 3.6.4 with "npm install -g cordova@3.6.4" gives a version not found error which makes it worrying when the Mobile SDK says "Salesforce Mobile SDK 3.3 upgrades its hybrid container to use Apache Cordova 3.6.x (3.6.3 for iOS, 3.6.4 for Android)" on page 117.

Maybe I'm missing something but this sure had me confused.

I will try using 3.6.3 and see if the samples work with that.

**Comment by bhariharan** [comment]
@RichardClarkeDW Yes, you'll need to downgrade ```Cordova CLI``` to use it with the existing version of ```Mobile SDK```. ```Cordova``` has changed its underlying platform in its newer versions. Our upcoming release, ```Mobile SDK 4.0```, will support the version of ```Cordova``` you're using (```5.0``` and above).

**Comment by RichardClarkeDW** [comment]
Thanks for your help but even with forcing version 4.3.1
npm install -g cordova@4.3.1
I still have a problem with the UserList sample and the equivalent from Trailhead https://developer.salesforce.com/trailhead/mobile_sdk_intro/mobile_sdk_hybrid/mobilesdk_hybrid_getting_started

When I run the app in the emulator both apps stop working

Debugging shows this error 
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.salesforce.androidsdk.smartsync.app.HybridAppWithSmartSync" 

Build manifest has
<application android:hardwareAccelerated="true" android:icon="@drawable/sf__icon" android:label="@string/app_name" android:manageSpaceActivity="com.salesforce.androidsdk.ui.ManageSpaceActivity" android:name="com.salesforce.androidsdk.smartsync.app.HybridAppWithSmartSync">

Given these are the most simplest samples why is HybridAppWithSmartSync referenced?

And any idea how to work around this?  I am not sure how to add that plugin to the application

Cordova -v reports 4.3.1
Forcedroid version is 3.3.1
Cordova plugin reports
com.phonegap.plugins.PushPlugin 2.2.1 "PushPlugin"
com.salesforce 3.3.2 "SalesforceMobileSDK Plugins"
org.apache.cordova.device 0.3.0 "Device"

**Comment by bhariharan** [comment]
@RichardClarkeDW I'm not sure what's going on with ```Trailhead```, since our team doesn't own/manage it. Try generating an app with [forcedroid](https://www.npmjs.com/package/forcedroid), and let me know if that works for you. This uses ```Cordova``` to generate the app, but it makes sure the dependencies are lined up correctly.

**Comment by RichardClarkeDW** [comment]
I've had another attempt today using forcedroid but with no change in the outcome.  For some reason the templates and scripts are misaligned (on my PC at least) and even a simple test application using the forcedroid output fails with this exception:

E/AndroidRuntime( 1110): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.salesforce.androidsdk.smartsync.app.HybridAppWithSmartSync" on path: DexPathList[[zip file "/data/app/com.richard.testapp-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.richard.testapp-1, /system/lib]]

The fact the sf__icon.png file is missing is another clue something is messed up.

Here is what I did today to check the versions and attempt a base forcedroid application creation

npm list -g --depth=1
> +-- cordova@4.3.1
¦ +-- cordova-lib@4.3.1
¦ +-- nopt@3.0.1
¦ +-- q@1.0.1
¦ +-- underscore@1.7.0
+-- forcedroid@3.3.1
¦ +-- shelljs@0.5.3

forcedroid version
> forcedroid version 3.3.1

forcedroid create --apptype=hybrid_local --appname=TestApp --targetdir=TrailHybridApps --packagename=com.richard.testapp

cd TrailHybridApps/TestApp

cordova platform
> Installed platforms: android 3.6.4

used AVD manager to launch default AVD (AVD_GalaxyNexus_ToolsForApacheCordova)

cordova emulate

build failure due to missing icon
cloned icon.png in "C:\Users\richard.clarke.DOWHAT\TrailHybridApps\TestApp\platforms\android\res\drawable" to sf__icon.png

cordova emulate

TestApp fails to load

"AndroidManifest.xml" in platforms/android has this
<application android:hardwareAccelerated="true" android:icon="@drawable/sf__icon" android:label="@string/app_name" android:manageSpaceActivity="com.salesforce.androidsdk.ui.ManageSpaceActivity" android:name="com.salesforce.androidsdk.smartsync.app.HybridAppWithSmartSync">

run debugger
E/AndroidRuntime( 1110): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.salesforce.androidsdk.smartsync.app.HybridAppWithSmartSync" on path: DexPathList[[zip file "/data/app/com.richard.testapp-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.richard.testapp-1, /system/lib]]
cd ../..

cordova platform rm android

cordova platform add android@3.6.4
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: com.richard.testapp
        Name: TespApp
        Android target: android-19
Copying template files...
Project successfully created.
Installing "com.phonegap.plugins.PushPlugin" for android
Installing "com.salesforce" for android
Installing "org.apache.cordova.device" for android
Running SalesforceMobileSDK plugin android pre-install script
Done SalesforceMobileSDK plugin android pre-install script
Running SalesforceMobileSDK plugin android post-install script
Fixing application AndroidManifest.xml
Fixing application project.properties
Removing cordova library project reference from SalesforceSDK's project.properti
es
Building cordova library
Updating application to use SmartSync library project
Updating SalesforceSDK to use CordovaLib
Building SalesforceSDK library
Updating SmartStore library target android api
Building SmartStore library
Updating SmartSync library target android api
Building SmartSync library
Done running SalesforceMobileSDK plugin android post-install script
Plugin "org.apache.cordova.device" already installed on android.

Cloned icon

cordova prepare

cordova emulate

same exception occurs

**Comment by sevem** [comment]
@bhariharan is downgrading to Cordova 4 really an option? Not sure in what problems we will run into on other OS like iOS 9. Is there a roadmap or a release plan for Mobile SDK 4.0? Our customer, a really big player is "not amused" about this situation. First the big problems with iOS 9 and now really big problems while building an Android version

**Comment by bhariharan** [comment]
@sevem See my comment [here](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/112).

**Comment by toddhalfpenny** [comment]
I believe I'm still seeing this issue with SDK v4.
I have;
* node 5.3.0
* SF Mobile SDK 4.0
* Cordova 5.4.1
* Gradle 1.4
* cordova-android 1.4

The project seems to build OK but I get this;
```
12-21 14:33:21.395  18158-18204/net.mobilecaddy.bio.bio001 W/System.err﹕ java.lang.ClassNotFoundException: com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin

...
12-21 14:33:21.395  18158-18204/net.mobilecaddy.bio.bio001 W/System.err﹕ Caused by: java.lang.ClassNotFoundException: Didn't find class "com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin" on path: DexPathList[[zip file "/data/app/net.mobilecaddy.bio.bio001-1/base.apk"],nativeLibraryDirectories=[/data/app/net.mobilecaddy.bio.bio001-1/lib/x86, /vendor/lib, /system/lib]]
```

This appears to be the same for a projects both manually created (`cordova plugin ad ...`) or using forcedroid.

**Comment by bhariharan** [comment]
@toddhalfpenny Could you post the console output generated by ```forcedroid```? Do you have ```shelljs``` installed?

**Comment by toddhalfpenny** [comment]
@bhariharan Sorry, do you mean the logs generated for the `create` command or logs at run time?

**Comment by bhariharan** [comment]
@toddhalfpenny I think the ```shelljs``` location might be the issue here. Try this:
* ```npm install forcedroid``` locally in a folder.
* ```npm install shelljs``` locally in that same folder.
* ```node_modules/.bin/forcedroid create``` from that same folder.
Let me know if that works for you?

**Comment by toddhalfpenny** [comment]
@bhariharan Yes, this seems to work OK, for the sample app at least.

I will try to see how I get on with my other project to see if it's that and the cordova cli commands that were causing issues. Thanks for your help so far.

On an aside I did some IOS testing earlier and everything is looking good so far.

**Comment by toddhalfpenny** [comment]
@bhariharan An update. Although forcedriod created app is able to run up (as is my manually built one) I have a new issues now when trying to use the SmartStore.

I see this issue when I run this from the JS dev console;
```
var smartstore = cordova.require("com.salesforce.plugin.smartstore");
smartstore.soupExists('anySoup', function(res){consoles.log(res);}, function(e){console.error(e);});
```

And this is the logcat output;
```
12-22 06:59:58.857 3814-3853/com.test.my_new_app E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
 Process: com.test.my_new_app, PID: 3814
 java.lang.UnsatisfiedLinkError: Couldn't load stlport_shared from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.test.my_new_app-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.test.my_new_app-1, /system/lib]]]: findLibrary returned null
     at java.lang.Runtime.loadLibrary(Runtime.java:358)
     at java.lang.System.loadLibrary(System.java:526)
     at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:173)
     at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:169)
     at com.salesforce.androidsdk.smartstore.store.DBOpenHelper.<init>(DBOpenHelper.java:132)
     at com.salesforce.androidsdk.smartstore.store.DBOpenHelper.getOpenHelper(DBOpenHelper.java:124)
     at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getSmartStore(SmartStoreSDKManager.java:252)
     at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getSmartStore(SmartStoreSDKManager.java:235)
     at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getSmartStore(SmartStoreSDKManager.java:223)
     at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getSmartStore(SmartStoreSDKManager.java:213)
     at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.getSmartStore(SmartStorePlugin.java:576)
     at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.soupExists(SmartStorePlugin.java:306)
     at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin.access$1400(SmartStorePlugin.java:58)
     at com.salesforce.androidsdk.phonegap.plugin.SmartStorePlugin$1.run(SmartStorePlugin.java:160)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:841)
```

Searching for this issue seems to point to locations of the libs, but I don't understand it yet.

Should I create a separate ticket for this? I'm tempted to as I see it as something different.

**Comment by toddhalfpenny** [comment]
*UPDATE* I think it's to do with the **jniLibs.srcDir** in the SmartStore/build.gradle. I'm trying this with 
`jniLibs.srcDir 'libs'` and I think I have it now working. If it's successful I'll create a PR

**Comment by bhariharan** [comment]
@toddhalfpenny Definitely a different issue. This does seem like some weirdness with that particular emulator/device though. It is basically complaining that it can't load the native ```SQLCipher``` library (```.so``` file). However, if the sample app that uses ```SmartStore``` works fine, other apps should work fine too. Did you check your ```libs``` folder?
