### ISSUE TITLE
Back to login page from Allow/Deny page

### ISSUE THREAD

**Issue by PhamQuangThinh** [forcedotcom/SalesforceMobileSDK-Android#989]
I used Salesforce SDK 3.3.1
Sometimes( not always) I login successfully but it goes back login page from Allow/Deny page:
  1. Enter name and password
  2. In 2nd screen grant permission by tapping Allow but the first screen comes back up with name and password empty.

Sometimes it didn't come back login screen, but sometimes it came back login screen more than one time.
I downloaded sample project and it still gets the same issue.

**Comment by bobceuppens** [comment]
@PhamQuangThinh We experience the same issue.
Did you find a solution for this?

**Comment by congtuyenvip** [comment]
@bobceuppens 
I and @PhamQuangThinh  had found root cause for this issue, and had solution for this.

**Comment by bhariharan** [comment]
This sounds like an issue with the scopes in the login workflow. Mobile SDK has no control over the login page - we simply display it within a WebView.

**Comment by congtuyenvip** [comment]
As we investigate, login by using webview  still works correctly. We still login successfully but login screen come back again. So we surely that this is SDK bug, because we had already fixed it.
