### ISSUE TITLE
sqlite error when running SmartStore#alterSoup

### ISSUE THREAD

**Issue by randalln** [forcedotcom/SalesforceMobileSDK-Android#991]
I/SmartStore.trackAlterStatus: contacts STARTING
I/SmartStore.trackAlterStatus: contacts RENAME_OLD_SOUP_TABLE
I/Database: sqlite returned: error code = 17, msg = statement aborts at 18: [UPDATE long_operations_status SET lastModified=?, status=? WHERE id = ?] database schema has changed
I/SmartStore.trackAlterStatus: contacts DROP_OLD_INDEXES
/SmartStore.trackAlterStatus: contacts REGISTER_SOUP_USING_TABLE_NAME
I/SmartStore.trackAlterStatus: contacts COPY_TABLE
I/SmartStore.trackAlterStatus: contacts RE_INDEX_SOUP
I/SmartStore.trackAlterStatus: contacts DROP_OLD_TABLE

Calling #alterSoup with either the single new IndexSpec or the current set of IndexSpecs results in error above.  Am I doing something wrong?

**Comment by wmathurin** [comment]
Could you give us more details?
What version of the SDK are you on?
What version of the SDK were you on when the database was setup?
