### ISSUE TITLE
Can't compile app with compileSdkVersion 23

### ISSUE THREAD

**Issue by randalln** [forcedotcom/SalesforceMobileSDK-Android#992]
Error:(681, 66) error: cannot access ParseException
class file for org.apache.http.ParseException not found

Related information:
https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-apache-http-client

**Comment by bhariharan** [comment]
@randalln Check out our ```unstable``` branch. We've added support for ```Marshmallow``` there, and this will be a part of our next release.

**Comment by randalln** [comment]
Any ETA on the next release?

**Comment by bhariharan** [comment]
@randalln We haven't finalized the date yet, but feel free to use our ```unstable``` branch. It's pretty stable, contrary to the branch name.
