### ISSUE TITLE
Cordova build error with Salesforce MobileSDK 

### ISSUE THREAD

**Issue by elviejokike** [forcedotcom/SalesforceMobileSDK-Android#996]
I am using Cordova 5.4.0 to create a hybrid application using  Salesforce MobileSDK, after:

> cordova create forcec5
> cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin
> cordova platform add android 

I have added www/bootconfig.json and the additional resorces jquery.js and forcetk.mobilesdk.js.

> cordova build android

I get the excepion related to the ... @drawable/sf__icon...., and I fix that removing that from the AndroidManifest.xml

Then I get the error related to  Element activity#com.plugin.gcm.PushHandlerActivity, so I remove it from the AndroidManifest.xml, and then BUILD SUCCESSFUL, so:
> cordova run android 
LAUNCH SUCCESS, but it does not work (crash). 

And then, it says: 

FYI: I have tried around 20 combinations of cordova 3.x, 4.x, 5x and SalesForce SDK (latest, unstable, different branchs), different versions of forcedroid, and different versions of android itself... and none of them work.

**Comment by rnng** [comment]
Hi,
I have the exactly same Problem. Tried to compile my project + SDK in Eclipse, getting these Errors:

    Description	Resource	Path	Location	Type
    CordovaWebViewClient cannot be resolved to a type	SalesforceDroidGapActivity.java	/SalesforceSDK/src/com/salesforce/androidsdk/ui/sfhybrid	line 157	Java Problem
    IceCreamCordovaWebViewClient cannot be resolved to a type	SalesforceIceCreamWebViewClient.java	/SalesforceSDK/src/com/salesforce/androidsdk/ui/sfhybrid	line 43	Java Problem
    IceCreamCordovaWebViewClient cannot be resolved to a type	SalesforceIceCreamWebViewClient.java	/SalesforceSDK/src/com/salesforce/androidsdk/ui/sfhybrid	line 70	Java Problem
    IceCreamCordovaWebViewClient cannot be resolved to a type	SalesforceIceCreamWebViewClient.java	/SalesforceSDK/src/com/salesforce/androidsdk/ui/sfhybrid	line 80	Java Problem
    IceCreamCordovaWebViewClient cannot be resolved to a type	SalesforceIceCreamWebViewClient.java	/SalesforceSDK/src/com/salesforce/androidsdk/ui/sfhybrid	line 85	Java Problem
    The constructor SalesforceIceCreamWebViewClient(SalesforceDroidGapActivity, CordovaWebView) is undefined	SalesforceDroidGapActivity.java	/SalesforceSDK/src/com/salesforce/androidsdk/ui/sfhybrid	line 158	Java Problem
    The import org.apache.cordova.CordovaWebViewClient cannot be resolved	SalesforceDroidGapActivity.java	/SalesforceSDK/src/com/salesforce/androidsdk/ui/sfhybrid	line 38	Java Problem
    The import org.apache.cordova.IceCreamCordovaWebViewClient cannot be resolved	SalesforceIceCreamWebViewClient.java	/SalesforceSDK/src/com/salesforce/androidsdk/ui/sfhybrid	line 36	Java Problem
    The method getSettings() is undefined for the type CordovaWebView	SalesforceDroidGapActivity.java	/SalesforceSDK/src/com/salesforce/androidsdk/ui/sfhybrid	line 140	Java Problem
    The method makeWebViewClient(CordovaWebView) of type SalesforceDroidGapActivity must override or implement a supertype method	SalesforceDroidGapActivity.java	/SalesforceSDK/src/com/salesforce/androidsdk/ui/sfhybrid	line 157	Java Problem
    The method onPageFinished(WebView, String) of type SalesforceIceCreamWebViewClient must override or implement a supertype method	SalesforceIceCreamWebViewClient.java	/SalesforceSDK/src/com/salesforce/androidsdk/ui/sfhybrid	line 75	Java Problem
    The method sendJavascript(String) is undefined for the type SalesforceDroidGapActivity	JSTestCase.java	/SalesforceSDK/src/com/salesforce/androidsdk/util/test	line 90	Java Problem
    The method shouldInterceptRequest(WebView, String) of type SalesforceIceCreamWebViewClient must override or implement a supertype method	SalesforceIceCreamWebViewClient.java	/SalesforceSDK/src/com/salesforce/androidsdk/ui/sfhybrid	line 84	Java Problem
    The method shouldOverrideUrlLoading(WebView, String) of type SalesforceIceCreamWebViewClient must override or implement a supertype method	SalesforceIceCreamWebViewClient.java	/SalesforceSDK/src/com/salesforce/androidsdk/ui/sfhybrid	line 66	Java Problem

**Comment by bhariharan** [comment]
@rnng Looks like you're using a newer unsupported version of ```Cordova``` against our plugin on ```master```. Try our ```unstable``` branch - that should work fine using ```Android Studio```.

@elviejokike Try installing the latest ```Cordova CLI 5.4.0``` and using it against our ```unstable``` branch. I verified that this works just fine last week. Don't forget to install ```shelljs``` as well. Let me know if that works for you.

**Comment by bhariharan** [comment]
I verified that ```Cordova 5.4.0``` works fine against our ```unstable``` branch. Feel free to reopen this if you still see issues.

**Comment by elviejokike** [comment]
It does not work...  can you provide me with the right steps to get it running?
